[package]
name = "bdm"
version = "0.1.0"
description = "Basketball Dynasty Manager"
authors = ["BDM"]
edition = "2021"

[lib]
name = "bdm_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
