import { describe, expect, it } from 'vitest'
import { createNewGame } from '@/app/game'
import { createCoachInvestment, liquidateCoachInvestment, processCoachFinancesForMonth, registerCoachAsset, registerCoachExternalIncome } from './CoachFinancesEngine'
import { getCoachNetWorth } from '@/domain/coachFinances'
import { deserializeGameWorldV1, serializeGameWorldV1 } from '@/save/GameWorldSaveV1'

describe('Coach finances', () => {
  it('initializes valid, persisted financial profiles for every coach', () => { const world = createNewGame(); expect(world.coachFinancesByCoachId[world.userCoachId]!.cash).toBeGreaterThan(0); expect(deserializeGameWorldV1(serializeGameWorldV1(world, '2032-10-01T00:00:00.000Z')).coachFinancesByCoachId).toEqual(world.coachFinancesByCoachId) })
  it('processes a month only once and records salary and expenses', () => { const world = createNewGame(); const first = processCoachFinancesForMonth(world); const second = processCoachFinancesForMonth(first); const profile = first.coachFinancesByCoachId[first.userCoachId]!; expect(profile.movements.map((item) => item.type)).toEqual(expect.arrayContaining(['salary', 'expense'])); expect(second).toEqual(first) })
  it('buys and liquidates an investment through the canonical finance operations', () => { const world = createNewGame(); const profile = world.coachFinancesByCoachId[world.userCoachId]!; const invested = createCoachInvestment(world, world.userCoachId, { id: 'investment:test', name: 'Academy stake', principal: 10_000, value: 10_000, monthlyReturnRate: .01, risk: .2, liquidity: 'medium', status: 'active' }); expect(invested.coachFinancesByCoachId[world.userCoachId]!.cash).toBe(profile.cash - 10_000); const sold = liquidateCoachInvestment(invested, world.userCoachId, 'investment:test'); expect(sold.coachFinancesByCoachId[world.userCoachId]!.cash).toBe(profile.cash); expect(getCoachNetWorth(sold.coachFinancesByCoachId[world.userCoachId]!)).toBe(profile.cash) })
  it('persists assets and external income, then applies the net income once per month', () => { const world = createNewGame(); const asset = registerCoachAsset(world, world.userCoachId, { id: 'asset:home', kind: 'property', name: 'Home', marketValue: 150_000, monthlyCost: 500, liquidity: 'low', status: 'active' }); const configured = registerCoachExternalIncome(asset, world.userCoachId, { id: 'income:sponsor', kind: 'sponsorship', name: 'Sponsor', monthlyGrossAmount: 4_000, status: 'active' }); const processed = processCoachFinancesForMonth(configured); const profile = processed.coachFinancesByCoachId[world.userCoachId]!; expect(getCoachNetWorth(profile)).toBeGreaterThan(getCoachNetWorth(world.coachFinancesByCoachId[world.userCoachId]!)); expect(profile.movements).toEqual(expect.arrayContaining([expect.objectContaining({ type: 'sponsorship', amount: 3_000 })])); expect(deserializeGameWorldV1(serializeGameWorldV1(processed, '2032-10-01T00:00:00.000Z')).coachFinancesByCoachId[world.userCoachId]).toEqual(profile) })
  it('resolves investment risk deterministically from coach, investment and month', () => { const world = createNewGame(); const configured = createCoachInvestment(world, world.userCoachId, { id: 'investment:risk', name: 'Risk fund', principal: 10_000, value: 10_000, monthlyReturnRate: 0, risk: .3, liquidity: 'low', status: 'active' }); expect(processCoachFinancesForMonth(configured).coachFinancesByCoachId).toEqual(processCoachFinancesForMonth(configured).coachFinancesByCoachId) })
})
