import { createCoachFinanceProfile, getCoachMonthlyExpenses, type CoachAsset, type CoachDebt, type CoachExternalIncome, type CoachFinanceMovement, type CoachFinanceProfile, type CoachInvestment, type Lifestyle } from '@/domain/coachFinances'
import type { GameDate } from '@/domain/date'
import type { CoachId } from '@/domain/ids'
import { addInboxItem, updateGameWorld, type GameWorld } from '@/domain/world'
import { hashStringToSeed, SeededRandomSource } from '@/engine/random'

export function registerCoachFinanceMovement(world: GameWorld, coachId: CoachId, movement: Omit<CoachFinanceMovement, 'id'> & { readonly id?: string }): GameWorld { const profile = required(world, coachId); const id = movement.id ?? `finance:${coachId}:${movement.date}:${movement.type}:${profile.movements.length + 1}`; if (profile.movements.some((item) => item.id === id)) return world; return replace(world, coachId, { ...profile, cash: profile.cash + movement.amount, movements: [...profile.movements, { ...movement, id }] }) }
export function setCoachLifestyle(world: GameWorld, coachId: CoachId, lifestyle: Lifestyle): GameWorld { return replace(world, coachId, { ...required(world, coachId), lifestyle }) }
export function createCoachInvestment(world: GameWorld, coachId: CoachId, investment: CoachInvestment): GameWorld { const profile = required(world, coachId); if (investment.principal <= 0 || investment.principal > profile.cash || profile.investments.some((item) => item.id === investment.id)) throw new RangeError('Invalid coach investment'); const charged = registerCoachFinanceMovement(world, coachId, { date: world.currentDate, type: 'investmentPurchase', amount: -investment.principal, description: investment.name, relatedEntityId: investment.id, id: `finance:${investment.id}:purchase` }); return replace(charged, coachId, { ...required(charged, coachId), investments: [...profile.investments, investment] }) }
export function liquidateCoachInvestment(world: GameWorld, coachId: CoachId, investmentId: string): GameWorld { const profile = required(world, coachId); const investment = profile.investments.find((item) => item.id === investmentId); if (investment === undefined || investment.status !== 'active') return world; const credited = registerCoachFinanceMovement(world, coachId, { date: world.currentDate, type: 'investmentLiquidation', amount: investment.value, description: investment.name, relatedEntityId: investment.id, id: `finance:${investment.id}:liquidation` }); return replace(credited, coachId, { ...required(credited, coachId), investments: profile.investments.map((item) => item.id === investmentId ? { ...item, status: 'liquidated' } : item) }) }
export function addCoachDebt(world: GameWorld, coachId: CoachId, debt: CoachDebt): GameWorld { const profile = required(world, coachId); if (debt.principalRemaining <= 0 || profile.debts.some((item) => item.id === debt.id)) throw new RangeError('Invalid coach debt'); return replace(world, coachId, { ...profile, debts: [...profile.debts, debt], cash: profile.cash + debt.principalRemaining }) }
export function registerCoachAsset(world: GameWorld, coachId: CoachId, asset: CoachAsset): GameWorld { const profile = required(world, coachId); if (profile.assets.some((item) => item.id === asset.id)) throw new RangeError('Coach asset already exists'); return replace(world, coachId, { ...profile, assets: [...profile.assets, asset] }) }
export function registerCoachExternalIncome(world: GameWorld, coachId: CoachId, income: CoachExternalIncome): GameWorld { const profile = required(world, coachId); if (profile.externalIncomes.some((item) => item.id === income.id)) throw new RangeError('Coach external income already exists'); return replace(world, coachId, { ...profile, externalIncomes: [...profile.externalIncomes, income] }) }
export function processCoachFinancesForMonth(world: GameWorld): GameWorld {
  const month = world.currentDate.slice(0, 7); let next = world
  for (const [coachId, initial] of Object.entries(world.coachFinancesByCoachId) as [CoachId, CoachFinanceProfile][]) {
    if (initial.processedMonths.includes(month)) continue
    const employed = world.coachEmploymentByCoachId[coachId]?.status === 'employed'
    if (employed) next = income(next, coachId, month, 'salary', initial.annualSalary / 12, 'Net coaching salary', `salary:${coachId}:${month}`)
    for (const source of initial.externalIncomes) if (source.status === 'active' && (source.endsOn === undefined || source.endsOn >= world.currentDate)) next = income(next, coachId, month, source.kind === 'sponsorship' ? 'sponsorship' : source.kind === 'business' ? 'businessIncome' : 'otherIncome', source.monthlyGrossAmount, source.name, `income:${source.id}:${month}`, source.id)
    const beforeExpenses = required(next, coachId)
    next = registerCoachFinanceMovement(next, coachId, { date: world.currentDate, type: 'expense', amount: -getCoachMonthlyExpenses(beforeExpenses), description: `${beforeExpenses.lifestyle} lifestyle, asset and debt costs`, id: `finance:${coachId}:${month}:expenses` })
    const current = required(next, coachId); const investments = current.investments.map((item) => valueInvestment(item, coachId, month)); const debts = current.debts.map((item) => payDebt(item)); const delta = investments.reduce((sum, item, index) => sum + item.value - current.investments[index]!.value, 0)
    next = replace(next, coachId, { ...current, investments, debts, processedMonths: [...current.processedMonths, month] })
    if (coachId === world.userCoachId && Math.abs(delta) >= 5000) next = addInboxItem(next, { id: `inbox:finance:${coachId}:${month}`, coachId, gameDate: world.currentDate, category: 'career', priority: 'normal', title: 'Investment update', body: `Your investment portfolio ${delta >= 0 ? 'gained' : 'lost'} a material amount this month.`, status: 'unread', context: { month, delta } })
  }
  return next
}
function income(world: GameWorld, coachId: CoachId, month: string, type: 'salary' | 'sponsorship' | 'businessIncome' | 'otherIncome', gross: number, description: string, key: string, relatedEntityId?: string): GameWorld { const tax = required(world, coachId).incomeTaxRate; return registerCoachFinanceMovement(world, coachId, { date: world.currentDate, type, amount: Math.round(gross * (1 - tax)), description, ...(relatedEntityId === undefined ? {} : { relatedEntityId }), id: `finance:${key}` }) }
function valueInvestment(investment: CoachInvestment, coachId: CoachId, month: string): CoachInvestment { if (investment.status !== 'active') return investment; const volatility = investment.risk === 0 ? 0 : new SeededRandomSource(hashStringToSeed(`coach-finance:${coachId}:${investment.id}:${month}`)).nextFloat(-investment.risk, investment.risk); return { ...investment, value: Math.max(0, Math.round(investment.value * (1 + investment.monthlyReturnRate + volatility))) } }
function payDebt(debt: CoachDebt): CoachDebt { if (debt.status !== 'active') return debt; const principalRemaining = Math.max(0, Math.round(debt.principalRemaining * (1 + debt.interestRate / 12) - debt.monthlyPayment)); return { ...debt, principalRemaining, status: principalRemaining === 0 ? 'paid' : 'active' } }
function required(world: GameWorld, coachId: CoachId) { const profile = world.coachFinancesByCoachId[coachId]; if (profile === undefined) throw new Error('Coach finance profile does not exist'); return profile }
function replace(world: GameWorld, coachId: CoachId, profile: CoachFinanceProfile): GameWorld { return updateGameWorld(world, { coachFinancesByCoachId: { ...world.coachFinancesByCoachId, [coachId]: createCoachFinanceProfile(profile) } }) }
