import { describe, expect, it } from 'vitest'
import { createNewGame } from '@/app/game'
import { createCoachInvestment, liquidateCoachInvestment, processCoachFinancesForMonth, registerCoachAsset, registerCoachExternalIncome } from './CoachFinancesEngine'
import { getCoachFinancialPosition, getCoachNetWorth } from '@/domain/coachFinances'
import { updateGameWorld } from '@/domain/world'
import { deserializeGameWorldV1, serializeGameWorldV1 } from '@/save/GameWorldSaveV1'
import { fireCoachFromTeam } from '@/app/coachCareer'

describe('Coach finances', () => {
  it('initializes valid, persisted financial profiles for every coach', () => { const world = createNewGame(); expect(world.coachFinancesByCoachId[world.userCoachId]!.cash).toBeGreaterThan(0); expect(deserializeGameWorldV1(serializeGameWorldV1(world, '2032-10-01T00:00:00.000Z')).coachFinancesByCoachId).toEqual(world.coachFinancesByCoachId) })
  it('processes a month only once and records salary and expenses', () => { const world = createNewGame(); const first = processCoachFinancesForMonth(world); const second = processCoachFinancesForMonth(first); const profile = first.coachFinancesByCoachId[first.userCoachId]!; expect(profile.movements.map((item) => item.type)).toEqual(expect.arrayContaining(['salary', 'expense'])); expect(second).toEqual(first) })
  it('buys and liquidates an investment through the canonical finance operations', () => { const world = createNewGame(); const profile = world.coachFinancesByCoachId[world.userCoachId]!; const invested = createCoachInvestment(world, world.userCoachId, { id: 'investment:test', name: 'Academy stake', principal: 10_000, value: 10_000, monthlyReturnRate: .01, risk: .2, liquidity: 'medium', status: 'active' }); expect(invested.coachFinancesByCoachId[world.userCoachId]!.cash).toBe(profile.cash - 10_000); const sold = liquidateCoachInvestment(invested, world.userCoachId, 'investment:test'); expect(sold.coachFinancesByCoachId[world.userCoachId]!.cash).toBe(profile.cash); expect(getCoachNetWorth(sold.coachFinancesByCoachId[world.userCoachId]!)).toBe(profile.cash) })
  it('persists assets and external income, then applies the net income once per month', () => { const world = createNewGame(); const asset = registerCoachAsset(world, world.userCoachId, { id: 'asset:home', kind: 'property', name: 'Home', marketValue: 150_000, monthlyCost: 500, liquidity: 'low', status: 'active' }); const configured = registerCoachExternalIncome(asset, world.userCoachId, { id: 'income:sponsor', kind: 'sponsorship', name: 'Sponsor', monthlyGrossAmount: 4_000, status: 'active' }); const processed = processCoachFinancesForMonth(configured); const profile = processed.coachFinancesByCoachId[world.userCoachId]!; expect(getCoachNetWorth(profile)).toBeGreaterThan(getCoachNetWorth(world.coachFinancesByCoachId[world.userCoachId]!)); expect(profile.movements).toEqual(expect.arrayContaining([expect.objectContaining({ type: 'sponsorship', amount: 3_000 })])); expect(deserializeGameWorldV1(serializeGameWorldV1(processed, '2032-10-01T00:00:00.000Z')).coachFinancesByCoachId[world.userCoachId]).toEqual(profile) })
  it('resolves investment risk deterministically from coach, investment and month', () => { const world = createNewGame(); const configured = createCoachInvestment(world, world.userCoachId, { id: 'investment:risk', name: 'Risk fund', principal: 10_000, value: 10_000, monthlyReturnRate: 0, risk: .3, liquidity: 'low', status: 'active' }); expect(processCoachFinancesForMonth(configured).coachFinancesByCoachId).toEqual(processCoachFinancesForMonth(configured).coachFinancesByCoachId) })
  it('continues expenses, debt and external income without paying salary while unemployed', () => { const base = createNewGame(); const coachId = base.userCoachId; const configured = registerCoachExternalIncome(registerCoachAsset(base, coachId, { id: 'asset:cost', kind: 'property', name: 'Home', marketValue: 100_000, monthlyCost: 500, liquidity: 'low', status: 'active' }), coachId, { id: 'income:external', kind: 'business', name: 'Clinic', monthlyGrossAmount: 1_000, status: 'active' }); const indebted = { ...configured.coachFinancesByCoachId[coachId]!, cash: 5_000, debts: [{ id: 'debt:test', name: 'Loan', principalRemaining: 10_000, monthlyPayment: 600, interestRate: 0, status: 'active' as const }] }; const fired = fireCoachFromTeam(configured, Object.values(configured.teams).find((team) => team.coachId === coachId)!.id); const unemployed = updateGameWorld(fired, { coachFinancesByCoachId: { ...fired.coachFinancesByCoachId, [coachId]: indebted } }); const processed = processCoachFinancesForMonth(unemployed).coachFinancesByCoachId[coachId]!; expect(processed.movements.map((movement) => movement.type)).not.toContain('salary'); expect(processed.movements).toEqual(expect.arrayContaining([expect.objectContaining({ type: 'businessIncome' }), expect.objectContaining({ type: 'expense' })])); expect(processed.debts[0]!.principalRemaining).toBe(9_400); expect(processed.cash).toBeLessThan(indebted.cash) })
  it('keeps illiquid wealth separate from cash and changes security after a loss', () => { const base = createNewGame(); const coachId = base.userCoachId; const profile = { ...base.coachFinancesByCoachId[coachId]!, cash: 500, annualSalary: 0, lifestyle: 'modest' as const, assets: [{ id: 'asset:estate', kind: 'property' as const, name: 'Estate', marketValue: 500_000, monthlyCost: 0, liquidity: 'low' as const, status: 'active' as const }], investments: [{ id: 'investment:loss', name: 'Loss fund', principal: 10_000, value: 10_000, monthlyReturnRate: -1, risk: 0, liquidity: 'low' as const, status: 'active' as const }] }; const fired = fireCoachFromTeam(base, Object.values(base.teams).find((team) => team.coachId === coachId)!.id); const unemployed = updateGameWorld(fired, { coachFinancesByCoachId: { ...fired.coachFinancesByCoachId, [coachId]: profile } }); const before = getCoachFinancialPosition(unemployed.coachFinancesByCoachId[coachId]!); const after = processCoachFinancesForMonth(unemployed).coachFinancesByCoachId[coachId]!; expect(before.netWorth).toBeGreaterThan(before.liquidCash); expect(before.runwayMonths).toBeLessThan(1); expect(after.investments[0]!.value).toBe(0); expect(getCoachNetWorth(after)).toBeLessThan(before.netWorth); expect(getCoachFinancialPosition(after).security).toBe('vulnerable') })
  it('moves from stable to vulnerable as unemployed liquidity is consumed', () => { const base = createNewGame(); const coachId = base.userCoachId; const profile = { ...base.coachFinancesByCoachId[coachId]!, cash: 4_000, annualSalary: 0, lifestyle: 'modest' as const }; const fired = fireCoachFromTeam(base, Object.values(base.teams).find((team) => team.coachId === coachId)!.id); const unemployed = updateGameWorld(fired, { coachFinancesByCoachId: { ...fired.coachFinancesByCoachId, [coachId]: profile } }); expect(getCoachFinancialPosition(profile).security).toBe('stable'); expect(getCoachFinancialPosition(processCoachFinancesForMonth(unemployed).coachFinancesByCoachId[coachId]!).security).toBe('vulnerable') })
})
