import type { GameWorld } from '@/domain/world'
import { createGameWorld } from '@/domain/world'
import type { PlayerDevelopmentContext, PlayerDevelopmentResult } from './PlayerDevelopment'
import { developPlayerForSeason } from './PlayerDevelopment'

export function applyOffseasonDevelopment(world: GameWorld, context: PlayerDevelopmentContext): { readonly world: GameWorld; readonly results: readonly PlayerDevelopmentResult[] } {
  const developed = Object.values(world.players).map((player) => developPlayerForSeason(player, context))
  return { world: createGameWorld({ currentDate: world.currentDate, currentSeasonId: world.currentSeasonId, userCoachId: world.userCoachId, countries: Object.values(world.countries), coaches: Object.values(world.coaches), players: developed.map((item) => item.player), teams: Object.values(world.teams), competitions: Object.values(world.competitions), seasons: Object.values(world.seasons), games: Object.values(world.games), matchStatLogs: Object.values(world.matchStatLogsByGameId), seasonHistory: Object.values(world.seasonHistoryBySeasonId), injuries: Object.values(world.injuriesById), contracts: Object.values(world.contractsById), teamFinances: Object.values(world.teamFinancesByTeamId), playerTransactions:Object.values(world.playerTransactionsById),playerKnowledge:Object.values(world.playerKnowledgeById),staffPeople:Object.values(world.staffPeopleById),teamStaffAssignments:Object.values(world.teamStaffAssignmentsById),coachProfessionalProfilesByCoachId:world.coachProfessionalProfilesByCoachId,coachRpgProfilesByCoachId: world.coachRpgProfilesByCoachId, coachReputationProfilesByCoachId: world.coachReputationProfilesByCoachId, coachEmploymentByCoachId: world.coachEmploymentByCoachId, coachCareerHistoryByCoachId: world.coachCareerHistoryByCoachId, coachJobOpeningsById: world.coachJobOpeningsById, coachJobCandidaciesById: world.coachJobCandidaciesById, coachInterviewsByCandidacyId: world.coachInterviewsByCandidacyId, coachJobOffersById: world.coachJobOffersById }), results: developed.map((item) => item.result) }
}
