import type { GameDate } from '@/domain/date'
import type { EcosystemId, PlayerId, SeasonId, TeamId } from '@/domain/ids'

export type TradeAssetKind = 'player' | 'draftPick' | 'futureDraftPick' | 'playerRights' | 'draftPickSwapRight' | 'cash'
export type PlayerRightsType = 'draft' | 'international'
export type PlayerRightsStatus = 'active' | 'expired'
export type ProtectionOutcome = { readonly kind: 'rollover'; readonly cycle: number; readonly round: number } | { readonly kind: 'extinguish' }
export interface DraftPickProtection { readonly protectedOrderRanges: readonly { readonly from: number; readonly to: number }[]; readonly outcome: ProtectionOutcome }
export interface PlayerRights { readonly id: string; readonly playerId: PlayerId; readonly ecosystemId: EcosystemId; readonly ownerTeamId: TeamId; readonly originalTeamId?: TeamId; readonly rightsType: PlayerRightsType; readonly acquiredAt: GameDate; readonly expiresAt?: GameDate; readonly status: PlayerRightsStatus }
export interface FutureDraftPickRight { readonly id: string; readonly ecosystemId: EcosystemId; readonly cycle: number; readonly round: number; readonly originalTeamId: TeamId; readonly ownerTeamId: TeamId; readonly protection?: DraftPickProtection; readonly conditionalRecipientTeamId?: TeamId }
export interface DraftPickSwapRight { readonly id: string; readonly ecosystemId: EcosystemId; readonly cycle: number; readonly round: number; readonly holderTeamId: TeamId; readonly counterpartTeamId: TeamId; readonly status: 'active' | 'resolved'; readonly resolvedPickIds?: readonly string[] }
export interface RetainedSalaryObligation { readonly id: string; readonly sourceTradeId: string; readonly playerId: PlayerId; readonly retainingTeamId: TeamId; readonly receivingTeamId: TeamId; readonly seasonId: SeasonId; readonly amount: number }
export type TradeAsset =
  | { readonly kind: 'player'; readonly playerId: PlayerId }
  | { readonly kind: 'draftPick'; readonly draftPickId: string }
  | { readonly kind: 'futureDraftPick'; readonly futureDraftPickRightId: string }
  | { readonly kind: 'playerRights'; readonly playerRightsId: string }
  | { readonly kind: 'draftPickSwapRight'; readonly draftPickSwapRightId: string }
  | { readonly kind: 'cash'; readonly amount: number }
export interface TradeAssetMovement { readonly asset: TradeAsset; readonly fromTeamId: TeamId; readonly toTeamId: TeamId }
export interface TradeExceptionUse { readonly teamId: TeamId; readonly exceptionId: string; readonly amount: number }
export interface RetainedSalaryTerm { readonly playerId: PlayerId; readonly retainingTeamId: TeamId; readonly receivingTeamId: TeamId; readonly amount: number }
export interface TradeProposal { readonly id: string; readonly ecosystemId: EcosystemId; readonly seasonId: SeasonId; readonly participantTeamIds: readonly TeamId[]; readonly movements: readonly TradeAssetMovement[]; readonly exceptionUses?: readonly TradeExceptionUse[]; readonly retainedSalary?: readonly RetainedSalaryTerm[] }
export interface TradeRecord { readonly id: string; readonly proposalId: string; readonly ecosystemId: EcosystemId; readonly seasonId: SeasonId; readonly executedAt: GameDate; readonly participantTeamIds: readonly TeamId[]; readonly movements: readonly TradeAssetMovement[]; readonly createdExceptionIds: readonly string[]; readonly retainedSalaryObligationIds: readonly string[] }
export interface TradeRules { readonly seasonId: SeasonId; readonly ecosystemId: EcosystemId; readonly maxTeamsPerTrade: number; readonly allowedAssetKinds: readonly TradeAssetKind[]; readonly maxFutureDraftCyclesTradable: number; readonly retainedSalary: { readonly allowed: boolean; readonly maximumPercentage: number; readonly maximumContractsPerTeam: number }; readonly cashConsideration: { readonly allowed: boolean; readonly maximumAmount: number }; readonly createTradeException: { readonly enabled: boolean; readonly expiresAfterSeasons: number } }

export function createTradeRules(input: TradeRules): TradeRules {
  if (!Number.isInteger(input.maxTeamsPerTrade) || input.maxTeamsPerTrade < 2 || !Number.isInteger(input.maxFutureDraftCyclesTradable) || input.maxFutureDraftCyclesTradable < 0 || input.allowedAssetKinds.length === 0 || new Set(input.allowedAssetKinds).size !== input.allowedAssetKinds.length || !Number.isFinite(input.retainedSalary.maximumPercentage) || input.retainedSalary.maximumPercentage < 0 || input.retainedSalary.maximumPercentage > 1 || !Number.isInteger(input.retainedSalary.maximumContractsPerTeam) || input.retainedSalary.maximumContractsPerTeam < 0 || !Number.isInteger(input.cashConsideration.maximumAmount) || input.cashConsideration.maximumAmount < 0 || !Number.isInteger(input.createTradeException.expiresAfterSeasons) || input.createTradeException.expiresAfterSeasons < 1) throw new RangeError('Trade rules are invalid')
  return Object.freeze({ ...input, allowedAssetKinds: Object.freeze([...input.allowedAssetKinds]), retainedSalary: Object.freeze({ ...input.retainedSalary }), cashConsideration: Object.freeze({ ...input.cashConsideration }), createTradeException: Object.freeze({ ...input.createTradeException }) })
}
export function createPlayerRights(input: PlayerRights): PlayerRights { if (!input.id || !['draft', 'international'].includes(input.rightsType) || !['active', 'expired'].includes(input.status)) throw new RangeError('Player rights are invalid'); return Object.freeze({ ...input }) }
export function createFutureDraftPickRight(input: FutureDraftPickRight): FutureDraftPickRight { if (!input.id || !Number.isInteger(input.cycle) || !Number.isInteger(input.round) || input.round < 1 || input.ownerTeamId === input.conditionalRecipientTeamId || input.protection?.protectedOrderRanges.some((range) => !Number.isInteger(range.from) || !Number.isInteger(range.to) || range.from < 1 || range.to < range.from)) throw new RangeError('Future draft pick right is invalid'); return Object.freeze({ ...input, ...(input.protection === undefined ? {} : { protection: Object.freeze({ protectedOrderRanges: Object.freeze(input.protection.protectedOrderRanges.map((range) => Object.freeze({ ...range }))), outcome: Object.freeze({ ...input.protection.outcome }) }) }) }) }
export function createDraftPickSwapRight(input: DraftPickSwapRight): DraftPickSwapRight { if (!input.id || !Number.isInteger(input.cycle) || !Number.isInteger(input.round) || input.round < 1 || input.holderTeamId === input.counterpartTeamId || (input.status === 'resolved') !== (input.resolvedPickIds !== undefined)) throw new RangeError('Draft pick swap right is invalid'); return Object.freeze({ ...input, ...(input.resolvedPickIds === undefined ? {} : { resolvedPickIds: Object.freeze([...input.resolvedPickIds]) }) }) }
export function createRetainedSalaryObligation(input: RetainedSalaryObligation): RetainedSalaryObligation { if (!input.id || !Number.isInteger(input.amount) || input.amount < 1 || input.retainingTeamId === input.receivingTeamId) throw new RangeError('Retained salary obligation is invalid'); return Object.freeze({ ...input }) }
export function createTradeRecord(input: TradeRecord): TradeRecord { if (!input.id || !input.proposalId || input.participantTeamIds.length < 2 || new Set(input.participantTeamIds).size !== input.participantTeamIds.length || input.movements.length === 0) throw new RangeError('Trade record is invalid'); return Object.freeze({ ...input, participantTeamIds: Object.freeze([...input.participantTeamIds]), movements: Object.freeze(input.movements.map((movement) => Object.freeze({ ...movement, asset: Object.freeze({ ...movement.asset }) }))), createdExceptionIds: Object.freeze([...input.createdExceptionIds]), retainedSalaryObligationIds: Object.freeze([...input.retainedSalaryObligationIds]) }) }
