import { describe, expect, it } from 'vitest'
import { createValidGameWorldInput } from '@/domain/world/testFixtures'
import { createGameWorld, updateGameWorld } from '@/domain/world'
import { createExpenseRecognition, createRevenueRecognition } from './Recognition'
import { createFinancialAccount, createFinancialTransaction } from './FinancialLedger'
import { createPayable, getPayableRemaining, settlePayable } from './Treasury'
import { createOperatingCostSource } from './OperatingCostEngine'
import { createRevenueSource } from './RevenueEngine'
import { createFinancialBudget, createBudgetLine, createFinancialForecast, createFinancialPlanningPeriod } from './BudgetForecasting'
import { applyEconomicObservation, applyExchangeRate, convertForReporting, createEconomicObservation, createExchangeRate, createEconomicFactor, getEconomicEnvironmentSnapshot, indexFutureMoney } from './EconomicEnvironment'
import { getFinancialReportingTotal, getForecastReportingTotal } from './EconomicReporting'
import { assessFinancialRegulation, createFinancialRegulationRule, getActiveFinancialRules, getOrganizationFinancialRegulationStatus, recordAuthorizedFinancialFine, recordFinancialAssessment } from './FinancialRegulation'

const source = { kind: 'CF10_TEST', id: 'fixture' }
const org = 'team-home'
const accounts = [
  createFinancialAccount({ id: 'cash:cf10', organizationId: org, accountType: 'CASH', currencyCode: 'EUR', openedOn: '2032-01-01' }),
  createFinancialAccount({ id: 'equity:cf10', organizationId: org, accountType: 'EQUITY', currencyCode: 'EUR', openedOn: '2032-01-01' }),
  createFinancialAccount({ id: 'payable:cf10', organizationId: org, accountType: 'PAYABLE', currencyCode: 'EUR', openedOn: '2032-01-01' }),
  createFinancialAccount({ id: 'expense:cf10', organizationId: org, accountType: 'EXPENSE', currencyCode: 'EUR', openedOn: '2032-01-01' }),
]
const cash = createFinancialTransaction({ id: 'cash:opening:cf10', organizationId: org, effectiveOn: '2032-01-01', transactionType: 'OWNER_FUNDING_RECEIPT', amount: { currencyCode: 'EUR', minorUnits: 100_000 }, postings: [{ accountId: 'cash:cf10', direction: 'DEBIT', amount: { currencyCode: 'EUR', minorUnits: 100_000 } }, { accountId: 'equity:cf10', direction: 'CREDIT', amount: { currencyCode: 'EUR', minorUnits: 100_000 } }], provenance: source })
const world = (extra: Partial<ReturnType<typeof createValidGameWorldInput>> = {}) => createGameWorld({ ...createValidGameWorldInput(), financialAccounts: accounts, financialTransactions: [cash], ...extra })
const rule = (metric: 'MINIMUM_CASH' | 'OVERDUE_PAYABLES' | 'OPERATING_LOSS' | 'PAYROLL_REVENUE_RATIO', threshold: number, version = '2027', effectiveFrom = '2032-01-01') => createFinancialRegulationRule({ id: 'rule:cf10', version, authorityOrganizationId: org as never, competitionId: null, applicableOrganizationIds: [org as never], effectiveFrom: effectiveFrom as never, effectiveTo: null, windowDays: 365, metric, comparison: metric === 'MINIMUM_CASH' ? 'MINIMUM' : 'MAXIMUM', threshold, currencyCode: 'EUR' as never, consequence: 'WARNING', provenance: source })
const observation = createEconomicObservation({ id: 'index:cf10', kind: 'INFLATION_INDEX', region: 'EU', currencyCode: 'EUR' as never, effectiveOn: '2032-01-01' as never, factor: { numerator: 103, denominator: 100 }, provenance: source })
const period = createFinancialPlanningPeriod({ kind: 'DATE_RANGE', startsOn: '2032-01-01', endsOn: '2032-12-31' })

describe('CF10 financial regulation', () => {
  it('assesses minimum liquidity without changing cash or ledger', () => { const initial = world(); const result = assessFinancialRegulation(initial, rule('MINIMUM_CASH', 120_000), org, '2032-10-01'); expect(result).toMatchObject({ measuredValue: 100_000, state: 'BREACH', threshold: 120_000 }); expect(initial.financialTransactionsById).toHaveProperty(cash.id) })
  it('assesses overdue payables using remaining unpaid amount', () => { const payable = createPayable({ id: 'payable:overdue:cf10', organizationId: org, amount: { currencyCode: 'EUR', minorUnits: 25_000 }, counterparty: { kind: 'EXTERNAL', label: 'Supplier' }, recognizedOn: '2032-05-01', dueOn: '2032-06-01', provenance: source }); const result = assessFinancialRegulation(world({ payables: [payable] }), rule('OVERDUE_PAYABLES', 10_000), org, '2032-10-01'); expect(result.measuredValue).toBe(25_000); expect(result.supportingFactIds).toContain(payable.id) })
  it('uses recognized revenue and expense for operating loss', () => { const revenue = createRevenueRecognition({ id: 'revenue:cf10', organizationId: org, amount: { currencyCode: 'EUR', minorUnits: 20_000 }, recognizedOn: '2032-04-01', category: 'SPONSORSHIP', provenance: source }); const expense = createExpenseRecognition({ id: 'expense:cf10:test', organizationId: org, amount: { currencyCode: 'EUR', minorUnits: 35_000 }, recognizedOn: '2032-04-02', category: 'FACILITY', provenance: source }); expect(assessFinancialRegulation(world({ revenueRecognitions: [revenue], expenseRecognitions: [expense] }), rule('OPERATING_LOSS', 10_000), org, '2032-10-01')).toMatchObject({ measuredValue: 15_000, state: 'BREACH' }) })
  it('reports missing revenue for payroll ratio instead of using Salary Cap', () => { const result = assessFinancialRegulation(world(), rule('PAYROLL_REVENUE_RATIO', 5000), org, '2032-10-01'); expect(result.state).toBe('INSUFFICIENT_DATA'); expect(result.measuredValue).toBeNull() })
  it('calculates payroll to revenue from CF5 and CF7 facts in basis points', () => { const revenue = createRevenueRecognition({ id: 'revenue:ratio:cf10', organizationId: org, amount: { currencyCode: 'EUR', minorUnits: 200_000 }, recognizedOn: '2032-05-01', category: 'SPONSORSHIP', provenance: source }); const payroll = createExpenseRecognition({ id: 'expense:payroll:cf10', organizationId: org, amount: { currencyCode: 'EUR', minorUnits: 120_000 }, recognizedOn: '2032-05-01', category: 'CONTRACT_PLAYER_SALARY_DUE', provenance: source }); const result = assessFinancialRegulation(world({ revenueRecognitions: [revenue], expenseRecognitions: [payroll] }), rule('PAYROLL_REVENUE_RATIO', 5000), org, '2032-10-01'); expect(result).toMatchObject({ measuredValue: 6000, state: 'BREACH' }); expect(result.supportingFactIds).toEqual([payroll.id, revenue.id].sort()) })
  it('reports absent cash-account evidence as insufficient data', () => { const current = createGameWorld(createValidGameWorldInput()); expect(assessFinancialRegulation(current, rule('MINIMUM_CASH', 1), org, '2032-10-01').state).toBe('INSUFFICIENT_DATA') })
  it('rejects assessment before a rule becomes effective', () => { expect(() => assessFinancialRegulation(world(), rule('MINIMUM_CASH', 1, '2028', '2033-01-01'), org, '2032-10-01')).toThrow() })
  it('keeps historical rule version in a recorded assessment', () => { const initial = world(); const oldRule = rule('MINIMUM_CASH', 50_000, '2027'); const nextRule = rule('MINIMUM_CASH', 120_000, '2028', '2033-01-01'); const old = assessFinancialRegulation(initial, oldRule, org, '2032-10-01'); const recorded = recordFinancialAssessment(initial, old); expect(getActiveFinancialRules([oldRule, nextRule], org, '2032-10-01')).toHaveLength(1); expect(recorded.financialRegulationAssessmentsById[old.id]?.ruleVersion).toBe('2027'); expect(recordFinancialAssessment(recorded, old)).toBe(recorded) })
  it('queries current warning and history without creating an order', () => { const initial = world(); const assessed = recordFinancialAssessment(initial, assessFinancialRegulation(initial, rule('MINIMUM_CASH', 120_000), org, '2032-10-01')); const status = getOrganizationFinancialRegulationStatus(assessed, org, '2032-10-01'); expect(status.breaches).toHaveLength(1); expect(status.warnings).toHaveLength(1); expect(status.outstandingRemediation).toHaveLength(0); expect(assessed.regulatoryOrdersById).toEqual({}) })
  it('routes only an authorized fine through expense, payable and ledger once', () => { const initial = world(); const fine = { id: 'sanction:cf10', authorityOrganizationId: org, organizationId: org, amount: { currencyCode: 'EUR' as never, minorUnits: 100_000 }, effectiveOn: '2032-10-01' as never, dueOn: '2032-11-01' as never, provenance: source }; const first = recordAuthorizedFinancialFine(initial, fine, { offsetAccountId: 'payable:cf10', resultAccountId: 'expense:cf10' }); expect(first.status).toBe('accepted'); expect(Object.values(first.world.expenseRecognitionsById)).toHaveLength(1); expect(Object.values(first.world.payablesById)).toHaveLength(1); expect(Object.values(first.world.financialTransactionsById)).toHaveLength(2); expect(recordAuthorizedFinancialFine(first.world, fine, { offsetAccountId: 'payable:cf10', resultAccountId: 'expense:cf10' }).status).toBe('alreadyProcessed'); expect(initial.expenseRecognitionsById).toEqual({}); const payable = Object.values(first.world.payablesById)[0]!; const payment = settlePayable(first.world, payable.id, { settlementId: 'settlement:fine:cf10', transactionId: 'transaction:fine:cf10', amount: payable.amount, settledOn: '2032-11-01', cashAccountId: 'cash:cf10', offsetAccountId: 'payable:cf10' }); const settled = updateGameWorld(first.world, { treasuryApplications: [...Object.values(first.world.treasuryApplicationsById), payment.settlement], financialTransactions: [...Object.values(first.world.financialTransactionsById), payment.transaction] }); expect(getPayableRemaining(settled, payable.id, '2032-11-01').minorUnits).toBe(0); expect(Object.values(settled.expenseRecognitionsById)).toHaveLength(1) })
})

describe('CF10 economic environment', () => {
  it('indexes only explicitly linked future money', () => { const amount = { currencyCode: 'EUR' as never, minorUnits: 100_000 }; expect(indexFutureMoney(amount, { kind: 'INDEXED', observationId: observation.id }, { [observation.id]: observation }, '2032-10-01').minorUnits).toBe(103_000); expect(indexFutureMoney(amount, { kind: 'FIXED' }, { [observation.id]: observation }, '2032-10-01')).toEqual(amount); expect(indexFutureMoney(amount, undefined, { [observation.id]: observation }, '2032-10-01')).toEqual(amount) })
  it('rejects an absent observation and an observation from the future', () => { const amount = { currencyCode: 'EUR' as never, minorUnits: 100_000 }; const policy = { kind: 'INDEXED' as const, observationId: observation.id }; expect(() => indexFutureMoney(amount, policy, {}, '2032-10-01')).toThrow(); expect(() => indexFutureMoney(amount, policy, { [observation.id]: observation }, '2031-12-31')).toThrow() })
  it('does not use a future observation as a known baseline fact', () => { const future = createEconomicObservation({ ...observation, effectiveOn: '2032-09-01' as never }); const cost = createOperatingCostSource({ id: 'cost:future-observation:cf10', organizationId: org, category: 'UTILITIES', currencyCode: 'EUR', amount: { currencyCode: 'EUR', minorUnits: 100_000 }, startsOn: '2032-10-01', endsOn: '2032-10-01', sourceAuthority: 'FACILITY', generationPolicy: 'ONE_OFF', indexation: { kind: 'INDEXED', observationId: future.id }, provenance: source }); const current = applyEconomicObservation(world({ operatingCostSources: [cost] }), future); expect(() => createFinancialForecast(current, { organizationId: org, asOfDate: '2032-06-01', period, currencyCode: 'EUR' })).toThrow(/observation is missing/) })
  it('rejects unsafe or zero economic factors', () => { expect(() => createEconomicFactor({ numerator: 0, denominator: 1 })).toThrow(); expect(() => createEconomicFactor({ numerator: 1.5, denominator: 1 })).toThrow() })
  it('returns dated regional economic context', () => { const current = applyEconomicObservation(world(), observation); expect(getEconomicEnvironmentSnapshot(current, 'EU', 'EUR', '2031-12-31').inflation).toBeNull(); expect(getEconomicEnvironmentSnapshot(current, 'EU', 'EUR', '2032-10-01').inflation?.id).toBe(observation.id) })
  it('converts by explicit rational FX while preserving original currency', () => { const rate = createExchangeRate({ id: 'fx:cf10', baseCurrencyCode: 'USD' as never, quoteCurrencyCode: 'EUR' as never, effectiveOn: '2032-10-01' as never, rate: { numerator: 9, denominator: 10 }, provenance: source }); const current = applyExchangeRate(world(), rate); const original = { currencyCode: 'USD' as never, minorUnits: 5_000_000 }; expect(convertForReporting(current, original, 'EUR', '2032-10-01')).toMatchObject({ amount: { currencyCode: 'EUR', minorUnits: 4_500_000 }, rateId: rate.id }); expect(original.minorUnits).toBe(5_000_000) })
  it('returns an explicit missing FX result', () => { expect(convertForReporting(world(), { currencyCode: 'USD' as never, minorUnits: 100 }, 'EUR', '2032-10-01')).toEqual({ missingRate: true, base: 'USD', quote: 'EUR' }) })
  it('does not use a future FX observation for an earlier reporting date', () => { const rate = createExchangeRate({ id: 'fx:future:cf10', baseCurrencyCode: 'USD' as never, quoteCurrencyCode: 'EUR' as never, effectiveOn: '2033-01-01' as never, rate: { numerator: 9, denominator: 10 }, provenance: source }); expect(convertForReporting(applyExchangeRate(world(), rate), { currencyCode: 'USD' as never, minorUnits: 100 }, 'EUR', '2032-10-01')).toHaveProperty('missingRate', true) })
  it('does not turn missing FX into a consolidated zero', () => { const result = getFinancialReportingTotal(world(), org, 'CASH', 'USD', '2032-10-01'); expect(result.complete).toBe(false); expect(result.missingCurrencies).toEqual(['EUR']) })
  it('changes a forecast from an indexed source without creating recognition', () => { const cost = createOperatingCostSource({ id: 'cost:cf10', organizationId: org, category: 'UTILITIES', currencyCode: 'EUR', amount: { currencyCode: 'EUR', minorUnits: 100_000 }, startsOn: '2032-10-01', endsOn: '2032-10-01', sourceAuthority: 'FACILITY', generationPolicy: 'ONE_OFF', dueDatePolicy: 'ON_RECOGNITION', indexation: { kind: 'INDEXED', observationId: observation.id }, provenance: source }); const current = applyEconomicObservation(world({ operatingCostSources: [cost] }), observation); const forecast = createFinancialForecast(current, { organizationId: org, asOfDate: '2032-06-01', period, currencyCode: 'EUR' }); expect(forecast.lines.find((item) => item.category === 'UTILITIES')?.amount.minorUnits).toBe(103_000); expect(current.expenseRecognitionsById).toEqual({}) })
  it('leaves an approved nominal budget unchanged while forecast moves', () => { const cost = createOperatingCostSource({ id: 'cost:budget:cf10', organizationId: org, category: 'UTILITIES', currencyCode: 'EUR', amount: { currencyCode: 'EUR', minorUnits: 100_000 }, startsOn: '2032-10-01', endsOn: '2032-10-01', sourceAuthority: 'FACILITY', generationPolicy: 'ONE_OFF', indexation: { kind: 'INDEXED', observationId: observation.id }, provenance: source }); const budget = createFinancialBudget({ id: 'budget:cf10', organizationId: org, currencyCode: 'EUR', period, status: 'APPROVED', label: '2032', createdOn: '2032-01-01', approval: { authorityKind: 'GOVERNANCE', authorityId: 'decision:budget:cf10', approvedOn: '2032-01-01', provenance: source }, provenance: source }); const line = createBudgetLine({ id: 'budget-line:cf10', budgetId: budget.id, organizationId: org, category: 'UTILITIES', direction: 'EXPENSE', amount: { currencyCode: 'EUR', minorUnits: 100_000 }, provenance: source }); const current = applyEconomicObservation(world({ operatingCostSources: [cost], financialBudgets: [budget], budgetLines: [line] }), observation); const forecast = createFinancialForecast(current, { organizationId: org, asOfDate: '2032-06-01', period, currencyCode: 'EUR' }); expect((forecast.lines.find((item) => item.category === 'UTILITIES')?.amount.minorUnits ?? 0) - line.amount.minorUnits).toBe(3_000); expect(current.budgetLinesById[line.id]?.amount.minorUnits).toBe(100_000) })
  it('keeps a fixed revenue source nominal in the forecast', () => { const revenue = createRevenueSource({ id: 'revenue:fixed:cf10', organizationId: org, category: 'SPONSORSHIP', currencyCode: 'EUR', amount: { currencyCode: 'EUR', minorUnits: 100_000 }, startsOn: '2032-10-01', endsOn: '2032-10-01', sourceAuthority: 'COMMERCIAL_CONTRACT', generationPolicy: 'ONE_OFF', dueDatePolicy: 'ON_RECOGNITION', indexation: { kind: 'FIXED' }, provenance: source }); const current = applyEconomicObservation(world({ revenueSources: [revenue] }), observation); expect(createFinancialForecast(current, { organizationId: org, asOfDate: '2032-06-01', period, currencyCode: 'EUR' }).lines.find((item) => item.category === 'SPONSORSHIP')?.amount.minorUnits).toBe(100_000) })
  it('accepts an explicit scenario factor without changing the world', () => { const cost = createOperatingCostSource({ id: 'cost:scenario:cf10', organizationId: org, category: 'UTILITIES', currencyCode: 'EUR', amount: { currencyCode: 'EUR', minorUnits: 100_000 }, startsOn: '2032-10-01', endsOn: '2032-10-01', sourceAuthority: 'FACILITY', generationPolicy: 'ONE_OFF', indexation: { kind: 'INDEXED', observationId: observation.id }, provenance: source }); const current = applyEconomicObservation(world({ operatingCostSources: [cost] }), observation); const alternate = { ...observation, factor: { numerator: 108, denominator: 100 } }; const projection = createFinancialForecast(current, { organizationId: org, asOfDate: '2032-06-01', period, currencyCode: 'EUR', scenario: 'UPSIDE', economicObservations: [alternate] }); expect(projection.lines.find((item) => item.category === 'UTILITIES')?.amount.minorUnits).toBe(108_000); expect(current.economicObservationsById[observation.id]?.factor.numerator).toBe(103) })
  it('uses explicit scenario FX only in a reporting forecast', () => { const revenue = createRevenueSource({ id: 'revenue:usd:cf10', organizationId: org, category: 'SPONSORSHIP', currencyCode: 'USD', amount: { currencyCode: 'USD', minorUnits: 100_000 }, startsOn: '2032-10-01', endsOn: '2032-10-01', sourceAuthority: 'COMMERCIAL_CONTRACT', generationPolicy: 'ONE_OFF', provenance: source }); const current = world({ revenueSources: [revenue] }); const input = { organizationId: org, asOfDate: '2032-06-01', period, reportingCurrencyCode: 'EUR', direction: 'INCOME' as const }; expect(getForecastReportingTotal(current, input).complete).toBe(false); const rate = createExchangeRate({ id: 'fx:scenario:cf10', baseCurrencyCode: 'USD' as never, quoteCurrencyCode: 'EUR' as never, effectiveOn: '2032-06-01' as never, rate: { numerator: 9, denominator: 10 }, provenance: source }); expect(getForecastReportingTotal(current, { ...input, scenario: 'DOWNSIDE', exchangeRates: [rate] })).toMatchObject({ complete: true, minorUnits: 90_000 }); expect(current.exchangeRatesById).toEqual({}) })
})
