import { describe, expect, it } from 'vitest'
import { createGameWorld } from '@/domain/world'
import { createValidGameWorldInput } from '@/domain/world/testFixtures'
import { createFinancialAccount, createFinancialTransaction } from './FinancialLedger'
import { createPayable, createReceivable } from './Treasury'
import { createRevenueRecognition, createExpenseRecognition } from './Recognition'
import { createExchangeRate } from './EconomicEnvironment'
import { createDebtInstrument } from './DebtEngine'
import { createFinancialBudget, createBudgetLine, createFinancialPlanningPeriod } from './BudgetForecasting'
import { getFinancialHealthSnapshot, assessFinancialHealth } from './FinancialHealth'
import { valueOrganization } from './OrganizationValuation'
import { getFinanceProposals, recommendFinanceActions, recordFinanceProposal, resolveFinanceProposal } from './FinanceAI'
import { deserializeGameWorldV4, serializeGameWorldV4 } from '@/save/GameWorldSaveV4'

const organizationId = 'team-home'
const source = { kind: 'CF11_TEST', id: 'fixture' }
const accounts = [createFinancialAccount({ id: 'cf11:cash', organizationId, accountType: 'CASH', currencyCode: 'EUR', openedOn: '2032-01-01' }), createFinancialAccount({ id: 'cf11:equity', organizationId, accountType: 'EQUITY', currencyCode: 'EUR', openedOn: '2032-01-01' })]
const opening = (minorUnits: number) => createFinancialTransaction({ id: 'cf11:opening', organizationId, effectiveOn: '2032-01-01', transactionType: 'OWNER_FUNDING_RECEIPT', amount: { currencyCode: 'EUR', minorUnits }, postings: [{ accountId: accounts[0]!.id, direction: 'DEBIT', amount: { currencyCode: 'EUR', minorUnits } }, { accountId: accounts[1]!.id, direction: 'CREDIT', amount: { currencyCode: 'EUR', minorUnits } }], provenance: source })
const world = (cash = 1_000_000, extra: Record<string, unknown> = {}) => createGameWorld({ ...createValidGameWorldInput(), financialAccounts: accounts, financialTransactions: cash > 0 ? [opening(cash)] : [], ...extra })
const payable = (amount: number, dueOn = '2032-10-15') => createPayable({ id: `cf11:payable:${amount}`, organizationId, amount: { currencyCode: 'EUR', minorUnits: amount }, recognizedOn: '2032-09-01', dueOn, counterparty: { kind: 'EXTERNAL', label: 'Supplier' }, provenance: source })
const assumptions = { id: 'cf11:multiple', method: 'REVENUE_MULTIPLE' as const, multipleNumerator: 3, multipleDenominator: 1, provenance: source }
const policy = { id: 'cf11:balanced', version: '1', recommendFinancingForShortfall: true, recommendCapitalForShortfall: false, recommendDeferringSpendForShortfall: true, recommendBudgetRevisionForAnyProjectedVariance: true }

describe('CF11 health', () => {
  it('reports funded liquidity without a crisis signal', () => { const result = getFinancialHealthSnapshot(world(5_000_000, { payables: [payable(1_000_000)] }), organizationId, '2032-10-01', '2032-01-01'); expect(result.byCurrency[0]).toMatchObject({ unrestrictedCashMinorUnits: 5_000_000, shortTermPayablesMinorUnits: 1_000_000, liquidityShortfallMinorUnits: 0 }); expect(result.distressIndicators).toHaveLength(0) })
  it('reports a shortfall and does not create bankruptcy state', () => { const current = world(1_000_000, { payables: [payable(3_000_000)] }); const result = getFinancialHealthSnapshot(current, organizationId, '2032-10-01', '2032-01-01'); expect(result.byCurrency[0]?.liquidityShortfallMinorUnits).toBe(2_000_000); expect(result.distressIndicators.map((item) => item.kind)).toContain('LIQUIDITY_SHORTFALL'); expect(current.organizationsById[organizationId as keyof typeof current.organizationsById]).toBeDefined() })
  it('uses receivables and excludes future recognized obligations', () => { const receivable = createReceivable({ id: 'cf11:receivable', organizationId, amount: { currencyCode: 'EUR', minorUnits: 1_000_000 }, recognizedOn: '2032-09-01', dueOn: '2032-10-15', counterparty: { kind: 'EXTERNAL', label: 'Sponsor' }, provenance: source }); const current = world(1_000_000, { payables: [payable(3_000_000)], receivables: [receivable] }); expect(getFinancialHealthSnapshot(current, organizationId, '2032-10-01', '2032-01-01').byCurrency[0]?.liquidityShortfallMinorUnits).toBe(1_000_000) })
  it('separates operating loss from owner funding', () => { const expense = createExpenseRecognition({ id: 'cf11:expense', organizationId, amount: { currencyCode: 'EUR', minorUnits: 1_500_000 }, recognizedOn: '2032-09-01', category: 'FACILITY', provenance: source }); const row = getFinancialHealthSnapshot(world(2_000_000, { expenseRecognitions: [expense] }), organizationId, '2032-10-01', '2032-01-01').byCurrency[0]!; expect(row.operatingResultMinorUnits).toBe(-1_500_000); expect(row.ownerFundingDependenceMinorUnits).toBe(1_500_000) })
  it('applies only explicit versioned thresholds', () => { const snapshot = getFinancialHealthSnapshot(world(), organizationId, '2032-10-01', '2032-01-01'); expect(assessFinancialHealth(snapshot, { id: 'local', version: '1' }).state).toBe('HEALTHY'); expect(() => assessFinancialHealth(snapshot, { id: 'local', version: '1', maximumDebtRevenueRatio: -1 })).toThrow() })
  it('reports overdue payables separately from future dues', () => { const row = getFinancialHealthSnapshot(world(1_000_000, { payables: [payable(500_000, '2032-09-30')] }), organizationId, '2032-10-01', '2032-01-01').byCurrency[0]!; expect(row.overduePayablesMinorUnits).toBe(500_000); expect(row.shortTermPayablesMinorUnits).toBe(500_000) })
  it('excludes recognition that occurs after the historical date', () => { const later = createRevenueRecognition({ id: 'cf11:future', organizationId, amount: { currencyCode: 'EUR', minorUnits: 9_000_000 }, recognizedOn: '2032-11-01', category: 'MEDIA', provenance: source }); expect(getFinancialHealthSnapshot(world(1_000_000, { revenueRecognitions: [later] }), organizationId, '2032-10-01', '2032-01-01').byCurrency[0]?.operatingRevenueMinorUnits).toBe(0) })
  it('reports debt maturity and outstanding principal from CF9 facts', () => { const liability = createFinancialAccount({ id: 'cf11:debt-account', organizationId, accountType: 'LIABILITY', currencyCode: 'EUR', openedOn: '2032-01-01' }); const debt = createDebtInstrument({ id: 'cf11:debt', organizationId, lender: { kind: 'EXTERNAL', label: 'Bank' }, debtType: 'TERM_LOAN', currencyCode: 'EUR', originalPrincipal: { currencyCode: 'EUR', minorUnits: 2_000_000 }, startsOn: '2032-09-01', maturityOn: '2032-10-20', provenance: source }); const draw = createFinancialTransaction({ id: 'cf11:draw', organizationId, effectiveOn: '2032-09-01', transactionType: 'DEBT_DRAWDOWN', amount: { currencyCode: 'EUR', minorUnits: 2_000_000 }, postings: [{ accountId: accounts[0]!.id, direction: 'DEBIT', amount: { currencyCode: 'EUR', minorUnits: 2_000_000 } }, { accountId: liability.id, direction: 'CREDIT', amount: { currencyCode: 'EUR', minorUnits: 2_000_000 } }], provenance: source, dimensions: { reference: { kind: 'DEBT_INSTRUMENT', id: debt.id } } }); const row = getFinancialHealthSnapshot(world(0, { financialAccounts: [...accounts, liability], financialTransactions: [draw], debtInstruments: [debt] }), organizationId, '2032-10-01', '2032-01-01').byCurrency[0]!; expect(row.outstandingDebtMinorUnits).toBe(2_000_000); expect(row.debtMaturityBurdenMinorUnits).toBe(2_000_000); expect(row.netDebtMinorUnits).toBe(0) })
  it('rejects an unknown Organization and reversed observation period', () => { expect(() => getFinancialHealthSnapshot(world(), 'missing', '2032-10-01', '2032-01-01')).toThrow(); expect(() => getFinancialHealthSnapshot(world(), organizationId, '2032-01-01', '2032-10-01')).toThrow() })
  it('keeps currencies separate in the health snapshot', () => { const usd = createRevenueRecognition({ id: 'cf11:usd:health', organizationId, amount: { currencyCode: 'USD', minorUnits: 1_000_000 }, recognizedOn: '2032-09-01', category: 'MEDIA', provenance: source }); const rows = getFinancialHealthSnapshot(world(2_000_000, { revenueRecognitions: [usd] }), organizationId, '2032-10-01', '2032-01-01').byCurrency; expect(rows.map((row) => row.currencyCode)).toEqual(['EUR', 'USD']); expect(rows[0]?.operatingRevenueMinorUnits).toBe(0); expect(rows[1]?.operatingRevenueMinorUnits).toBe(1_000_000) })
})

describe('CF11 valuation', () => {
  const revenue = createRevenueRecognition({ id: 'cf11:revenue', organizationId, amount: { currencyCode: 'EUR', minorUnits: 20_000_000 }, recognizedOn: '2032-09-01', category: 'SPONSORSHIP', provenance: source })
  it('requires an explicit multiple', () => expect(valueOrganization(world(0, { revenueRecognitions: [revenue] }), { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', reportingCurrencyCode: 'EUR' })).toBeNull())
  it('separates enterprise and indicative equity value', () => { const valuation = valueOrganization(world(5_000_000, { revenueRecognitions: [revenue] }), { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', reportingCurrencyCode: 'EUR', assumptions }); expect(valuation?.enterpriseValue?.minorUnits).toBe(60_000_000); expect(valuation?.indicativeEquityValue?.minorUnits).toBe(65_000_000); expect(valuation?.components.map((item) => item.original.currencyCode)).toEqual(['EUR', 'EUR', 'EUR']) })
  it('subtracts 15M of net debt from 60M enterprise value', () => { const liability = createFinancialAccount({ id: 'cf11:valuation-debt', organizationId, accountType: 'LIABILITY', currencyCode: 'EUR', openedOn: '2032-01-01' }); const asset = createFinancialAccount({ id: 'cf11:valuation-asset', organizationId, accountType: 'ASSET', currencyCode: 'EUR', openedOn: '2032-01-01' }); const debt = createDebtInstrument({ id: 'cf11:valuation-loan', organizationId, lender: { kind: 'EXTERNAL', label: 'Bank' }, debtType: 'TERM_LOAN', currencyCode: 'EUR', originalPrincipal: { currencyCode: 'EUR', minorUnits: 20_000_000 }, startsOn: '2032-09-01', maturityOn: '2033-09-01', provenance: source }); const draw = createFinancialTransaction({ id: 'cf11:valuation-draw', organizationId, effectiveOn: '2032-09-01', transactionType: 'DEBT_DRAWDOWN', amount: { currencyCode: 'EUR', minorUnits: 20_000_000 }, postings: [{ accountId: accounts[0]!.id, direction: 'DEBIT', amount: { currencyCode: 'EUR', minorUnits: 20_000_000 } }, { accountId: liability.id, direction: 'CREDIT', amount: { currencyCode: 'EUR', minorUnits: 20_000_000 } }], provenance: source, dimensions: { reference: { kind: 'DEBT_INSTRUMENT', id: debt.id } } }); const spend = createFinancialTransaction({ id: 'cf11:valuation-spend', organizationId, effectiveOn: '2032-09-02', transactionType: 'CAPITAL_EXPENDITURE', amount: { currencyCode: 'EUR', minorUnits: 20_000_000 }, postings: [{ accountId: asset.id, direction: 'DEBIT', amount: { currencyCode: 'EUR', minorUnits: 20_000_000 } }, { accountId: accounts[0]!.id, direction: 'CREDIT', amount: { currencyCode: 'EUR', minorUnits: 20_000_000 } }], provenance: { kind: source.kind, id: 'spend' } }); const current = world(5_000_000, { financialAccounts: [...accounts, liability, asset], financialTransactions: [opening(5_000_000), draw, spend], debtInstruments: [debt], revenueRecognitions: [revenue] }); const valuation = valueOrganization(current, { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', reportingCurrencyCode: 'EUR', assumptions }); expect(valuation?.enterpriseValue?.minorUnits).toBe(60_000_000); expect(valuation?.indicativeEquityValue?.minorUnits).toBe(45_000_000) })
  it('returns partial result when FX is missing', () => { const usd = createRevenueRecognition({ id: 'cf11:usd', organizationId, amount: { currencyCode: 'USD', minorUnits: 10_000_000 }, recognizedOn: '2032-09-01', category: 'MEDIA', provenance: { kind: source.kind, id: 'usd' } }); const valuation = valueOrganization(world(0, { revenueRecognitions: [revenue, usd] }), { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', reportingCurrencyCode: 'EUR', assumptions }); expect(valuation?.complete).toBe(false); expect(valuation?.missingCurrencies).toEqual(['USD']); expect(valuation?.indicativeEquityValue).toBeNull() })
  it('uses only FX known as of the valuation date', () => { const usd = createRevenueRecognition({ id: 'cf11:usd', organizationId, amount: { currencyCode: 'USD', minorUnits: 10_000_000 }, recognizedOn: '2032-09-01', category: 'MEDIA', provenance: source }); const rate = createExchangeRate({ id: 'cf11:fx', baseCurrencyCode: 'USD' as never, quoteCurrencyCode: 'EUR' as never, effectiveOn: '2032-10-01' as never, rate: { numerator: 9, denominator: 10 }, provenance: source }); const valuation = valueOrganization(world(0, { revenueRecognitions: [usd], exchangeRates: [rate] }), { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', reportingCurrencyCode: 'EUR', assumptions }); expect(valuation?.enterpriseValue?.minorUnits).toBe(27_000_000) })
  it('rejects invalid multiples', () => expect(() => valueOrganization(world(0, { revenueRecognitions: [revenue] }), { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', reportingCurrencyCode: 'EUR', assumptions: { ...assumptions, multipleDenominator: 0 } })).toThrow())
  it('does not value nonpositive earnings with an earnings multiple', () => { const result = valueOrganization(world(0, { revenueRecognitions: [revenue] }), { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', reportingCurrencyCode: 'EUR', assumptions: { ...assumptions, method: 'OPERATING_RESULT_MULTIPLE' } }); expect(result?.enterpriseValue?.minorUnits).toBe(60_000_000); const expense = createExpenseRecognition({ id: 'cf11:large-cost', organizationId, amount: { currencyCode: 'EUR', minorUnits: 25_000_000 }, recognizedOn: '2032-09-01', category: 'FACILITY', provenance: source }); expect(valueOrganization(world(0, { expenseRecognitions: [expense] }), { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', reportingCurrencyCode: 'EUR', assumptions: { ...assumptions, method: 'OPERATING_RESULT_MULTIPLE' } })).toBeNull() })
  it('does not use future FX rates for a historical valuation', () => { const usd = createRevenueRecognition({ id: 'cf11:usd:future-fx', organizationId, amount: { currencyCode: 'USD', minorUnits: 10_000_000 }, recognizedOn: '2032-09-01', category: 'MEDIA', provenance: source }); const futureRate = createExchangeRate({ id: 'cf11:future-fx', baseCurrencyCode: 'USD' as never, quoteCurrencyCode: 'EUR' as never, effectiveOn: '2032-11-01' as never, rate: { numerator: 9, denominator: 10 }, provenance: source }); const result = valueOrganization(world(0, { revenueRecognitions: [usd], exchangeRates: [futureRate] }), { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', reportingCurrencyCode: 'EUR', assumptions }); expect(result?.complete).toBe(false) })
})

describe('CF11 finance AI', () => {
  it('recommends action without creating debt, capital or a budget', () => { const current = world(1_000_000, { payables: [payable(3_000_000)] }); const proposals = recommendFinanceActions(current, { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', policy }); expect(proposals.map((item) => item.actionType)).toContain('RECOMMEND_FINANCING'); expect(current.debtInstrumentsById).toEqual({}); expect(current.financialBudgetsById).toEqual({}) })
  it('produces identical advice from identical inputs and no crisis for a healthy club', () => { const current = world(5_000_000); const input = { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', policy }; expect(recommendFinanceActions(current, input)).toEqual(recommendFinanceActions(current, input)); expect(recommendFinanceActions(current, input)).toEqual([]) })
  it('records a gameplay proposal and gates approval on Governance', () => { const current = world(1_000_000, { payables: [payable(3_000_000)] }); const recommendation = recommendFinanceActions(current, { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', policy }).find((item) => item.actionType === 'RECOMMEND_FINANCING')!; const recorded = recordFinanceProposal(current, recommendation); expect(getFinanceProposals(recorded, organizationId, 'RECOMMENDED')).toHaveLength(1); expect(() => resolveFinanceProposal(recorded, recommendation.id, 'APPROVED')).toThrow(); expect(recorded.debtInstrumentsById).toEqual({}) })
  it('round trips proposals and defaults older V4 saves', () => { const current = world(1_000_000, { payables: [payable(3_000_000)] }); const proposal = recommendFinanceActions(current, { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', policy })[0]!; const recorded = recordFinanceProposal(current, proposal); const save = serializeGameWorldV4(recorded, '2032-10-01T00:00:00.000Z'); expect(deserializeGameWorldV4(save).financeDecisionProposalsById[proposal.id]).toEqual(proposal); const legacy = { ...save, payload: { ...save.payload, financeDecisionProposals: undefined } }; delete (legacy.payload as { financeDecisionProposals?: unknown }).financeDecisionProposals; expect(deserializeGameWorldV4(legacy).financeDecisionProposalsById).toEqual({}) })
  it('recommends revision for an approved overrun without changing the budget', () => { const period = createFinancialPlanningPeriod({ kind: 'DATE_RANGE', startsOn: '2032-01-01', endsOn: '2032-12-31' }); const budget = createFinancialBudget({ id: 'cf11:budget', organizationId, currencyCode: 'EUR', period, status: 'APPROVED', label: 'Season', createdOn: '2032-01-01', approval: { authorityKind: 'GOVERNANCE', authorityId: 'board', approvedOn: '2032-01-01', provenance: source }, provenance: source }); const line = createBudgetLine({ id: 'cf11:budget-line', budgetId: budget.id, organizationId, category: 'FACILITY', direction: 'EXPENSE', amount: { currencyCode: 'EUR', minorUnits: 100_000 }, provenance: source }); const expense = createExpenseRecognition({ id: 'cf11:overrun', organizationId, amount: { currencyCode: 'EUR', minorUnits: 200_000 }, recognizedOn: '2032-09-01', category: 'FACILITY', provenance: source }); const current = world(5_000_000, { financialBudgets: [budget], budgetLines: [line], expenseRecognitions: [expense] }); const proposals = recommendFinanceActions(current, { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', budgetPeriod: period, policy }); expect(proposals.some((item) => item.actionType === 'RECOMMEND_BUDGET_REVISION')).toBe(true); expect(current.financialBudgetsById[budget.id]?.status).toBe('APPROVED') })
  it('can reject a recorded proposal without mutating financial facts', () => { const current = world(1_000_000, { payables: [payable(3_000_000)] }); const proposal = recommendFinanceActions(current, { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', policy })[0]!; const rejected = resolveFinanceProposal(recordFinanceProposal(current, proposal), proposal.id, 'REJECTED'); expect(getFinanceProposals(rejected, organizationId, 'REJECTED')).toHaveLength(1); expect(rejected.financialTransactionsById).toEqual(current.financialTransactionsById) })
  it('records the same proposal idempotently', () => { const current = world(1_000_000, { payables: [payable(3_000_000)] }); const proposal = recommendFinanceActions(current, { organizationId, asOfDate: '2032-10-01', periodStartsOn: '2032-01-01', policy })[0]!; const recorded = recordFinanceProposal(current, proposal); expect(recordFinanceProposal(recorded, proposal)).toBe(recorded) })
  it('rejects malformed proposal data on save load', () => { const save = serializeGameWorldV4(world(), '2032-10-01T00:00:00.000Z'); const malformed = { ...save, payload: { ...save.payload, financeDecisionProposals: [{ id: 'bad', organizationId, asOfDate: '2032-10-01', actionType: 'UNSUPPORTED', evidence: [], expectedFinancialImpact: null, risks: [], authorityRequired: 'NONE', responsibleActor: null, governanceDecisionId: null, status: 'RECOMMENDED', provenance: source }] } }; expect(() => deserializeGameWorldV4(malformed)).toThrow() })
})
