import { describe, expect, it } from 'vitest'
import { createValidGameWorldInput } from '@/domain/world/testFixtures'
import { createGameWorld } from '@/domain/world'
import { createFinancialAccount } from './FinancialLedger'
import { createCompetitionDistributionFact, createCompetitionParticipationFeeFact, getCompetitionFees, getCompetitionRevenue, materializeCompetitionEconomyForDate, materializeCompetitionInterOrganizationTransfer, materializeCompetitionParticipationFeesForDate } from './CompetitionEconomy'

function accounts() { return [
  createFinancialAccount({ id: 'cash:home', organizationId: 'team-home', accountType: 'CASH', currencyCode: 'EUR', openedOn: '2032-01-01' }), createFinancialAccount({ id: 'receivable:home', organizationId: 'team-home', accountType: 'RECEIVABLE', currencyCode: 'EUR', openedOn: '2032-01-01' }), createFinancialAccount({ id: 'revenue:home', organizationId: 'team-home', accountType: 'REVENUE', currencyCode: 'EUR', openedOn: '2032-01-01' }), createFinancialAccount({ id: 'payable:home', organizationId: 'team-home', accountType: 'PAYABLE', currencyCode: 'EUR', openedOn: '2032-01-01' }), createFinancialAccount({ id: 'expense:home', organizationId: 'team-home', accountType: 'EXPENSE', currencyCode: 'EUR', openedOn: '2032-01-01' }),
  createFinancialAccount({ id: 'cash:away', organizationId: 'team-away', accountType: 'CASH', currencyCode: 'EUR', openedOn: '2032-01-01' }), createFinancialAccount({ id: 'expense:away', organizationId: 'team-away', accountType: 'EXPENSE', currencyCode: 'EUR', openedOn: '2032-01-01' }), createFinancialAccount({ id: 'revenue:away', organizationId: 'team-away', accountType: 'REVENUE', currencyCode: 'EUR', openedOn: '2032-01-01' }),
] }
function world(extra: Partial<ReturnType<typeof createValidGameWorldInput>> = {}) { return createGameWorld({ ...createValidGameWorldInput(), financialAccounts: accounts(), ...extra }) }
const provenance = { kind: 'CF9_TEST', id: 'competition-fact' }

describe('CF9 competition economy', () => {
  it.each(['PRIZE', 'PARTICIPATION_DISTRIBUTION', 'MEDIA_DISTRIBUTION', 'SOLIDARITY', 'REVENUE_SHARE', 'LEAGUE_DISTRIBUTION', 'DEVELOPMENT_PAYMENT', 'OTHER_DISTRIBUTION'] as const)('accepts only an authorized fact for category %s', (category) => { const fact = createCompetitionDistributionFact({ id: `distribution:${category}`, competitionId: 'competition-a', seasonId: 'season-a', recipientOrganizationId: 'team-home', recipientTeamId: 'team-home', amount: { currencyCode: 'EUR', minorUnits: 100 }, category, effectiveOn: '2032-10-02', dueOn: '2032-10-02', sourceRule: `rule-${category}`, provenance: { kind: 'CF9_TEST', id: category } }); expect(fact.category).toBe(category); expect(fact.amount.minorUnits).toBe(100) })
  it('consumes an authorized distribution fact through CF4 and CF3', () => { const fact = createCompetitionDistributionFact({ id: 'distribution:prize', competitionId: 'competition-a', seasonId: 'season-a', recipientOrganizationId: 'team-home', recipientTeamId: 'team-home', amount: { currencyCode: 'EUR', minorUnits: 25_000 }, category: 'PRIZE', effectiveOn: '2032-10-02', dueOn: '2032-10-03', sourceRule: 'authorized-league-rule-1', provenance }); const result = materializeCompetitionEconomyForDate(world({ competitionDistributionFacts: [fact] }), '2032-10-02', { organizationId: 'team-home', ledger: { receivableAccountId: 'receivable:home', revenueAccountId: 'revenue:home' } }); expect(result.status).toBe('accepted'); expect(Object.values(result.world.revenueRecognitionsById)[0]?.amount.minorUnits).toBe(25_000); expect(getCompetitionRevenue(result.world, { organizationId: 'team-home', from: '2032-10-01', to: '2032-10-31' })).toEqual([{ category: 'PRIZE', currencyCode: 'EUR', minorUnits: 25_000 }]); expect(materializeCompetitionEconomyForDate(result.world, '2032-10-02', { organizationId: 'team-home', ledger: { receivableAccountId: 'receivable:home', revenueAccountId: 'revenue:home' } }).status).toBe('alreadyProcessed') })
  it('routes participation fees through the CF8 operating-cost path', () => { const fact = createCompetitionParticipationFeeFact({ id: 'fee:season', competitionId: 'competition-a', seasonId: 'season-a', organizationId: 'team-home', amount: { currencyCode: 'EUR', minorUnits: 4_000 }, effectiveOn: '2032-10-02', dueOn: '2032-10-02', sourceRule: 'authorized-fee-rule', provenance }); const result = materializeCompetitionParticipationFeesForDate(world({ competitionDistributionFacts: [fact] }), '2032-10-02', { organizationId: 'team-home', ledger: { payableAccountId: 'payable:home', expenseAccountId: 'expense:home' } }); expect(result.status).toBe('accepted'); expect(Object.values(result.world.expenseRecognitionsById)[0]?.category).toBe('COMPETITION'); expect(Object.values(result.world.operatingCostFactsById)).toHaveLength(1) })
  it('queries competition fees and preserves source-rule provenance', () => { const fact = createCompetitionParticipationFeeFact({ id: 'fee:query', competitionId: 'competition-a', seasonId: 'season-a', organizationId: 'team-home', amount: { currencyCode: 'EUR', minorUnits: 3_000 }, effectiveOn: '2032-10-02', dueOn: '2032-10-02', sourceRule: 'db-fee-rule', provenance: { kind: 'CF9_TEST', id: 'fee-query' } }); const result = materializeCompetitionParticipationFeesForDate(world({ competitionDistributionFacts: [fact] }), '2032-10-02', { organizationId: 'team-home', ledger: { payableAccountId: 'payable:home', expenseAccountId: 'expense:home' } }); expect(result.facts[0]?.sourceRule).toBe('db-fee-rule'); expect(getCompetitionFees(result.world, { organizationId: 'team-home', from: '2032-10-01', to: '2032-10-31' })).toEqual([{ currencyCode: 'EUR', minorUnits: 3_000 }]) })
  it('supports a linked inter-organization transfer without creating value twice', () => { const fact = createCompetitionDistributionFact({ id: 'distribution:transfer', competitionId: 'competition-a', seasonId: 'season-a', recipientOrganizationId: 'team-away', recipientTeamId: 'team-away', payerOrganizationId: 'team-home', amount: { currencyCode: 'EUR', minorUnits: 6_000 }, category: 'SOLIDARITY', effectiveOn: '2032-10-02', dueOn: '2032-10-02', sourceRule: 'authorized-solidarity-rule', provenance }); const result = materializeCompetitionInterOrganizationTransfer(world({ competitionDistributionFacts: [fact] }), { factId: fact.id, effectiveOn: '2032-10-02', payerLedger: { cashAccountId: 'cash:home', expenseAccountId: 'expense:home' }, recipientLedger: { cashAccountId: 'cash:away', revenueAccountId: 'revenue:away' } }); expect(Object.values(result.financialTransactionsById).filter((item) => item.provenance.id === fact.id)).toHaveLength(2); expect(Object.values(result.financialTransactionsById).filter((item) => item.transactionType === 'COMPETITION_TRANSFER_OUTFLOW')[0]?.amount.minorUnits).toBe(6_000); expect(Object.values(result.financialTransactionsById).filter((item) => item.transactionType === 'COMPETITION_TRANSFER_INFLOW')[0]?.amount.minorUnits).toBe(6_000) })
  it('rejects unsupported recipient organizations and missing due dates', () => { const fact = createCompetitionDistributionFact({ id: 'distribution:bad', competitionId: 'competition-a', seasonId: 'season-a', recipientOrganizationId: 'team-home', recipientTeamId: 'team-home', amount: { currencyCode: 'EUR', minorUnits: 1 }, category: 'MEDIA_DISTRIBUTION', effectiveOn: '2032-10-02', sourceRule: 'rule', provenance }); expect(() => createGameWorld({ ...createValidGameWorldInput(), financialAccounts: accounts(), competitionDistributionFacts: [{ ...fact, recipientOrganizationId: 'unknown-org' as never }] })).toThrow(); const result = materializeCompetitionEconomyForDate(world({ competitionDistributionFacts: [fact] }), '2032-10-02', { organizationId: 'team-home', ledger: { receivableAccountId: 'receivable:home', revenueAccountId: 'revenue:home' } }); expect(result.status).toBe('rejected') })
  it('does not invent a distribution when the Competition fact is absent', () => { const result = materializeCompetitionEconomyForDate(world(), '2032-10-02', { organizationId: 'team-home', ledger: { receivableAccountId: 'receivable:home', revenueAccountId: 'revenue:home' } }); expect(result.status).toBe('accepted'); expect(result.facts).toHaveLength(0); expect(Object.keys(result.world.revenueRecognitionsById)).toHaveLength(0) })
})
