import { describe, expect, it } from 'vitest'
import { createValidGameWorldInput } from '@/domain/world/testFixtures'
import { createGameWorld } from '@/domain/world'
import { createFinancialAccount } from './FinancialLedger'
import { createDebtInstrument, getActiveDebtInstruments, getDebtInterestPaid, getDebtInterestRecognized, getDebtMaturities, getDebtSchedule, getDebtServiceForecast, getFinancingTransactions, getOutstandingPrincipal, materializeCapitalContribution, materializeDebtFinanceForDate, materializeOwnerDistribution } from './DebtEngine'

function accounts() { return [
  createFinancialAccount({ id: 'cash:eur', organizationId: 'team-home', accountType: 'CASH', currencyCode: 'EUR', openedOn: '2032-01-01' }),
  createFinancialAccount({ id: 'debt:eur', organizationId: 'team-home', accountType: 'LIABILITY', currencyCode: 'EUR', openedOn: '2032-01-01' }),
  createFinancialAccount({ id: 'payable:eur', organizationId: 'team-home', accountType: 'PAYABLE', currencyCode: 'EUR', openedOn: '2032-01-01' }),
  createFinancialAccount({ id: 'interest:eur', organizationId: 'team-home', accountType: 'EXPENSE', currencyCode: 'EUR', openedOn: '2032-01-01' }),
  createFinancialAccount({ id: 'equity:eur', organizationId: 'team-home', accountType: 'EQUITY', currencyCode: 'EUR', openedOn: '2032-01-01' }),
] }
function world(extra: Partial<ReturnType<typeof createValidGameWorldInput>> = {}) { return createGameWorld({ ...createValidGameWorldInput(), financialAccounts: accounts(), ...extra }) }
const debt = createDebtInstrument({ id: 'debt:loan-1', organizationId: 'team-home', lender: { kind: 'EXTERNAL', label: 'Bank' }, debtType: 'TERM_LOAN', currencyCode: 'EUR', originalPrincipal: { currencyCode: 'EUR', minorUnits: 100_000 }, startsOn: '2032-10-01', maturityOn: '2032-10-03', interest: { kind: 'EXPLICIT_SCHEDULE', entries: [{ recognitionOn: '2032-10-02', dueOn: '2032-10-03', amount: { currencyCode: 'EUR', minorUnits: 2_000 } }] }, provenance: { kind: 'CF9_TEST', id: 'loan' } })
const ledger = { cashAccountId: 'cash:eur', debtLiabilityAccountId: 'debt:eur', interestPayableAccountId: 'payable:eur', interestExpenseAccountId: 'interest:eur' }

describe('CF9 debt and capital engine', () => {
  it.each(['TERM_LOAN', 'CREDIT_FACILITY', 'OWNER_LOAN', 'BRIDGE_FINANCING', 'OTHER_DEBT'] as const)('accepts the explicit debt type %s without changing monetary semantics', (debtType) => { const item = createDebtInstrument({ ...debt, id: `debt:type:${debtType}`, debtType }); expect(item.debtType).toBe(debtType); expect(item.originalPrincipal.minorUnits).toBe(100_000) })
  it('derives a deterministic debt schedule and keeps principal separate from interest', () => { const current = world({ debtInstruments: [debt] }); expect(getDebtSchedule(current, debt.id).map((entry) => [entry.kind, entry.effectiveOn, entry.amount.minorUnits])).toEqual([['DRAWDOWN', '2032-10-01', 100_000], ['INTEREST', '2032-10-02', 2_000], ['PRINCIPAL_REPAYMENT', '2032-10-03', 100_000]]); const drawn = materializeDebtFinanceForDate(current, '2032-10-01', { organizationId: 'team-home', ledger }); expect(drawn.status).toBe('accepted'); expect(getOutstandingPrincipal(drawn.world, debt.id, '2032-10-01').minorUnits).toBe(100_000); const interest = materializeDebtFinanceForDate(drawn.world, '2032-10-02', { organizationId: 'team-home', ledger }); expect(interest.status).toBe('accepted'); expect(Object.values(interest.world.expenseRecognitionsById)[0]?.category).toBe('INTEREST_EXPENSE'); const paid = materializeDebtFinanceForDate(interest.world, '2032-10-03', { organizationId: 'team-home', ledger }); expect(paid.status).toBe('accepted'); expect(getOutstandingPrincipal(paid.world, debt.id, '2032-10-03').minorUnits).toBe(0) })
  it('is idempotent and rejects principal repayment that exceeds the derived balance', () => { const overpay = createDebtInstrument({ ...debt, id: 'debt:overpay', startsOn: '2032-09-01', originalPrincipal: { currencyCode: 'EUR', minorUnits: 50_000 }, repayment: { kind: 'EXPLICIT_SCHEDULE', entries: [{ repaymentOn: '2032-10-03', amount: { currencyCode: 'EUR', minorUnits: 50_000 } }] } }); const current = world({ debtInstruments: [overpay] }); const drawn = materializeDebtFinanceForDate(current, '2032-09-01', { organizationId: 'team-home', debtId: 'debt:overpay', ledger }); expect(drawn.status).toBe('accepted'); const secondRetry = materializeDebtFinanceForDate(drawn.world, '2032-09-01', { organizationId: 'team-home', debtId: 'debt:overpay', ledger }); expect(secondRetry.status).toBe('alreadyProcessed'); const repayment = materializeDebtFinanceForDate(current, '2032-10-03', { organizationId: 'team-home', debtId: 'debt:overpay', ledger }); expect(repayment.status).toBe('rejected') })
  it('forecasts debt service without creating ledger transactions', () => { const current = world({ debtInstruments: [debt] }); expect(getDebtServiceForecast(current, { organizationId: 'team-home', from: '2032-10-01', to: '2032-10-03', currencyCode: 'EUR' })).toEqual([{ effectiveOn: '2032-10-02', currencyCode: 'EUR', principalMinorUnits: 0, interestMinorUnits: 2_000, cashOutflowMinorUnits: 2_000 }, { effectiveOn: '2032-10-03', currencyCode: 'EUR', principalMinorUnits: 100_000, interestMinorUnits: 0, cashOutflowMinorUnits: 100_000 }]) })
  it('keeps owner funding, owner loans and distributions explicit', () => { const contribution = materializeCapitalContribution(world(), { organizationId: 'team-home', amount: { currencyCode: 'EUR', minorUnits: 10_000 }, effectiveOn: '2032-10-01', sourceEntityId: 'capital:1', provenance: { kind: 'CF9_TEST', id: 'capital' }, cashAccountId: 'cash:eur', equityAccountId: 'equity:eur' }); expect(Object.values(contribution.financialTransactionsById)[0]?.transactionType).toBe('OWNER_FUNDING_RECEIPT'); const distribution = materializeOwnerDistribution(contribution, { organizationId: 'team-home', amount: { currencyCode: 'EUR', minorUnits: 1_000 }, effectiveOn: '2032-10-02', sourceEntityId: 'distribution:1', provenance: { kind: 'CF9_TEST', id: 'distribution' }, cashAccountId: 'cash:eur', equityAccountId: 'equity:eur', governanceAuthorizationReference: { kind: 'GOVERNANCE_DECISION', id: 'decision:1' } }); expect(Object.values(distribution.financialTransactionsById).some((item) => item.transactionType === 'OWNER_DISTRIBUTION')).toBe(true) })
  it('exposes financing queries from persisted facts and derived ledger consequences', () => { const current = world({ debtInstruments: [debt] }); expect(getActiveDebtInstruments(current, 'team-home', '2032-10-01')).toHaveLength(1); expect(getDebtMaturities(current, 'team-home', '2032-12-31')).toHaveLength(1); const drawn = materializeDebtFinanceForDate(current, '2032-10-01', { organizationId: 'team-home', ledger }); const interest = materializeDebtFinanceForDate(drawn.world, '2032-10-02', { organizationId: 'team-home', ledger }); expect(getDebtInterestRecognized(interest.world, 'team-home', '2032-10-02')).toEqual([{ currencyCode: 'EUR', minorUnits: 2_000 }]); expect(getDebtInterestPaid(interest.world, 'team-home', '2032-10-02')).toEqual([{ currencyCode: 'EUR', minorUnits: 0 }]); expect(getFinancingTransactions(drawn.world, 'team-home')).toHaveLength(1) })
  it('keeps currencies isolated and requires explicit schedule currency', () => { expect(() => createDebtInstrument({ ...debt, id: 'debt:usd-mismatch', currencyCode: 'USD', originalPrincipal: { currencyCode: 'USD', minorUnits: 10 }, interest: { kind: 'EXPLICIT_SCHEDULE', entries: [{ recognitionOn: '2032-10-02', dueOn: '2032-10-02', amount: { currencyCode: 'EUR', minorUnits: 1 } }] } })).toThrow(/instrument currency/) })
})
