import { compareGameDates, parseGameDate, type GameDate } from '@/domain/date'
import type { GovernanceActor } from '@/domain/governance'
import type { TeamId } from '@/domain/ids'
import { INSTITUTIONAL_SUPPORT_SCOPES, type InstitutionalSupportScope } from './InstitutionalSupport'

export const SUPPORT_FUNDING_SCOPES = [...INSTITUTIONAL_SUPPORT_SCOPES, 'COLLECTIVE_FUNDING'] as const
export type SupportFundingScope = typeof SUPPORT_FUNDING_SCOPES[number]
export const SUPPORT_FUNDING_RESTRICTIONS = ['UNRESTRICTED', 'ATHLETICS_ONLY', 'PROGRAM_ONLY', 'MEN_BASKETBALL', 'WOMEN_BASKETBALL', 'FACILITY_PROJECT', 'SPECIFIC_PURPOSE'] as const
export type SupportFundingRestriction = typeof SUPPORT_FUNDING_RESTRICTIONS[number]
export const SUPPORT_FUNDING_PLEDGE_SCHEDULES = ['ONE_TIME', 'RECURRING', 'MULTI_YEAR'] as const
export type SupportFundingPledgeSchedule = typeof SUPPORT_FUNDING_PLEDGE_SCHEDULES[number]
export const SUPPORT_CONTRIBUTION_MEDIA = ['CASH', 'IN_KIND'] as const
export type SupportContributionMedium = typeof SUPPORT_CONTRIBUTION_MEDIA[number]
export const SUPPORT_FUNDING_PLEDGE_EVENT_KINDS = ['CONFIRMED', 'WITHDRAWN', 'EXPIRED', 'DEFAULTED'] as const
export type SupportFundingPledgeEventKind = typeof SUPPORT_FUNDING_PLEDGE_EVENT_KINDS[number]
export type SupportFundingPledgeStatus = 'ACTIVE' | 'PARTIALLY_FULFILLED' | 'FULFILLED' | 'WITHDRAWN' | 'EXPIRED' | 'DEFAULTED'

export interface SupportFundingTarget { readonly institutionId: string; readonly scope: SupportFundingScope; readonly programTeamIds: readonly TeamId[]; readonly collectiveId?: string }
export interface SupportFundingPledge { readonly id: string; readonly contributor: GovernanceActor; readonly target: SupportFundingTarget; readonly supporterRelationshipId?: string; readonly effectiveOn: GameDate; readonly endsOn?: GameDate; readonly schedule: SupportFundingPledgeSchedule; readonly medium: SupportContributionMedium; readonly amountMinorUnits?: number; readonly currencyCode?: string; readonly inKindDescription?: string; readonly restriction: SupportFundingRestriction; readonly purpose?: string }
export interface SupportFundingPledgeEvent { readonly id: string; readonly pledgeId: string; readonly kind: SupportFundingPledgeEventKind; readonly effectiveOn: GameDate }
export interface SupportContribution { readonly id: string; readonly contributor: GovernanceActor; readonly target: SupportFundingTarget; readonly supporterRelationshipId?: string; readonly pledgeId?: string; readonly effectiveOn: GameDate; readonly medium: SupportContributionMedium; readonly amountMinorUnits?: number; readonly currencyCode?: string; readonly inKindDescription?: string; readonly declaredValueMinorUnits?: number; readonly declaredValueCurrencyCode?: string; readonly restriction: SupportFundingRestriction; readonly purpose?: string }

function actor(value: GovernanceActor): GovernanceActor { if (!value.id.trim() || !['COACH', 'STAFF', 'EXTERNAL'].includes(value.kind)) throw new RangeError('Invalid support funding contributor'); return { ...value } }
function currency(value: string | undefined): string { if (value === undefined || !/^[A-Z]{3}$/.test(value)) throw new RangeError('Support funding cash requires an ISO currency code'); return value }
function positiveAmount(value: number | undefined, label: string): number { if (typeof value !== 'number' || !Number.isSafeInteger(value) || value <= 0) throw new RangeError(`${label} must be a positive integer minor-unit amount`); return value }
function optionalDescription(value: string | undefined, label: string): string { if (value === undefined || !value.trim()) throw new RangeError(`${label} is required`); return value }
function target(value: SupportFundingTarget): SupportFundingTarget { const programTeamIds = [...value.programTeamIds]; if (!value.institutionId.trim() || !SUPPORT_FUNDING_SCOPES.includes(value.scope) || new Set(programTeamIds).size !== programTeamIds.length || programTeamIds.some((id) => !id.trim())) throw new RangeError('Invalid support funding target'); const programScope = value.scope === 'PROGRAM_SPECIFIC' || value.scope === 'MEN_BASKETBALL' || value.scope === 'WOMEN_BASKETBALL' || value.scope === 'MULTI_PROGRAM'; if (programScope !== (programTeamIds.length > 0) || (['PROGRAM_SPECIFIC', 'MEN_BASKETBALL', 'WOMEN_BASKETBALL'].includes(value.scope) && programTeamIds.length !== 1) || (value.scope === 'COLLECTIVE_FUNDING') !== (value.collectiveId !== undefined) || (value.scope !== 'COLLECTIVE_FUNDING' && value.collectiveId !== undefined)) throw new RangeError('Support funding target scope does not match references'); return value.collectiveId === undefined ? { ...value, programTeamIds } : { ...value, programTeamIds, collectiveId: value.collectiveId }
}
function restriction(value: SupportFundingRestriction, purpose?: string): SupportFundingRestriction { if (!SUPPORT_FUNDING_RESTRICTIONS.includes(value) || (value === 'SPECIFIC_PURPOSE' && !purpose?.trim())) throw new RangeError('Invalid support funding restriction'); return value }
function mediumFields(value: { readonly medium: SupportContributionMedium; readonly amountMinorUnits?: number; readonly currencyCode?: string; readonly inKindDescription?: string; readonly declaredValueMinorUnits?: number; readonly declaredValueCurrencyCode?: string }): void { if (!SUPPORT_CONTRIBUTION_MEDIA.includes(value.medium)) throw new RangeError('Invalid support contribution medium'); if (value.medium === 'CASH') { positiveAmount(value.amountMinorUnits, 'Cash amount'); currency(value.currencyCode); if (value.inKindDescription !== undefined || value.declaredValueMinorUnits !== undefined || value.declaredValueCurrencyCode !== undefined) throw new RangeError('Cash support cannot contain in-kind fields') } else { optionalDescription(value.inKindDescription, 'In-kind description'); if (value.amountMinorUnits !== undefined || value.currencyCode !== undefined || (value.declaredValueMinorUnits === undefined) !== (value.declaredValueCurrencyCode === undefined)) throw new RangeError('Invalid in-kind support value'); if (value.declaredValueMinorUnits !== undefined) { positiveAmount(value.declaredValueMinorUnits, 'Declared value'); currency(value.declaredValueCurrencyCode) } } }
export function createSupportFundingPledge(value: SupportFundingPledge): SupportFundingPledge { if (!value.id.trim() || !SUPPORT_FUNDING_PLEDGE_SCHEDULES.includes(value.schedule)) throw new RangeError('Invalid support funding pledge'); const effectiveOn = parseGameDate(value.effectiveOn), endsOn = value.endsOn === undefined ? undefined : parseGameDate(value.endsOn); if (endsOn !== undefined && endsOn < effectiveOn) throw new RangeError('Support funding pledge ends before it starts'); mediumFields(value); restriction(value.restriction, value.purpose); return { ...value, contributor: actor(value.contributor), target: target(value.target), effectiveOn, ...(endsOn === undefined ? {} : { endsOn }) } }
export function createSupportFundingPledgeEvent(value: SupportFundingPledgeEvent): SupportFundingPledgeEvent { if (!value.id.trim() || !value.pledgeId.trim() || !SUPPORT_FUNDING_PLEDGE_EVENT_KINDS.includes(value.kind)) throw new RangeError('Invalid support funding pledge event'); return { ...value, effectiveOn: parseGameDate(value.effectiveOn) } }
export function createSupportContribution(value: SupportContribution): SupportContribution { if (!value.id.trim()) throw new RangeError('Invalid support contribution'); mediumFields(value); restriction(value.restriction, value.purpose); return { ...value, contributor: actor(value.contributor), target: target(value.target), effectiveOn: parseGameDate(value.effectiveOn) } }

export function sortSupportFundingPledgeEvents(events: readonly SupportFundingPledgeEvent[]): readonly SupportFundingPledgeEvent[] { return [...events].sort((a, b) => compareGameDates(a.effectiveOn, b.effectiveOn) || a.id.localeCompare(b.id)) }
export function selectPledgeContributions(contributions: readonly SupportContribution[], pledgeId: string): readonly SupportContribution[] { return contributions.filter((item) => item.pledgeId === pledgeId).sort((a, b) => compareGameDates(a.effectiveOn, b.effectiveOn) || a.id.localeCompare(b.id)) }
export function totalPledgeFulfilledAmount(pledge: SupportFundingPledge, contributions: readonly SupportContribution[]): number | undefined { return pledge.medium === 'CASH' ? selectPledgeContributions(contributions, pledge.id).reduce((sum, item) => sum + (item.amountMinorUnits ?? 0), 0) : undefined }
export function remainingPledgeAmount(pledge: SupportFundingPledge, contributions: readonly SupportContribution[]): number | undefined { const fulfilled = totalPledgeFulfilledAmount(pledge, contributions); return fulfilled === undefined ? undefined : Math.max(0, pledge.amountMinorUnits! - fulfilled) }
export function deriveSupportFundingPledgeStatus(pledge: SupportFundingPledge, events: readonly SupportFundingPledgeEvent[], contributions: readonly SupportContribution[]): SupportFundingPledgeStatus { const terminal = sortSupportFundingPledgeEvents(events.filter((event) => event.pledgeId === pledge.id && event.kind !== 'CONFIRMED'))[0]; if (terminal !== undefined) return terminal.kind as Exclude<SupportFundingPledgeEventKind, 'CONFIRMED'>; if (pledge.medium === 'IN_KIND') return selectPledgeContributions(contributions, pledge.id).length > 0 ? 'FULFILLED' : 'ACTIVE'; const fulfilled = totalPledgeFulfilledAmount(pledge, contributions)!; return fulfilled >= pledge.amountMinorUnits! ? 'FULFILLED' : fulfilled > 0 ? 'PARTIALLY_FULFILLED' : 'ACTIVE' }
export const selectContributionsByContributor = (items: readonly SupportContribution[], contributorId: string) => items.filter((item) => item.contributor.id === contributorId).sort((a, b) => a.id.localeCompare(b.id))
export const selectContributionsByInstitution = (items: readonly SupportContribution[], institutionId: string) => items.filter((item) => item.target.institutionId === institutionId).sort((a, b) => a.id.localeCompare(b.id))
export const selectContributionsByProgram = (items: readonly SupportContribution[], teamId: TeamId) => items.filter((item) => item.target.programTeamIds.includes(teamId)).sort((a, b) => a.id.localeCompare(b.id))
export const selectContributionsByCollective = (items: readonly SupportContribution[], collectiveId: string) => items.filter((item) => item.target.collectiveId === collectiveId).sort((a, b) => a.id.localeCompare(b.id))
export const selectContributionsByScope = (items: readonly SupportContribution[], scope: SupportFundingScope) => items.filter((item) => item.target.scope === scope).sort((a, b) => a.id.localeCompare(b.id))
