import { parseGameDate, type GameDate } from '@/domain/date'
import type { SupportContribution, SupportFundingPledge } from './SupportFunding'
import type { SupporterRelationship } from './InstitutionalSupport'

export const SUPPORTER_EXPECTATION_CATEGORIES = ['SPORTING_SUCCESS', 'COACH_RETENTION', 'COACH_DISMISSAL', 'PLAYER_RECRUITMENT', 'PLAYER_RETENTION', 'TRANSFER_PORTAL_ACTIVITY', 'NIL_COMPETITIVENESS', 'PROGRAM_INVESTMENT', 'FACILITY_INVESTMENT', 'WOMEN_BASKETBALL_SUPPORT', 'MEN_BASKETBALL_SUPPORT', 'ATHLETICS_INVESTMENT', 'PUBLIC_PROFILE', 'GOVERNANCE_CHANGE'] as const
export const SUPPORTER_EXPECTATION_INTENSITIES = ['PREFERENCE', 'REQUEST', 'STRONG_EXPECTATION', 'PRESSURE', 'ULTIMATUM'] as const
export const SUPPORTER_EXPECTATION_EVENT_KINDS = ['ACTIVATED', 'MET', 'PARTIALLY_MET', 'UNMET', 'WITHDRAWN', 'SUPERSEDED', 'EXPIRED'] as const
export const SUPPORTER_PRESSURE_EVENT_KINDS = ['PRIVATE_REQUEST', 'DIRECT_MEETING', 'PUBLIC_COMMENT', 'FUNDING_WARNING', 'FUNDING_WITHDRAWAL_THREAT', 'COLLECTIVE_WARNING', 'PROGRAM_SUPPORT_WARNING', 'MEDIA_PRESSURE', 'ALUMNI_CAMPAIGN', 'BOARD_CONTACT'] as const
export const SUPPORTER_PRESSURE_VISIBILITIES = ['PRIVATE', 'INTERNAL', 'PUBLIC', 'MEDIA'] as const
export const SUPPORTER_REACTION_KINDS = ['SATISFIED', 'DISAPPOINTED', 'ANGRY', 'SUPPORTIVE', 'WITHDRAWS_SUPPORT', 'ESCALATES_PRESSURE', 'PUBLICLY_CRITICIZES', 'BACKS_COACH', 'OPPOSES_COACH'] as const
export type SupporterExpectationTarget = { readonly kind: 'INSTITUTION' | 'ATHLETICS' | 'PROGRAM' | 'COACH' | 'STAFF' | 'GOVERNANCE_BODY' | 'COLLECTIVE'; readonly id: string }
export interface SupporterExpectation { readonly id: string; readonly supporterRelationshipId: string; readonly institutionId: string; readonly target: SupporterExpectationTarget; readonly category: typeof SUPPORTER_EXPECTATION_CATEGORIES[number]; readonly intensity: typeof SUPPORTER_EXPECTATION_INTENSITIES[number]; readonly createdOn: GameDate; readonly linkedGovernanceRequestId?: string; readonly linkedGovernanceCommitmentId?: string }
export interface SupporterExpectationEvent { readonly id: string; readonly expectationId: string; readonly kind: typeof SUPPORTER_EXPECTATION_EVENT_KINDS[number]; readonly effectiveOn: GameDate }
export interface SupporterPressureEvent { readonly id: string; readonly supporterRelationshipId: string; readonly institutionId: string; readonly target: SupporterExpectationTarget; readonly kind: typeof SUPPORTER_PRESSURE_EVENT_KINDS[number]; readonly visibility: typeof SUPPORTER_PRESSURE_VISIBILITIES[number]; readonly effectiveOn: GameDate; readonly linkedGovernanceMeetingId?: string; readonly linkedGovernanceRequestId?: string; readonly linkedFundingPledgeId?: string }
export interface SupporterReaction { readonly id: string; readonly supporterRelationshipId: string; readonly institutionId: string; readonly expectationId?: string; readonly kind: typeof SUPPORTER_REACTION_KINDS[number]; readonly effectiveOn: GameDate }
const text=(value:string)=>value.trim()!==''
const target=(value:SupporterExpectationTarget)=>{if(!['INSTITUTION','ATHLETICS','PROGRAM','COACH','STAFF','GOVERNANCE_BODY','COLLECTIVE'].includes(value.kind)||!text(value.id))throw new RangeError('Invalid supporter expectation target');return {...value}}
export function createSupporterExpectation(value:SupporterExpectation):SupporterExpectation { if(!text(value.id)||!text(value.supporterRelationshipId)||!text(value.institutionId)||!SUPPORTER_EXPECTATION_CATEGORIES.includes(value.category)||!SUPPORTER_EXPECTATION_INTENSITIES.includes(value.intensity))throw new RangeError('Invalid supporter expectation');return {...value,target:target(value.target),createdOn:parseGameDate(value.createdOn)} }
export function createSupporterExpectationEvent(value:SupporterExpectationEvent):SupporterExpectationEvent { if(!text(value.id)||!text(value.expectationId)||!SUPPORTER_EXPECTATION_EVENT_KINDS.includes(value.kind))throw new RangeError('Invalid supporter expectation event');return {...value,effectiveOn:parseGameDate(value.effectiveOn)} }
export function createSupporterPressureEvent(value:SupporterPressureEvent):SupporterPressureEvent { if(!text(value.id)||!text(value.supporterRelationshipId)||!text(value.institutionId)||!SUPPORTER_PRESSURE_EVENT_KINDS.includes(value.kind)||!SUPPORTER_PRESSURE_VISIBILITIES.includes(value.visibility))throw new RangeError('Invalid supporter pressure event');return {...value,target:target(value.target),effectiveOn:parseGameDate(value.effectiveOn)} }
export function createSupporterReaction(value:SupporterReaction):SupporterReaction { if(!text(value.id)||!text(value.supporterRelationshipId)||!text(value.institutionId)||!SUPPORTER_REACTION_KINDS.includes(value.kind))throw new RangeError('Invalid supporter reaction');return {...value,effectiveOn:parseGameDate(value.effectiveOn)} }
export const sortSupporterExpectationEvents=(items:readonly SupporterExpectationEvent[])=>[...items].sort((a,b)=>a.effectiveOn.localeCompare(b.effectiveOn)||a.id.localeCompare(b.id))
export const deriveSupporterExpectationStatus=(expectation:SupporterExpectation,events:readonly SupporterExpectationEvent[])=>sortSupporterExpectationEvents(events.filter(item=>item.expectationId===expectation.id)).at(-1)?.kind??'ACTIVATED'
export const activeSupporterExpectations=(items:readonly SupporterExpectation[],events:readonly SupporterExpectationEvent[])=>items.filter(item=>['ACTIVATED','PARTIALLY_MET'].includes(deriveSupporterExpectationStatus(item,events))).sort((a,b)=>a.id.localeCompare(b.id))
export const expectationsByTarget=(items:readonly SupporterExpectation[],target:SupporterExpectationTarget)=>items.filter(item=>item.target.kind===target.kind&&item.target.id===target.id).sort((a,b)=>a.id.localeCompare(b.id))
export const pressureHistory=(items:readonly SupporterPressureEvent[],relationshipId:string)=>items.filter(item=>item.supporterRelationshipId===relationshipId).sort((a,b)=>a.effectiveOn.localeCompare(b.effectiveOn)||a.id.localeCompare(b.id))
/** Interpretable factual context only; it deliberately contains no authority or opaque power score. */
export function deriveSupporterInfluenceContext(relationship: SupporterRelationship, expectations: readonly SupporterExpectation[], expectationEvents: readonly SupporterExpectationEvent[], pressures: readonly SupporterPressureEvent[], reactions: readonly SupporterReaction[], pledges: readonly SupportFundingPledge[], contributions: readonly SupportContribution[]) { const active=activeSupporterExpectations(expectations.filter(item=>item.supporterRelationshipId===relationship.id),expectationEvents); return { supporterRelationshipId: relationship.id, relationshipKind: relationship.kind, activeExpectationCount: active.length, pressureEventCount: pressureHistory(pressures,relationship.id).length, reactionCount: reactions.filter(item=>item.supporterRelationshipId===relationship.id).length, pledgeCount: pledges.filter(item=>item.supporterRelationshipId===relationship.id).length, contributionCount: contributions.filter(item=>item.supporterRelationshipId===relationship.id).length, collectiveFundingContributionCount: contributions.filter(item=>item.supporterRelationshipId===relationship.id&&item.target.collectiveId!==undefined).length } }
