import { compareGameDates, parseGameDate, type GameDate } from '@/domain/date'
import type { GovernanceActor } from '@/domain/governance'

export const SUPPORT_COMPLIANCE_CASE_EVENT_KINDS = ['OPENED', 'UNDER_REVIEW', 'INFORMATION_REQUESTED', 'REFERRED', 'CLEARED', 'WARNING_ISSUED', 'VIOLATION_CONFIRMED', 'CLOSED', 'REOPENED'] as const
export const SUPPORT_COMPLIANCE_FINDING_KINDS = ['NO_ISSUE_FOUND', 'POLICY_CONCERN', 'DISCLOSURE_FAILURE', 'BOUNDARY_BREACH', 'IMPROPER_COORDINATION', 'IMPROPER_PRESSURE', 'IMPROPER_FUNDING_LINKAGE', 'RECRUITING_RELATED_CONCERN', 'NIL_BOUNDARY_CONCERN', 'CONFLICT_OF_INTEREST', 'DOCUMENTATION_FAILURE'] as const
export const SUPPORT_COMPLIANCE_SEVERITIES = ['MINOR', 'MODERATE', 'MAJOR', 'CRITICAL'] as const
export const SUPPORT_DISCLOSURE_STATUSES = ['DISCLOSED', 'UNDISCLOSED', 'RECUSED', 'NOT_RECUSED', 'REVIEW_REQUIRED', 'RESOLVED'] as const
export const SUPPORT_CONSEQUENCE_KINDS = ['INTERNAL_WARNING', 'FORMAL_WARNING', 'DISCLOSURE_REQUIRED', 'RECUSAL_REQUIRED', 'CONTACT_RESTRICTION', 'ACCESS_RESTRICTION', 'FUNDING_RESTRICTION', 'COLLECTIVE_RECOGNITION_CHANGE', 'COLLECTIVE_LIAISON_SUSPENSION', 'REFERRAL', 'PROGRAM_RESTRICTION', 'STAFF_REVIEW_TRIGGER', 'GOVERNANCE_REVIEW_TRIGGER', 'RECRUITING_REVIEW_TRIGGER'] as const
export const SUPPORT_REMEDIATION_KINDS = ['DISCLOSURE_COMPLETED', 'RECUSAL_COMPLETED', 'POLICY_UPDATED', 'CONTACT_RESTRICTED', 'DOCUMENTATION_PROVIDED', 'RELATIONSHIP_TERMINATED', 'TRAINING_COMPLETED'] as const
export type SupportComplianceSource = { readonly kind: 'SUPPORTER_RELATIONSHIP' | 'PLEDGE' | 'CONTRIBUTION' | 'COLLECTIVE_AFFILIATION' | 'COLLECTIVE_LIAISON' | 'COLLECTIVE_PARTICIPANT' | 'EXPECTATION' | 'PRESSURE_EVENT' | 'REACTION' | 'GOVERNANCE_APPOINTMENT' | 'GOVERNANCE_DECISION' | 'GOVERNANCE_REQUEST' | 'GOVERNANCE_MEETING'; readonly id: string }
export interface SupportComplianceCase { readonly id: string; readonly institutionId: string; readonly openedOn: GameDate; readonly sourceRefs: readonly SupportComplianceSource[]; readonly relatedCaseId?: string }
export interface SupportComplianceCaseEvent { readonly id: string; readonly caseId: string; readonly kind: typeof SUPPORT_COMPLIANCE_CASE_EVENT_KINDS[number]; readonly effectiveOn: GameDate }
export interface SupportComplianceFinding { readonly id: string; readonly caseId: string; readonly kind: typeof SUPPORT_COMPLIANCE_FINDING_KINDS[number]; readonly severity: typeof SUPPORT_COMPLIANCE_SEVERITIES[number]; readonly issuedOn: GameDate; readonly sourceRefs: readonly SupportComplianceSource[] }
export interface SupportConflictDisclosure { readonly id: string; readonly institutionId: string; readonly actor: GovernanceActor; readonly status: typeof SUPPORT_DISCLOSURE_STATUSES[number]; readonly effectiveOn: GameDate; readonly sourceRefs: readonly SupportComplianceSource[]; readonly caseId?: string }
export interface SupportConsequence { readonly id: string; readonly caseId: string; readonly findingId?: string; readonly kind: typeof SUPPORT_CONSEQUENCE_KINDS[number]; readonly effectiveOn: GameDate }
export interface SupportRemediation { readonly id: string; readonly caseId: string; readonly kind: typeof SUPPORT_REMEDIATION_KINDS[number]; readonly effectiveOn: GameDate; readonly disclosureId?: string }
const text = (value: string) => value.trim() !== ''
const actor = (value: GovernanceActor): GovernanceActor => { if (!text(value.id) || !['COACH', 'STAFF', 'EXTERNAL'].includes(value.kind)) throw new RangeError('Invalid support compliance actor'); return { ...value } }
const refs = (value: readonly SupportComplianceSource[], required: boolean) => { if ((required && !value.length) || value.some((ref) => !text(ref.id)) || new Set(value.map((ref) => `${ref.kind}:${ref.id}`)).size !== value.length) throw new RangeError('Invalid support compliance sources'); return value.map((ref) => ({ ...ref })) }
export function createSupportComplianceCase(value: SupportComplianceCase): SupportComplianceCase { if (!text(value.id) || !text(value.institutionId) || (value.relatedCaseId !== undefined && !text(value.relatedCaseId))) throw new RangeError('Invalid support compliance case'); return { ...value, openedOn: parseGameDate(value.openedOn), sourceRefs: refs(value.sourceRefs, true) } }
export function createSupportComplianceCaseEvent(value: SupportComplianceCaseEvent): SupportComplianceCaseEvent { if (!text(value.id) || !text(value.caseId) || !SUPPORT_COMPLIANCE_CASE_EVENT_KINDS.includes(value.kind)) throw new RangeError('Invalid support compliance case event'); return { ...value, effectiveOn: parseGameDate(value.effectiveOn) } }
export function createSupportComplianceFinding(value: SupportComplianceFinding): SupportComplianceFinding { if (!text(value.id) || !text(value.caseId) || !SUPPORT_COMPLIANCE_FINDING_KINDS.includes(value.kind) || !SUPPORT_COMPLIANCE_SEVERITIES.includes(value.severity)) throw new RangeError('Invalid support compliance finding'); return { ...value, issuedOn: parseGameDate(value.issuedOn), sourceRefs: refs(value.sourceRefs, true) } }
export function createSupportConflictDisclosure(value: SupportConflictDisclosure): SupportConflictDisclosure { if (!text(value.id) || !text(value.institutionId) || !SUPPORT_DISCLOSURE_STATUSES.includes(value.status) || (value.caseId !== undefined && !text(value.caseId))) throw new RangeError('Invalid support conflict disclosure'); return { ...value, actor: actor(value.actor), effectiveOn: parseGameDate(value.effectiveOn), sourceRefs: refs(value.sourceRefs, true) } }
export function createSupportConsequence(value: SupportConsequence): SupportConsequence { if (!text(value.id) || !text(value.caseId) || !SUPPORT_CONSEQUENCE_KINDS.includes(value.kind) || (value.findingId !== undefined && !text(value.findingId))) throw new RangeError('Invalid support consequence'); return { ...value, effectiveOn: parseGameDate(value.effectiveOn) } }
export function createSupportRemediation(value: SupportRemediation): SupportRemediation { if (!text(value.id) || !text(value.caseId) || !SUPPORT_REMEDIATION_KINDS.includes(value.kind) || (value.disclosureId !== undefined && !text(value.disclosureId))) throw new RangeError('Invalid support remediation'); return { ...value, effectiveOn: parseGameDate(value.effectiveOn) } }
export const sortSupportComplianceCaseEvents = (items: readonly SupportComplianceCaseEvent[]) => [...items].sort((a, b) => compareGameDates(a.effectiveOn, b.effectiveOn) || a.id.localeCompare(b.id))
export const deriveSupportComplianceCaseStatus = (item: SupportComplianceCase, events: readonly SupportComplianceCaseEvent[]) => sortSupportComplianceCaseEvents(events.filter((event) => event.caseId === item.id)).at(-1)?.kind ?? 'OPENED'
export const detectPotentialSupportConflicts = (relationships: readonly { readonly id: string; readonly actor: GovernanceActor; readonly institutionId: string }[], appointments: readonly { readonly id: string; readonly actor: GovernanceActor; readonly bodyId: string }[], bodyInstitutionIds: Readonly<Record<string, string>>) => relationships.flatMap((relationship) => appointments.filter((appointment) => appointment.actor.kind === relationship.actor.kind && appointment.actor.id === relationship.actor.id && bodyInstitutionIds[appointment.bodyId] === relationship.institutionId).map((appointment) => ({ supporterRelationshipId: relationship.id, governanceAppointmentId: appointment.id, institutionId: relationship.institutionId, kind: 'DUAL_ROLE' as const }))).sort((a, b) => a.supporterRelationshipId.localeCompare(b.supporterRelationshipId) || a.governanceAppointmentId.localeCompare(b.governanceAppointmentId))
export const deriveSupportComplianceContext = (cases: readonly SupportComplianceCase[], events: readonly SupportComplianceCaseEvent[], findings: readonly SupportComplianceFinding[], disclosures: readonly SupportConflictDisclosure[], consequences: readonly SupportConsequence[]) => ({ caseCount: cases.length, openCaseCount: cases.filter((item) => !['CLOSED', 'CLEARED'].includes(deriveSupportComplianceCaseStatus(item, events))).length, confirmedFindingCount: findings.filter((item) => item.kind !== 'NO_ISSUE_FOUND').length, undisclosedConflictCount: disclosures.filter((item) => item.status === 'UNDISCLOSED').length, activeRestrictionCount: consequences.filter((item) => ['CONTACT_RESTRICTION', 'ACCESS_RESTRICTION', 'FUNDING_RESTRICTION', 'PROGRAM_RESTRICTION'].includes(item.kind)).length })
