import { useState } from 'react'
import DraggableSubnav from './components/DraggableSubnav'
import ClubAnalytics from './components/club/ClubAnalytics'
import ClubBoard from './components/club/ClubBoard'
import ClubDashboard from './components/club/ClubDashboard'
import ClubFacilities from './components/club/ClubFacilities'
import ClubFinances from './components/club/ClubFinances'
import ClubHistory from './components/club/ClubHistory'
import ClubStaffAssignments from './components/club/ClubStaffAssignments'
import { clubFixtures } from './fixtures/clubFixtures'

type ClubTab = 'dashboard' | 'facilities' | 'staff' | 'board' | 'finances' | 'analytics' | 'history'
const tabs: readonly [ClubTab, string][] = [['dashboard', 'Visión General'], ['facilities', 'Instalaciones'], ['staff', 'Staff & Roles'], ['board', 'Junta Directiva'], ['finances', 'Finanzas'], ['analytics', 'Analítica'], ['history', 'Historia']]
const players = [{ id: 1, name: 'Marcus Cole', data: { bio: { pos: 'PG', age: 26 }, potential: 84, market_value: 950000 } }, { id: 2, name: 'Julian Price', data: { bio: { pos: 'SF', age: 24 }, potential: 81, market_value: 720000 } }]
const staff = [{ id: 1, name: 'Álvaro Quirós', skills: { leadership: 800, tactics: 850, motivation: 760, offensive_tactics: 700, shooting: 700, playmaking: 720 } }, { id: 2, name: 'Marta Vidal', skills: { medical: 800, recovery: 820, strength: 750, conditioning: 780 } }]
const analytics = { league_name: 'ACB', season_label: '2026/27', updated_at: 0, team_metrics: { games: 24, wins: 16, losses: 8, pace: 98.3, off_rating: 114.2, def_rating: 108.6, net_rating: 5.6, efg_pct: 54.1, ts_pct: 58.4, ast_pg: 24.2, reb_pg: 39.7, tov_pg: 12.1, ft_rate: .22, tp_rate: .39 }, league_averages: {}, team_ranks: {}, leaders: {}, awards: [] }

export function ClubPcbPage() { const [tab, setTab] = useState<ClubTab>('dashboard'); const [assignments, setAssignments] = useState<Record<string, unknown>>({}); const [balance, setBalance] = useState(850000); return <section className="pcb-club" aria-label="Club PCB migrado"><DraggableSubnav className="subnav club-subnav" items={tabs.map(([id, label]) => ({ id, label, active: tab === id, onClick: () => setTab(id) }))} storageKey="pcbasket.subnav.club" />{tab === 'dashboard' && <ClubDashboard alerts={clubFixtures.alerts} balance={balance} boardConfidence={76} jobSecurity={82} leaguePosition={3} nextOpponent="Real Madrid" objectives={clubFixtures.objectives} reputation={68} teamDivision="ACB" teamName="Casademont Zaragoza" topPlayers={players} upcomingMatches={clubFixtures.matches} />}{tab === 'facilities' && <ClubFacilities onUpgradeFacility={() => setBalance((value) => value - 50000)} teamBudget={balance} teamFacilities={{}} teamLevel={4} />}{tab === 'staff' && <ClubStaffAssignments assignments={assignments} onAssignPlayerToCoach={() => undefined} onAssignStaff={(staffId: string, role: string) => setAssignments((value) => ({ ...value, [staffId]: { role } }))} onHireStaff={() => undefined} staffMembers={staff} teamPlayers={players} />}{tab === 'board' && <ClubBoard confidence={76} currentMetrics={{ league_position: 3 }} currentObjectives={clubFixtures.objectives} onNegotiateObjectives={() => undefined} season={22} />}{tab === 'finances' && <ClubFinances currentBalance={balance} fiscalYear={2027} projectedExpenses={{ wages: 300000, operations: 100000, facilities: 50000 }} projectedIncome={{ ticket_sales: 420000, sponsorships: 280000, tv_rights: 190000 }} seasonBudget={1200000} transactions={clubFixtures.transactions} />}{tab === 'analytics' && <ClubAnalytics analytics={analytics} teamName="Casademont Zaragoza" />}{tab === 'history' && <ClubHistory clubFounded={1990} hallOfFame={clubFixtures.hallOfFame} milestones={clubFixtures.milestones} records={clubFixtures.records} seasonHistory={clubFixtures.seasons} trophies={clubFixtures.trophies} />}</section> }
