import { addDevelopmentStimulus } from '@/domain/development/DevelopmentStimulus'
import { clampCareerFatigue, recoverCareerFatigue } from '@/domain/careerFatigue/CareerFatigue'
import { createGameWorld, type GameWorld } from '@/domain/world'
import { createTrainingPlan, trainingLoad, type TrainingFocus, type TrainingIntensity } from '@/domain/training'
import { BASKETBALL_RATING_KEYS, type BasketballRatingKey } from '@/domain/player'
import type { TeamId } from '@/domain/ids'

export function recoverCareerFatigueForDay(world:GameWorld):GameWorld{return rebuild(world,{},Object.fromEntries(Object.entries(world.careerFatigueByPlayerId).map(([id,value])=>[id,recoverCareerFatigue(value)])))}
export function canTeamTrainOnDate(world:GameWorld,teamId:string,date=world.currentDate):boolean{return !Object.values(world.games).some(game=>game.date===date&&(game.homeTeamId===teamId||game.awayTeamId===teamId))}
export function executeTeamTraining(world:GameWorld,teamId:string):GameWorld{const plan=world.trainingPlansByTeamId[teamId],id=`training:${world.currentDate}:${teamId}`;if(!plan||world.trainingSessionsById[id]||!canTeamTrainOnDate(world,teamId))return world;const load=trainingLoad(plan.intensity);let stimulus={...world.developmentStimulusByPlayerId},fatigue={...world.careerFatigueByPlayerId};const results=world.teams[teamId as TeamId]!.rosterPlayerIds.map(playerId=>{const efficiency=Math.max(.4,1-(fatigue[playerId]??0)/150);const base=load.stimulus*efficiency;const delta=distribution(plan.focus,base);stimulus[playerId]=addDevelopmentStimulus(stimulus[playerId]!,delta);fatigue[playerId]=clampCareerFatigue((fatigue[playerId]??0)+load.fatigue);return{playerId,stimulus:delta,careerFatigueAdded:load.fatigue}});return rebuild(world,{[id]:{id,teamId,gameDate:world.currentDate,intensity:plan.intensity,focus:plan.focus,playerResults:results}},fatigue,stimulus)}
export function executeEligibleTraining(world:GameWorld):GameWorld{return Object.keys(world.teams).sort().reduce((next,teamId)=>executeTeamTraining(next,teamId),world)}
export function setTeamTrainingPlan(world:GameWorld,teamId:string,changes:Partial<Pick<import('@/domain/training').TeamTrainingPlan,'intensity'|'focus'>>):GameWorld{const plan=world.trainingPlansByTeamId[teamId];if(!plan)throw new Error(`Unknown team training plan: ${teamId}`);return rebuild(world,{},world.careerFatigueByPlayerId,world.developmentStimulusByPlayerId,{...world.trainingPlansByTeamId,[teamId]:createTrainingPlan({...plan,...changes})})}
function distribution(focus:TrainingFocus,base:number):Partial<Record<BasketballRatingKey,number>>{if(focus==='balanced')return Object.fromEntries(BASKETBALL_RATING_KEYS.map(key=>[key,base])) as Partial<Record<BasketballRatingKey,number>>;return Object.fromEntries(BASKETBALL_RATING_KEYS.map(key=>[key,key===focus?base*3:base*.35])) as Partial<Record<BasketballRatingKey,number>>}
function rebuild(world:GameWorld,sessions:Record<string,import('@/domain/training').TrainingSession>,fatigue:Record<string,number>=world.careerFatigueByPlayerId,stimulus:typeof world.developmentStimulusByPlayerId=world.developmentStimulusByPlayerId,plans=world.trainingPlansByTeamId):GameWorld{return createGameWorld({currentDate:world.currentDate,currentSeasonId:world.currentSeasonId,userCoachId:world.userCoachId,countries:Object.values(world.countries),coaches:Object.values(world.coaches),players:Object.values(world.players),teams:Object.values(world.teams),competitions:Object.values(world.competitions),seasons:Object.values(world.seasons),games:Object.values(world.games),matchStatLogs:Object.values(world.matchStatLogsByGameId),seasonHistory:Object.values(world.seasonHistoryBySeasonId),injuries:Object.values(world.injuriesById),contracts:Object.values(world.contractsById),teamFinances:Object.values(world.teamFinancesByTeamId),playerTransactions:Object.values(world.playerTransactionsById),playerKnowledge:Object.values(world.playerKnowledgeById),staffPeople:Object.values(world.staffPeopleById),teamStaffAssignments:Object.values(world.teamStaffAssignmentsById),coachProfessionalProfilesByCoachId:world.coachProfessionalProfilesByCoachId,coachRpgProfilesByCoachId:world.coachRpgProfilesByCoachId,coachReputationProfilesByCoachId:world.coachReputationProfilesByCoachId,coachEmploymentByCoachId:world.coachEmploymentByCoachId,coachCareerHistoryByCoachId:world.coachCareerHistoryByCoachId,coachJobOpeningsById:world.coachJobOpeningsById,coachJobCandidaciesById:world.coachJobCandidaciesById,coachInterviewsByCandidacyId:world.coachInterviewsByCandidacyId,coachJobOffersById:world.coachJobOffersById,relationshipsByKey:world.relationshipsByKey,personalitiesByPersonId:world.personalitiesByPersonId,moraleByPersonId:world.moraleByPersonId,inboxItemsById:world.inboxItemsById,newsItemsById:world.newsItemsById,trainingPlansByTeamId:plans,trainingSessionsById:{...world.trainingSessionsById,...sessions},developmentStimulusByPlayerId:stimulus,careerFatigueByPlayerId:fatigue})}
