import { addDevelopmentStimulus } from '@/domain/development/DevelopmentStimulus'
import { clampCareerFatigue, recoverCareerFatigue } from '@/domain/careerFatigue/CareerFatigue'
import { updateGameWorld, type GameWorld } from '@/domain/world'
import { createIndividualTrainingPlan, createTrainingPlan, trainingLoad, type IndividualTrainingPlan, type TrainingFocus, type TrainingIntensity, type TrainingModuleId, type TrainingResponsibility } from '@/domain/training'
import { BASKETBALL_RATING_KEYS, type BasketballRatingKey } from '@/domain/player'
import type { TeamId } from '@/domain/ids'

export function recoverCareerFatigueForDay(world:GameWorld):GameWorld{return rebuild(world,{},Object.fromEntries(Object.entries(world.careerFatigueByPlayerId).map(([id,value])=>[id,recoverCareerFatigue(value)])))}
export function canTeamTrainOnDate(world:GameWorld,teamId:string,date=world.currentDate):boolean{return !Object.values(world.games).some(game=>game.date===date&&(game.homeTeamId===teamId||game.awayTeamId===teamId))}
export function executeTeamTraining(world:GameWorld,teamId:string):GameWorld{const plan=world.trainingPlansByTeamId[teamId],id=`training:${world.currentDate}:${teamId}`;if(!plan||world.trainingSessionsById[id]||!canTeamTrainOnDate(world,teamId))return world;const load=trainingLoad(plan.intensity);let stimulus={...world.developmentStimulusByPlayerId},fatigue={...world.careerFatigueByPlayerId};const results=world.teams[teamId as TeamId]!.rosterPlayerIds.map(playerId=>{const individual=world.individualTrainingPlansByPlayerId[playerId];const effective=individual?.active?trainingLoad(individual.intensity):load;const efficiency=Math.max(.4,1-(fatigue[playerId]??0)/150);const base=effective.stimulus*efficiency;const delta=distribution(individual?.active?individual.primaryFocus:plan.focus,base);stimulus[playerId]=addDevelopmentStimulus(stimulus[playerId]!,delta);fatigue[playerId]=clampCareerFatigue((fatigue[playerId]??0)+effective.fatigue);return{playerId,stimulus:delta,careerFatigueAdded:effective.fatigue}});return rebuild(world,{[id]:{id,teamId,gameDate:world.currentDate,intensity:plan.intensity,focus:plan.focus,playerResults:results}},fatigue,stimulus)}
export function executeEligibleTraining(world:GameWorld):GameWorld{return Object.keys(world.teams).sort().reduce((next,teamId)=>executeTeamTraining(next,teamId),world)}
export function setTeamTrainingPlan(world:GameWorld,teamId:string,changes:Partial<Pick<import('@/domain/training').TeamTrainingPlan,'intensity'|'focus'>>):GameWorld{const plan=world.trainingPlansByTeamId[teamId];if(!plan)throw new Error(`Unknown team training plan: ${teamId}`);return rebuild(world,{},world.careerFatigueByPlayerId,world.developmentStimulusByPlayerId,{...world.trainingPlansByTeamId,[teamId]:createTrainingPlan({...plan,...changes})})}
export function getIndividualTrainingPlan(world:GameWorld,playerId:string):IndividualTrainingPlan|undefined{return world.individualTrainingPlansByPlayerId[playerId]}
export function setIndividualTrainingPlan(world:GameWorld,plan:IndividualTrainingPlan):GameWorld { if(!world.players[plan.playerId as import('@/domain/ids').PlayerId])throw new Error(`Unknown player: ${plan.playerId}`);return updateGameWorld(world,{individualTrainingPlansByPlayerId:{...world.individualTrainingPlansByPlayerId,[plan.playerId]:createIndividualTrainingPlan(plan)}}) }
export function setIndividualTrainingFocus(world:GameWorld,playerId:string,primaryFocus:TrainingFocus):GameWorld { const current=getIndividualTrainingPlan(world,playerId)??{playerId,primaryFocus,intensity:'normal' as const,active:true};return setIndividualTrainingPlan(world,{...current,primaryFocus}) }
export function setIndividualTrainingIntensity(world:GameWorld,playerId:string,intensity:TrainingIntensity):GameWorld { const current=getIndividualTrainingPlan(world,playerId)??{playerId,primaryFocus:'balanced' as const,intensity,active:true};return setIndividualTrainingPlan(world,{...current,intensity}) }
export function assignIndividualTrainingStaff(world:GameWorld,playerId:string,responsibleStaffId:import('@/domain/ids').StaffPersonId|undefined):GameWorld { const current=getIndividualTrainingPlan(world,playerId)??{playerId,primaryFocus:'balanced' as const,intensity:'normal' as const,active:true};return setIndividualTrainingPlan(world,{...current,...(responsibleStaffId===undefined?{}:{responsibleStaffId})}) }
export function clearIndividualTrainingPlan(world:GameWorld,playerId:string):GameWorld { const plans={...world.individualTrainingPlansByPlayerId};delete plans[playerId];return updateGameWorld(world,{individualTrainingPlansByPlayerId:plans}) }
export function setTrainingResponsibility(world:GameWorld,teamId:string,responsibility:TrainingResponsibility,staffPersonId:import('@/domain/ids').StaffPersonId):GameWorld { if(!world.teams[teamId as TeamId]||!world.staffPeopleById[staffPersonId])throw new Error('Unknown training responsibility reference');return updateGameWorld(world,{trainingResponsibilitiesByTeamId:{...world.trainingResponsibilitiesByTeamId,[teamId]:{...world.trainingResponsibilitiesByTeamId[teamId],[responsibility]:staffPersonId}}}) }
export function getTrainingLoad(world:GameWorld,teamId:string){const team=world.teams[teamId as TeamId];if(!team)throw new Error(`Unknown team: ${teamId}`);const plan=world.trainingPlansByTeamId[teamId]!;return team.rosterPlayerIds.map(playerId=>{const individual=world.individualTrainingPlansByPlayerId[playerId];const effective=individual?.active?individual:plan;const load=trainingLoad(effective.intensity);return{playerId,scheduledTrainingLoad:load.stimulus,recentLoad:world.trainingSessionsById[`training:${world.currentDate}:${teamId}`]?.playerResults.find(result=>result.playerId===playerId)?.careerFatigueAdded??0,currentFatigue:world.careerFatigueByPlayerId[playerId]??0,recoveryContext:Math.max(0,100-(world.careerFatigueByPlayerId[playerId]??0)),availability:!Object.values(world.injuriesById).some(injury=>injury.playerId===playerId&&injury.expectedReturnDate>=world.currentDate),trainingIntensity:effective.intensity,individualPlanLoad:individual?.active?load.stimulus:0,teamPlanLoad:individual?.active?0:load.stimulus}})}
function distribution(focus:TrainingFocus,base:number):Partial<Record<BasketballRatingKey,number>>{if(focus==='balanced')return Object.fromEntries(BASKETBALL_RATING_KEYS.map(key=>[key,base])) as Partial<Record<BasketballRatingKey,number>>;return Object.fromEntries(BASKETBALL_RATING_KEYS.map(key=>[key,key===focus?base*3:base*.35])) as Partial<Record<BasketballRatingKey,number>>}
function rebuild(world:GameWorld,sessions:Record<string,import('@/domain/training').TrainingSession>,fatigue:Record<string,number>=world.careerFatigueByPlayerId,stimulus:typeof world.developmentStimulusByPlayerId=world.developmentStimulusByPlayerId,plans=world.trainingPlansByTeamId):GameWorld{return updateGameWorld(world,{trainingPlansByTeamId:plans,trainingSessionsById:{...world.trainingSessionsById,...sessions},developmentStimulusByPlayerId:stimulus,careerFatigueByPlayerId:fatigue})}
