import { createNewGame } from '@/app/game/createNewGame'
import { describe, expect, it } from 'vitest'
import { organizationIdForTeam } from '@/domain/ids'
import { updateGameWorld } from '@/domain/world'
import { deriveOrganizationPlayerValuation, formatRatingEvaluation, getOrganizationRatingEvaluation, intelligenceSortValue, matchesIntelligenceFilter } from './OrganizationPlayerEvaluation'

describe('OrganizationPlayerEvaluation',()=>{
  function fixture(){const world=createNewGame(),team=Object.values(world.teams).find(t=>t.coachId===world.userCoachId)!,player=Object.values(world.players).find(p=>!team.rosterPlayerIds.includes(p.id))!;return{world,team,player,organizationId:organizationIdForTeam(team.id)}}
  it('never falls back to hidden truth when knowledge is absent',()=>{const f=fixture(),one=getOrganizationRatingEvaluation({organizationId:f.organizationId,playerId:f.player.id,dimension:'shooting',knowledge:[],currentDate:f.world.currentDate,publicPosition:f.player.basketball.primaryPosition});const altered=updateGameWorld(f.world,{players:Object.values(f.world.players).map(p=>p.id===f.player.id?{...p,basketball:{...p.basketball,ratings:{...p.basketball.ratings,threePointShooting:100}}}:p)});const two=getOrganizationRatingEvaluation({organizationId:f.organizationId,playerId:f.player.id,dimension:'shooting',knowledge:altered.organizationKnowledge,currentDate:altered.currentDate,publicPosition:f.player.basketball.primaryPosition});expect(one).toEqual(two);expect(formatRatingEvaluation(one)).toBe('?')})
  it('uses organization-specific knowledge and changes with a report-like finding',()=>{const f=fixture(),base=deriveOrganizationPlayerValuation({organizationId:f.organizationId,playerId:f.player.id,knowledge:[],currentDate:f.world.currentDate,context:'DRAFT'}),known=deriveOrganizationPlayerValuation({organizationId:f.organizationId,playerId:f.player.id,knowledge:[{organizationId:f.organizationId,subjectPlayerId:f.player.id,dimensions:{shooting:{coverage:.8,confidence:.9,assessedAt:f.world.currentDate,provenance:'scoutReport',estimate:90,uncertainty:4}}}],currentDate:f.world.currentDate,context:'DRAFT'});expect(known.priorityScore).not.toBe(base.priorityScore)})
  it('never displays potential as exact even with precise knowledge',()=>{const f=fixture(),evaluation=getOrganizationRatingEvaluation({organizationId:f.organizationId,playerId:f.player.id,dimension:'potential:physical',knowledge:[{organizationId:f.organizationId,subjectPlayerId:f.player.id,dimensions:{'potential:physical':{coverage:1,confidence:1,assessedAt:f.world.currentDate,provenance:'scoutReport',estimate:90,uncertainty:1}}}],currentDate:f.world.currentDate});expect(evaluation.mode).not.toBe('EXACT')})
  it('uses knowledge-derived filter and sort semantics without unknown truth fallback',()=>{const unknown={mode:'UNKNOWN' as const,estimate:95,uncertainty:20,confidence:0,freshness:0,disagreement:'LOW' as const},range={mode:'RANGE' as const,estimate:75,uncertainty:8,confidence:80,freshness:1,disagreement:'MODERATE' as const};expect(intelligenceSortValue(unknown)).toBeUndefined();expect(intelligenceSortValue(range)).toBe(75);expect(matchesIntelligenceFilter(unknown,{kind:'ESTIMATE',minimum:80})).toBe(false);expect(matchesIntelligenceFilter(range,{kind:'LOWER_BOUND',minimum:70})).toBe(false);expect(matchesIntelligenceFilter(range,{kind:'UPPER_BOUND',minimum:83})).toBe(true);expect(matchesIntelligenceFilter(range,{kind:'CONFIDENCE',minimum:80})).toBe(true);expect(matchesIntelligenceFilter(range,{kind:'KNOWN_STATE',modes:['RANGE']})).toBe(true)})
  it('makes free-agency valuation knowledge-responsive while hidden truth remains irrelevant',()=>{const f=fixture(),base=deriveOrganizationPlayerValuation({organizationId:f.organizationId,playerId:f.player.id,knowledge:[],currentDate:f.world.currentDate,context:'FREE_AGENCY'}),known=deriveOrganizationPlayerValuation({organizationId:f.organizationId,playerId:f.player.id,knowledge:[{organizationId:f.organizationId,subjectPlayerId:f.player.id,dimensions:{shooting:{coverage:1,confidence:1,assessedAt:f.world.currentDate,provenance:'scoutReport',estimate:95,uncertainty:1}}}],currentDate:f.world.currentDate,context:'FREE_AGENCY'}),changed=updateGameWorld(f.world,{players:Object.values(f.world.players).map(p=>p.id===f.player.id?{...p,basketball:{...p.basketball,ratings:{...p.basketball.ratings,threePointShooting:1}}}:p)});expect(known.priorityScore).not.toBe(base.priorityScore);expect(deriveOrganizationPlayerValuation({organizationId:f.organizationId,playerId:f.player.id,knowledge:[],currentDate:changed.currentDate,context:'FREE_AGENCY'})).toEqual(base)})
})
