import type { OrganizationKnowledge } from '@/domain/knowledge'
import type { OrganizationId, PlayerId } from '@/domain/ids'
import type { GameDate } from '@/domain/date'

export type IntelligenceDisplayMode = 'EXACT' | 'RANGE' | 'DESCRIPTOR' | 'UNKNOWN' | 'MIXED'
export interface OrganizationEvaluationPolicy { readonly riskTolerance:number; readonly certaintyPreference:number; readonly upsidePreference:number; readonly currentAbilityPreference:number; readonly scoutingReliance:number }
export interface RatingEvaluation { readonly mode:IntelligenceDisplayMode; readonly estimate?:number; readonly uncertainty?:number; readonly descriptor?:string; readonly confidence:number; readonly freshness:number; readonly disagreement:'LOW'|'MODERATE'|'HIGH' }
export type IntelligenceFilter =
  | { readonly kind:'ESTIMATE'|'LOWER_BOUND'|'UPPER_BOUND'|'CONFIDENCE'; readonly minimum:number }
  | { readonly kind:'KNOWN_STATE'; readonly modes:readonly Exclude<IntelligenceDisplayMode,'UNKNOWN'>[] }
export interface OrganizationPlayerValuation { readonly currentValue:number; readonly futureValue:number; readonly risk:number; readonly certainty:number; readonly priorityScore:number }

/** A deterministic institutional identity until organizations become first-class records. */
export function deriveOrganizationEvaluationPolicy(organizationId:OrganizationId):OrganizationEvaluationPolicy { const n=hash(String(organizationId)); return {riskTolerance:35+n%46,certaintyPreference:35+(n>>>5)%46,upsidePreference:35+(n>>>11)%46,currentAbilityPreference:35+(n>>>17)%46,scoutingReliance:35+(n>>>23)%46} }
export function getOrganizationRatingEvaluation(input:{readonly organizationId:OrganizationId;readonly playerId:PlayerId;readonly dimension:string;readonly knowledge:readonly OrganizationKnowledge[];readonly currentDate:GameDate;readonly publicPosition?:string}):RatingEvaluation { const finding=input.knowledge.find(k=>k.organizationId===input.organizationId&&k.subjectPlayerId===input.playerId)?.dimensions[input.dimension]; if(!finding||finding.estimate===undefined)return unknownPrior(input);const freshness=lazyFreshness(finding.assessedAt,input.currentDate), uncertainty=Math.min(20,(finding.uncertainty??15)+Math.round((1-freshness)*5));const confidence=Math.round(finding.confidence*100);const disagreement=uncertainty>=13?'HIGH':uncertainty>=8?'MODERATE':'LOW';if(!input.dimension.startsWith('potential:')&&uncertainty<=1&&freshness>=.8&&finding.provenance!=='inferred')return{mode:'EXACT',estimate:Math.round(finding.estimate),confidence,freshness,disagreement};if(uncertainty<=9)return{mode:'RANGE',estimate:Math.round(finding.estimate),uncertainty,confidence,freshness,disagreement};return{mode:disagreement==='HIGH'?'MIXED':'DESCRIPTOR',estimate:Math.round(finding.estimate),uncertainty,descriptor:descriptor(finding.estimate),confidence,freshness,disagreement} }
export function formatRatingEvaluation(value:RatingEvaluation):string { if(value.mode==='UNKNOWN')return '?';if(value.mode==='EXACT')return String(value.estimate);if(value.mode==='RANGE')return `${Math.max(1,(value.estimate??50)-(value.uncertainty??0))}-${Math.min(100,(value.estimate??50)+(value.uncertainty??0))}`;return value.mode==='MIXED'?`${value.descriptor??'Mixed'} ±${value.uncertainty??'?'}`:value.descriptor??'Unknown' }
/** Shared UI semantics: unknown evaluations neither sort by hidden truth nor pass numeric filters. */
export function intelligenceSortValue(value:RatingEvaluation):number|undefined{return value.mode==='UNKNOWN'?undefined:value.estimate}
export function matchesIntelligenceFilter(value:RatingEvaluation,filter:IntelligenceFilter):boolean{if(filter.kind==='KNOWN_STATE')return value.mode!=='UNKNOWN'&&filter.modes.includes(value.mode);if(value.mode==='UNKNOWN')return false;if(filter.kind==='CONFIDENCE')return value.confidence>=filter.minimum;const estimate=value.estimate;if(estimate===undefined)return false;const uncertainty=value.uncertainty??0;return filter.kind==='ESTIMATE'?estimate>=filter.minimum:filter.kind==='LOWER_BOUND'?estimate-uncertainty>=filter.minimum:estimate+uncertainty>=filter.minimum}
export function deriveOrganizationPlayerValuation(input:{readonly organizationId:OrganizationId;readonly playerId:PlayerId;readonly knowledge:readonly OrganizationKnowledge[];readonly currentDate:GameDate;readonly context:'DRAFT'|'RECRUITING'|'FREE_AGENCY'|'TRADE'|'ROSTER';readonly publicPosition?:string;readonly policy?:OrganizationEvaluationPolicy}):OrganizationPlayerValuation { const policy=input.policy??deriveOrganizationEvaluationPolicy(input.organizationId);const dimensions=['finishing','shooting','creation','perimeterDefense','interiorDefense','rebounding','physical'];const evaluations=dimensions.map(d=>getOrganizationRatingEvaluation({...input,dimension:d}));const estimates=evaluations.map(x=>x.estimate??50), certainty=evaluations.reduce((s,x)=>s+x.confidence,0)/evaluations.length;const uncertainty=evaluations.reduce((s,x)=>s+(x.uncertainty??20),0)/evaluations.length;const current=estimates.reduce((s,x)=>s+x,0)/estimates.length;const potential=getOrganizationRatingEvaluation({...input,dimension:'potential:physical'});const future=(potential.estimate??current)+(policy.upsidePreference-50)*.08;const risk=Math.min(100,uncertainty*5+(100-certainty)*.3+(50-policy.riskTolerance)*.2);const contextBoost=input.context==='DRAFT'||input.context==='RECRUITING'?policy.upsidePreference*.08:policy.currentAbilityPreference*.08;return{currentValue:Math.round(current),futureValue:Math.round(Math.max(1,Math.min(100,future))),risk:Math.round(risk),certainty:Math.round(certainty),priorityScore:Math.round(current*.55+future*.25+contextBoost-risk*(policy.certaintyPreference/200))} }
function unknownPrior(input:{readonly organizationId:OrganizationId;readonly playerId:PlayerId;readonly currentDate:GameDate;readonly publicPosition?:string}):RatingEvaluation { const estimate=42+hash(`${input.organizationId}:${input.playerId}:${input.publicPosition??''}`)%17;return{mode:'UNKNOWN',estimate,uncertainty:20,confidence:0,freshness:0,disagreement:'LOW'} }
function descriptor(value:number):string{return value>=85?'Elite':value>=72?'Very good':value>=60?'Good':value>=48?'Average':'Below average'}
function hash(value:string):number{let h=2166136261;for(const c of value)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0}
function lazyFreshness(assessed:GameDate,now:GameDate):number{const days=Math.max(0,Math.round((Date.UTC(+now.slice(0,4),+now.slice(5,7)-1,+now.slice(8,10))-Date.UTC(+assessed.slice(0,4),+assessed.slice(5,7)-1,+assessed.slice(8,10)))/86400000));return Math.max(0,1-days/365)}
