import { describe, expect, it } from 'vitest'
import { createGameWorld, updateGameWorld } from '@/domain/world'
import { createValidGameWorldInput } from '@/domain/world/testFixtures'
import { createGame } from '@/domain/game'
import { createNarrativeThread } from '@/domain/narrative'
import { createPreMatchMediaOpportunity, processMediaMatch, respondToMediaOpportunity, skipMediaOpportunity } from './MediaEngine'
import { deserializeGameWorldV1, serializeGameWorldV1 } from '@/save/GameWorldSaveV1'

function world(stakes: 'regular'|'final'='final') { const base=createGameWorld(createValidGameWorldInput()); return updateGameWorld(base,{games:[createGame({...base.games['game-a' as keyof typeof base.games]!,stakes})]}) }
describe('Hito 064 acceptance',()=>{
 it('1,3,8,9,10,13: selects deterministic relevant pre-match coverage without spam and publishes News',()=>{const ordinary=world('regular');expect(createPreMatchMediaOpportunity(ordinary,'game-a' as never)).toBe(ordinary);const relevant=world();const a=createPreMatchMediaOpportunity(relevant,'game-a' as never);const b=createPreMatchMediaOpportunity(a,'game-a' as never);expect(a).toEqual(createPreMatchMediaOpportunity(relevant,'game-a' as never));expect(Object.keys(b.mediaOpportunitiesById)).toHaveLength(1);expect(Object.keys(b.newsItemsById)).toHaveLength(1)})
 it('2,4,14: creates post-match coverage from real narrative context without modifying it',()=>{const base=world();const t=base.teams['team-away' as keyof typeof base.teams]!;const n=createNarrativeThread({id:'n',type:'formerClub',protagonistIds:[base.userCoachId],relatedEntityIds:[t.id],startedOn:base.currentDate,lastOccurredOn:base.currentDate,status:'active',intensity:80,relevance:90,supportingMemoryIds:[],tags:['formerClub'],beats:[{id:'b',semanticKey:'b',occurredOn:base.currentDate,kind:'origin',intensity:55,context:{}}]});const done=updateGameWorld(base,{games:[createGame({...base.games['game-a' as keyof typeof base.games]!,status:'completed',result:{homeScore:80,awayScore:70}})],narratives:[n]});const media=processMediaMatch(done,'game-a' as never);expect(Object.values(media.mediaOpportunitiesById)[0]!.questions[0]!.topic).toBe('performance');expect(media.narrativesById.n).toEqual(n)})
 it('5,6,7,11,12,15: response/skip effects are idempotent and persist with legacy defaults',()=>{const base=world();const player=base.players['player-home' as keyof typeof base.players]!;const item={id:'m',semanticKey:'m',coachId:base.userCoachId,gameDate:base.currentDate,type:'narrative' as const,status:'pending' as const,importance:90,questions:[{id:'q',topic:'player' as const,text:'?',targetPlayerId:player.id,context:{}}],answers:[{stance:'protective' as const,text:'x'},{stance:'critical' as const,text:'y'}]};const withItem=updateGameWorld(base,{mediaOpportunitiesById:{m:item}});const defended=respondToMediaOpportunity(withItem,'m','protective');expect(Object.keys(defended.mediaInteractionsById)).toHaveLength(1);expect(defended).toBe(respondToMediaOpportunity(defended,'m','protective'));const skipped=skipMediaOpportunity(updateGameWorld(base,{mediaOpportunitiesById:{m:item}}),'m');expect(skipped.mediaOpportunitiesById.m!.status).toBe('skipped');const save=serializeGameWorldV1(defended,'2032-10-01T00:00:00.000Z');expect(deserializeGameWorldV1(save).mediaInteractionsById).toEqual(defended.mediaInteractionsById);const legacy={...save,payload:{...save.payload}};delete (legacy.payload as {mediaOpportunities?:unknown}).mediaOpportunities;expect(deserializeGameWorldV1(legacy).mediaOpportunitiesById).toEqual({})})
})
