import type { GameDate } from '@/domain/date'
import type { AgencyId, AgentId, OrganizationId, PlayerId } from '@/domain/ids'

export interface AgentAbilities { readonly negotiation:number; readonly marketKnowledge:number; readonly network:number; readonly clientManagement:number; readonly mediaInfluence:number }
export interface AgentProfessionalPersonality { readonly aggressiveness:number; readonly loyalty:number; readonly opportunism:number; readonly patience:number; readonly discretion:number }
export interface Agent { readonly id:AgentId; readonly name:string; readonly agencyId?:AgencyId; readonly reputation:number; readonly abilities:AgentAbilities; readonly personality:AgentProfessionalPersonality }
export interface Agency { readonly id:AgencyId; readonly name:string; readonly reputation:number }
/** The sole persistent player-to-agent authority; portfolios are derived. */
export interface PlayerRepresentation { readonly playerId:PlayerId; readonly agentId:AgentId; readonly trust:number; readonly startedOn:GameDate }
export interface MarketReality { readonly playerId:PlayerId; readonly availability:'NOT_FOR_SALE'|'LISTENING'|'OPEN'; readonly expectedSalary:number; readonly expectedYears:number; readonly playerWillingness:number; readonly sellerWillingness:number; readonly competition:number }
export interface MarketKnowledge { readonly organizationId:OrganizationId; readonly playerId:PlayerId; readonly availability?:'NOT_FOR_SALE'|'LISTENING'|'OPEN'; readonly expectedSalary?:number; readonly expectedYears?:number; readonly playerInterest?:number; readonly sellerWillingness?:number; readonly competition?:number; readonly confidence:number; readonly assessedAt:GameDate; readonly source:'AGENT'|'CLUB_CONTACT'|'MEDIA' }
export interface MarketSignal { readonly id:string; readonly organizationId:OrganizationId; readonly playerId:PlayerId; readonly source:'AGENT'|'CLUB_CONTACT'|'MEDIA'; readonly occurredOn:GameDate; readonly reliability:number; readonly availability?:MarketReality['availability']; readonly expectedSalary?:number; readonly expectedYears?:number; readonly playerInterest?:number; readonly sellerWillingness?:number; readonly competition?:number }
export interface ContractNegotiation { readonly id:string; readonly organizationId:OrganizationId; readonly playerId:PlayerId; readonly agentId?:AgentId; readonly salary:number; readonly years:number; readonly role:'STAR'|'STARTER'|'ROTATION'|'DEPTH'; readonly agentFee:number; readonly status:'OPEN'|'COUNTERED'|'ACCEPTED'|'REJECTED'; readonly round:number }
export interface RolePromise { readonly id:string; readonly playerId:PlayerId; readonly teamOrganizationId:OrganizationId; readonly role:ContractNegotiation['role']; readonly acceptedOn:GameDate; readonly status:'ACTIVE'|'FULFILLED'|'BROKEN' }

export function getAgentClients(representations:readonly PlayerRepresentation[],agentId:AgentId):readonly PlayerId[]{return representations.filter(item=>item.agentId===agentId).map(item=>item.playerId)}
export function getMarketKnowledge(knowledge:readonly MarketKnowledge[],organizationId:OrganizationId,playerId:PlayerId):MarketKnowledge|undefined{return knowledge.find(item=>item.organizationId===organizationId&&item.playerId===playerId)}
/** Market queries are pure; absent knowledge remains absent rather than reading MarketReality. */
export function marketAvailability(knowledge:readonly MarketKnowledge[],organizationId:OrganizationId,playerId:PlayerId):MarketKnowledge['availability']|undefined{return getMarketKnowledge(knowledge,organizationId,playerId)?.availability}
export function consolidateMarketSignal(current:readonly MarketKnowledge[],signal:MarketSignal):readonly MarketKnowledge[]{const prior=getMarketKnowledge(current,signal.organizationId,signal.playerId);const next:MarketKnowledge={organizationId:signal.organizationId,playerId:signal.playerId,availability:signal.availability??prior?.availability,expectedSalary:signal.expectedSalary??prior?.expectedSalary,expectedYears:signal.expectedYears??prior?.expectedYears,playerInterest:signal.playerInterest??prior?.playerInterest,sellerWillingness:signal.sellerWillingness??prior?.sellerWillingness,competition:signal.competition??prior?.competition,confidence:Math.max(prior?.confidence??0,Math.round(signal.reliability*100)),assessedAt:signal.occurredOn,source:signal.source};return[...current.filter(item=>item!==prior),next]}
export function agentCounter(negotiation:ContractNegotiation,agent:Agent|undefined):ContractNegotiation{if(!agent||negotiation.status!=='OPEN')return negotiation;const pressure=Math.round((agent.abilities.negotiation+agent.personality.aggressiveness+agent.personality.opportunism)/30);return{...negotiation,salary:negotiation.salary+pressure*10_000,agentFee:negotiation.agentFee+Math.round(negotiation.salary*agent.abilities.negotiation/10_000),status:'COUNTERED',round:negotiation.round+1}}
