import type { GameDate } from '@/domain/date'

export type NarrativeType = 'formerClub' | 'revenge' | 'rivalry' | 'formerPlayer' | 'promotionJourney' | 'dynasty'
export type NarrativeStatus = 'emerging' | 'active' | 'escalating' | 'resolved' | 'dormant' | 'historic'
export interface NarrativeBeat { readonly id: string; readonly semanticKey: string; readonly occurredOn: GameDate; readonly kind: string; readonly intensity: number; readonly context: Readonly<Record<string, string | number | boolean>> }
export interface NarrativeThread { readonly id: string; readonly type: NarrativeType; readonly protagonistIds: readonly string[]; readonly relatedEntityIds: readonly string[]; readonly startedOn: GameDate; readonly lastOccurredOn: GameDate; readonly status: NarrativeStatus; readonly intensity: number; readonly relevance: number; readonly supportingMemoryIds: readonly string[]; readonly tags: readonly string[]; readonly beats: readonly NarrativeBeat[]; readonly resolvedOn?: GameDate }
export const NARRATIVE_THRESHOLDS = { dynastyChampionships: 3, dormancyMonths: 24, newsRelevance: 90 } as const
export function createNarrativeThread(input: NarrativeThread): NarrativeThread { if (!input.id || !input.protagonistIds.length || !input.relatedEntityIds.length || !input.beats.length || input.intensity < 1 || input.intensity > 100 || input.relevance < 0) throw new RangeError('Invalid narrative thread'); if (new Set(input.supportingMemoryIds).size !== input.supportingMemoryIds.length || new Set(input.beats.map((beat) => beat.semanticKey)).size !== input.beats.length) throw new RangeError('Narrative references must be unique'); return { ...input, protagonistIds: [...input.protagonistIds], relatedEntityIds: [...input.relatedEntityIds], supportingMemoryIds: [...input.supportingMemoryIds], tags: [...input.tags], beats: input.beats.map((beat) => ({ ...beat, context: { ...beat.context } })) } }
export function getNarrativeRelevance(thread: NarrativeThread, userCoachId: string, asOf: GameDate): number { const months = Math.max(0, (Number(asOf.slice(0, 4)) - Number(thread.lastOccurredOn.slice(0, 4))) * 12 + Number(asOf.slice(5, 7)) - Number(thread.lastOccurredOn.slice(5, 7))); return thread.relevance + (thread.protagonistIds.includes(userCoachId) ? 50 : 0) + (thread.status === 'escalating' ? 15 : 0) - Math.min(30, months) }
