import { coachPerkIdFromString, coachProfessionalTraitIdFromString, coachSkillIdFromString, type CoachId, type CoachPerkId, type CoachProfessionalTraitId, type CoachSkillId } from '@/domain/ids'
import { createCoachRpgProfile, PROFESSIONAL_TRAIT_EVIDENCE_IDS, type CoachRpgProfile, type ProfessionalTraitEvidenceId } from '@/domain/coachRpg'
import { STAFF_PROFESSIONAL_ATTRIBUTE_KEYS, type StaffProfessionalAttributeKey } from '@/domain/staff'
import { createGameWorld, type GameWorld } from '@/domain/world'

export const COACH_SKILL_MAX_RANK = 3
export const COACH_SKILL_RANK_COSTS = [0, 1, 2, 3] as const
export const COACH_SKILL_RANK_TWO_ATTRIBUTE_REQUIREMENT = 45
export const COACH_SKILL_RANK_THREE_ATTRIBUTE_REQUIREMENT = 60
export const COACH_SKILL_LEARNING_REDUCTION_PER_RANK = .02
export const COACH_LEARNING_REDUCTION_CAP = .15
export const PROFESSIONAL_TRAIT_EVIDENCE_THRESHOLD = 100
export const COACH_CAREER_FOCUS_PERK_LIMIT = 2
export type CoachPerkType = 'specialization' | 'careerFocus'
export type CoachCapability = 'advancedOpponentInsights'|'advancedIndividualDevelopmentPlans'|'secondaryUnitGamePlan'|'staffAssignedDevelopmentPlans'|'careerFocusTacticalMastery'|'careerFocusPlayerDevelopment'|'careerFocusCultureBuilding'|'careerFocusOrganizationBuilding'
export interface CoachSkillCatalogEntry { readonly id: CoachSkillId; readonly category: 'tactical'|'development'|'leadership'|'analysis'|'management'; readonly primaryAttribute: StaffProfessionalAttributeKey; readonly maxRank: 3 }
export interface CoachTraitCatalogEntry { readonly id: CoachProfessionalTraitId; readonly evidenceId: ProfessionalTraitEvidenceId; readonly requiredSkill?: readonly [CoachSkillId, number] }
export interface CoachPerkCatalogEntry { readonly id: CoachPerkId; readonly type: CoachPerkType; readonly cost: number; readonly skills: readonly (readonly [CoachSkillId, number])[]; readonly attributes: readonly (readonly [StaffProfessionalAttributeKey, number])[]; readonly capability: CoachCapability }
const skill = (id:string, category:CoachSkillCatalogEntry['category'], primaryAttribute:StaffProfessionalAttributeKey):CoachSkillCatalogEntry => ({id:coachSkillIdFromString(id),category,primaryAttribute,maxRank:3})
export const COACH_SKILL_CATALOG = [skill('gamePreparation','tactical','tacticalKnowledge'),skill('inGameAdjustment','tactical','adaptability'),skill('practiceDesign','development','coaching'),skill('individualDevelopmentPlanning','development','playerDevelopment'),skill('lockerRoomCommunication','leadership','communication'),skill('pressureLeadership','leadership','leadership'),skill('opponentStudy','analysis','analysis'),skill('performanceReview','analysis','analysis'),skill('delegation','management','communication'),skill('staffCoordination','management','discipline')] as const
const sid=(x:string)=>coachSkillIdFromString(x); const pid=(x:string)=>coachPerkIdFromString(x); const tid=(x:string)=>coachProfessionalTraitIdFromString(x)
export const COACH_TRAIT_CATALOG:readonly CoachTraitCatalogEntry[]=[{id:tid('youthDeveloper'),evidenceId:'youthDevelopment',requiredSkill:[sid('individualDevelopmentPlanning'),1]},{id:tid('shortRotationCoach'),evidenceId:'shortRotationUsage'},{id:tid('playersCoach'),evidenceId:'playerRelationshipSupport',requiredSkill:[sid('lockerRoomCommunication'),1]},{id:tid('tacticalTinkerer'),evidenceId:'tacticalVariation',requiredSkill:[sid('inGameAdjustment'),1]},{id:tid('practiceArchitect'),evidenceId:'practicePlanning',requiredSkill:[sid('practiceDesign'),2]},{id:tid('staffBuilder'),evidenceId:'staffDevelopment',requiredSkill:[sid('staffCoordination'),1]}]
const perk=(id:string,type:CoachPerkType,cost:number,skills:CoachPerkCatalogEntry['skills'],attributes:CoachPerkCatalogEntry['attributes'],capability:CoachCapability):CoachPerkCatalogEntry=>({id:pid(id),type,cost,skills,attributes,capability})
export const COACH_PERK_CATALOG:readonly CoachPerkCatalogEntry[]=[perk('filmRoomSpecialist','specialization',2,[[sid('opponentStudy'),2]],[['analysis',50]],'advancedOpponentInsights'),perk('individualDevelopmentPlans','specialization',2,[[sid('individualDevelopmentPlanning'),2]],[['playerDevelopment',50]],'advancedIndividualDevelopmentPlans'),perk('secondUnitArchitect','specialization',2,[[sid('gamePreparation'),2]],[['tacticalKnowledge',50]],'secondaryUnitGamePlan'),perk('delegatedDevelopment','specialization',2,[[sid('delegation'),2],[sid('staffCoordination'),1]],[],'staffAssignedDevelopmentPlans'),perk('tacticalMastery','careerFocus',4,[[sid('gamePreparation'),3],[sid('inGameAdjustment'),2]],[['tacticalKnowledge',60]],'careerFocusTacticalMastery'),perk('playerDevelopmentFocus','careerFocus',4,[[sid('individualDevelopmentPlanning'),3],[sid('practiceDesign'),2]],[['playerDevelopment',60]],'careerFocusPlayerDevelopment'),perk('cultureBuilder','careerFocus',4,[[sid('lockerRoomCommunication'),3],[sid('pressureLeadership'),2]],[['leadership',60]],'careerFocusCultureBuilding'),perk('organizationBuilder','careerFocus',4,[[sid('staffCoordination'),3],[sid('delegation'),2]],[['discipline',60]],'careerFocusOrganizationBuilding')]
export type CoachRpgOperationResult = {readonly ok:true;readonly world:GameWorld}|{readonly ok:false;readonly reason:string;readonly world:GameWorld}
export function calculateCoachLearningReduction(rpg:CoachRpgProfile,attribute:StaffProfessionalAttributeKey,externalReduction=0):number { if(!Number.isFinite(externalReduction)||externalReduction<0)throw new RangeError('External learning reduction must be finite and non-negative'); const reduction=COACH_SKILL_CATALOG.filter(x=>x.primaryAttribute===attribute).reduce((n,x)=>n+(rpg.skills[x.id]?.rank??0)*COACH_SKILL_LEARNING_REDUCTION_PER_RANK,externalReduction);return Math.min(COACH_LEARNING_REDUCTION_CAP,reduction) }
export function calculateEffectiveCoachLearningCost(cost:number,rpg:CoachRpgProfile,attribute:StaffProfessionalAttributeKey,externalReduction=0):number { if(!Number.isFinite(cost)||cost<0)throw new RangeError('Learning cost must be finite and non-negative');return Math.round(cost*(1-calculateCoachLearningReduction(rpg,attribute,externalReduction))*10000)/10000 }
export function purchaseCoachSkillRank(world:GameWorld,coachId:CoachId,skillId:CoachSkillId):CoachRpgOperationResult { const p=profiles(world,coachId);if(!p)return fail(world,'coachProfileUnavailable');const d=COACH_SKILL_CATALOG.find(x=>x.id===skillId);if(!d)return fail(world,'invalidSkill');const old=p.rpg.skills[skillId]?.rank??0;if(old>=3)return fail(world,'maxRankReached');const next=old+1,cost=COACH_SKILL_RANK_COSTS[next]!;if(p.rpg.development.developmentPoints<cost)return fail(world,'insufficientDevelopmentPoints');const min=next===2?45:next===3?60:0;if(p.professional.attributes[d.primaryAttribute]<min)return fail(world,'attributeRequirementNotMet');return succeed(world,coachId,{...p.rpg,skills:{...p.rpg.skills,[skillId]:{skillId,rank:next}},development:{...p.rpg.development,developmentPoints:p.rpg.development.developmentPoints-cost}}) }
export function purchaseCoachPerk(world:GameWorld,coachId:CoachId,perkId:CoachPerkId):CoachRpgOperationResult { const p=profiles(world,coachId);if(!p)return fail(world,'coachProfileUnavailable');const d=COACH_PERK_CATALOG.find(x=>x.id===perkId);if(!d)return fail(world,'invalidPerk');if(p.rpg.perks[perkId])return fail(world,'alreadyOwned');if(p.rpg.development.developmentPoints<d.cost)return fail(world,'insufficientDevelopmentPoints');if(d.skills.some(([id,rank])=>(p.rpg.skills[id]?.rank??0)<rank))return fail(world,'skillRequirementNotMet');if(d.attributes.some(([id,value])=>p.professional.attributes[id]<value))return fail(world,'attributeRequirementNotMet');if(d.type==='careerFocus'&&COACH_PERK_CATALOG.filter(x=>x.type==='careerFocus'&&p.rpg.perks[x.id]).length>=2)return fail(world,'careerFocusLimitReached');return succeed(world,coachId,{...p.rpg,perks:{...p.rpg.perks,[perkId]:{perkId,rank:1}},development:{...p.rpg.development,developmentPoints:p.rpg.development.developmentPoints-d.cost}}) }
export function hasCoachCapability(rpg:CoachRpgProfile,capability:CoachCapability):boolean{return COACH_PERK_CATALOG.some(x=>x.capability===capability&&rpg.perks[x.id]!==undefined)}
export function recordProfessionalTraitEvidence(world:GameWorld,coachId:CoachId,id:ProfessionalTraitEvidenceId,amount:number):CoachRpgOperationResult { if(!PROFESSIONAL_TRAIT_EVIDENCE_IDS.includes(id))return fail(world,'invalidTraitEvidence');if(!Number.isFinite(amount)||amount<0)return fail(world,'invalidTraitEvidence');const p=profiles(world,coachId);if(!p)return fail(world,'coachProfileUnavailable');return succeed(world,coachId,{...p.rpg,professionalTraitEvidence:{...p.rpg.professionalTraitEvidence,[id]:(p.rpg.professionalTraitEvidence[id]??0)+amount}}) }
export function reconcileProfessionalTraits(world:GameWorld,coachId:CoachId):CoachRpgOperationResult { const p=profiles(world,coachId);if(!p)return fail(world,'coachProfileUnavailable');const traits=[...p.rpg.professionalTraits];for(const t of COACH_TRAIT_CATALOG)if((p.rpg.professionalTraitEvidence[t.evidenceId]??0)>=100&&(!t.requiredSkill||(p.rpg.skills[t.requiredSkill[0]]?.rank??0)>=t.requiredSkill[1])&&!traits.includes(t.id))traits.push(t.id);return succeed(world,coachId,{...p.rpg,professionalTraits:traits}) }
function profiles(world:GameWorld,id:CoachId){const professional=world.coachProfessionalProfilesByCoachId[id],rpg=world.coachRpgProfilesByCoachId[id];return professional&&rpg?{professional,rpg}:undefined}function fail(world:GameWorld,reason:string):CoachRpgOperationResult{return{ok:false,reason,world}}function succeed(world:GameWorld,id:CoachId,rpg:CoachRpgProfile):CoachRpgOperationResult{return{ok:true,world:rebuild(world,id,createCoachRpgProfile(rpg))}}function rebuild(w:GameWorld,id:CoachId,rpg:CoachRpgProfile):GameWorld{return createGameWorld({currentDate:w.currentDate,currentSeasonId:w.currentSeasonId,userCoachId:w.userCoachId,countries:Object.values(w.countries),coaches:Object.values(w.coaches),players:Object.values(w.players),teams:Object.values(w.teams),competitions:Object.values(w.competitions),seasons:Object.values(w.seasons),games:Object.values(w.games),matchStatLogs:Object.values(w.matchStatLogsByGameId),seasonHistory:Object.values(w.seasonHistoryBySeasonId),injuries:Object.values(w.injuriesById),contracts:Object.values(w.contractsById),teamFinances:Object.values(w.teamFinancesByTeamId),playerTransactions:Object.values(w.playerTransactionsById),playerKnowledge:Object.values(w.playerKnowledgeById),staffPeople:Object.values(w.staffPeopleById),teamStaffAssignments:Object.values(w.teamStaffAssignmentsById),coachProfessionalProfilesByCoachId:w.coachProfessionalProfilesByCoachId,coachRpgProfilesByCoachId:{...w.coachRpgProfilesByCoachId,[id]:rpg},coachReputationProfilesByCoachId: w.coachReputationProfilesByCoachId, coachEmploymentByCoachId: w.coachEmploymentByCoachId, coachCareerHistoryByCoachId: w.coachCareerHistoryByCoachId, coachJobOpeningsById: w.coachJobOpeningsById, coachJobCandidaciesById: w.coachJobCandidaciesById, coachInterviewsByCandidacyId: w.coachInterviewsByCandidacyId, coachJobOffersById: w.coachJobOffersById, relationshipsByKey: w.relationshipsByKey})}
