import { addYears } from '@/domain/date'
import { createPlayerContract, getPlayerContractStatus } from '@/domain/contract'
import { contractIdFromString, playerTransactionIdFromString, type PlayerId, type TeamId } from '@/domain/ids'
import { calculateBootstrapAbilityProxy } from '@/domain/player'
import { canTeamAffordAdditionalSalary, createGameWorld, getActivePlayerContract, getAvailableRosterPlayers, getPlayerRosterTeamId, isPlayerFreeAgent, type GameWorld } from '@/domain/world'
import { hashStringToSeed, SeededRandomSource } from '@/engine/random'
export interface FreeAgentMarketTerms{readonly playerId:PlayerId;readonly annualSalary:number;readonly contractYears:number}
export const calculateBootstrapSalaryBase=(ability:number)=>100_000+Math.pow(Math.max(0,ability-40),2)*1_000
export function getFreeAgentMarketTerms(world:GameWorld,playerId:PlayerId,onDate=world.currentDate):FreeAgentMarketTerms{const player=world.players[playerId];if(!player||!isPlayerFreeAgent(world,playerId,onDate))throw new Error('Player is not a free agent');const ability=calculateBootstrapAbilityProxy(player.basketball.ratings);const variance=new SeededRandomSource(hashStringToSeed(`free-agent-market-salary-v1:${world.currentSeasonId}:${playerId}`)).nextFloat(.95,1.15);return{playerId,annualSalary:Math.max(1,Math.round(calculateBootstrapSalaryBase(ability)*variance/10_000)*10_000),contractYears:new SeededRandomSource(hashStringToSeed(`free-agent-market-term-v1:${world.currentSeasonId}:${playerId}`)).nextInt(1,4)}}
export function releasePlayer(world:GameWorld,teamId:TeamId,playerId:PlayerId):GameWorld{const team=world.teams[teamId];if(!team||!team.rosterPlayerIds.includes(playerId))throw new Error('Player is not on Team roster');if(team.rosterPlayerIds.length<=5||getAvailableRosterPlayers(world,teamId).length<=5)throw new Error('Release would leave insufficient players');const contract=getActivePlayerContract(world,playerId);if(!contract||contract.teamId!==teamId)throw new Error('Player has no active Contract with Team');return rebuild(world,Object.values(world.contractsById).map(c=>c.id===contract.id?{...c,termination:{terminatedOn:world.currentDate,reason:'released' as const}}:c),Object.values(world.teams).map(t=>t.id===teamId?{...t,rosterPlayerIds:t.rosterPlayerIds.filter(id=>id!==playerId)}:t),[{id:playerTransactionIdFromString(`transaction:released:${contract.id}`),playerId,kind:'released' as const,occurredOn:world.currentDate,fromTeamId:teamId,contractId:contract.id}])}
export function signFreeAgent(world:GameWorld,teamId:TeamId,playerId:PlayerId):GameWorld{if(!world.teams[teamId]||!isPlayerFreeAgent(world,playerId))throw new Error('Player is not a free agent');const terms=getFreeAgentMarketTerms(world,playerId);if(!canTeamAffordAdditionalSalary(world,teamId,terms.annualSalary))throw new Error('Team cannot afford salary');const ordinal=Object.values(world.contractsById).filter(c=>c.playerId===playerId&&c.term.startsOn===world.currentDate).length+1;const contract=createPlayerContract({id:contractIdFromString(`contract:${playerId}:${teamId}:${world.currentDate}:${ordinal}`),playerId,teamId,kind:'standard',term:{startsOn:world.currentDate,expiresOn:addYears(world.currentDate,terms.contractYears)},compensation:{annualSalary:terms.annualSalary}});return rebuild(world,[...Object.values(world.contractsById),contract],Object.values(world.teams).map(t=>t.id===teamId?{...t,rosterPlayerIds:[...t.rosterPlayerIds,playerId]}:t),[{id:playerTransactionIdFromString(`transaction:signedFreeAgent:${contract.id}`),playerId,kind:'signedFreeAgent' as const,occurredOn:world.currentDate,toTeamId:teamId,contractId:contract.id}])}
function rebuild(world:GameWorld,contracts:readonly any[],teams:readonly any[],transactions:readonly any[]):GameWorld{return createGameWorld({currentDate:world.currentDate,currentSeasonId:world.currentSeasonId,userCoachId:world.userCoachId,countries:Object.values(world.countries),coaches:Object.values(world.coaches),players:Object.values(world.players),teams,competitions:Object.values(world.competitions),seasons:Object.values(world.seasons),games:Object.values(world.games),matchStatLogs:Object.values(world.matchStatLogsByGameId),seasonHistory:Object.values(world.seasonHistoryBySeasonId),injuries:Object.values(world.injuriesById),contracts,teamFinances:Object.values(world.teamFinancesByTeamId),playerTransactions:[...Object.values(world.playerTransactionsById),...transactions],playerKnowledge:Object.values(world.playerKnowledgeById),staffPeople:Object.values(world.staffPeopleById),teamStaffAssignments:Object.values(world.teamStaffAssignmentsById),coachProfessionalProfilesByCoachId:world.coachProfessionalProfilesByCoachId,coachRpgProfilesByCoachId: world.coachRpgProfilesByCoachId, coachReputationProfilesByCoachId: world.coachReputationProfilesByCoachId})}
