import type { CoachAchievementType, CoachLegacyState, CoachTeamLegacy } from '@/domain/legacy'
import { coachTeamLegacyKey } from '@/domain/legacy'
import type { CoachId, TeamId } from '@/domain/ids'
import { updateGameWorld, type GameWorld } from '@/domain/world'
import { recordMemory } from '@/engine/memory'
export const LEGACY_CONFIG={clubLegend:100,hallCandidate:140,hallInducted:220,dynastyTitles:3} as const
export function openCoachTenure(world:GameWorld,coachId:CoachId,teamId:TeamId){const id=`tenure:${coachId}:${teamId}:${world.currentDate}`;if(world.coachTenuresById[id])return world;const tenure={id,coachId,teamId,startedOn:world.currentDate,achievementIds:[],seasonsManaged:0,processedSeasonIds:[],milestoneKeys:[],dynastyCount:0};const legacy=world.coachLegacyByCoachId[coachId]??empty(coachId);const teamLegacy=world.coachTeamLegacyByKey[coachTeamLegacyKey(coachId,teamId)]??emptyTeam(coachId,teamId);return updateGameWorld(world,{coachTenuresById:{...world.coachTenuresById,[id]:tenure},coachLegacyByCoachId:{...world.coachLegacyByCoachId,[coachId]:{...legacy,tenureIds:[...legacy.tenureIds,id]}},coachTeamLegacyByKey:{...world.coachTeamLegacyByKey,[coachTeamLegacyKey(coachId,teamId)]:{...teamLegacy,tenureIds:[...teamLegacy.tenureIds,id]}}})}
export function closeCoachTenure(world:GameWorld,coachId:CoachId,teamId:TeamId){const tenure=Object.values(world.coachTenuresById).filter(item=>item.coachId===coachId&&item.teamId===teamId&&item.endedOn===undefined).sort((a,b)=>b.startedOn.localeCompare(a.startedOn))[0];return tenure===undefined?world:updateGameWorld(world,{coachTenuresById:{...world.coachTenuresById,[tenure.id]:{...tenure,endedOn:world.currentDate}}})}
export function recordCoachAchievement(world:GameWorld,input:{coachId:CoachId;teamId:TeamId;seasonId:any;type:CoachAchievementType;sourceEventKey:string;outsider?:boolean}){const id=`legacy:${input.coachId}:${input.teamId}:${input.seasonId}:${input.type}`;if(Object.values(world.coachAchievementsById).some(a=>a.sourceEventKey===input.sourceEventKey))return world;const value=(input.type==='championship'?40:input.type==='promotion'?22:input.type==='dynasty'?35:15)+(input.outsider?20:0);const achievement={id,...input,legacyValue:value,occurredOn:world.currentDate};const legacy=world.coachLegacyByCoachId[input.coachId]??empty(input.coachId);const key=coachTeamLegacyKey(input.coachId,input.teamId);const team=world.coachTeamLegacyByKey[key]??emptyTeam(input.coachId,input.teamId);const teamValue=team.legacyValue+value;const globalValue=legacy.legacyValue+value;let next=updateGameWorld(world,{coachAchievementsById:{...world.coachAchievementsById,[id]:achievement},coachLegacyByCoachId:{...world.coachLegacyByCoachId,[input.coachId]:{...legacy,achievementIds:[...legacy.achievementIds,id],legacyValue:globalValue,status:globalStatus(globalValue),hallStatus:hallStatus(globalValue,legacy.hallStatus)}},coachTeamLegacyByKey:{...world.coachTeamLegacyByKey,[key]:{...team,legacyValue:teamValue,status:clubStatus(teamValue)}}});return recognizeMilestones(next,input.coachId,input.teamId)}
export function processCoachSeason(world:GameWorld,input:{coachId:CoachId;teamId:TeamId;seasonId:string}){const tenure=activeTenure(world,input.coachId,input.teamId);if(!tenure||tenure.processedSeasonIds?.includes(input.seasonId))return world;const seasons=(tenure.seasonsManaged??0)+1;const longevity=Math.max(1,Math.round(4/Math.sqrt(seasons)));let next=updateGameWorld(world,{coachTenuresById:{...world.coachTenuresById,[tenure.id]:{...tenure,seasonsManaged:seasons,processedSeasonIds:[...(tenure.processedSeasonIds??[]),input.seasonId]}}});next=addLegacyValue(next,input.coachId,input.teamId,longevity);return recognizeMilestones(next,input.coachId,input.teamId)}
export function recordTierLegacy(world:GameWorld,input:{coachId:CoachId;teamId:TeamId;seasonId:string;resolutionId:string;movement:'promotion'|'relegation';unexpected:boolean}){const eventKey=`legacy:${input.movement}:${input.resolutionId}:${input.teamId}`,legacy=world.coachLegacyByCoachId[input.coachId]??empty(input.coachId);if(legacy.processedEventKeys.includes(eventKey))return world;if(input.movement==='promotion')return recordCoachAchievement(updateGameWorld(world,{coachLegacyByCoachId:{...world.coachLegacyByCoachId,[input.coachId]:{...legacy,processedEventKeys:[...legacy.processedEventKeys,eventKey]}}}),{...input,type:'promotion',sourceEventKey:eventKey,outsider:input.unexpected});const next=addLegacyValue(world,input.coachId,input.teamId,input.unexpected?-1:-4);const updated=next.coachLegacyByCoachId[input.coachId]??legacy;return updateGameWorld(next,{coachLegacyByCoachId:{...next.coachLegacyByCoachId,[input.coachId]:{...updated,processedEventKeys:[...updated.processedEventKeys,eventKey]}}})}
export function evaluateCoachLegacy(world:GameWorld,coachId:CoachId,teamId?:TeamId){return teamId===undefined?recognizeMilestones(world,coachId,Object.values(world.coachTenuresById).find(x=>x.coachId===coachId)?.teamId??('' as TeamId)):recognizeMilestones(world,coachId,teamId)}
export function getCoachLegacySummary(world:GameWorld,coachId:CoachId){return world.coachLegacyByCoachId[coachId]??empty(coachId)}
export function getTeamCoachLegends(world:GameWorld,teamId:TeamId):readonly CoachTeamLegacy[]{return Object.values(world.coachTeamLegacyByKey).filter(x=>x.teamId===teamId&&x.status==='clubLegend').sort((a,b)=>b.legacyValue-a.legacyValue)}
function activeTenure(world:GameWorld,coachId:CoachId,teamId:TeamId){return Object.values(world.coachTenuresById).filter(x=>x.coachId===coachId&&x.teamId===teamId&&x.endedOn===undefined).sort((a,b)=>b.startedOn.localeCompare(a.startedOn))[0]}
function addLegacyValue(world:GameWorld,coachId:CoachId,teamId:TeamId,value:number){const legacy=world.coachLegacyByCoachId[coachId]??empty(coachId),key=coachTeamLegacyKey(coachId,teamId),team=world.coachTeamLegacyByKey[key]??emptyTeam(coachId,teamId);const globalValue=Math.max(0,legacy.legacyValue+value),teamValue=Math.max(0,team.legacyValue+value);return updateGameWorld(world,{coachLegacyByCoachId:{...world.coachLegacyByCoachId,[coachId]:{...legacy,legacyValue:globalValue,status:globalStatus(globalValue),hallStatus:hallStatus(globalValue,legacy.hallStatus)}},coachTeamLegacyByKey:{...world.coachTeamLegacyByKey,[key]:{...team,legacyValue:teamValue,status:clubStatus(teamValue)}}})}
function recognizeMilestones(world:GameWorld,coachId:CoachId,teamId:TeamId){const legacy=world.coachLegacyByCoachId[coachId]??empty(coachId),key=coachTeamLegacyKey(coachId,teamId),team=world.coachTeamLegacyByKey[key]??emptyTeam(coachId,teamId);const titles=Object.values(world.coachAchievementsById).filter(x=>x.coachId===coachId&&x.teamId===teamId&&x.type==='championship').length;let next=world;if(titles>=LEGACY_CONFIG.dynastyTitles&&!Object.values(next.coachAchievementsById).some(x=>x.coachId===coachId&&x.teamId===teamId&&x.type==='dynasty'))next=recordCoachAchievement(next,{coachId,teamId,seasonId:`dynasty-${titles}`,type:'dynasty',sourceEventKey:`legacy:dynasty:${coachId}:${teamId}`,outsider:false});const currentLegacy=next.coachLegacyByCoachId[coachId]??legacy,currentTeam=next.coachTeamLegacyByKey[key]??team;const marks:string[]=[];if(currentTeam.status==='clubLegend')marks.push('clubLegendReached');if(titles>=LEGACY_CONFIG.dynastyTitles)marks.push('dynastyEstablished');if(currentLegacy.hallStatus==='candidate'||currentLegacy.hallStatus==='inducted')marks.push(`hall${currentLegacy.hallStatus==='inducted'?'Inducted':'Candidate'}`);for(const mark of marks){const global=next.coachLegacyByCoachId[coachId]??legacy,club=next.coachTeamLegacyByKey[key]??team;if((global.milestoneKeys??[]).includes(`${mark}:${teamId}`))continue;next=updateGameWorld(next,{coachLegacyByCoachId:{...next.coachLegacyByCoachId,[coachId]:{...global,milestoneKeys:[...(global.milestoneKeys??[]),`${mark}:${teamId}`]}},coachTeamLegacyByKey:{...next.coachTeamLegacyByKey,[key]:{...club,milestoneKeys:[...(club.milestoneKeys??[]),mark]}}});next=recordMemory(next,{id:`memory:legacy:${mark}:${coachId}:${teamId}`,owner:{kind:'coach',id:coachId},type:'historicSeason',occurredOn:next.currentDate,entityRefs:[{kind:'team',id:teamId}],semanticKey:`legacy:${mark}:${coachId}:${teamId}`,importance:mark==='hallInducted'?'historic':'major',valence:100,intensity:100,decayPerMonth:0,permanent:true,tags:['legacy',mark],context:{milestone:mark,teamId}})}return next}
function empty(coachId:CoachId):CoachLegacyState{return{coachId,achievementIds:[],tenureIds:[],legacyValue:0,status:'unproven',hallStatus:'notEligible',processedEventKeys:[],milestoneKeys:[]}}
function emptyTeam(coachId:CoachId,teamId:TeamId):CoachTeamLegacy{return{coachId,teamId,tenureIds:[],legacyValue:0,status:'forgettable',milestoneKeys:[]}}
function clubStatus(value:number):CoachTeamLegacy['status']{return value>=100?'clubLegend':value>=65?'icon':value>=35?'respected':value>=10?'remembered':'forgettable'}
function globalStatus(value:number):CoachLegacyState['status']{return value>=220?'legendary':value>=150?'historic':value>=90?'distinguished':value>=45?'notable':value>=15?'established':'unproven'}
function hallStatus(value:number,current:CoachLegacyState['hallStatus']):CoachLegacyState['hallStatus']{if(current==='inducted'||value>=220)return'inducted';return value>=140?'candidate':value>=80?'eligible':'notEligible'}
