import { describe, expect, it } from 'vitest'
import { createNewGame } from '@/app/game'
import { updateGameWorld } from '@/domain/world'
import { deserializeGameWorldV1, serializeGameWorldV1 } from '@/save/GameWorldSaveV1'
import { closeCoachTenure, getCoachLegacySummary, openCoachTenure, recordCoachAchievement, recordTierLegacy, processCoachSeason } from './LegacyEngine'

const setup=()=>{const world=createNewGame();const team=Object.values(world.teams).find(item=>item.coachId===world.userCoachId)!;return{world:openCoachTenure(world,world.userCoachId,team.id),coachId:world.userCoachId,teamId:team.id}}
const title=(world:ReturnType<typeof createNewGame>,coachId:any,teamId:any,season:string,outsider=false)=>recordCoachAchievement(world,{coachId,teamId,seasonId:season,type:'championship',sourceEventKey:`title:${season}:${teamId}`,outsider})

describe('Hito 066 acceptance',()=>{
 it('1 Expected Title',()=>{const {world,coachId,teamId}=setup(),next=title(world,coachId,teamId,'s1');expect(next.coachAchievementsById).toHaveProperty(`legacy:${coachId}:${teamId}:s1:championship`);expect(getCoachLegacySummary(next,coachId).legacyValue).toBeGreaterThan(0);expect(title(next,coachId,teamId,'s1')).toEqual(next)})
 it('2 Outsider Title',()=>{const a=setup(),b=setup();expect(title(b.world,b.coachId,b.teamId,'s1',true).coachAchievementsById[`legacy:${b.coachId}:${b.teamId}:s1:championship`]!.legacyValue).toBeGreaterThan(title(a.world,a.coachId,a.teamId,'s1').coachAchievementsById[`legacy:${a.coachId}:${a.teamId}:s1:championship`]!.legacyValue)})
 it('3 Promotion',()=>{const {world,coachId,teamId}=setup(),next=recordTierLegacy(world,{coachId,teamId,seasonId:'s1',resolutionId:'r1',movement:'promotion',unexpected:true});expect(Object.values(next.coachAchievementsById).some(item=>item.type==='promotion')).toBe(true);expect(next.coachTeamLegacyByKey[`${coachId}:${teamId}`]!.legacyValue).toBeGreaterThan(0);expect(recordTierLegacy(next,{coachId,teamId,seasonId:'s1',resolutionId:'r1',movement:'promotion',unexpected:true})).toEqual(next)})
 it('4 Transformative Era',()=>{const {world,coachId,teamId}=setup();const ordinary=title(world,coachId,teamId,'s1');let era=recordTierLegacy(world,{coachId,teamId,seasonId:'s1',resolutionId:'r1',movement:'promotion',unexpected:true});era=processCoachSeason(era,{coachId,teamId,seasonId:'s1'});era=title(era,coachId,teamId,'s2',true);expect(era.coachTeamLegacyByKey[`${coachId}:${teamId}`]!.legacyValue).toBeGreaterThan(ordinary.coachTeamLegacyByKey[`${coachId}:${teamId}`]!.legacyValue)})
 it('5 Short Failed Tenure',()=>{const {world,coachId,teamId}=setup();const high=title(world,coachId,teamId,'s1',true);const next=recordTierLegacy(high,{coachId,teamId,seasonId:'s2',resolutionId:'r2',movement:'relegation',unexpected:false});expect(getCoachLegacySummary(next,coachId).legacyValue).toBeGreaterThan(0)})
 it('6 Long Successful Era',()=>{const a=setup();let long=a.world;for(let i=0;i<6;i++)long=processCoachSeason(long,{coachId:a.coachId,teamId:a.teamId,seasonId:`s${i}`});long=title(long,a.coachId,a.teamId,'title');const short=title(a.world,a.coachId,a.teamId,'title');expect(long.coachTeamLegacyByKey[`${a.coachId}:${a.teamId}`]!.legacyValue).toBeGreaterThan(short.coachTeamLegacyByKey[`${a.coachId}:${a.teamId}`]!.legacyValue)})
 it('7 Dynasty',()=>{const a=setup();let world=a.world;for(let i=1;i<=3;i++)world=title(world,a.coachId,a.teamId,`s${i}`);expect(Object.values(world.coachAchievementsById).filter(item=>item.type==='dynasty')).toHaveLength(1);expect(world.coachLegacyByCoachId[a.coachId]!.milestoneKeys).toContain(`dynastyEstablished:${a.teamId}`)})
 it('8 Single Title Is Not Dynasty',()=>{const a=setup(),world=title(a.world,a.coachId,a.teamId,'s1');expect(Object.values(world.coachAchievementsById).some(item=>item.type==='dynasty')).toBe(false)})
 it('9 Club Legend',()=>{const a=setup();let world=a.world;for(let i=1;i<=3;i++)world=title(world,a.coachId,a.teamId,`s${i}`,true);expect(world.coachTeamLegacyByKey[`${a.coachId}:${a.teamId}`]!.status).toBe('clubLegend');expect(Object.values(world.memoriesById).filter(item=>item.semanticKey===`legacy:clubLegendReached:${a.coachId}:${a.teamId}`)).toHaveLength(1)})
 it('10 Global Legend / Minor Club Legacy',()=>{const a=setup();let world=a.world;for(let i=1;i<=4;i++)world=title(world,a.coachId,a.teamId,`s${i}`,true);const other=Object.values(world.teams).find(item=>item.id!==a.teamId)!;world=openCoachTenure(world,a.coachId,other.id);expect(world.coachLegacyByCoachId[a.coachId]!.legacyValue).toBeGreaterThan(world.coachTeamLegacyByKey[`${a.coachId}:${other.id}`]!.legacyValue)})
 it('11 Successful Return',()=>{const a=setup();let world=title(a.world,a.coachId,a.teamId,'s1');world=closeCoachTenure(world,a.coachId,a.teamId);world=updateGameWorld(world,{currentDate:'2033-01-01' as never});world=openCoachTenure(world,a.coachId,a.teamId);world=title(world,a.coachId,a.teamId,'s2');expect(Object.values(world.coachTenuresById).filter(item=>item.teamId===a.teamId)).toHaveLength(2);expect(Object.values(world.coachTeamLegacyByKey).filter(item=>item.teamId===a.teamId)).toHaveLength(1)})
 it('12 Legacy vs Reputation',()=>{const a=setup(),world=title(a.world,a.coachId,a.teamId,'s1',true);const lowered=updateGameWorld(world,{coachReputationProfilesByCoachId:{...world.coachReputationProfilesByCoachId,[a.coachId]:{...world.coachReputationProfilesByCoachId[a.coachId]!,values:{competitive:0,development:0,professional:0,publicStanding:0}}}});expect(getCoachLegacySummary(lowered,a.coachId).legacyValue).toBe(getCoachLegacySummary(world,a.coachId).legacyValue)})
 it('13 Hall',()=>{const a=setup();let world=a.world;for(let i=1;i<=4;i++)world=title(world,a.coachId,a.teamId,`s${i}`,true);expect(world.coachLegacyByCoachId[a.coachId]!.hallStatus).toBe('inducted');expect(recordTierLegacy(world,{coachId:a.coachId,teamId:a.teamId,seasonId:'bad',resolutionId:'bad',movement:'relegation',unexpected:false}).coachLegacyByCoachId[a.coachId]!.hallStatus).toBe('inducted')})
 it('14 Save / Load',()=>{const a=setup();let world=title(a.world,a.coachId,a.teamId,'s1',true);world=processCoachSeason(world,{coachId:a.coachId,teamId:a.teamId,seasonId:'s1'});const loaded=deserializeGameWorldV1(serializeGameWorldV1(world,'2032-01-01T00:00:00.000Z'));expect(title(loaded,a.coachId,a.teamId,'s1',true).coachAchievementsById).toEqual(world.coachAchievementsById)})
 it('15 Legacy Empty State',()=>{const world=createNewGame();expect(getCoachLegacySummary(world,world.userCoachId).legacyValue).toBe(0);expect(Object.values(world.coachTenuresById)).toHaveLength(0);expect(Object.values(world.coachAchievementsById)).toHaveLength(0)})
})
