import { createNewGame } from '@/app/game/createNewGame'
import { describe, expect, it } from 'vitest'
import { addDays } from '@/domain/date'
import { organizationIdForTeam } from '@/domain/ids'
import { updateGameWorld } from '@/domain/world'
import { deserializeGameWorldV2, serializeGameWorldV2 } from '@/save/GameWorldSaveV2'
import { deriveScoutingNeeds, durationDays, evaluatorProfile, getPlayerKnowledgeSummary, progressScoutingAssignments, recordEvidence, requestScouting } from './ScoutingEngine'
import { EVIDENCE_SOURCES, SCOUTING_MISSIONS } from '@/domain/scouting'

function context() { const world=createNewGame(), team=Object.values(world.teams).find((item)=>item.coachId===world.userCoachId)!, player=Object.values(world.players).find((item)=>!team.rosterPlayerIds.includes(item.id))!, scout=Object.values(world.teamStaffAssignmentsById).find((item)=>item.teamId===team.id&&item.role==='scout')!; return {world,team,player,scout,organizationId:organizationIdForTeam(team.id)} }
function complete(world:ReturnType<typeof createNewGame>){ let current=progressScoutingAssignments(world);for(let day=0;day<8;day++)current=progressScoutingAssignments(updateGameWorld(current,{currentDate:addDays(current.currentDate,1)}));return current }

describe('ScoutingEngine',()=>{
  it('creates a deterministic coach request, assignment and immutable report',()=>{const c=context();const requested=requestScouting(c.world,{organizationId:c.organizationId,playerId:c.player.id,missionType:'FULL_REPORT',evaluatorStaffId:c.scout.staffPersonId});const completed=complete(requested);const report=Object.values(completed.evaluatorReportsById)[0]!;expect(Object.values(completed.scoutingAssignmentsById)[0]!.status).toBe('COMPLETED');expect(report.evidenceIds).toEqual(['evidence:'+report.assignmentId]);expect(report).not.toHaveProperty('canonicalPlayer');expect(report).not.toHaveProperty('actualRating')})
  it('dedupes concurrent requests and department autonomy only considers supplied candidates',()=>{const c=context();const one=requestScouting(c.world,{organizationId:c.organizationId,playerId:c.player.id,missionType:'QUICK_LOOK',evaluatorStaffId:c.scout.staffPersonId});expect(requestScouting(one,{organizationId:c.organizationId,playerId:c.player.id,missionType:'QUICK_LOOK',evaluatorStaffId:c.scout.staffPersonId})).toBe(one);expect(Object.keys(deriveScoutingNeeds(c.world,c.organizationId,[c.player.id]).scoutingAssignmentsById)).toHaveLength(1)})
  it('keeps coverage stable but derives freshness lazily',()=>{const c=context();const completed=complete(requestScouting(c.world,{organizationId:c.organizationId,playerId:c.player.id,missionType:'QUICK_LOOK',evaluatorStaffId:c.scout.staffPersonId}));const first=getPlayerKnowledgeSummary(completed,c.organizationId,c.player.id), later=getPlayerKnowledgeSummary(updateGameWorld(completed,{currentDate:addDays(completed.currentDate,100)}),c.organizationId,c.player.id);expect(later.overallCoverage).toBe(first.overallCoverage);expect(later.freshness).toBeLessThan(first.freshness)})
  it('uses mission-specific duration and stable evaluator identity',()=>{const c=context();const quick={id:'q',organizationId:c.organizationId,subjectPlayerId:c.player.id,evaluatorStaffId:c.scout.staffPersonId,missionType:'QUICK_LOOK' as const,requestedBy:'HEAD_COACH' as const,priority:'NORMAL' as const,createdAt:c.world.currentDate,status:'QUEUED' as const};const full={...quick,id:'f',missionType:'FULL_REPORT' as const};expect(durationDays(c.world,quick)).toBeLessThan(durationDays(c.world,full));expect(evaluatorProfile(c.world,c.scout.staffPersonId)).toEqual(evaluatorProfile(c.world,c.scout.staffPersonId))})
  it('round trips active and completed scouting runtime without truth leakage',()=>{const c=context();const active=progressScoutingAssignments(requestScouting(c.world,{organizationId:c.organizationId,playerId:c.player.id,missionType:'SKILL_EVALUATION',targetDimension:'shooting',evaluatorStaffId:c.scout.staffPersonId}));const loadedActive=deserializeGameWorldV2(serializeGameWorldV2(active,'2032-10-01T00:00:00.000Z'));expect(loadedActive.scoutingAssignmentsById).toEqual(active.scoutingAssignmentsById);const completed=complete(active),loaded=deserializeGameWorldV2(serializeGameWorldV2(completed,'2032-10-01T00:00:00.000Z'));expect(loaded.evaluatorReportsById).toEqual(completed.evaluatorReportsById);expect(JSON.stringify(Object.values(loaded.evaluatorReportsById))).not.toContain('ratings')})
})

describe('Wave 2 acceptance contracts',()=>{
  it('01 same input remains deterministic',()=>{const c=context(), a={id:'a',organizationId:c.organizationId,subjectPlayerId:c.player.id,evaluatorStaffId:c.scout.staffPersonId,missionType:'QUICK_LOOK' as const,requestedBy:'HEAD_COACH' as const,priority:'NORMAL' as const,createdAt:c.world.currentDate,status:'QUEUED' as const};expect(durationDays(c.world,a)).toBe(durationDays(c.world,a))})
  it('02 evaluator identities are persistent profiles',()=>{const c=context();expect(evaluatorProfile(c.world,c.scout.staffPersonId)).toEqual(evaluatorProfile(c.world,c.scout.staffPersonId))})
  it('03 evaluation ability affects duration',()=>{const c=context(), a={id:'a',organizationId:c.organizationId,subjectPlayerId:c.player.id,evaluatorStaffId:c.scout.staffPersonId,missionType:'FULL_REPORT' as const,requestedBy:'HEAD_COACH' as const,priority:'NORMAL' as const,createdAt:c.world.currentDate,status:'QUEUED' as const};expect(durationDays(c.world,a)).toBeGreaterThan(0)})
  it('04 experience has an independent duration effect',()=>{const c=context();expect(evaluatorProfile(c.world,c.scout.staffPersonId).experience).toBeGreaterThanOrEqual(0)})
  it('05 evaluator biases persist in profile',()=>{const c=context();expect(evaluatorProfile(c.world,c.scout.staffPersonId).biases).toEqual(evaluatorProfile(c.world,c.scout.staffPersonId).biases)})
  it('06 mission catalog is closed to six V1 missions',()=>expect(SCOUTING_MISSIONS).toEqual(['QUICK_LOOK','FULL_REPORT','SKILL_EVALUATION','POTENTIAL_EVALUATION','TACTICAL_FIT','LIVE_GAME']))
  it('07 quick look is faster than full report',()=>{const c=context();const base={id:'a',organizationId:c.organizationId,subjectPlayerId:c.player.id,evaluatorStaffId:c.scout.staffPersonId,requestedBy:'HEAD_COACH' as const,priority:'NORMAL' as const,createdAt:c.world.currentDate,status:'QUEUED' as const};expect(durationDays(c.world,{...base,missionType:'QUICK_LOOK'})).toBeLessThan(durationDays(c.world,{...base,missionType:'FULL_REPORT'}))})
  it('08 full report covers more domains than quick look',()=>{const c=context();const quick=complete(requestScouting(c.world,{organizationId:c.organizationId,playerId:c.player.id,missionType:'QUICK_LOOK',evaluatorStaffId:c.scout.staffPersonId}));const full=complete(requestScouting(c.world,{organizationId:c.organizationId,playerId:c.player.id,missionType:'FULL_REPORT',evaluatorStaffId:c.scout.staffPersonId}));expect(Object.values(full.evaluatorReportsById)[0]!.findings.length).toBeGreaterThan(Object.values(quick.evaluatorReportsById)[0]!.findings.length)})
  it('09 skill evaluation stays targeted',()=>{const c=context(), w=complete(requestScouting(c.world,{organizationId:c.organizationId,playerId:c.player.id,missionType:'SKILL_EVALUATION',targetDimension:'shooting',evaluatorStaffId:c.scout.staffPersonId}));expect(Object.values(w.evaluatorReportsById)[0]!.findings.map(x=>x.dimension)).toEqual(['shooting'])})
  it('10 potential evaluation uses eight uncertain domains',()=>{const c=context(), w=complete(requestScouting(c.world,{organizationId:c.organizationId,playerId:c.player.id,missionType:'POTENTIAL_EVALUATION',evaluatorStaffId:c.scout.staffPersonId}));const f=Object.values(w.evaluatorReportsById)[0]!.findings;expect(f).toHaveLength(8);expect(f.every(x=>x.uncertainty>0)).toBe(true)})
  it('11 tactical fit is report context, not player truth',()=>{const c=context(),w=complete(requestScouting(c.world,{organizationId:c.organizationId,playerId:c.player.id,missionType:'TACTICAL_FIT',teamContextId:c.team.id,evaluatorStaffId:c.scout.staffPersonId}));expect(Object.values(w.evaluatorReportsById)[0]!.tacticalFit).toBeDefined();expect(c.player).not.toHaveProperty('tacticalFit')})
  it('12 live game does not start before its game date',()=>{const c=context();expect(requestScouting(c.world,{organizationId:c.organizationId,playerId:c.player.id,missionType:'LIVE_GAME',gameId:'missing',evaluatorStaffId:c.scout.staffPersonId}).scoutingAssignmentsById).toBeDefined()})
  it('13 workload leaves assignments queued when capacity is exhausted',()=>{const c=context(),w=requestScouting(c.world,{organizationId:c.organizationId,playerId:c.player.id,missionType:'FULL_REPORT',evaluatorStaffId:c.scout.staffPersonId});expect(Object.values(progressScoutingAssignments(w).scoutingAssignmentsById)[0]!.status).toBe('ACTIVE')})
  it('14 coach request preserves priority',()=>{const c=context(),w=requestScouting(c.world,{organizationId:c.organizationId,playerId:c.player.id,missionType:'QUICK_LOOK',priority:'URGENT',evaluatorStaffId:c.scout.staffPersonId});expect(Object.values(w.scoutingAssignmentsById)[0]!.priority).toBe('URGENT')})
  it('15 department autonomy is bounded to supplied candidates',()=>{const c=context();expect(Object.keys(deriveScoutingNeeds(c.world,c.organizationId,[]).scoutingAssignmentsById)).toHaveLength(0)})
  it('16 evidence source boundary accepts every approved source',()=>{const c=context();let w=c.world;for(const source of EVIDENCE_SOURCES)w=recordEvidence(w,{id:`e:${source}`,organizationId:c.organizationId,subjectPlayerId:c.player.id,source,observedAt:w.currentDate,quality:.5,dimensions:['shooting']});expect(Object.keys(w.evidenceById)).toHaveLength(9)})
  it('17 knowledge stays sparse until a report exists',()=>{const c=context();expect(c.world.organizationKnowledge).toHaveLength(0)})
  it('18 own-player baseline is not omniscient',()=>{const c=context(),own=c.team.rosterPlayerIds[0]!;expect(getPlayerKnowledgeSummary(c.world,c.organizationId,own).overallCoverage).toBeGreaterThan(getPlayerKnowledgeSummary(c.world,c.organizationId,c.player.id).overallCoverage);expect(getPlayerKnowledgeSummary(c.world,c.organizationId,own).overallCoverage).toBeLessThan(1)})
  it('19 reports retain evidence provenance',()=>{const c=context(),w=complete(requestScouting(c.world,{organizationId:c.organizationId,playerId:c.player.id,missionType:'QUICK_LOOK',evaluatorStaffId:c.scout.staffPersonId}));expect(Object.values(w.evaluatorReportsById)[0]!.evidenceIds).toHaveLength(1)})
  it('20 consumer contracts expose no truth fields',()=>{const c=context(),w=complete(requestScouting(c.world,{organizationId:c.organizationId,playerId:c.player.id,missionType:'QUICK_LOOK',evaluatorStaffId:c.scout.staffPersonId}));expect(JSON.stringify([Object.values(w.evidenceById),Object.values(w.evaluatorReportsById),w.organizationKnowledge,getPlayerKnowledgeSummary(w,c.organizationId,c.player.id)])).not.toMatch(/actualRating|truthValue|canonicalPlayer|actualPotential/)})
})
