import { createNarrativeThread, NARRATIVE_THRESHOLDS, type NarrativeThread } from '@/domain/narrative'
import { addNewsItem, updateGameWorld, type GameWorld } from '@/domain/world'
import type { GameId } from '@/domain/ids'

export function refreshNarratives(world: GameWorld): GameWorld {
  let next = world
  for (const coachId of Object.keys(world.coaches)) {
    const departures = Object.values(world.memoriesById).filter((memory) => memory.owner.id === coachId && (memory.type === 'fired' || memory.type === 'leftClub'))
    for (const departure of departures) { const teamId = departure.entityRefs.find((entity) => entity.kind === 'team')?.id; if (teamId !== undefined) next = upsert(next, `narrative:${departure.type}:${coachId}:${teamId}`, departure.type === 'fired' ? 'revenge' : 'formerClub', [coachId], [teamId], departure.occurredOn, departure.id, departure.type === 'fired' ? 'dismissed' : 'departed') }
    const promotions = Object.values(world.memoriesById).filter((memory) => memory.owner.id === coachId && memory.tags.includes('promotion'))
    if (promotions.length) next = upsert(next, `narrative:promotion:${coachId}`, 'promotionJourney', [coachId], promotions.flatMap((memory) => memory.entityRefs.filter((entity) => entity.kind === 'team').map((entity) => entity.id)).slice(0, 1), promotions[promotions.length - 1]!.occurredOn, promotions.map((memory) => memory.id).join(','), 'promotion', promotions.length * 15)
    const titles = Object.values(world.memoriesById).filter((memory) => memory.owner.id === coachId && memory.type === 'championship')
    if (titles.length >= NARRATIVE_THRESHOLDS.dynastyChampionships) next = upsert(next, `narrative:dynasty:${coachId}`, 'dynasty', [coachId], titles.flatMap((memory) => memory.entityRefs.filter((entity) => entity.kind === 'team').map((entity) => entity.id)).slice(0, 1), titles[titles.length - 1]!.occurredOn, titles.map((memory) => memory.id).join(','), 'championship', titles.length * 20)
  }
  return applyNarrativeDormancy(next)
}
export function processNarrativeMatch(world: GameWorld, gameId: GameId): GameWorld { const game = world.games[gameId]; if (!game?.result) return world; let next = refreshNarratives(world); const pairGames = Object.values(next.games).filter((item) => item.status === 'completed' && item.stakes !== 'regular' && ((item.homeTeamId === game.homeTeamId && item.awayTeamId === game.awayTeamId) || (item.homeTeamId === game.awayTeamId && item.awayTeamId === game.homeTeamId))); if (pairGames.length >= 3 && new Set(pairGames.map((item) => item.seasonId)).size >= 2) next = upsert(next, `narrative:rivalry:${[game.homeTeamId, game.awayTeamId].sort().join(':')}`, 'rivalry', [next.teams[game.homeTeamId]!.coachId ?? game.homeTeamId, next.teams[game.awayTeamId]!.coachId ?? game.awayTeamId], [game.homeTeamId, game.awayTeamId], game.date, pairGames.map((item) => item.id).join(','), 'rivalryMeeting', pairGames.length * 5)
  for (const playerId of [...next.teams[game.homeTeamId]!.rosterPlayerIds, ...next.teams[game.awayTeamId]!.rosterPlayerIds]) for (const memory of Object.values(next.memoriesById).filter((item) => item.owner.id === playerId && item.type === 'opportunity' && item.importance !== 'minor' && item.entityRefs.some((entity) => entity.kind === 'coach'))) { const coachId = memory.entityRefs.find((entity) => entity.kind === 'coach')!.id; const coachTeam = Object.values(next.teams).find((team) => team.coachId === coachId); if (coachTeam !== undefined && !coachTeam.rosterPlayerIds.includes(playerId) && (coachTeam.id === game.homeTeamId || coachTeam.id === game.awayTeamId)) next = upsert(next, `narrative:former-player:${coachId}:${playerId}`, 'formerPlayer', [coachId], [playerId], game.date, memory.id, 'formerPlayerReunion', 20) }
  for (const thread of Object.values(next.narrativesById)) { const coachId = thread.protagonistIds[0]; const coachTeam = Object.values(next.teams).find((team) => team.coachId === coachId); if (coachTeam === undefined) continue; const opponent = coachTeam.id === game.homeTeamId ? game.awayTeamId : coachTeam.id === game.awayTeamId ? game.homeTeamId : undefined; if (opponent === undefined || !thread.relatedEntityIds.includes(opponent)) continue; const won = coachTeam.id === game.homeTeamId ? game.result.homeScore > game.result.awayScore : game.result.awayScore > game.result.homeScore; next = beat(next, thread, game.date, won ? 'wonMeeting' : 'lostMeeting', `match:${gameId}:${thread.id}`, won ? 20 : 10, won && thread.type === 'revenge') }
  return next
}
export function applyNarrativeDormancy(world: GameWorld): GameWorld { const dormant = Object.values(world.narrativesById).map((thread) => { const months = (Number(world.currentDate.slice(0, 4)) - Number(thread.lastOccurredOn.slice(0, 4))) * 12 + Number(world.currentDate.slice(5, 7)) - Number(thread.lastOccurredOn.slice(5, 7)); if (thread.status === 'resolved' && thread.resolvedOn !== undefined && months >= NARRATIVE_THRESHOLDS.dormancyMonths) return createNarrativeThread({ ...thread, status: 'historic' }); return !['resolved', 'historic'].includes(thread.status) && months >= NARRATIVE_THRESHOLDS.dormancyMonths ? createNarrativeThread({ ...thread, status: 'dormant' }) : thread }); return dormant.some((thread, index) => thread !== Object.values(world.narrativesById)[index]) ? updateGameWorld(world, { narratives: dormant }) : world }
function upsert(world: GameWorld, id: string, type: NarrativeThread['type'], protagonists: readonly string[], related: readonly string[], date: import('@/domain/date').GameDate, evidence: string, kind: string, bonus = 0): GameWorld { if (!related.length) return world; const existing = world.narrativesById[id]; if (existing !== undefined) return evidence.split(',').reduce((next, key) => next.narrativesById[id]!.beats.some((beat) => beat.semanticKey === `evidence:${key}`) ? next : beat(next, next.narrativesById[id]!, date, kind, `evidence:${key}`, 8), world); const thread = createNarrativeThread({ id, type, protagonistIds: protagonists, relatedEntityIds: related, startedOn: date, lastOccurredOn: date, status: 'active', intensity: Math.min(100, 55 + bonus), relevance: 60 + bonus, supportingMemoryIds: evidence.split(','), tags: [type, 'memory-derived'], beats: [{ id: `${id}:origin`, semanticKey: `evidence:${evidence.split(',')[0]}`, occurredOn: date, kind, intensity: 55, context: {} }] }); const next = updateGameWorld(world, { narratives: [...Object.values(world.narrativesById), thread] }); return thread.relevance < NARRATIVE_THRESHOLDS.newsRelevance ? next : addNewsItem(next, { id: `news:narrative:${thread.id}:origin`, gameDate: date, category: 'career', headline: `Nueva historia: ${type}`, body: `Una historia relevante ha surgido de acontecimientos reales de la carrera.`, context: { narrativeId: thread.id, type } }) }
function beat(world: GameWorld, thread: NarrativeThread, date: import('@/domain/date').GameDate, kind: string, semanticKey: string, gain: number, resolve = false): GameWorld { if (thread.beats.some((item) => item.semanticKey === semanticKey)) return world; const intensity = Math.min(100, thread.intensity + gain); const updated = createNarrativeThread({ ...thread, lastOccurredOn: date, intensity, relevance: thread.relevance + gain, status: resolve ? 'resolved' : intensity >= 80 ? 'escalating' : 'active', ...(resolve ? { resolvedOn: date } : {}), beats: [...thread.beats, { id: `${thread.id}:beat:${thread.beats.length + 1}`, semanticKey, occurredOn: date, kind, intensity: gain, context: {} }] }); const next = updateGameWorld(world, { narratives: Object.values(world.narrativesById).map((item) => item.id === thread.id ? updated : item) }); return updated.relevance < NARRATIVE_THRESHOLDS.newsRelevance || updated.status === 'active' ? next : addNewsItem(next, { id: `news:narrative:${updated.id}:${semanticKey}`, gameDate: date, category: 'career', headline: `Historia actualizada: ${updated.type}`, body: `Un nuevo acontecimiento ha cambiado una historia relevante.`, context: { narrativeId: updated.id, beat: kind } }) }
