// Copy to public/bdm-icons
export const BDM_ICONS = {
  "home": '/bdm-icons/svg/sidebar__home.svg',
  "roster": '/bdm-icons/svg/apps_large__roster.svg',
  "tactics": '/bdm-icons/svg/apps_large__tactics.svg',
  "calendar": '/bdm-icons/svg/apps_large__calendar.svg',
  "matchCenter": '/bdm-icons/svg/apps_large__match_center.svg',
  "competition": '/bdm-icons/svg/apps_large__competition.svg',
  "market": '/bdm-icons/svg/apps_large__market.svg',
  "training": '/bdm-icons/svg/apps_large__training.svg',
  "staff": '/bdm-icons/svg/apps_large__staff.svg',
  "medical": '/bdm-icons/svg/apps_large__medical.svg',
  "finances": '/bdm-icons/svg/apps_large__finances.svg',
  "club": '/bdm-icons/svg/apps_large__club.svg',
  "press": '/bdm-icons/svg/apps_large__press.svg',
  "board": '/bdm-icons/svg/apps_small__board.svg',
  "compliance": '/bdm-icons/svg/apps_small__compliance.svg',
  "profile": '/bdm-icons/svg/apps_small__profile.svg',
  "wealth": '/bdm-icons/svg/apps_small__wealth.svg',
  "stories": '/bdm-icons/svg/apps_small__stories.svg',
  "memories": '/bdm-icons/svg/apps_small__memories.svg',
  "recruiting": '/bdm-icons/svg/apps_small__recruiting.svg',
  "nil": '/bdm-icons/svg/apps_small__nil.svg',
  "boosters": '/bdm-icons/svg/apps_small__boosters.svg',
  "news": '/bdm-icons/svg/sidebar__news.svg',
  "messages": '/bdm-icons/svg/sidebar__messages.svg',
  "search": '/bdm-icons/svg/sidebar__search.svg',
  "settings": '/bdm-icons/svg/sidebar__settings.svg',
} as const;
