import { getContractYearCompensation, getPlayerContractStatus, type PlayerContract } from '@/domain/contract'
import type { GameDate } from '@/domain/date'
import type { SalaryRules } from '@/domain/salary'

export interface TeamPayroll { readonly activeContractCapHits: number; readonly guaranteedObligations: number; readonly deadMoney: number; readonly retainedSalary: number; readonly totalCapHit: number }
export interface TeamSalaryStatus { readonly payroll: TeamPayroll; readonly capAmount: number; readonly capSpace: number; readonly salaryFloor?: number; readonly belowSalaryFloor: boolean; readonly taxThreshold?: number; readonly taxOverage: number; readonly taxLiability: number; readonly activeApronIds: readonly string[] }
export interface IncomingSalaryLimit { readonly maximumIncomingSalary: number; readonly matchingRule: { readonly maximumPayroll: number | null; readonly incomingMultiplier: number; readonly incomingAllowance: number }; readonly restrictedByApron: boolean }
export type SalaryValidationReason = 'ABOVE_HARD_CAP' | 'INSUFFICIENT_CAP_SPACE' | 'EXCEPTION_REQUIRED' | 'EXCEPTION_INSUFFICIENT' | 'PLAYER_MINIMUM_NOT_MET' | 'PLAYER_MAXIMUM_EXCEEDED' | 'INVALID_CONTRACT_LENGTH' | 'ROOKIE_SCALE_VIOLATION' | 'APRON_RESTRICTION'
export interface SalaryValidationResult { readonly allowed: boolean; readonly reasons: readonly SalaryValidationReason[] }
export interface ProposedSalaryContract { readonly years: readonly { readonly cashSalary: number; readonly capHit: number; readonly guaranteedAmount: number }[]; readonly serviceYears: number; readonly exceptionAmount?: number; readonly transactionKind?: string }

export function calculateTeamPayroll(contracts: readonly PlayerContract[], onDate: GameDate, deadMoney = 0, retainedSalary = 0): TeamPayroll { const active = contracts.filter((contract) => getPlayerContractStatus(contract, onDate) === 'active').map((contract) => getContractYearCompensation(contract, onDate)); const activeContractCapHits = active.reduce((sum, year) => sum + year.capHit, 0); const guaranteedObligations = active.reduce((sum, year) => sum + year.guaranteedAmount, 0); return { activeContractCapHits, guaranteedObligations, deadMoney, retainedSalary, totalCapHit: activeContractCapHits + deadMoney + retainedSalary } }
export function calculateTeamSalaryStatus(rules: SalaryRules, payroll: TeamPayroll): TeamSalaryStatus { const taxOverage = rules.tax === undefined ? 0 : Math.max(0, payroll.totalCapHit - rules.tax.threshold); return { payroll, capAmount: rules.capAmount, capSpace: rules.capAmount - payroll.totalCapHit, ...(rules.salaryFloor === undefined ? {} : { salaryFloor: rules.salaryFloor }), belowSalaryFloor: rules.salaryFloor !== undefined && payroll.totalCapHit < rules.salaryFloor, ...(rules.tax === undefined ? {} : { taxThreshold: rules.tax.threshold }), taxOverage, taxLiability: calculateLuxuryTax(rules, taxOverage), activeApronIds: rules.aprons.filter((apron) => payroll.totalCapHit > apron.amount).map((apron) => apron.id) } }
export function calculateLuxuryTax(rules: SalaryRules, overage: number): number { if (rules.tax === undefined || overage <= 0) return 0; let remaining = overage; let previous = 0; let total = 0; for (const tier of rules.tax.tiers) { const width = tier.upTo === null ? remaining : Math.max(0, tier.upTo - previous); const taxed = Math.min(remaining, width); total += taxed * tier.rate; remaining -= taxed; if (tier.upTo !== null) previous = tier.upTo; if (remaining === 0) break } return Math.round(total) }
export function getIncomingSalaryLimit(rules: SalaryRules, status: TeamSalaryStatus, outgoingSalary: number): IncomingSalaryLimit { if (!Number.isInteger(outgoingSalary) || outgoingSalary < 0) throw new RangeError('Outgoing salary must be a non-negative integer'); const rule = rules.tradeSalaryMatchingRules.find((item) => item.maximumPayroll === null || status.payroll.totalCapHit <= item.maximumPayroll) ?? rules.tradeSalaryMatchingRules[rules.tradeSalaryMatchingRules.length - 1]!; const restrictedByApron = status.activeApronIds.length > 0; return { maximumIncomingSalary: restrictedByApron ? outgoingSalary : Math.floor(outgoingSalary * rule.incomingMultiplier + rule.incomingAllowance), matchingRule: rule, restrictedByApron } }
export function validateContractOffer(rules: SalaryRules, currentPayroll: TeamPayroll, proposed: ProposedSalaryContract): SalaryValidationResult { const reasons: SalaryValidationReason[] = []; const first = proposed.years[0]; if (first === undefined || proposed.years.length < rules.contractLength.minimumYears || proposed.years.length > rules.contractLength.maximumYears) reasons.push('INVALID_CONTRACT_LENGTH'); if (first !== undefined) { const minimum = salaryBand(rules.minimumSalaryBands, proposed.serviceYears)?.amount; const maximum = salaryBand(rules.maximumSalaryBands, proposed.serviceYears)?.capPercentage; if (minimum !== undefined && first.cashSalary < minimum) reasons.push('PLAYER_MINIMUM_NOT_MET'); if (maximum !== undefined && first.cashSalary > Math.floor(rules.capAmount * maximum)) reasons.push('PLAYER_MAXIMUM_EXCEEDED'); const postPayroll = currentPayroll.totalCapHit + first.capHit; if (rules.capModel === 'hard' && postPayroll > rules.capAmount) reasons.push('ABOVE_HARD_CAP'); if (rules.capModel === 'soft' && postPayroll > rules.capAmount) { if (proposed.exceptionAmount === undefined) reasons.push('EXCEPTION_REQUIRED'); else if (proposed.exceptionAmount < first.capHit) reasons.push('EXCEPTION_INSUFFICIENT') } if (rules.aprons.some((apron) => postPayroll > apron.amount && apron.restrictedTransactionKinds.includes(proposed.transactionKind ?? 'sign'))) reasons.push('APRON_RESTRICTION') } return { allowed: reasons.length === 0, reasons: Object.freeze(reasons) } }
function salaryBand<T extends { readonly minServiceYears: number; readonly maxServiceYears: number | null }>(bands: readonly T[], serviceYears: number): T | undefined { return bands.find((band) => serviceYears >= band.minServiceYears && (band.maxServiceYears === null || serviceYears <= band.maxServiceYears)) }
