import { parseGameDate, type GameDate } from '@/domain/date'

export type MemoryOwnerKind = 'coach' | 'player' | 'staff' | 'team'
export type MemoryEntityKind = MemoryOwnerKind | 'competition' | 'game' | 'season' | 'contract'
export type MemoryType = 'hired' | 'fired' | 'leftClub' | 'championship' | 'historicSeason' | 'opportunity' | 'trust' | 'conflict' | 'support' | 'betrayal' | 'contractEvent' | 'majorVictory' | 'majorDefeat'
export type MemoryImportance = 'minor' | 'notable' | 'important' | 'major' | 'historic'
export interface MemoryEntityRef { readonly kind: MemoryEntityKind; readonly id: string }
export interface MemoryRelationshipImpact { readonly targetPersonId: string; readonly delta: number }
export interface MemoryRecord { readonly id: string; readonly owner: MemoryEntityRef; readonly type: MemoryType; readonly occurredOn: GameDate; readonly entityRefs: readonly MemoryEntityRef[]; readonly sourceId?: string; readonly semanticKey: string; readonly importance: MemoryImportance; readonly valence: number; readonly intensity: number; readonly decayPerMonth: number; readonly permanent: boolean; readonly tags: readonly string[]; readonly context: Readonly<Record<string, string | number | boolean>>; readonly relationshipImpact?: MemoryRelationshipImpact; readonly lastDecayedMonth?: string }
export interface MemoryQuery { readonly ownerId?: string; readonly aboutEntityId?: string; readonly teamId?: string; readonly type?: MemoryType; readonly minimumImportance?: MemoryImportance; readonly valence?: 'positive' | 'negative' | 'neutral'; readonly limit?: number }
export interface MemoryRelevance { readonly memory: MemoryRecord; readonly score: number }
const IMPORTANCE_RANK: Readonly<Record<MemoryImportance, number>> = { minor: 1, notable: 2, important: 3, major: 4, historic: 5 }
const MEMORY_TYPES: readonly MemoryType[] = ['hired', 'fired', 'leftClub', 'championship', 'historicSeason', 'opportunity', 'trust', 'conflict', 'support', 'betrayal', 'contractEvent', 'majorVictory', 'majorDefeat']
export function createMemory(input: MemoryRecord): MemoryRecord { if (!input.id.trim() || !input.owner.id.trim() || !input.semanticKey.trim() || !MEMORY_TYPES.includes(input.type) || !Number.isInteger(input.valence) || input.valence < -100 || input.valence > 100 || !Number.isInteger(input.intensity) || input.intensity < 1 || input.intensity > 100 || !Number.isInteger(input.decayPerMonth) || input.decayPerMonth < 0 || input.decayPerMonth > 100 || !Number.isInteger(IMPORTANCE_RANK[input.importance])) throw new RangeError('Invalid memory'); const occurredOn = parseGameDate(input.occurredOn); if (input.relationshipImpact !== undefined && (!input.relationshipImpact.targetPersonId.trim() || !Number.isInteger(input.relationshipImpact.delta) || input.relationshipImpact.delta === 0)) throw new RangeError('Invalid memory relationship impact'); if (new Set(input.entityRefs.map((item) => `${item.kind}:${item.id}`)).size !== input.entityRefs.length || new Set(input.tags).size !== input.tags.length) throw new RangeError('Memory refs and tags must be unique'); return { ...input, occurredOn, entityRefs: input.entityRefs.map((item) => ({ ...item })), tags: [...input.tags], context: { ...input.context }, ...(input.relationshipImpact === undefined ? {} : { relationshipImpact: { ...input.relationshipImpact } }) } }
export function getMemoryImportanceRank(importance: MemoryImportance): number { return IMPORTANCE_RANK[importance] }
export function queryMemories(memories: readonly MemoryRecord[], query: MemoryQuery = {}): readonly MemoryRecord[] { const minimum = query.minimumImportance === undefined ? 0 : IMPORTANCE_RANK[query.minimumImportance]; return memories.filter((memory) => (query.ownerId === undefined || memory.owner.id === query.ownerId) && (query.aboutEntityId === undefined || memory.entityRefs.some((item) => item.id === query.aboutEntityId)) && (query.teamId === undefined || memory.entityRefs.some((item) => item.kind === 'team' && item.id === query.teamId)) && (query.type === undefined || memory.type === query.type) && IMPORTANCE_RANK[memory.importance] >= minimum && (query.valence === undefined || query.valence === 'positive' && memory.valence > 0 || query.valence === 'negative' && memory.valence < 0 || query.valence === 'neutral' && memory.valence === 0)).sort((a, b) => b.intensity - a.intensity || IMPORTANCE_RANK[b.importance] - IMPORTANCE_RANK[a.importance] || b.occurredOn.localeCompare(a.occurredOn) || a.id.localeCompare(b.id)).slice(0, query.limit ?? Number.MAX_SAFE_INTEGER) }
export function getMemoriesBetween(memories: readonly MemoryRecord[], firstId: string, secondId: string): readonly MemoryRecord[] { return queryMemories(memories).filter((memory) => memory.owner.id === firstId && memory.entityRefs.some((item) => item.id === secondId) || memory.owner.id === secondId && memory.entityRefs.some((item) => item.id === firstId)) }
export function getRecentMemories(memories: readonly MemoryRecord[], limit = 10): readonly MemoryRecord[] { return [...memories].sort((a, b) => b.occurredOn.localeCompare(a.occurredOn) || b.intensity - a.intensity || a.id.localeCompare(b.id)).slice(0, limit) }
export function getCurrentlyRelevantMemories(memories: readonly MemoryRecord[], asOf: GameDate, limit = 10): readonly MemoryRelevance[] { return memories.map((memory) => ({ memory, score: relevanceScore(memory, asOf) })).sort((a, b) => b.score - a.score || b.memory.occurredOn.localeCompare(a.memory.occurredOn) || a.memory.id.localeCompare(b.memory.id)).slice(0, limit) }
export function getMemoryReinforcement(memories: readonly MemoryRecord[], ownerId: string, relatedEntityId: string): Readonly<Record<string, readonly MemoryRecord[]>> { const matching = memories.filter((memory) => memory.owner.id === ownerId && memory.entityRefs.some((entity) => entity.id === relatedEntityId)); return Object.fromEntries([...new Set(matching.map((memory) => memory.type))].sort().map((type) => [type, matching.filter((memory) => memory.type === type)])) }
function relevanceScore(memory: MemoryRecord, asOf: GameDate): number { const ageMonths = Math.max(0, (Number(asOf.slice(0, 4)) - Number(memory.occurredOn.slice(0, 4))) * 12 + Number(asOf.slice(5, 7)) - Number(memory.occurredOn.slice(5, 7))); return memory.intensity + IMPORTANCE_RANK[memory.importance] * 12 + (memory.permanent ? 20 : 0) - Math.min(30, ageMonths) }
