import { useState } from 'react'
import MedicalPage from './MedicalSectionPage'
import './MedicalPcbPage.css'

const safeNum = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : 0

export function MedicalPcbPage() {
  const [medicalView, setMedicalView] = useState('overview')
  const myTeam = { name: 'Casademont Zaragoza', data: { tier: 3 } }
  const myRoster = Array.from({ length: 15 }, (_, index) => ({ id: String(index), name: `Jugador ${index + 1}` }))
  const injuryList = [{ player: { id: 'p7', name: 'Álvaro Martín' }, injury: 'Esguince de tobillo', source: 'Entrenamiento', days: 8, status: 'Moderada' }, { player: { id: 'p11', name: 'Marcus Cole' }, injury: 'Sobrecarga muscular', source: 'Partido', days: 3, status: 'Leve' }]
  const injuryHistory = [{ id: 'h1', player: { name: 'Álvaro Martín' }, label: 'Esguince de tobillo', source: 'Entrenamiento', severity: 'moderate', start_date: '2026-09-23', end_date: '2026-10-01' }, { id: 'h2', player: { name: 'Marcus Cole' }, label: 'Sobrecarga muscular', source: 'Partido', severity: 'minor', start_date: '2026-09-28', end_date: '2026-10-01' }]
  const myStaff = [{ role_id: 'doctor', name: 'Dra. Lucía Ortega', role: 'Jefa médica', experience_years: 12 }, { role_id: 'physio', name: 'Mario Ruiz', role: 'Fisioterapeuta', experience_years: 8 }, { role_id: 'nutrition', name: 'Elena Serra', role: 'Nutricionista', experience_years: 6 }]
  const rosterAttrAverages = { fatigue_recov: 70, durability: 70 }
  const loopState = { date: '2026-10-01' }
  const [openPlayerId, setOpenPlayerId] = useState<string | null>(null)
  const toIdList = () => myRoster.map((player) => player.id)
  const openPlayer = (playerId: string) => setOpenPlayerId(playerId)
  const openPlayerEntry = injuryList.find((item) => item.player.id === openPlayerId)

  const renderMedicalOverview = () => (
    <section className="bento">
      <div className="card hero modal-glass-tactical">
        <div className="card-header"><h2>Medical Overview</h2><span className="tag">Salud</span></div>
        <div className="detail-tags"><span className="chip">Club {myTeam.name}</span><span className="chip">Lesionados {injuryList.length}</span><span className="chip">Disponibles {Math.max(0, myRoster.length - injuryList.length)}</span></div>
        <div className="desc">Resumen de estado físico y disponibilidad de la plantilla.</div>
      </div>
      <div className="card metrics attribute-section-refined">
        <div className="card-header"><h2>Indicadores</h2><span className="tag muted">Riesgo</span></div>
        <div className="bars">
          <div className="bar"><div className="label">Fatiga</div><div className="track"><div className="fill" style={{ width: `${100 - (rosterAttrAverages.fatigue_recov || 0)}%` }} /></div><div className="value mono">{100 - (rosterAttrAverages.fatigue_recov || 0)}</div></div>
          <div className="bar"><div className="label">Recuperación</div><div className="track"><div className="fill" style={{ width: `${rosterAttrAverages.fatigue_recov || 0}%` }} /></div><div className="value mono">{rosterAttrAverages.fatigue_recov || 0}</div></div>
          <div className="bar"><div className="label">Prevención</div><div className="track"><div className="fill" style={{ width: `${rosterAttrAverages.durability || 0}%` }} /></div><div className="value mono">{rosterAttrAverages.durability || 0}</div></div>
        </div>
      </div>
    </section>
  )
  const renderMedicalInjuredList = () => <section className="bento"><div className="card roster player-card-elite"><div className="card-header"><h2>Injured List</h2><span className="tag muted">Activos</span></div><div className="desc">Lesiones registradas.</div><div className="table injuries"><div className="row head injuries"><div>Jugador</div><div>Lesión</div><div>Origen</div><div>Días</div><div>Estado</div></div>{injuryList.length === 0 ? <div className="row empty">Sin lesionados activos.</div> : injuryList.map((item) => <div className="row injuries" key={item.player.id}><div><button className="link mono" onClick={() => openPlayer(item.player.id)}>{item.player.name}</button></div><div>{item.injury}</div><div>{item.source}</div><div className="mono">{item.days} d</div><div className={`pill ${item.status === 'Grave' ? 'danger' : item.status === 'Moderada' ? 'warn' : ''}`}>{item.status}</div></div>)}</div>{openPlayerEntry && <aside className="pcb-medical__detail" aria-label="Detalle de jugador lesionado"><header><h3>{openPlayerEntry.player.name}</h3><button onClick={() => setOpenPlayerId(null)} type="button">Cerrar</button></header><dl><div><dt>Lesión</dt><dd>{openPlayerEntry.injury}</dd></div><div><dt>Origen</dt><dd>{openPlayerEntry.source}</dd></div><div><dt>Días de baja</dt><dd>{openPlayerEntry.days}</dd></div><div><dt>Estado</dt><dd>{openPlayerEntry.status}</dd></div><div><dt>Plantilla</dt><dd>{toIdList().length} jugadores</dd></div></dl></aside>}</div></section>
  const renderMedicalHistory = () => <section className="bento"><div className="card roster player-card-elite roster-full"><div className="card-header"><h2>Injury History</h2><span className="tag muted">Temporada</span></div><div className="desc">Histórico de lesiones registradas.</div><div className="table training-table scroll-x"><div className="row head training load"><div>Jugador</div><div>Lesión</div><div>Origen</div><div>Severidad</div><div>Inicio</div><div>Fin</div><div>Estado</div></div>{injuryHistory.length ? injuryHistory.slice(0, 12).map((entry) => { const sevKey = String(entry.severity || '').toLowerCase(); const severity = sevKey === 'severe' ? 'Grave' : sevKey === 'moderate' ? 'Moderada' : sevKey === 'minor' ? 'Leve' : ''; const isRecovered = entry.end_date && loopState?.date ? entry.end_date < loopState.date : false; const status = isRecovered ? 'Recuperado' : 'Activo'; return <div className="row training load" key={entry.id}><div className="mono">{entry.player.name}</div><div>{entry.label}</div><div>{entry.source}</div><div>{severity}</div><div className="mono">{entry.start_date || ''}</div><div className="mono">{entry.end_date || ''}</div><div><span className={`training-badge ${status === 'Activo' ? 'warn' : ''}`}>{status}</span></div></div> }) : <div className="row empty">Sin historial registrado.</div>}</div></div></section>
  const renderMedicalFacilities = () => <section className="bento"><div className="card roster player-card-elite roster-full"><div className="card-header"><h2>Medical Facilities</h2><span className="tag muted">Infraestructura</span></div><div className="list">{(() => { const tier = safeNum(myTeam?.data?.tier || 3); const level = Math.max(1, 4 - tier); const descriptor = level >= 3 ? 'élite' : level === 2 ? 'avanzado' : 'básico'; return <><div className="list-item"><div className="title">Centro de recuperación</div><div className="desc">Nivel {level} · Equipamiento {descriptor} para recuperación post-partido.</div></div><div className="list-item"><div className="title">Gimnasio de fuerza</div><div className="desc">Nivel {level} · Planes personalizados según carga y posición.</div></div><div className="list-item"><div className="title">Biomecánica</div><div className="desc">Nivel {level} · Análisis de movimiento y prevención de lesiones.</div></div></> })()}</div></div></section>
  const renderMedicalStaff = () => <section className="bento"><div className="card roster player-card-elite roster-full"><div className="card-header"><h2>Medical Staff</h2><span className="tag muted">{myStaff.length} miembros</span></div><div className="table training-table scroll-x"><div className="row head training"><div>Staff</div><div>Rol</div><div>Especialidad</div><div>Turno</div><div>Experiencia</div></div>{myStaff.length === 0 ? <div className="row empty">Sin staff médico asignado.</div> : [...myStaff].map((s, idx) => <div className="row training" key={`${s.role_id}-${idx}`}><div className="mono">{s.name}</div><div>{s.role || '--'}</div><div>Médico</div><div>{idx % 3 === 0 ? 'Mañana' : idx % 3 === 1 ? 'Tarde' : 'Mixto'}</div><div className="mono">{s.experience_years || 0}y</div></div>)}</div></div></section>
  const renderPreventionCenter = () => <section className="bento"><div className="card roster player-card-elite roster-full"><div className="card-header"><h2>Prevention Center</h2><span className="tag muted">Protocolos</span></div><div className="list">{(() => { const riskIndex = 100 - (rosterAttrAverages.durability || 0); const intensity = riskIndex >= 60 ? 'Alto' : riskIndex >= 45 ? 'Medio' : 'Bajo'; return <><div className="list-item"><div className="title">Control de cargas</div><div className="desc">Nivel {intensity} · Ajuste según fatiga y recuperación real.</div></div><div className="list-item"><div className="title">Movilidad</div><div className="desc">Protocolos basados en durabilidad media ({rosterAttrAverages.durability || 0}).</div></div><div className="list-item"><div className="title">Sueño y nutrición</div><div className="desc">Rutina personalizada según recuperación ({rosterAttrAverages.fatigue_recov || 0}).</div></div></> })()}</div></div></section>
  return <MedicalPage myTeam={myTeam} medicalView={medicalView} setMedicalView={setMedicalView} renderMedicalOverview={renderMedicalOverview} renderMedicalInjuredList={renderMedicalInjuredList} renderMedicalHistory={renderMedicalHistory} renderMedicalFacilities={renderMedicalFacilities} renderMedicalStaff={renderMedicalStaff} renderPreventionCenter={renderPreventionCenter} />
}
