import { describe, expect, it } from "vitest";
import { createBoardState } from "@/domain/board";
import { aggregateGovernanceObjectiveEvaluations, createGovernanceExpectationPeriod, createGovernanceObjective, evaluateGovernanceObjective } from "./GovernanceExpectations";

const objective = (comparison: "AT_LEAST" | "AT_MOST" | "EXACT_OR_TOLERANCE" = "AT_LEAST") => createGovernanceObjective({ id: comparison, expectationPeriodId: "period", ownerInstitutionId: "institution", family: "PLAYER_DEVELOPMENT", horizon: "SHORT", metric: "PLAYER_DEVELOPMENT_SCORE", comparison, target: { kind: "NUMERIC", value: 50 }, tolerance: 5, partialTolerance: 10, importance: comparison === "AT_LEAST" ? 80 : 20, evaluationStartsOn: "2032-01-01" as never, evaluationEndsOn: "2032-01-31" as never });
const assess = (value: number | undefined, date = "2032-02-01") => evaluateGovernanceObjective(objective(), value === undefined ? undefined : { metric: "PLAYER_DEVELOPMENT_SCORE", value }, date as never);

describe("Governance expectations", () => {
  it("evaluates AT_LEAST statuses deterministically", () => { expect(assess(40, "2031-12-31").status).toBe("NOT_STARTED"); expect(assess(undefined).status).toBe("NOT_EVALUABLE"); expect(assess(40, "2032-01-15").status).toBe("IN_PROGRESS"); expect(assess(50).status).toBe("MET"); expect(assess(56).status).toBe("EXCEEDED"); expect(assess(42).status).toBe("PARTIALLY_MET"); expect(assess(30).status).toBe("MISSED"); });
  it("supports AT_MOST and exact tolerance without unreachable states", () => { const atMost=objective("AT_MOST"); expect(evaluateGovernanceObjective(atMost,{metric:atMost.metric,value:44},"2032-02-01" as never).status).toBe("EXCEEDED"); const exact=objective("EXACT_OR_TOLERANCE"); expect(evaluateGovernanceObjective(exact,{metric:exact.metric,value:58},"2032-02-01" as never).status).toBe("PARTIALLY_MET"); });
  it("evaluates ranges and booleans without coercing their target semantics", () => { const range=createGovernanceObjective({ ...objective(), id:"range", family:"ROSTER_CONSTRUCTION", metric:"ROSTER_AGE_PROFILE", comparison:"BETWEEN", target:{kind:"RANGE",minimum:24,maximum:28} }); expect(evaluateGovernanceObjective(range,{metric:range.metric,value:26},"2032-02-01" as never).status).toBe("MET"); expect(evaluateGovernanceObjective(range,{metric:range.metric,value:50},"2032-02-01" as never).status).toBe("MISSED"); const bool=createGovernanceObjective({ ...objective(), id:"bool", family:"SPORTING_RESULTS", metric:"PLAYOFF_QUALIFICATION", comparison:"BOOLEAN_SUCCESS", target:{kind:"BOOLEAN",value:true}, tolerance:0 }); expect(evaluateGovernanceObjective(bool,{metric:bool.metric,value:true},"2032-02-01" as never).status).toBe("MET"); expect(evaluateGovernanceObjective(bool,{metric:bool.metric,value:false},"2032-02-01" as never).status).toBe("MISSED"); });
  it("rejects incompatible targets and normalizes evaluable objectives", () => { expect(() => createGovernanceObjective({ ...objective(), comparison:"BOOLEAN_SUCCESS", target:{kind:"NUMERIC",value:1} })).toThrow(); const aggregate=aggregateGovernanceObjectiveEvaluations([objective()],[assess(50)]); expect(aggregate.expectationAttainment).toBe(1); expect(aggregate.objectiveWeights.AT_LEAST).toBe(1); });
  it("keeps universe expectation fixtures distinct and leaves NCAA NIL unevaluable without a provider", () => { const club=fixture("PROFESSIONAL_CLUB",[["SPORTING_RESULTS","LEAGUE_FINISH_POSITION"],["SPORTING_RESULTS","CUP_ROUND_REACHED"],["FINANCIAL_DISCIPLINE","BUDGET_VARIANCE"],["YOUTH_ACADEMY_USAGE","ACADEMY_PLAYER_MINUTES_SHARE"],["STYLE_IDENTITY","STYLE_IDENTITY_ADHERENCE"]]); const nba=fixture("NBA_WNBA",[["SPORTING_RESULTS","PLAYOFF_QUALIFICATION"],["PAYROLL_DISCIPLINE","PAYROLL_TO_BUDGET_RATIO"],["ROSTER_CONSTRUCTION","ROSTER_AGE_PROFILE"],["PLAYER_DEVELOPMENT","PLAYER_DEVELOPMENT_SCORE"],["ROSTER_CONSTRUCTION","ROSTER_CONTINUITY"]]); const ncaa=fixture("NCAA",[["COMPETITION_PERFORMANCE","CONFERENCE_FINISH_POSITION"],["COMPETITION_PERFORMANCE","TOURNAMENT_QUALIFICATION"],["RECRUITING","RECRUITING_CLASS_STRENGTH"],["RECRUITING","RECRUIT_RETENTION"],["PLAYER_DEVELOPMENT","PLAYER_DEVELOPMENT_SCORE"],["COMPLIANCE_ACADEMIC","ACADEMIC_STANDARD"],["COMPLIANCE_ACADEMIC","COMPLIANCE_STANDARD"],["NIL_STRATEGY","NIL_STRATEGY_EXECUTION"],["INSTITUTIONAL_PRESTIGE","PRESTIGE_CHANGE"]]); const federation=fixture("FEDERATION",[["COMPETITION_PERFORMANCE","QUALIFICATION_SUCCESS"],["COMPETITION_PERFORMANCE","TOURNAMENT_ROUND_REACHED"],["NATIONAL_TEAM_DEVELOPMENT","PLAYER_POOL_DEVELOPMENT"],["NATIONAL_TEAM_DEVELOPMENT","YOUTH_PATHWAY_USAGE"],["NATIONAL_TEAM_DEVELOPMENT","NATIONAL_TEAM_RANKING"]]); expect([club,nba,ncaa,federation].map(x=>x.length)).toEqual([5,5,9,5]); const nil=ncaa.find(x=>x.metric==="NIL_STRATEGY_EXECUTION")!; expect(evaluateGovernanceObjective(nil,undefined,"2032-02-01" as never).status).toBe("NOT_EVALUABLE"); });
  it("allows formal bodies to disagree without selecting a winner", () => { const board=createGovernanceObjective({...objective(),id:"board-win",ownerBodyId:"body:board",ownerInstitutionId:undefined,family:"SPORTING_RESULTS",metric:"WIN_PERCENTAGE",horizon:"SHORT",importance:90,target:{kind:"NUMERIC",value:60}}); const executive=createGovernanceObjective({...objective(),id:"executive-development",ownerBodyId:"body:executive",ownerInstitutionId:undefined,horizon:"LONG",importance:70,target:{kind:"NUMERIC",value:70}}); expect([board,executive].map(x=>x.ownerBodyId)).toEqual(["body:board","body:executive"]); expect(evaluateGovernanceObjective(board,{metric:board.metric,value:60},"2032-02-01" as never).status).toBe("MET"); expect(evaluateGovernanceObjective(executive,{metric:executive.metric,value:50},"2032-02-01" as never).status).toBe("MISSED"); });
  it("keeps rebuild and contend expectation periods immutable and additive", () => { const rebuild=createGovernanceExpectationPeriod({id:"rebuild",institutionId:"institution",universe:"NBA_WNBA",startedOn:"2032-01-01" as never,endedOn:"2033-12-31" as never}); const rebuildObjectives=fixture("rebuild",[["PLAYER_DEVELOPMENT","YOUNG_PLAYER_MINUTES_SHARE"],["ROSTER_CONSTRUCTION","ROSTER_AGE_PROFILE"],["PAYROLL_DISCIPLINE","PAYROLL_TO_BUDGET_RATIO"]]).map(x=>createGovernanceObjective({...x,expectationPeriodId:rebuild.id,ownerInstitutionId:rebuild.institutionId})); const before=structuredClone(rebuildObjectives); const contend=createGovernanceExpectationPeriod({id:"contend",institutionId:"institution",universe:"NBA_WNBA",startedOn:"2034-01-01" as never}); const contendObjectives=fixture("contend",[["SPORTING_RESULTS","PLAYOFF_QUALIFICATION"],["SPORTING_RESULTS","PLAYOFF_ROUND_REACHED"],["ROSTER_CONSTRUCTION","ROSTER_CONTINUITY"]]).map(x=>createGovernanceObjective({...x,expectationPeriodId:contend.id,ownerInstitutionId:contend.institutionId})); expect(rebuild.endedOn! < contend.startedOn).toBe(true); expect(rebuildObjectives).toEqual(before); expect(rebuildObjectives.every(x=>x.expectationPeriodId===rebuild.id)).toBe(true); expect(contendObjectives.every(x=>x.expectationPeriodId===contend.id)).toBe(true); });
  it("keeps BG2 evaluation isolated from legacy BoardState confidence", () => { const objectiveState=objective(); const input={metric:objectiveState.metric,value:50}; const low=legacyBoard(1); const high=legacyBoard(99); const lowBefore=structuredClone(low); const highBefore=structuredClone(high); const lowEvaluation=evaluateGovernanceObjective(objectiveState,input,"2032-02-01" as never); const highEvaluation=evaluateGovernanceObjective(objectiveState,input,"2032-02-01" as never); expect(lowEvaluation).toEqual(highEvaluation); expect(aggregateGovernanceObjectiveEvaluations([objectiveState],[lowEvaluation])).toEqual(aggregateGovernanceObjectiveEvaluations([objectiveState],[highEvaluation])); expect(low).toEqual(lowBefore); expect(high).toEqual(highBefore); });
});

function fixture(universe:string, entries: readonly [any,any][]) { return entries.map(([family,metric],index)=>createGovernanceObjective({ id:`${universe}:${metric}`,expectationPeriodId:`period:${universe}`,ownerInstitutionId:`institution:${universe}`,family,metric,comparison:metric.includes("QUALIFICATION")?"BOOLEAN_SUCCESS":"AT_LEAST",target:metric.includes("QUALIFICATION")?{kind:"BOOLEAN",value:true}:{kind:"NUMERIC",value:50},horizon:index%2===0?"SHORT":"LONG",tolerance:5,partialTolerance:10,importance:90-index,evaluationStartsOn:"2032-01-01" as never,evaluationEndsOn:"2032-12-31" as never})); }
function legacyBoard(confidence:number) { return createBoardState({ teamId:"team" as never, coachId:"coach" as never, startedOn:"2032-01-01" as never, profile:{ambition:60,patience:60,stability:60,resultsFocus:60,developmentFocus:60,prestigeFocus:60}, expectation:{summary:"Legacy",baselinePosition:4,seasonId:"season" as never}, objectives:[], confidence, reasons:[], processedEventKeys:[] }); }
