import type { GameDate } from '@/domain/date'
import type { GovernanceMeetingAgendaItem, GovernanceInteractionParty } from './GovernanceMeeting'
import { type GovernanceRequest, type GovernanceRequestEvent, deriveGovernanceRequestStatus, isGovernanceRequestOverdue, sameGovernanceInteractionParty } from './GovernanceRequest'
import { type GovernanceCommitment, type GovernanceCommitmentEvent, deriveGovernanceCommitmentStatus, hasGovernanceCommitmentBreach, isGovernanceCommitmentFulfilledLate, isGovernanceCommitmentOverdue } from './GovernanceCommitment'

export type GovernanceInteractionDerivationInput = { readonly institutionId: string; readonly asOfDate: GameDate; readonly requests: readonly GovernanceRequest[]; readonly requestEvents: readonly GovernanceRequestEvent[]; readonly commitments: readonly GovernanceCommitment[]; readonly commitmentEvents: readonly GovernanceCommitmentEvent[] }
type RequestEventSignal = { readonly requestId: string; readonly institutionId: string; readonly issuer: GovernanceInteractionParty; readonly recipient: GovernanceInteractionParty; readonly effectiveOn: GameDate; readonly sourceEventId: string; readonly evidence?: Extract<GovernanceRequestEvent, { kind: 'FULFILLED' }>['evidence'] }
type CommitmentEventSignal = { readonly commitmentId: string; readonly institutionId: string; readonly promisor: GovernanceInteractionParty; readonly beneficiary: GovernanceInteractionParty; readonly effectiveOn: GameDate; readonly sourceEventId: string }
export type GovernanceInteractionSignal = ({ readonly kind: 'REQUEST_DECLINED' | 'REQUEST_WITHDRAWN' | 'REQUEST_FULFILLED' } & RequestEventSignal) | { readonly kind: 'REQUEST_OVERDUE'; readonly requestId: string; readonly institutionId: string; readonly issuer: GovernanceInteractionParty; readonly recipient: GovernanceInteractionParty; readonly dueOn: GameDate } | ({ readonly kind: 'COMMITMENT_BREACHED' | 'COMMITMENT_WITHDRAWN' } & CommitmentEventSignal) | ({ readonly kind: 'COMMITMENT_SUPERSEDED' } & CommitmentEventSignal & { readonly successorCommitmentId: string }) | ({ readonly kind: 'COMMITMENT_FULFILLED' } & CommitmentEventSignal & { readonly fulfilledLate: boolean; readonly hadPriorBreach: boolean }) | { readonly kind: 'COMMITMENT_OVERDUE'; readonly commitmentId: string; readonly institutionId: string; readonly promisor: GovernanceInteractionParty; readonly beneficiary: GovernanceInteractionParty; readonly dueOn: GameDate }
export type GovernanceFollowUpItem = { readonly kind: 'REQUEST'; readonly requestId: string; readonly institutionId: string; readonly issuer: GovernanceInteractionParty; readonly recipient: GovernanceInteractionParty; readonly status: 'ISSUED' | 'ACKNOWLEDGED' | 'ACCEPTED'; readonly dueOn?: GameDate; readonly overdue: boolean } | { readonly kind: 'COMMITMENT'; readonly commitmentId: string; readonly institutionId: string; readonly promisor: GovernanceInteractionParty; readonly beneficiary: GovernanceInteractionParty; readonly status: 'MADE' | 'BREACHED'; readonly dueOn?: GameDate; readonly overdue: boolean; readonly breachRecorded: boolean }
const byId = <T extends { readonly id: string }>(items: readonly T[]) => [...items].sort((a, b) => a.id.localeCompare(b.id))
const visible = <T extends { readonly id: string; readonly effectiveOn: GameDate }>(items: readonly T[], asOfDate: GameDate) => items.filter((item) => item.effectiveOn <= asOfDate).sort((a, b) => a.effectiveOn.localeCompare(b.effectiveOn) || a.id.localeCompare(b.id))
const signalDate = (signal: GovernanceInteractionSignal) => 'effectiveOn' in signal ? signal.effectiveOn : signal.dueOn
const signalId = (signal: GovernanceInteractionSignal) => 'requestId' in signal ? signal.requestId : signal.commitmentId
export function deriveGovernanceInteractionSignals(input: GovernanceInteractionDerivationInput): readonly GovernanceInteractionSignal[] {
  const signals: GovernanceInteractionSignal[] = []
  for (const request of byId(input.requests).filter((item) => item.institutionId === input.institutionId)) { const events = visible(input.requestEvents.filter((event) => event.requestId === request.id), input.asOfDate); for (const event of events) { if (event.kind === 'DECLINED' || event.kind === 'WITHDRAWN' || event.kind === 'FULFILLED') signals.push({ kind: `REQUEST_${event.kind}` as 'REQUEST_DECLINED' | 'REQUEST_WITHDRAWN' | 'REQUEST_FULFILLED', requestId: request.id, institutionId: request.institutionId, issuer: request.issuer, recipient: request.recipient, effectiveOn: event.effectiveOn, sourceEventId: event.id, ...(event.kind === 'FULFILLED' && event.evidence !== undefined ? { evidence: event.evidence } : {}) }) }; if (request.dueOn !== undefined && isGovernanceRequestOverdue(request, events, input.asOfDate)) signals.push({ kind: 'REQUEST_OVERDUE', requestId: request.id, institutionId: request.institutionId, issuer: request.issuer, recipient: request.recipient, dueOn: request.dueOn }) }
  for (const commitment of byId(input.commitments).filter((item) => item.institutionId === input.institutionId)) { const events = visible(input.commitmentEvents.filter((event) => event.commitmentId === commitment.id), input.asOfDate); for (const event of events) { const base = { commitmentId: commitment.id, institutionId: commitment.institutionId, promisor: commitment.promisor, beneficiary: commitment.beneficiary, effectiveOn: event.effectiveOn, sourceEventId: event.id }; if (event.kind === 'BREACHED') signals.push({ kind: 'COMMITMENT_BREACHED', ...base }); if (event.kind === 'WITHDRAWN') signals.push({ kind: 'COMMITMENT_WITHDRAWN', ...base }); if (event.kind === 'SUPERSEDED') signals.push({ kind: 'COMMITMENT_SUPERSEDED', ...base, successorCommitmentId: event.successorCommitmentId }); if (event.kind === 'FULFILLED') signals.push({ kind: 'COMMITMENT_FULFILLED', ...base, fulfilledLate: isGovernanceCommitmentFulfilledLate(commitment, events), hadPriorBreach: hasGovernanceCommitmentBreach(events.filter((item) => item.effectiveOn <= event.effectiveOn)) }) }; if (commitment.dueOn !== undefined && isGovernanceCommitmentOverdue(commitment, events, input.asOfDate)) signals.push({ kind: 'COMMITMENT_OVERDUE', commitmentId: commitment.id, institutionId: commitment.institutionId, promisor: commitment.promisor, beneficiary: commitment.beneficiary, dueOn: commitment.dueOn }) }
  return signals.sort((a, b) => signalDate(a).localeCompare(signalDate(b)) || a.kind.localeCompare(b.kind) || signalId(a).localeCompare(signalId(b)) || ('sourceEventId' in a ? a.sourceEventId.localeCompare('sourceEventId' in b ? b.sourceEventId : '') : 0))
}
export function deriveGovernanceFollowUpItems(input: GovernanceInteractionDerivationInput): readonly GovernanceFollowUpItem[] { const result: GovernanceFollowUpItem[] = []; for (const request of byId(input.requests).filter((item) => item.institutionId === input.institutionId)) { const events = visible(input.requestEvents.filter((event) => event.requestId === request.id), input.asOfDate), status = deriveGovernanceRequestStatus(events); if (status === 'ISSUED' || status === 'ACKNOWLEDGED' || status === 'ACCEPTED') result.push({ kind: 'REQUEST', requestId: request.id, institutionId: request.institutionId, issuer: request.issuer, recipient: request.recipient, status, ...(request.dueOn === undefined ? {} : { dueOn: request.dueOn }), overdue: isGovernanceRequestOverdue(request, events, input.asOfDate) }) }; for (const commitment of byId(input.commitments).filter((item) => item.institutionId === input.institutionId)) { const events = visible(input.commitmentEvents.filter((event) => event.commitmentId === commitment.id), input.asOfDate), status = deriveGovernanceCommitmentStatus(events); if (status === 'MADE' || status === 'BREACHED') result.push({ kind: 'COMMITMENT', commitmentId: commitment.id, institutionId: commitment.institutionId, promisor: commitment.promisor, beneficiary: commitment.beneficiary, status, ...(commitment.dueOn === undefined ? {} : { dueOn: commitment.dueOn }), overdue: isGovernanceCommitmentOverdue(commitment, events, input.asOfDate), breachRecorded: hasGovernanceCommitmentBreach(events) }) }; return result.sort((a, b) => (a.dueOn ?? '9999-12-31').localeCompare(b.dueOn ?? '9999-12-31') || a.kind.localeCompare(b.kind) || (a.kind === 'REQUEST' ? a.requestId : a.commitmentId).localeCompare(b.kind === 'REQUEST' ? b.requestId : b.commitmentId)) }
export const selectGovernanceInteractionSignalsForParty = (signals: readonly GovernanceInteractionSignal[], party: GovernanceInteractionParty) => signals.filter((signal) => 'issuer' in signal ? sameGovernanceInteractionParty(signal.issuer, party) || sameGovernanceInteractionParty(signal.recipient, party) : sameGovernanceInteractionParty(signal.promisor, party) || sameGovernanceInteractionParty(signal.beneficiary, party))
export const selectGovernanceRequestsOriginatingFromMeeting = (requests: readonly GovernanceRequest[], meetingId: string) => byId(requests.filter((request) => request.origin.kind === 'MEETING' && request.origin.meetingId === meetingId))
export const selectGovernanceCommitmentsForRequest = (commitments: readonly GovernanceCommitment[], requestId: string) => byId(commitments.filter((commitment) => commitment.provenance.kind === 'REQUEST' && commitment.provenance.requestId === requestId))
export const selectGovernanceCommitmentsForDecision = (commitments: readonly GovernanceCommitment[], decisionId: string) => byId(commitments.filter((commitment) => commitment.provenance.kind === 'GOVERNANCE_DECISION' && commitment.provenance.decisionId === decisionId))
export const selectGovernanceCommitmentsOriginatingFromMeeting = (commitments: readonly GovernanceCommitment[], meetingId: string) => byId(commitments.filter((commitment) => commitment.provenance.kind === 'MEETING' && commitment.provenance.meetingId === meetingId))
export const selectGovernanceAgendaItemsReferencingRequest = (items: readonly GovernanceMeetingAgendaItem[], requestId: string) => [...items.filter((item) => item.subject.kind === 'GOVERNANCE_REQUEST' && item.subject.requestId === requestId)].sort((a, b) => a.sequence - b.sequence || a.id.localeCompare(b.id))
export const selectGovernanceAgendaItemsReferencingCommitment = (items: readonly GovernanceMeetingAgendaItem[], commitmentId: string) => [...items.filter((item) => item.subject.kind === 'GOVERNANCE_COMMITMENT' && item.subject.commitmentId === commitmentId)].sort((a, b) => a.sequence - b.sequence || a.id.localeCompare(b.id))
