import { describe, expect, it } from 'vitest'
import { applyGovernanceStructureInstantiation, planGovernanceStructureInstantiation } from './GovernanceStructureInstantiation'
import { createGovernanceUniverseProfile } from './GovernanceUniverseProfile'
const p=(kind:any,ownershipModel:any)=>createGovernanceUniverseProfile({id:`${kind}:${ownershipModel}`,institutionId:'shared',kind,ownershipModel,expectedBodyKinds:['BOARD','EXECUTIVE'],externalOversight:false})
const ids={OWNERSHIP:'owner',BOARD:'board',EXECUTIVE:'executive',ATHLETIC_DEPARTMENT:'athletics',COMPLIANCE:'compliance'}
describe('Governance structure instantiation coverage',()=>{
 it.each([['PROFESSIONAL_CLUB','PRIVATE'],['PROFESSIONAL_CLUB','MEMBER_OWNED'],['PROFESSIONAL_CLUB','MULTISPORT_SECTION'],['NBA_FRANCHISE','OWNERSHIP_GROUP'],['WNBA_FRANCHISE','PRIVATE'],['NCAA_PROGRAM','UNIVERSITY'],['NCAAW_PROGRAM','UNIVERSITY'],['FEDERATION','FEDERATION']] as const)('plans %s/%s deterministically',(kind,ownership)=>{const profile=p(kind,ownership);expect(planGovernanceStructureInstantiation(profile,[],ids)).toEqual(planGovernanceStructureInstantiation(profile,[],ids))})
 it('omits optional slots by default and creates one only when selected',()=>{const profile=p('NCAA_PROGRAM','UNIVERSITY');const base=planGovernanceStructureInstantiation(profile,[],ids);expect(base.bodiesToCreate.some(b=>b.kind==='COMPLIANCE')).toBe(false);expect(planGovernanceStructureInstantiation(profile,[],ids,['COMPLIANCE']).bodiesToCreate.some(b=>b.kind==='COMPLIANCE')).toBe(true)})
 it('reports missing and duplicate IDs deterministically without partial application',()=>{const profile=p('PROFESSIONAL_CLUB','PRIVATE'),existing=[{id:'taken',institutionId:'other',kind:'BOARD' as const,name:'Other'}],plan=planGovernanceStructureInstantiation(profile,existing,{...ids,OWNERSHIP:'taken'});expect(plan.conflicts).toEqual(['DUPLICATE_ID:taken']);expect(applyGovernanceStructureInstantiation(existing,plan)).toBe(existing);expect(planGovernanceStructureInstantiation(profile,[],{}).conflicts).toEqual(['MISSING_ID:BOARD','MISSING_ID:EXECUTIVE','MISSING_ID:OWNERSHIP'])})
 it('allows shared parent contexts without cloning parent bodies or fabricating actors',()=>{const profile=p('WNBA_FRANCHISE','PRIVATE'),parent=[{id:'shared-owner',institutionId:'parent',kind:'OWNERSHIP' as const,name:'Shared'}],plan=planGovernanceStructureInstantiation(profile,parent,ids);expect(plan.bodiesToCreate.every(b=>b.institutionId==='shared')).toBe(true);expect(plan).not.toHaveProperty('appointments');expect(plan).not.toHaveProperty('authorityGrants')})
})
