import { describe, expect, it } from 'vitest'
import { createGovernanceManagerEvaluation, deriveGovernanceJobSecurityState, governanceManagerEvaluationScore, type GovernanceManagerEvaluationFactor } from './GovernanceManagerEvaluation'

const source={kind:'GOVERNANCE_BODY',bodyId:'body'} as const
const f=(id:string,value:number,direction:GovernanceManagerEvaluationFactor['direction']='POSITIVE',kind:GovernanceManagerEvaluationFactor['kind']='OBJECTIVE_ATTAINMENT',critical?:true):GovernanceManagerEvaluationFactor=>({id,kind,status:'PRESENT',weight:1,direction,normalizedValue:value,source,...(critical?{critical}: {})})
const e=(id:string,body:string,factors:readonly GovernanceManagerEvaluationFactor[])=>createGovernanceManagerEvaluation({id,evaluationPeriodId:'period',evaluatorBodyId:body,evaluatedOn:'2032-12-31' as never,objectiveEvaluations:[],factors})

describe('BG3 universe fixtures',()=>{
  it('keeps Professional Club Board pressure separate from Executive development support',()=>{const board=e('club-board','board',[f('league-form',.4),f('finance',.5),f('trend',.3,'POSITIVE','RECENT_TREND')]);const executive=e('club-executive','executive',[f('league-form',.4),f('academy',.9,'POSITIVE','LONG_HORIZON_PROGRESS'),f('identity',.8),f('patience',.9,'POSITIVE','INSTITUTIONAL_PATIENCE')]);expect(deriveGovernanceJobSecurityState(board)).toBe('PRESSURED');expect(deriveGovernanceJobSecurityState(executive)).toBe('STABLE')})
  it('distinguishes NBA rebuild protection from win-now failure',()=>{const rebuild=e('nba-rebuild','board',[f('current-results',.25),f('player-development',.9,'POSITIVE','LONG_HORIZON_PROGRESS'),f('roster-construction',.8),f('patience',.9,'POSITIVE','INSTITUTIONAL_PATIENCE'),f('trend',.5,'POSITIVE','RECENT_TREND')]);const contend=e('nba-contend','board',[f('playoff-failure',.1),f('payroll-tax',.2),f('declining',.1,'POSITIVE','RECENT_TREND'),f('patience',.1,'POSITIVE','INSTITUTIONAL_PATIENCE'),f('long',.1,'POSITIVE','LONG_HORIZON_PROGRESS')]);expect(deriveGovernanceJobSecurityState(rebuild)).toBe('STABLE');expect(deriveGovernanceJobSecurityState(contend)).toBe('CRITICAL')})
  it('uses NCAA recruiting/development context and lets a critical compliance incident override it',()=>{const building=e('ncaa-building','athletic-director',[f('conference',.5),f('recruiting',.9),f('development',.9,'POSITIVE','LONG_HORIZON_PROGRESS'),f('academic',.8),f('nil-missing',.5,'NEUTRAL','CONTRACT_CONTEXT'),f('patience',.9,'POSITIVE','INSTITUTIONAL_PATIENCE')]);const incident=e('ncaa-incident','athletic-director',[f('sporting',.95),f('recruiting',.95),f('compliance',.9,'NEGATIVE','COMPLIANCE_INCIDENT',true)]);expect(deriveGovernanceJobSecurityState(building)).toBe('STABLE');expect(governanceManagerEvaluationScore(incident)).toBeGreaterThan(.5);expect(deriveGovernanceJobSecurityState(incident)).toBe('CRITICAL')})
  it('uses Federation cycle progress to protect minor form but escalates qualification failure',()=>{const protectedCycle=e('federation-cycle','federation',[f('friendly-form',.25),f('qualification',.9,'POSITIVE','LONG_HORIZON_PROGRESS'),f('player-pool',.9),f('youth-pathway',.9),f('cycle-patience',.9,'POSITIVE','INSTITUTIONAL_PATIENCE'),f('trend',.5,'POSITIVE','RECENT_TREND')]);const failedCycle=e('federation-failure','federation',[f('qualification-failure',.05),f('tournament',.1),f('declining',.1,'POSITIVE','RECENT_TREND'),f('cycle-patience',.1,'POSITIVE','INSTITUTIONAL_PATIENCE'),f('pathway',.2,'POSITIVE','LONG_HORIZON_PROGRESS')]);expect(deriveGovernanceJobSecurityState(protectedCycle)).toBe('STABLE');expect(deriveGovernanceJobSecurityState(failedCycle)).toBe('TERMINATION_RECOMMENDED')})
  it('records a deterministic history without overwriting prior evaluations and holds minor recovery',()=>{const one=e('history-1','board',[f('one',.7)]),two=e('history-2','board',[f('two',.55)]),three=e('history-3','board',[f('three',.4)]),minor=e('history-4','board',[f('minor',.5)]),recovery=e('history-5','board',[f('recovery',.85)]);expect([deriveGovernanceJobSecurityState(one),deriveGovernanceJobSecurityState(two,'STABLE'),deriveGovernanceJobSecurityState(three,'UNDER_REVIEW'),deriveGovernanceJobSecurityState(minor,'PRESSURED'),deriveGovernanceJobSecurityState(recovery,'PRESSURED')]).toEqual(['STABLE','UNDER_REVIEW','PRESSURED','PRESSURED','SECURE']);expect(one.factors[0]!.normalizedValue).toBe(.7)})
  it('represents political, tenure, and contract evidence without duplicating their systems',()=>{const supported=e('staff-evidence','board',[f('results',.5),f('support',.9,'POSITIVE','POLITICAL_SUPPORT'),f('opposition',.1,'NEGATIVE','POLITICAL_OPPOSITION'),f('new-appointment',.8,'POSITIVE','TENURE_CONTEXT'),f('contract',.5,'NEUTRAL','CONTRACT_CONTEXT')]);expect(deriveGovernanceJobSecurityState(supported)).toBe('STABLE')})
})
