import { describe, expect, it } from "vitest";
import { createGovernanceManagerEvaluation, createGovernanceManagerEvaluationPeriod, createGovernanceObjective, deriveGovernanceJobSecurityState, evaluateGovernanceManager, governanceCriticalNegativeFactors, governanceManagerEvaluationScore, governanceManagerEvaluationStatus, type GovernanceManagerEvaluationFactor } from "./index";
import { evaluateGovernanceObjective } from "./GovernanceExpectations";

const source = { kind: "GOVERNANCE_BODY", bodyId: "body" } as const;
const factor = (id: string, normalizedValue: number | undefined, direction: GovernanceManagerEvaluationFactor["direction"] = "POSITIVE", kind: GovernanceManagerEvaluationFactor["kind"] = "OBJECTIVE_ATTAINMENT", critical?: true): GovernanceManagerEvaluationFactor => normalizedValue === undefined ? { id, kind, status: "MISSING", weight: 1, direction, source } : { id, kind, status: "PRESENT", weight: 1, direction, normalizedValue, source, ...(critical ? { critical } : {}) };
const evaluation = (factors: readonly GovernanceManagerEvaluationFactor[]) => createGovernanceManagerEvaluation({ id: "evaluation", evaluationPeriodId: "period", evaluatorBodyId: "body", evaluatedOn: "2032-12-31" as never, objectiveEvaluations: [], factors });
const objective = createGovernanceObjective({ id: "objective", expectationPeriodId: "expectation", ownerInstitutionId: "institution", family: "SPORTING_RESULTS", horizon: "SHORT", metric: "WIN_PERCENTAGE", comparison: "AT_LEAST", target: { kind: "NUMERIC", value: 60 }, tolerance: 0, importance: 100, evaluationStartsOn: "2032-01-01" as never, evaluationEndsOn: "2032-12-31" as never });

describe("Governance manager evaluation", () => {
  it("uses only PRESENT factors, direction, weights, and canonical ordering", () => {
    const first = evaluation([factor("positive", 1), factor("negative", .2, "NEGATIVE"), factor("missing", undefined)]);
    const reversed = evaluation([...first.factors].reverse());
    expect(governanceManagerEvaluationScore(first)).toBe(.9); expect(governanceManagerEvaluationScore(reversed)).toBe(.9); expect(governanceManagerEvaluationStatus(first)).toBe("EVALUABLE");
  });
  it("does not invent a neutral score without evidence", () => { const empty = evaluation([factor("missing", undefined)]); expect(governanceManagerEvaluationStatus(empty)).toBe("NOT_EVALUABLE"); expect(governanceManagerEvaluationScore(empty)).toBeUndefined(); expect(deriveGovernanceJobSecurityState(empty)).toBeUndefined(); });
  it("applies critical evidence independently of strong score evidence", () => { const strong = evaluation([factor("performance", .95), factor("incident", .9, "NEGATIVE", "COMPLIANCE_INCIDENT", true)]); expect(governanceCriticalNegativeFactors(strong).map((item) => item.id)).toEqual(["incident"]); expect(deriveGovernanceJobSecurityState(strong)).toBe("CRITICAL"); });
  it("protects a patient rebuild from a weak short-term result", () => { const rebuild = evaluation([factor("short", .3), factor("long", .9, "POSITIVE", "LONG_HORIZON_PROGRESS"), factor("patience", .9, "POSITIVE", "INSTITUTIONAL_PATIENCE"), factor("trend", .5, "POSITIVE", "RECENT_TREND")]); expect(deriveGovernanceJobSecurityState(rebuild)).toBe("STABLE"); });
  it("allows Board and Executive assessments to disagree without an institution average", () => { const board = createGovernanceManagerEvaluation({ ...evaluation([factor("sporting", .4)]), id: "board-evaluation", evaluatorBodyId: "board" }); const executive = createGovernanceManagerEvaluation({ ...evaluation([factor("sporting", .4), factor("long", .9, "POSITIVE", "LONG_HORIZON_PROGRESS"), factor("patience", .9, "POSITIVE", "INSTITUTIONAL_PATIENCE")]), id: "executive-evaluation", evaluatorBodyId: "executive" }); expect(deriveGovernanceJobSecurityState(board)).toBe("PRESSURED"); expect(deriveGovernanceJobSecurityState(executive)).toBe("STABLE"); });
  it("supports every job-security state and hysteresis", () => { const state = (score: number) => deriveGovernanceJobSecurityState(evaluation([factor("score", score)])); expect(state(.9)).toBe("SECURE"); expect(state(.7)).toBe("STABLE"); expect(state(.55)).toBe("UNDER_REVIEW"); expect(state(.4)).toBe("PRESSURED"); expect(state(.2)).toBe("CRITICAL"); expect(state(.05)).toBe("TERMINATION_RECOMMENDED"); expect(deriveGovernanceJobSecurityState(evaluation([factor("minor", .63)]), "STABLE")).toBe("STABLE"); });
  it("builds typed missing/present evidence without using BoardState confidence", () => { const objectiveEvaluation = evaluateGovernanceObjective(objective, { metric: objective.metric, value: 60 }, "2032-12-31" as never); const result = evaluateGovernanceManager({ id: "built", evaluationPeriodId: "period", evaluatorBodyId: "board", evaluatedOn: "2032-12-31" as never, objectives: [objective], objectiveEvaluations: [objectiveEvaluation], context: { institutionalPatience: { normalizedValue: .8, bodyId: "board" }, politicalSupport: { normalizedValue: .6, teamId: "team", politicalCaseIds: [], politicalActionIds: [] } } }); expect(result.factors.find((item) => item.kind === "OBJECTIVE_ATTAINMENT")?.status).toBe("PRESENT"); expect(result.factors.find((item) => item.kind === "CONTRACT_CONTEXT")?.status).toBe("MISSING"); expect(result.factors.find((item) => item.kind === "POLITICAL_OPPOSITION")?.status).toBe("MISSING"); });
  it("keeps periods historical and validates their chronology", () => { expect(createGovernanceManagerEvaluationPeriod({ id: "period", institutionId: "institution", universe: "NBA_WNBA", manager: { kind: "COACH", id: "coach" }, startedOn: "2032-01-01" as never, endedOn: "2032-12-31" as never }).manager.id).toBe("coach"); });
});
