import { parseGameDate, type GameDate } from '@/domain/date'
import type { GovernanceInteractionParty } from './GovernanceMeeting'
import { sameGovernanceInteractionParty } from './GovernanceRequest'

export const GOVERNANCE_COMMITMENT_EVENT_KINDS = ['MADE', 'FULFILLED', 'BREACHED', 'WITHDRAWN', 'SUPERSEDED'] as const
export type GovernanceCommitmentProvenance = { readonly kind: 'MEETING'; readonly meetingId: string; readonly agendaItemId?: string } | { readonly kind: 'REQUEST'; readonly requestId: string } | { readonly kind: 'GOVERNANCE_DECISION'; readonly decisionId: string } | { readonly kind: 'STANDALONE' }
export type GovernanceCommitment = { readonly id: string; readonly institutionId: string; readonly promisor: GovernanceInteractionParty; readonly beneficiary: GovernanceInteractionParty; readonly summary: string; readonly dueOn?: GameDate; readonly provenance: GovernanceCommitmentProvenance }
export type GovernanceCommitmentFulfillmentEvidence = { readonly kind: 'GOVERNANCE_DECISION'; readonly decisionId: string }
export type GovernanceCommitmentEvent = { readonly id: string; readonly commitmentId: string; readonly kind: 'MADE' | 'WITHDRAWN'; readonly effectiveOn: GameDate; readonly actor: GovernanceInteractionParty } | { readonly id: string; readonly commitmentId: string; readonly kind: 'FULFILLED'; readonly effectiveOn: GameDate; readonly actor: GovernanceInteractionParty; readonly evidence?: GovernanceCommitmentFulfillmentEvidence } | { readonly id: string; readonly commitmentId: string; readonly kind: 'BREACHED'; readonly effectiveOn: GameDate } | { readonly id: string; readonly commitmentId: string; readonly kind: 'SUPERSEDED'; readonly effectiveOn: GameDate; readonly successorCommitmentId: string }
const nonempty = (value: string) => value.trim() !== ''
const validParty = (party: GovernanceInteractionParty) => party.kind === 'BODY' ? nonempty(party.bodyId) : party.kind === 'APPOINTMENT' ? nonempty(party.appointmentId) : party.kind === 'ACTOR' && (party.actor.kind === 'COACH' || party.actor.kind === 'STAFF') && nonempty(party.actor.id)
export function createGovernanceCommitment(value: GovernanceCommitment): GovernanceCommitment { if (!nonempty(value.id) || !nonempty(value.institutionId) || !validParty(value.promisor) || !validParty(value.beneficiary) || sameGovernanceInteractionParty(value.promisor, value.beneficiary) || !nonempty(value.summary) || (value.provenance.kind === 'MEETING' && (!nonempty(value.provenance.meetingId) || (value.provenance.agendaItemId !== undefined && !nonempty(value.provenance.agendaItemId)))) || (value.provenance.kind === 'REQUEST' && !nonempty(value.provenance.requestId)) || (value.provenance.kind === 'GOVERNANCE_DECISION' && !nonempty(value.provenance.decisionId)) || !['MEETING', 'REQUEST', 'GOVERNANCE_DECISION', 'STANDALONE'].includes(value.provenance.kind)) throw new RangeError('Invalid governance commitment'); return { ...value, ...(value.dueOn === undefined ? {} : { dueOn: parseGameDate(value.dueOn) }) } }
export function createGovernanceCommitmentEvent(value: GovernanceCommitmentEvent): GovernanceCommitmentEvent { if (!nonempty(value.id) || !nonempty(value.commitmentId) || !GOVERNANCE_COMMITMENT_EVENT_KINDS.includes(value.kind) || (('actor' in value) && !validParty(value.actor)) || (value.kind === 'SUPERSEDED' && !nonempty(value.successorCommitmentId)) || (value.kind === 'FULFILLED' && value.evidence !== undefined && (value.evidence.kind !== 'GOVERNANCE_DECISION' || !nonempty(value.evidence.decisionId)))) throw new RangeError('Invalid governance commitment event'); return { ...value, effectiveOn: parseGameDate(value.effectiveOn) } }
export const sortGovernanceCommitmentEvents = (events: readonly GovernanceCommitmentEvent[]) => [...events].sort((a, b) => a.effectiveOn.localeCompare(b.effectiveOn) || a.id.localeCompare(b.id))
export function validateGovernanceCommitmentLifecycle(events: readonly GovernanceCommitmentEvent[]): void { let status: GovernanceCommitmentEvent['kind'] | undefined; let made = 0; for (const event of sortGovernanceCommitmentEvents(events)) { const allowed = status === undefined ? event.kind === 'MADE' : status === 'MADE' ? ['FULFILLED', 'BREACHED', 'WITHDRAWN', 'SUPERSEDED'].includes(event.kind) : status === 'BREACHED' ? ['FULFILLED', 'WITHDRAWN', 'SUPERSEDED'].includes(event.kind) : false; if (!allowed) throw new RangeError('Invalid governance commitment lifecycle'); if (event.kind === 'MADE') made++; status = event.kind }; if (made !== 1) throw new RangeError('Governance commitment requires exactly one MADE event') }
export const deriveGovernanceCommitmentStatus = (events: readonly GovernanceCommitmentEvent[]) => sortGovernanceCommitmentEvents(events).at(-1)?.kind
export const hasGovernanceCommitmentBreach = (events: readonly GovernanceCommitmentEvent[]) => events.some((event) => event.kind === 'BREACHED')
export const isGovernanceCommitmentOverdue = (commitment: GovernanceCommitment, events: readonly GovernanceCommitmentEvent[], currentDate: GameDate) => commitment.dueOn !== undefined && currentDate > commitment.dueOn && !['FULFILLED', 'WITHDRAWN', 'SUPERSEDED'].includes(deriveGovernanceCommitmentStatus(events) ?? '')
export const isGovernanceCommitmentFulfilledLate = (commitment: GovernanceCommitment, events: readonly GovernanceCommitmentEvent[]) => { const fulfilled = sortGovernanceCommitmentEvents(events).find((event) => event.kind === 'FULFILLED'); return commitment.dueOn !== undefined && fulfilled !== undefined && fulfilled.effectiveOn > commitment.dueOn }
