import { describe, expect, it } from 'vitest'
import { createGovernanceUniverseProfile, governanceUniverseForProfile } from './GovernanceUniverseProfile'
import { createNewGame } from '@/app/game'
import { updateGameWorld } from '@/domain/world'
import { createGovernanceBody, createGovernanceInstitution } from './Governance'
import { deserializeGameWorldV3, serializeGameWorldV3 } from '@/save/GameWorldSaveV3'
const create = (kind: any, ownershipModel: any) => createGovernanceUniverseProfile({ id: kind, institutionId: `institution:${kind}`, kind, ownershipModel, expectedBodyKinds: kind.includes('NCAA') ? ['BOARD', 'ATHLETIC_DEPARTMENT', 'EXECUTIVE'] : kind === 'FEDERATION' ? ['BOARD', 'EXECUTIVE'] : ['OWNERSHIP', 'BOARD', 'EXECUTIVE'], apexAuthorityBodyId: 'apex', executiveAuthorityBodyId: 'executive', externalOversight: kind !== 'PROFESSIONAL_CLUB' })
describe('Governance universe profiles', () => {
  it.each([['PROFESSIONAL_CLUB','PRIVATE'],['PROFESSIONAL_CLUB','MEMBER_OWNED'],['PROFESSIONAL_CLUB','MULTISPORT_SECTION'],['NBA_FRANCHISE','OWNERSHIP_GROUP'],['WNBA_FRANCHISE','PRIVATE'],['NCAA_PROGRAM','UNIVERSITY'],['NCAAW_PROGRAM','UNIVERSITY'],['FEDERATION','FEDERATION']])('supports %s with %s semantics',(kind, ownership) => expect(create(kind, ownership).ownershipModel).toBe(ownership))
  it('keeps NBA governor semantics separate from ownership and formal grants', () => { const profile=create('NBA_FRANCHISE','OWNERSHIP_GROUP');expect(profile.expectedBodyKinds).toContain('OWNERSHIP');expect(profile).not.toHaveProperty('decision');expect(governanceUniverseForProfile(profile)).toBe('NBA_WNBA') })
  it('rejects incompatible ownership configurations', () => { expect(() => create('NCAA_PROGRAM','PRIVATE')).toThrow();expect(() => create('FEDERATION','PRIVATE')).toThrow() })
  it('integrates a profile into GameWorld and Save V3 without granting decision rights', () => { const base=createNewGame(), team=Object.values(base.teams)[0]!, institution=createGovernanceInstitution({id:'institution',universe:'PROFESSIONAL_CLUB',name:'Club',teamIds:[team.id]}), bodies=[createGovernanceBody({id:'owner',institutionId:institution.id,kind:'OWNERSHIP',name:'Owner'}),createGovernanceBody({id:'board',institutionId:institution.id,kind:'BOARD',name:'Board'}),createGovernanceBody({id:'executive',institutionId:institution.id,kind:'EXECUTIVE',name:'Executive'})], profile={...create('PROFESSIONAL_CLUB','PRIVATE'),id:'profile',institutionId:institution.id,apexAuthorityBodyId:'owner',executiveAuthorityBodyId:'executive'}; const world=updateGameWorld(base,{governanceInstitutions:[institution],governanceBodies:bodies,governanceUniverseProfiles:[profile]}); expect(deserializeGameWorldV3(serializeGameWorldV3(world,'2032-01-01T00:00:00.000Z')).governanceUniverseProfilesById.profile).toEqual(profile); expect(Object.keys(world.governanceAuthorityGrantsById)).toEqual([]) })
})
