import { describe, expect, it } from 'vitest'
import { deriveGovernanceInstitutionStructure, validateGovernanceInstitutionStructure } from './GovernanceInstitutionStructure'
import { createGovernanceUniverseProfile } from './GovernanceUniverseProfile'
const profile=(kind:any,ownershipModel:any)=>createGovernanceUniverseProfile({id:kind,institutionId:'institution',kind,ownershipModel,expectedBodyKinds:['BOARD','EXECUTIVE'],externalOversight:false})
describe('Governance institutional structures',()=>{
  it.each([['PROFESSIONAL_CLUB','PRIVATE'],['PROFESSIONAL_CLUB','MEMBER_OWNED'],['PROFESSIONAL_CLUB','MULTISPORT_SECTION'],['NBA_FRANCHISE','OWNERSHIP_GROUP'],['WNBA_FRANCHISE','PRIVATE'],['NCAA_PROGRAM','UNIVERSITY'],['NCAAW_PROGRAM','UNIVERSITY'],['FEDERATION','FEDERATION']] as const)('derives deterministic %s structure',(kind,ownership)=>expect(deriveGovernanceInstitutionStructure(profile(kind,ownership))).toEqual(deriveGovernanceInstitutionStructure(profile(kind,ownership))))
  it('keeps governors, appointments, and authority grants uncreated',()=>{const structure=deriveGovernanceInstitutionStructure(profile('NBA_FRANCHISE','OWNERSHIP_GROUP'));expect(structure.slots.find(s=>s.bodyKind==='OWNERSHIP')?.expectedRoles).toContain('GOVERNOR');expect(structure).not.toHaveProperty('authorityGrants');expect(structure).not.toHaveProperty('appointments')})
  it('reports only missing required bodies and permits optional deviations',()=>{const p=profile('NCAA_PROGRAM','UNIVERSITY');expect(validateGovernanceInstitutionStructure(p,[{id:'board',institutionId:'institution',kind:'BOARD',name:'Trustees'}])).toEqual([{kind:'MISSING_REQUIRED_BODY',bodyKind:'ATHLETIC_DEPARTMENT',severity:'ERROR'},{kind:'MISSING_REQUIRED_BODY',bodyKind:'EXECUTIVE',severity:'ERROR'}])})
  it('supports shared parents because validation is institution-local',()=>{const p=profile('WNBA_FRANCHISE','PRIVATE');expect(validateGovernanceInstitutionStructure(p,[{id:'owner',institutionId:'institution',kind:'OWNERSHIP',name:'Shared owner'},{id:'board',institutionId:'institution',kind:'BOARD',name:'Board'},{id:'executive',institutionId:'institution',kind:'EXECUTIVE',name:'Executive'}])).toEqual([])})
})
