import { parseGameDate, type GameDate } from '@/domain/date'
export const GOVERNANCE_MEETING_CATEGORIES=['ORDINARY','EXTRAORDINARY','EMERGENCY'] as const
export const GOVERNANCE_MEETING_PARTICIPANT_ROLES=['CHAIR','ATTENDEE','OBSERVER'] as const
export const GOVERNANCE_MEETING_ATTENDANCES=['PRESENT','ABSENT','EXCUSED'] as const
export const GOVERNANCE_MEETING_EVENT_KINDS=['SCHEDULED','RESCHEDULED','HELD','CANCELLED'] as const
export type GovernanceMeeting={readonly id:string;readonly institutionId:string;readonly conveningBodyId:string;readonly category:typeof GOVERNANCE_MEETING_CATEGORIES[number];readonly title:string;readonly createdOn:GameDate}
export type GovernanceInteractionParty={readonly kind:'BODY';readonly bodyId:string}|{readonly kind:'APPOINTMENT';readonly appointmentId:string}|{readonly kind:'ACTOR';readonly actor:{readonly kind:'COACH'|'STAFF';readonly id:string}}
export type GovernanceMeetingParticipant={readonly id:string;readonly meetingId:string;readonly party:GovernanceInteractionParty;readonly role:typeof GOVERNANCE_MEETING_PARTICIPANT_ROLES[number];readonly attendance:typeof GOVERNANCE_MEETING_ATTENDANCES[number]}
export type GovernanceMeetingAgendaItem={readonly id:string;readonly meetingId:string;readonly sequence:number;readonly subject:{readonly kind:'GOVERNANCE_DECISION';readonly decisionId:string}|{readonly kind:'GOVERNANCE_OBJECTIVE';readonly objectiveId:string}|{readonly kind:'GOVERNANCE_MANAGER_EVALUATION';readonly evaluationId:string}|{readonly kind:'GOVERNANCE_REQUEST';readonly requestId:string}|{readonly kind:'INSTITUTIONAL_TOPIC';readonly topic:string}}
export type GovernanceMeetingEvent={readonly id:string;readonly meetingId:string;readonly kind:'SCHEDULED'|'RESCHEDULED';readonly effectiveOn:GameDate;readonly scheduledFor:GameDate}|{readonly id:string;readonly meetingId:string;readonly kind:'HELD'|'CANCELLED';readonly effectiveOn:GameDate}
const nonempty=(v:string)=>v.trim()!==''
export function createGovernanceMeeting(v:GovernanceMeeting):GovernanceMeeting{if(!nonempty(v.id)||!nonempty(v.institutionId)||!nonempty(v.conveningBodyId)||!nonempty(v.title)||!GOVERNANCE_MEETING_CATEGORIES.includes(v.category))throw new RangeError('Invalid governance meeting');return {...v,createdOn:parseGameDate(v.createdOn)}}
export function createGovernanceMeetingParticipant(v:GovernanceMeetingParticipant):GovernanceMeetingParticipant{if(!nonempty(v.id)||!nonempty(v.meetingId)||!GOVERNANCE_MEETING_PARTICIPANT_ROLES.includes(v.role)||!GOVERNANCE_MEETING_ATTENDANCES.includes(v.attendance)||(v.party.kind==='BODY'&&!nonempty(v.party.bodyId))||(v.party.kind==='APPOINTMENT'&&!nonempty(v.party.appointmentId))||(v.party.kind==='ACTOR'&&(!nonempty(v.party.actor.id)||!['COACH','STAFF'].includes(v.party.actor.kind))))throw new RangeError('Invalid governance meeting participant');return structuredClone(v)}
export function createGovernanceMeetingAgendaItem(v:GovernanceMeetingAgendaItem):GovernanceMeetingAgendaItem{const s=v.subject;if(!nonempty(v.id)||!nonempty(v.meetingId)||!Number.isInteger(v.sequence)||v.sequence<1||('decisionId'in s&&!nonempty(s.decisionId))||('objectiveId'in s&&!nonempty(s.objectiveId))||('evaluationId'in s&&!nonempty(s.evaluationId))||('requestId'in s&&!nonempty(s.requestId))||('topic'in s&&!nonempty(s.topic)))throw new RangeError('Invalid governance meeting agenda item');return structuredClone(v)}
export function createGovernanceMeetingEvent(v:GovernanceMeetingEvent):GovernanceMeetingEvent{if(!nonempty(v.id)||!nonempty(v.meetingId)||!GOVERNANCE_MEETING_EVENT_KINDS.includes(v.kind))throw new RangeError('Invalid governance meeting event');return 'scheduledFor'in v?{...v,effectiveOn:parseGameDate(v.effectiveOn),scheduledFor:parseGameDate(v.scheduledFor)}:{...v,effectiveOn:parseGameDate(v.effectiveOn)}}
export const sortGovernanceMeetingEvents=(v:readonly GovernanceMeetingEvent[])=>[...v].sort((a,b)=>a.effectiveOn.localeCompare(b.effectiveOn)||a.id.localeCompare(b.id))
export const sortGovernanceMeetingAgendaItems=(v:readonly GovernanceMeetingAgendaItem[])=>[...v].sort((a,b)=>a.sequence-b.sequence||a.id.localeCompare(b.id))
export function validateGovernanceMeetingLifecycle(v:readonly GovernanceMeetingEvent[]):void{let status:string|undefined;let scheduled=0;for(const e of sortGovernanceMeetingEvents(v)){const ok=status===undefined?e.kind==='SCHEDULED':status==='SCHEDULED'&&['RESCHEDULED','HELD','CANCELLED'].includes(e.kind);if(!ok)throw new RangeError('Invalid governance meeting lifecycle');if(e.kind==='SCHEDULED')scheduled++;status=e.kind==='RESCHEDULED'?'SCHEDULED':e.kind}if(scheduled!==1)throw new RangeError('Governance meeting requires exactly one SCHEDULED event')}
export const deriveGovernanceMeetingStatus=(v:readonly GovernanceMeetingEvent[])=>{const e=sortGovernanceMeetingEvents(v).at(-1);return e===undefined?undefined:e.kind==='RESCHEDULED'?'SCHEDULED':e.kind}
export const deriveGovernanceMeetingScheduledFor=(v:readonly GovernanceMeetingEvent[])=>sortGovernanceMeetingEvents(v).filter((e):e is Extract<GovernanceMeetingEvent,{scheduledFor:GameDate}>=>'scheduledFor'in e).at(-1)?.scheduledFor
