import { useEffect, useRef, useState } from 'react'

import { getCurrentSeason } from '@/app/game'
import type { Game } from '@/domain/game'
import { getCareerFatigueForPlayer, getInboxItemsForCoach, getNewsFeed, getTeamRoster, getUnreadInboxCount } from '@/domain/world'
import { getGamesToday, getNextUserGame, getUserTeam, inspectCurrentDate } from '@/engine/calendar'
import { calculateStandings } from '@/engine/competition/standings'
import { selectUserTrainingPlan } from '@/stores/gameStore'
import { useDesktopWidgetStore } from '@/stores/desktopWidgetStore'
import { DESKTOP_WIDGET_SNAP, getDesktopWidget, rectsIntersect, snapToGrid, type DesktopWidgetBounds, type DesktopWidgetId, type DesktopWidgetLayout } from './DesktopWidgetRegistry'

interface DesktopWidgetLayerProps { readonly world: Parameters<typeof getUserTeam>[0]; readonly onOpenApp: (id: string) => void; readonly onPlayGame: () => void; readonly onInstantResult: () => void }

export function DesktopWidgetLayer({ world, onOpenApp, onPlayGame, onInstantResult }: DesktopWidgetLayerProps) {
  const layerRef = useRef<HTMLDivElement>(null); const [bounds, setBounds] = useState<DesktopWidgetBounds>({ width: 1920, height: 1080 })
  const widgets = useDesktopWidgetStore((state) => state.widgets); const editMode = useDesktopWidgetStore((state) => state.editMode); const selectedWidgetId = useDesktopWidgetStore((state) => state.selectedWidgetId)
  const { clampToBounds, enterEditMode, exitEditMode, selectWidget, moveWidget, resizeWidget, hideWidget, showWidget, resetLayout } = useDesktopWidgetStore()
  useEffect(() => { const element = layerRef.current; if (element === null) return; const update = () => { const next = { width: element.clientWidth, height: element.clientHeight }; setBounds(next); clampToBounds(next) }; update(); const observer = new ResizeObserver(update); observer.observe(element); return () => observer.disconnect() }, [clampToBounds])
  useEffect(() => { if (!editMode) return; const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') exitEditMode() }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown) }, [editMode, exitEditMode])
  const visible = widgets.filter((widget) => widget.visible); const hidden = widgets.filter((widget) => !widget.visible)
  return <div aria-label="Widgets del escritorio" className={`desktop-widget-layer${editMode ? ' is-editing' : ''}`} data-testid="desktop-widget-layer" ref={layerRef}>{visible.map((widget) => <DesktopWidget bounds={bounds} editMode={editMode} key={widget.id} layout={widget} onHide={() => hideWidget(widget.id)} onMove={moveWidget} onResize={resizeWidget} onSelect={() => selectWidget(widget.id)} selected={selectedWidgetId === widget.id}><DesktopWidgetContent id={widget.id} onInstantResult={onInstantResult} onOpenApp={onOpenApp} onPlayGame={onPlayGame} world={world} /></DesktopWidget>)}{editMode && <aside className="desktop-widget-customizer"><button onClick={() => { for (const widget of hidden) showWidget(widget.id, bounds) }} type="button">+ Añadir widget</button>{hidden.length > 0 && <div className="desktop-widget-customizer__picker">{hidden.map((widget) => <button key={widget.id} onClick={() => showWidget(widget.id, bounds)} type="button">{getDesktopWidget(widget.id).title}</button>)}</div>}<button onClick={resetLayout} type="button">Restablecer</button><button className="primary-button" onClick={exitEditMode} type="button">Terminar</button></aside>}{!editMode && <button aria-label="Personalizar escritorio" className="desktop-widget-customize-shortcut" onClick={enterEditMode} type="button">Personalizar escritorio</button>}</div>
}

function DesktopWidget({ bounds, children, editMode, layout, onHide, onMove, onResize, onSelect, selected }: { readonly bounds: DesktopWidgetBounds; readonly children: React.ReactNode; readonly editMode: boolean; readonly layout: DesktopWidgetLayout; readonly onHide: () => void; readonly onMove: (id: DesktopWidgetId, x: number, y: number, bounds: DesktopWidgetBounds) => void; readonly onResize: (id: DesktopWidgetId, width: number, height: number, bounds: DesktopWidgetBounds) => void; readonly onSelect: () => void; readonly selected: boolean }) {
  const definition = getDesktopWidget(layout.id); const [preview, setPreview] = useState<DesktopWidgetLayout | null>(null); const candidate = preview ?? layout
  const isInvalid = preview !== null && !isPlacementValid(preview, layout.id, useDesktopWidgetStore.getState().widgets, bounds)
  const startMove = (event: React.PointerEvent<HTMLElement>) => { if (!editMode || (event.target as HTMLElement).closest('button,select,input')) return; event.preventDefault(); onSelect(); const origin = { clientX: event.clientX, clientY: event.clientY, x: layout.x, y: layout.y }; let current: DesktopWidgetLayout | null = null; const move = (pointer: PointerEvent) => { current = { ...layout, x: snapToGrid(origin.x + pointer.clientX - origin.clientX), y: snapToGrid(origin.y + pointer.clientY - origin.clientY) }; setPreview(current) }; const stop = () => { const next = useDesktopWidgetStore.getState(); if (current !== null && isPlacementValid(current, layout.id, next.widgets, bounds)) onMove(layout.id, current.x, current.y, bounds); setPreview(null); window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop) }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', stop) }
  const startResize = (event: React.PointerEvent<HTMLButtonElement>) => { event.preventDefault(); event.stopPropagation(); onSelect(); const origin = { clientX: event.clientX, clientY: event.clientY, width: layout.width, height: layout.height }; let current: DesktopWidgetLayout | null = null; const move = (pointer: PointerEvent) => { current = { ...layout, width: snapToGrid(origin.width + pointer.clientX - origin.clientX), height: snapToGrid(origin.height + pointer.clientY - origin.clientY) }; setPreview(current) }; const stop = () => { const next = useDesktopWidgetStore.getState(); if (current !== null && isPlacementValid(current, layout.id, next.widgets, bounds)) onResize(layout.id, current.width, current.height, bounds); setPreview(null); window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop) }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', stop) }
  const onKeyDown = (event: React.KeyboardEvent<HTMLElement>) => { if (!editMode) return; const delta = event.shiftKey ? DESKTOP_WIDGET_SNAP * 5 : DESKTOP_WIDGET_SNAP; const horizontal = event.key === 'ArrowLeft' ? -1 : event.key === 'ArrowRight' ? 1 : 0; const vertical = event.key === 'ArrowUp' ? -1 : event.key === 'ArrowDown' ? 1 : 0; if (horizontal === 0 && vertical === 0) return; event.preventDefault(); if (event.altKey) onResize(layout.id, layout.width + horizontal * delta, layout.height + vertical * delta, bounds); else onMove(layout.id, layout.x + horizontal * delta, layout.y + vertical * delta, bounds) }
  return <section aria-label={definition.title} aria-roledescription={editMode ? 'widget editable' : undefined} className={`desktop-widget${editMode ? ' is-editing' : ''}${selected ? ' is-selected' : ''}${isInvalid ? ' is-invalid' : ''}`} onKeyDown={onKeyDown} onPointerDown={startMove} onPointerUp={() => setPreview(null)} onFocus={onSelect} style={{ left: candidate.x, top: candidate.y, width: candidate.width, height: candidate.height }} tabIndex={editMode ? 0 : -1}>{editMode && <header className="desktop-widget__edit-chrome"><span aria-label={`${definition.title}. Use arrow keys to move; Alt plus arrows to resize.`}>⋮⋮ {definition.title}</span><button aria-label={`Ocultar ${definition.title}`} onClick={onHide} type="button">Ocultar</button></header>}<div className="desktop-widget__content">{children}</div>{editMode && <button aria-label={`Redimensionar ${definition.title}`} className="desktop-widget__resize-handle" onPointerDown={startResize} type="button" />}</section>
}

function isPlacementValid(candidate: DesktopWidgetLayout, id: DesktopWidgetId, widgets: readonly DesktopWidgetLayout[], bounds: DesktopWidgetBounds) { const definition = getDesktopWidget(id); if (candidate.x < 0 || candidate.y < 0 || candidate.x + candidate.width > bounds.width || candidate.y + candidate.height > bounds.height - 104 || candidate.width < definition.minWidth || candidate.height < definition.minHeight || candidate.width > definition.maxWidth || candidate.height > definition.maxHeight) return false; return !widgets.some((widget) => widget.visible && widget.id !== id && rectsIntersect(candidate, widget)) }

function DesktopWidgetContent({ id, world, onOpenApp, onPlayGame, onInstantResult }: { readonly id: DesktopWidgetId; readonly world: DesktopWidgetLayerProps['world']; readonly onOpenApp: (id: string) => void; readonly onPlayGame: () => void; readonly onInstantResult: () => void }) {
  const team = getUserTeam(world); if (team === undefined) return null; const season = getCurrentSeason(world); const today = getGamesToday(world).find((game) => game.homeTeamId === team.id || game.awayTeamId === team.id); const next = getNextUserGame(world)
  if (id === 'nextGame') { const game = today ?? next; if (game === undefined) return <WidgetFrame title="PRÓXIMO PARTIDO"><strong>No hay partido programado</strong></WidgetFrame>; const opponent = world.teams[game.homeTeamId === team.id ? game.awayTeamId : game.homeTeamId]!; return <WidgetFrame action={() => onOpenApp('match')} actionLabel="Abrir centro de partido" title={today === undefined ? 'PRÓXIMO PARTIDO' : 'DÍA DE PARTIDO'}><strong>{team.name} <span>vs</span> {opponent.name}</strong><p>{game.date} · {game.homeTeamId === team.id ? 'Local' : 'Visitante'}</p>{today !== undefined && game.status === 'scheduled' && <div><button className="primary-button" onClick={onPlayGame} type="button">Jugar</button><button onClick={onInstantResult} type="button">Resultado</button></div>}</WidgetFrame> }
  if (id === 'dayStatus') { const status = inspectCurrentDate(world); return <WidgetFrame title="ESTADO DEL DÍA"><strong>{status.scheduledGames.length === 0 ? 'Partidos resueltos' : `${status.scheduledGames.length} partidos pendientes`}</strong><p>{world.currentDate}</p></WidgetFrame> }
  if (id === 'standings') return <WidgetFrame action={() => onOpenApp('standings')} actionLabel="Abrir liga" title="CLASIFICACIÓN"><ol>{calculateStandings(world, season.id).slice(0, 5).map((entry, index) => <li key={entry.teamId}><span>{index + 1}. {world.teams[entry.teamId]!.name}</span><b>{entry.wins}-{entry.losses}</b></li>)}</ol></WidgetFrame>
  if (id === 'training') { const plan = selectUserTrainingPlan(world); const roster = getTeamRoster(world, team.id); const fatigue = roster.length === 0 ? 0 : roster.reduce((total, player) => total + getCareerFatigueForPlayer(world, player.id), 0) / roster.length; return <WidgetFrame action={() => onOpenApp('training')} actionLabel="Abrir entrenamiento" title="ENTRENAMIENTO"><strong>{plan?.intensity ?? 'normal'} · {plan?.focus ?? 'balanced'}</strong><p>Fatiga media: {fatigue.toFixed(1)}</p></WidgetFrame> }
  if (id === 'calendar') { const games = Object.values(world.games).filter((game) => game.seasonId === season.id && (game.homeTeamId === team.id || game.awayTeamId === team.id)).filter((game) => game.date >= world.currentDate).sort((a, b) => a.date.localeCompare(b.date)).slice(0, 4); return <WidgetFrame action={() => onOpenApp('schedule')} actionLabel="Abrir calendario" title="CALENDARIO"><ul>{games.map((game) => <li key={game.id}>{game.date} · {world.teams[game.homeTeamId === team.id ? game.awayTeamId : game.homeTeamId]!.name}</li>)}</ul></WidgetFrame> }
  if (id === 'squad') { const roster = getTeamRoster(world, team.id); return <WidgetFrame action={() => onOpenApp('squad')} actionLabel="Abrir plantilla" title="PLANTILLA"><strong>{roster.length} jugadores</strong><p>{roster.slice(0, 3).map((player) => `${player.firstName} ${player.lastName}`).join(' · ')}</p></WidgetFrame> }
  if (id === 'inbox') { const inbox = getInboxItemsForCoach(world, world.userCoachId).slice(0, 3); return <WidgetFrame title={`INBOX · ${getUnreadInboxCount(world, world.userCoachId)}`}><ul>{inbox.length === 0 ? <li>Sin mensajes</li> : inbox.map((item) => <li key={item.id}>{item.title}</li>)}</ul></WidgetFrame> }
  return <WidgetFrame title="ÚLTIMAS NOTICIAS"><ul>{getNewsFeed(world).slice(0, 3).map((item) => <li key={item.id}>{item.headline}</li>)}</ul></WidgetFrame>
}
function WidgetFrame({ action, actionLabel, children, title }: { readonly action?: () => void; readonly actionLabel?: string; readonly children: React.ReactNode; readonly title: string }) { return <><p className="desktop-widget__eyebrow">{title}</p><div className="desktop-widget__body">{children}</div>{action !== undefined && <button aria-label={actionLabel} className="desktop-widget__open" onClick={action} type="button">Abrir</button>}</> }
