export type DesktopSection = 'coach' | 'tactics' | 'training' | 'squad' | 'staff' | 'schedule' | 'standings' | 'market' | 'draft' | 'finances' | 'trades' | 'recruiting' | 'nil' | 'boosters' | 'enforcement'
export type DesktopIcon = 'bdm' | 'squad' | 'calendar' | 'league' | 'training' | 'staff' | 'inbox' | 'match' | 'club' | 'tactics' | 'market' | 'draft' | 'settings'
export type LauncherCapability = 'hasDraft' | 'hasTrades'
export interface DesktopAppDefinition { readonly id: string; readonly label: string; readonly icon: DesktopIcon; readonly section?: DesktopSection; readonly defaultPinned: boolean; readonly availability: 'available' | 'future'; readonly launcherOrder: number; readonly requiredCapability?: LauncherCapability; readonly singleton?: boolean; readonly window?: { readonly width: number; readonly height: number; readonly minWidth: number; readonly minHeight: number }; readonly renderKey?: 'squad' | 'schedule' | 'standings' | 'training' | 'staff' | 'coach' | 'tactics' | 'market' | 'draft' | 'finances' | 'trades' | 'recruiting' | 'nil' | 'boosters' | 'enforcement' | 'match' }
const app = (definition: DesktopAppDefinition) => definition
export const DESKTOP_APPS: readonly DesktopAppDefinition[] = [
  app({ id: 'bdm', label: 'BDM Launcher', icon: 'bdm', defaultPinned: true, availability: 'available', launcherOrder: 0 }),
  app({ id: 'squad', label: 'Plantilla', icon: 'squad', section: 'squad', defaultPinned: true, availability: 'available', launcherOrder: 10, singleton: true, window: { width: 980, height: 700, minWidth: 620, minHeight: 440 }, renderKey: 'squad' }),
  app({ id: 'schedule', label: 'Calendario', icon: 'calendar', section: 'schedule', defaultPinned: true, availability: 'available', launcherOrder: 20, singleton: true, window: { width: 760, height: 620, minWidth: 520, minHeight: 400 }, renderKey: 'schedule' }),
  app({ id: 'standings', label: 'Liga', icon: 'league', section: 'standings', defaultPinned: true, availability: 'available', launcherOrder: 30, singleton: true, window: { width: 900, height: 680, minWidth: 600, minHeight: 440 }, renderKey: 'standings' }),
  app({ id: 'training', label: 'Entrenamiento', icon: 'training', section: 'training', defaultPinned: true, availability: 'available', launcherOrder: 40, singleton: true, window: { width: 920, height: 680, minWidth: 560, minHeight: 440 }, renderKey: 'training' }),
  app({ id: 'staff', label: 'Staff', icon: 'staff', section: 'staff', defaultPinned: true, availability: 'available', launcherOrder: 50, singleton: true, window: { width: 1020, height: 720, minWidth: 680, minHeight: 480 }, renderKey: 'staff' }),
  app({ id: 'coach', label: 'Tu Club', icon: 'club', section: 'coach', defaultPinned: false, availability: 'available', launcherOrder: 60, singleton: true, window: { width: 920, height: 700, minWidth: 600, minHeight: 460 }, renderKey: 'coach' }),
  app({ id: 'tactics', label: 'Tácticas', icon: 'tactics', section: 'tactics', defaultPinned: false, availability: 'available', launcherOrder: 70, singleton: true, window: { width: 900, height: 660, minWidth: 600, minHeight: 420 }, renderKey: 'tactics' }),
  app({ id: 'market', label: 'Mercado', icon: 'market', section: 'market', defaultPinned: false, availability: 'available', launcherOrder: 80, singleton: true, window: { width: 1040, height: 700, minWidth: 680, minHeight: 460 }, renderKey: 'market' }),
  app({ id: 'draft', label: 'Draft', icon: 'draft', section: 'draft', defaultPinned: false, availability: 'available', launcherOrder: 90, requiredCapability: 'hasDraft', singleton: true, window: { width: 1040, height: 700, minWidth: 680, minHeight: 460 }, renderKey: 'draft' }),
  app({ id: 'trades', label: 'Trades', icon: 'market', section: 'trades', defaultPinned: false, availability: 'available', launcherOrder: 100, requiredCapability: 'hasTrades', singleton: true, window: { width: 1040, height: 700, minWidth: 680, minHeight: 460 }, renderKey: 'trades' }),
  app({ id: 'recruiting', label: 'Recruiting', icon: 'settings', section: 'recruiting', defaultPinned: false, availability: 'available', launcherOrder: 105, singleton: true, window: { width: 1040, height: 700, minWidth: 680, minHeight: 460 }, renderKey: 'recruiting' }),
  app({ id: 'nil', label: 'NIL', icon: 'settings', section: 'nil', defaultPinned: false, availability: 'available', launcherOrder: 106, singleton: true, window: { width: 920, height: 640, minWidth: 600, minHeight: 420 }, renderKey: 'nil' }),
  app({ id: 'boosters', label: 'Boosters', icon: 'club', section: 'boosters', defaultPinned: false, availability: 'available', launcherOrder: 107, singleton: true, window: { width: 920, height: 640, minWidth: 600, minHeight: 420 }, renderKey: 'boosters' }),
  app({ id: 'enforcement', label: 'Compliance', icon: 'settings', section: 'enforcement', defaultPinned: false, availability: 'available', launcherOrder: 108, singleton: true, window: { width: 920, height: 640, minWidth: 600, minHeight: 420 }, renderKey: 'enforcement' }),
  app({ id: 'inbox', label: 'Inbox', icon: 'inbox', defaultPinned: false, availability: 'future', launcherOrder: 110 }),
  app({ id: 'match', label: 'Centro de Partido', icon: 'match', defaultPinned: false, availability: 'available', launcherOrder: 120, singleton: true, window: { width: 680, height: 520, minWidth: 480, minHeight: 360 }, renderKey: 'match' }),
  app({ id: 'scouting', label: 'Scouting', icon: 'settings', defaultPinned: false, availability: 'future', launcherOrder: 130 }),
  app({ id: 'finances', label: 'Finanzas', icon: 'settings', section: 'finances', defaultPinned: false, availability: 'available', launcherOrder: 140, singleton: true, window: { width: 900, height: 680, minWidth: 600, minHeight: 440 }, renderKey: 'finances' }),
  app({ id: 'development', label: 'Desarrollo', icon: 'settings', defaultPinned: false, availability: 'future', launcherOrder: 150 }),
  app({ id: 'settings', label: 'Ajustes', icon: 'settings', defaultPinned: false, availability: 'future', launcherOrder: 160 }),
]
export const DEFAULT_PINNED_APP_IDS = DESKTOP_APPS.filter((app) => app.defaultPinned).map((app) => app.id)
export function getDesktopApp(id: string) { return DESKTOP_APPS.find((app) => app.id === id) }
export function getDesktopAppForSection(section: DesktopSection) { return DESKTOP_APPS.find((app) => app.section === section) }
export function resolveLauncherOrder(savedOrder: readonly string[]): readonly string[] { const ids = DESKTOP_APPS.filter((app) => app.id !== 'bdm').sort((a, b) => a.launcherOrder - b.launcherOrder).map((app) => app.id); return [...savedOrder.filter((id) => ids.includes(id)), ...ids.filter((id) => !savedOrder.includes(id))] }
export function reorderLauncherApps(order: readonly string[], movedId: string, targetId: string): readonly string[] { if (movedId === targetId || !order.includes(movedId) || !order.includes(targetId)) return order; const rest = order.filter((id) => id !== movedId); const at = rest.indexOf(targetId); return [...rest.slice(0, at), movedId, ...rest.slice(at)] }
export function getLauncherApps(query: string, capabilities: Partial<Record<LauncherCapability, boolean>> = {}, savedOrder: readonly string[] = []) { const queryText = query.trim().toLocaleLowerCase(); return resolveLauncherOrder(savedOrder).map(getDesktopApp).filter((item): item is DesktopAppDefinition => item !== undefined && item.availability === 'available' && (item.requiredCapability === undefined || capabilities[item.requiredCapability] === true) && (queryText === '' || item.label.toLocaleLowerCase().includes(queryText))) }
