import { useEffect, useRef, useState } from 'react'

import { Badge, Tooltip } from '@/ui/components/primitives'
import type { GameCapabilities } from '@/ui/gameContext'
import { BdmIcon } from '@/ui/icons/BdmIcon'
import { BDM_APP_ICON_BY_ID } from '@/ui/icons/iconRegistry'
import { DESKTOP_APPS, DOCK_APP_ICON_REGISTRY, getDesktopApp, getLauncherApps, LAUNCHER_GROUPS, type DesktopAppDefinition, type DesktopIcon } from './DesktopAppRegistry'
import { BdmStartMenu, type BdmStartMenuProps } from './BdmStartMenu'
import './BdmStartMenu.css'
import './DockPinned.css'

export function DesktopDock({ activeAppId, dockPinnedAppIds = [], launcherOpen = false, onAppOpen, onLauncherToggle, onPinApp, unreadCount = 0 }: { readonly activeAppId: string | null; readonly dockPinnedAppIds?: readonly string[]; readonly launcherOpen?: boolean; readonly onAppOpen: (appId: string) => void; readonly onLauncherToggle: () => void; readonly onPinApp: (appId: string) => void; readonly unreadCount?: number }) {
  const [expanded, setExpanded] = useState(true); const closeTimer = useRef<number | undefined>(undefined)
  const keepOpen = () => { if (closeTimer.current !== undefined) window.clearTimeout(closeTimer.current); setExpanded(true) }; const scheduleClose = () => undefined
  useEffect(() => () => { if (closeTimer.current !== undefined) window.clearTimeout(closeTimer.current) }, [])
  const apps = dockPinnedAppIds.map(getDesktopApp).filter((app): app is DesktopAppDefinition => app !== undefined && app.id !== 'bdm')
  return <nav aria-label="BDM taskbar" className={'desktop-dock desktop-taskbar' + (expanded || launcherOpen ? ' is-expanded' : ' is-collapsed')} data-testid="desktop-dock" onFocus={keepOpen} onMouseEnter={keepOpen} onMouseLeave={scheduleClose} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); const appId = event.dataTransfer.getData('application/x-bdm-app-id'); if (appId !== '') onPinApp(appId) }}><div className="desktop-taskbar__apps"><DockItem active={false} app={DESKTOP_APPS[0]!} central launcherOpen={launcherOpen} notificationCount={unreadCount} open={false} onClick={onLauncherToggle} />{apps.map((app) => <DockItem active={app.id === activeAppId} app={app} key={app.id} open={app.id === activeAppId} onClick={() => onAppOpen(app.id)} />)}</div></nav>
}

function DockItem({ active, app, central = false, launcherOpen = false, notificationCount = 0, onClick, open }: { readonly active: boolean; readonly app: DesktopAppDefinition; readonly central?: boolean; readonly launcherOpen?: boolean; readonly notificationCount?: number; readonly onClick: () => void; readonly open: boolean }) { const label = central ? 'BDM' : app.label; const icon = BDM_APP_ICON_BY_ID[app.id as keyof typeof BDM_APP_ICON_BY_ID] ?? 'home'; return <Tooltip content={label}><button aria-current={active ? 'page' : undefined} aria-expanded={central ? launcherOpen : undefined} aria-label={central ? 'Toggle BDM launcher' : app.label} className={'desktop-dock__item' + (central ? ' desktop-dock__item--system' : '') + (active ? ' is-active' : '') + (open ? ' is-open' : '')} onClick={onClick} title={label} type="button"><BdmIcon className="bdm-dock-icon" name={icon} size={central ? 192 : 84} /><span className="desktop-dock__label">{label}</span>{notificationCount > 0 && <Badge className="desktop-dock__badge" tone="danger">{notificationCount}</Badge>}</button></Tooltip> }

function LegacyDesktopLauncher({ activeAppId = null, capabilities = {}, isOpen, launcherOrder = [], onAppOpen, onClose, onReorder, onAdvanceDay, onSave, onLoad, onCustomizeDesktop = () => undefined, canAdvanceDay, canLoad, query, onQueryChange, recentAppIds }: { readonly activeAppId?: string | null; readonly capabilities?: Partial<GameCapabilities>; readonly isOpen: boolean; readonly launcherOrder?: readonly string[]; readonly onAppOpen: (appId: string) => void; readonly onClose: () => void; readonly onReorder?: (movedId: string, targetId: string) => void; readonly onAdvanceDay: () => void; readonly onSave: () => void; readonly onLoad: () => void; readonly onCustomizeDesktop?: () => void; readonly canAdvanceDay: boolean; readonly canLoad: boolean; readonly query: string; readonly onQueryChange: (query: string) => void; readonly recentAppIds: readonly string[] }) {
  const [draggedId, setDraggedId] = useState<string | null>(null)
  const [allApps, setAllApps] = useState(false)
  useEffect(() => { if (!isOpen) return; const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown) }, [isOpen, onClose])
  if (!isOpen) return null
  const apps = getLauncherApps(query, capabilities, launcherOrder); const pinned = apps.filter((app) => app.defaultPinned); const visible = allApps ? apps : pinned; const groups = allApps ? LAUNCHER_GROUPS.map((label) => ({ label, apps: visible.filter((app) => app.launcherGroup === label) })).filter((group) => group.apps.length > 0) : [{ label: undefined, apps: visible }]; const ungroupedApps = allApps ? visible.filter((app) => app.launcherGroup === undefined) : []; const recent = recentAppIds.map(getDesktopApp).filter((app): app is DesktopAppDefinition => app !== undefined).slice(0, 6)
  const appClassName = 'desktop-launcher__apps' + (allApps ? ' desktop-launcher__apps--list' : '')
  const renderApp = (app: DesktopAppDefinition) => <button aria-current={activeAppId === app.id ? 'page' : undefined} className={'desktop-launcher__app' + (draggedId === app.id ? ' is-dragging' : '')} draggable={!allApps && onReorder !== undefined} key={app.id} onClick={() => { onAppOpen(app.id); onClose() }} onDragEnd={() => setDraggedId(null)} onDragOver={(event) => { if (onReorder !== undefined) event.preventDefault() }} onDragStart={() => setDraggedId(app.id)} onDrop={() => { if (draggedId !== null) onReorder?.(draggedId, app.id); setDraggedId(null) }} type="button"><DesktopIcon icon={app.icon} /><span>{app.label}</span></button>
  return <div className="desktop-launcher-backdrop" onPointerDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section aria-label="BDM Start Menu" className="desktop-launcher" data-testid="desktop-launcher"><label className="desktop-launcher__search">Search<input aria-label="Search BDM" onChange={(event) => onQueryChange(event.target.value)} placeholder="Search apps" type="search" value={query} /></label><div className="desktop-launcher__section"><div className="desktop-launcher__section-heading"><p>{allApps ? 'ALL APPS' : 'PINNED'}</p><button onClick={() => setAllApps((current) => !current)} type="button">{allApps ? '‹ Back' : 'All apps ›'}</button></div>{ungroupedApps.length > 0 && <div className={appClassName}>{ungroupedApps.map(renderApp)}</div>}{groups.map((group) => <section className="desktop-launcher__group" key={group.label ?? 'pinned'}>{group.label !== undefined && <p>{group.label}</p>}<div className={appClassName}>{group.apps.map(renderApp)}</div></section>)}</div>{!allApps && recent.length > 0 && <div className="desktop-launcher__section desktop-launcher__recent"><p>RECENT</p>{recent.map((app) => <button key={app.id} onClick={() => { onAppOpen(app.id); onClose() }} type="button"><DesktopIcon icon={app.icon} />{app.label}</button>)}</div>}<div className="desktop-launcher__section desktop-launcher__actions"><button disabled={!canAdvanceDay} onClick={onAdvanceDay} type="button">Advance day</button><button onClick={onSave} type="button">Save game</button><button disabled={!canLoad} onClick={onLoad} type="button">Load game</button><button onClick={() => { onCustomizeDesktop(); onClose() }} type="button">Customize desktop</button></div></section></div>
}

function LegacyBdmStartMenu({ activeAppId = null, capabilities = {}, isOpen, launcherOrder = [], onAppOpen, onClose, onAdvanceDay, onSave, onLoad, onCustomizeDesktop = () => undefined, canAdvanceDay, canLoad, query, onQueryChange }: { readonly activeAppId?: string | null; readonly capabilities?: Partial<GameCapabilities>; readonly isOpen: boolean; readonly launcherOrder?: readonly string[]; readonly onAppOpen: (appId: string) => void; readonly onClose: () => void; readonly onReorder?: (movedId: string, targetId: string) => void; readonly onAdvanceDay: () => void; readonly onSave: () => void; readonly onLoad: () => void; readonly onCustomizeDesktop?: () => void; readonly canAdvanceDay: boolean; readonly canLoad: boolean; readonly query: string; readonly onQueryChange: (query: string) => void; readonly recentAppIds: readonly string[] }) {
  const [selectedGroup, setSelectedGroup] = useState<(typeof LAUNCHER_GROUPS)[number] | null>(null)
  useEffect(() => { if (!isOpen) return; const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown) }, [isOpen, onClose])
  if (!isOpen) return null
  const apps = getLauncherApps(query, capabilities, launcherOrder)
  const pinned = apps.filter((app) => app.defaultPinned)
  const groups = LAUNCHER_GROUPS.map((label) => ({ label, apps: apps.filter((app) => app.launcherGroup === label) })).filter((group) => group.apps.length > 0)
  const displayedGroups = selectedGroup === null ? groups : groups.filter((group) => group.label === selectedGroup)
  const open = (appId: string) => { onAppOpen(appId); onClose() }
  return <div className="bdm-start-backdrop" onPointerDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section aria-label="BDM Inicio" className="bdm-start-menu"><aside className="bdm-start-menu__nav"><div className="bdm-start-menu__brand"><b>BDM</b><span>Basketball Dynasty Manager</span></div><button className={selectedGroup === null ? 'is-active' : ''} onClick={() => setSelectedGroup(null)} type="button">Inicio</button>{groups.map((group) => <button className={selectedGroup === group.label ? 'is-active' : ''} key={group.label} onClick={() => setSelectedGroup(group.label)} type="button">{group.label}</button>)}<footer><button onClick={onCustomizeDesktop} type="button">Ajustes</button></footer></aside><main className="bdm-start-menu__content"><header><label><span>⌕</span><input aria-label="Buscar en BDM" onChange={(event) => onQueryChange(event.target.value)} placeholder="Buscar apps, jugadores, equipos, competiciones..." value={query} /></label><button onClick={onCustomizeDesktop} type="button">Editar</button></header>{selectedGroup === null && <section className="bdm-start-menu__pinned"><div><h2>Apps fijadas</h2><span>{pinned.length} aplicaciones</span></div><div className="bdm-start-menu__pinned-grid">{pinned.map((app) => <button aria-current={activeAppId === app.id ? 'page' : undefined} key={app.id} onClick={() => open(app.id)} type="button"><DesktopIcon icon={app.icon} /><span>{app.label}</span></button>)}</div></section>}<section className="bdm-start-menu__categories"><h2>{selectedGroup === null ? 'Todas las categorías' : selectedGroup}</h2>{displayedGroups.map((group) => <section className="bdm-start-menu__category" key={group.label}><header><div><h3>{group.label}</h3><small>{categoryDescription(group.label)}</small></div><button onClick={() => setSelectedGroup(group.label)} type="button">›</button></header><div>{group.apps.map((app) => <button aria-current={activeAppId === app.id ? 'page' : undefined} key={app.id} onClick={() => open(app.id)} type="button"><DesktopIcon icon={app.icon} /><span>{app.label}</span></button>)}</div></section>)}</section><footer className="bdm-start-menu__footer"><button disabled={!canAdvanceDay} onClick={onAdvanceDay} type="button">Avanzar día</button><button onClick={onSave} type="button">Guardar</button><button disabled={!canLoad} onClick={onLoad} type="button">Cargar</button><span>Ctrl + K para búsqueda rápida</span></footer></main></section></div>
}

export function DesktopLauncher(props: BdmStartMenuProps) { return <BdmStartMenu {...props} /> }

function categoryDescription(group: (typeof LAUNCHER_GROUPS)[number]) { return group === 'EQUIPO' ? 'Gestiona tu equipo y cuerpo técnico' : group === 'PARTIDOS Y COMPETICIÓN' ? 'Competiciones, calendario y partidos' : group === 'MERCADO' ? 'Fichajes, agentes libres y operaciones' : group === 'GESTIÓN DEL CLUB' ? 'Organización, finanzas y cumplimiento' : group === 'MI CARRERA' ? 'Tu entrenador, carrera y patrimonio' : group === 'MUNDO Y NARRATIVA' ? 'Prensa, historias y recuerdos' : 'Operaciones de baloncesto universitario' }

export function StatusCluster({ date, saveMessage }: { readonly date?: string; readonly saveMessage: string | null }) { return date === undefined && saveMessage === null ? null : <div aria-label="Game status" className="status-cluster">{date !== undefined && <time>{date}</time>}{saveMessage !== null && <span>{saveMessage}</span>}</div> }

export function DesktopIcon({ icon }: { readonly icon: DesktopIcon }) { return <img alt="" className="desktop-icon desktop-icon--illustrated" draggable={false} src={DOCK_APP_ICON_REGISTRY[icon]} /> }
