import { useEffect, useRef, useState } from 'react'
import { Badge, Tooltip } from '@/ui/components/primitives'
import { DESKTOP_APPS, getDesktopApp, getLauncherApps, type DesktopAppDefinition, type DesktopIcon } from './DesktopAppRegistry'

export function DesktopDock({ activeAppId, launcherOpen = false, onAppOpen, onLauncherToggle, openAppIds, unreadCount = 0 }: { readonly activeAppId: string | null; readonly launcherOpen?: boolean; readonly onAppOpen: (appId: string) => void; readonly onLauncherToggle: () => void; readonly openAppIds: readonly string[]; readonly unreadCount?: number }) {
  const [expanded, setExpanded] = useState(false); const closeTimer = useRef<number | undefined>(undefined)
  const keepOpen = () => { if (closeTimer.current !== undefined) window.clearTimeout(closeTimer.current); setExpanded(true) }; const scheduleClose = () => { if (!launcherOpen) closeTimer.current = window.setTimeout(() => setExpanded(false), 360) }
  useEffect(() => () => { if (closeTimer.current !== undefined) window.clearTimeout(closeTimer.current) }, [])
  const apps = DESKTOP_APPS.filter((app) => app.defaultPinned && app.id !== 'bdm'); const split = Math.ceil(apps.length / 2)
  return <nav aria-label="Aplicaciones BDM" className={'desktop-dock' + (expanded || launcherOpen ? ' is-expanded' : ' is-collapsed')} data-testid="desktop-dock" onFocus={keepOpen} onMouseEnter={keepOpen} onMouseLeave={scheduleClose}><div className="desktop-dock__side desktop-dock__side--left">{apps.slice(0, split).map((app) => <Item active={app.id === activeAppId} app={app} key={app.id} open={openAppIds.includes(app.id)} onClick={() => onAppOpen(app.id)} />)}</div><Item active={false} app={DESKTOP_APPS[0]!} central launcherOpen={launcherOpen} notificationCount={unreadCount} open={false} onClick={onLauncherToggle} /><div className="desktop-dock__side desktop-dock__side--right">{apps.slice(split).map((app) => <Item active={app.id === activeAppId} app={app} key={app.id} open={openAppIds.includes(app.id)} onClick={() => onAppOpen(app.id)} />)}</div></nav>
}
function Item({ active, app, central = false, launcherOpen = false, notificationCount = 0, onClick, open }: { readonly active: boolean; readonly app: DesktopAppDefinition; readonly central?: boolean; readonly launcherOpen?: boolean; readonly notificationCount?: number; readonly onClick: () => void; readonly open: boolean }) { return <Tooltip content={central ? 'BDM' : app.label}><button aria-current={active ? 'page' : undefined} aria-expanded={central ? launcherOpen : undefined} aria-label={central ? 'Abrir lanzador BDM' : app.label} className={'desktop-dock__item' + (central ? ' desktop-dock__item--system' : '') + (active ? ' is-active' : '') + (open ? ' is-open' : '')} onClick={onClick} type="button"><DesktopIcon icon={app.icon} /><span className="desktop-dock__label">{central ? 'BDM' : app.label}</span>{notificationCount > 0 && <Badge className="desktop-dock__badge" tone="danger">{notificationCount}</Badge>}</button></Tooltip> }
export function DesktopLauncher({ isOpen, onAppOpen, onClose, onAdvanceDay, onSave, onLoad, onCustomizeDesktop = () => undefined, canAdvanceDay, canLoad, query, onQueryChange, recentAppIds }: { readonly isOpen: boolean; readonly onAppOpen: (appId: string) => void; readonly onClose: () => void; readonly onAdvanceDay: () => void; readonly onSave: () => void; readonly onLoad: () => void; readonly onCustomizeDesktop?: () => void; readonly canAdvanceDay: boolean; readonly canLoad: boolean; readonly query: string; readonly onQueryChange: (query: string) => void; readonly recentAppIds: readonly string[] }) { if (!isOpen) return null; const apps = getLauncherApps(query); const recent = recentAppIds.map(getDesktopApp).filter((app): app is DesktopAppDefinition => app !== undefined); return <div className="desktop-launcher-backdrop"><section aria-label="BDM Launcher" className="desktop-launcher" data-testid="desktop-launcher"><label className="desktop-launcher__search">Buscar en BDM<input aria-label="Buscar en BDM" onChange={(event) => onQueryChange(event.target.value)} type="search" value={query} /></label><div className="desktop-launcher__section"><p>APLICACIONES</p><div className="desktop-launcher__apps">{apps.map((app) => <button disabled={app.availability === 'future'} key={app.id} onClick={() => { if (app.availability === 'available') { onAppOpen(app.id); onClose() } }} type="button"><DesktopIcon icon={app.icon} />{app.label}</button>)}</div></div>{recent.length > 0 && <div className="desktop-launcher__section"><p>RECIENTES</p>{recent.map((app) => <button key={app.id} onClick={() => onAppOpen(app.id)} type="button">{app.label}</button>)}</div>}<div className="desktop-launcher__section"><p>ACCIONES RÁPIDAS</p><button disabled={!canAdvanceDay} onClick={onAdvanceDay} type="button">Avanzar día</button><button onClick={onSave} type="button">Guardar partida</button><button disabled={!canLoad} onClick={onLoad} type="button">Cargar partida</button><button onClick={() => { onCustomizeDesktop(); onClose() }} type="button">Personalizar escritorio</button></div></section></div> }
export function StatusCluster({ date, saveMessage }: { readonly date: string; readonly saveMessage: string | null }) { return <div aria-label="Estado de partida" className="status-cluster"><time>{date}</time>{saveMessage !== null && <span>{saveMessage}</span>}</div> }
export function DesktopIcon({ icon }: { readonly icon: DesktopIcon }) { const paths: Record<DesktopIcon, string> = { bdm: 'M5 4h14v16H5zM8 7h8M8 10h5M8 13h8', squad: 'M8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6M16 12a2 2 0 1 0 0-4M3 19c0-3 2-5 5-5s5 2 5 5M14 19c0-2 1-4 3-4s4 2 4 4', calendar: 'M5 4h14v16H5zM8 2v4M16 2v4M5 9h14M8 13h3M8 16h6', league: 'M12 3 4 7l8 4 8-4-8-4M6 11v5l6 3 6-3v-5', training: 'M4 18 9 13l3 3 7-8M4 6h4M16 18h4', staff: 'M8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6M16 10a2 2 0 1 0 0-4M3 20c0-3 2-5 5-5s5 2 5 5M14 20c0-2 1-4 3-4s4 2 4 4', inbox: 'M4 5h16v14H4zM4 7l8 6 8-6', match: 'M5 4h14v16H5zM8 8h8M8 12h3M8 16h8', club: 'M12 3 5 6v5c0 5 3 8 7 10 4-2 7-5 7-10V6l-7-3', tactics: 'M5 19 19 5M5 5h6v6H5zM13 13h6v6h-6z', market: 'M4 7h16v12H4zM7 7V5h10v2M8 13h8M12 10v6', settings: 'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 3v2M12 19v2M21 12h-2M5 12H3M18.4 5.6 17 7M7 17l-1.4 1.4M18.4 18.4 17 17M7 7 5.6 5.6' }; return <svg aria-hidden="true" className="desktop-icon" fill="none" viewBox="0 0 24 24"><path d={paths[icon]} stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" /></svg> }
