import { useEffect, useRef, useState } from 'react'

import { Badge, Tooltip } from '@/ui/components/primitives'
import type { GameCapabilities } from '@/ui/gameContext'
import { DESKTOP_APPS, DOCK_APP_ICON_REGISTRY, getDesktopApp, getLauncherApps, type DesktopAppDefinition, type DesktopIcon } from './DesktopAppRegistry'

export function DesktopDock({ activeAppId, launcherOpen = false, onAppOpen, onLauncherToggle, openAppIds, unreadCount = 0 }: { readonly activeAppId: string | null; readonly launcherOpen?: boolean; readonly onAppOpen: (appId: string) => void; readonly onLauncherToggle: () => void; readonly openAppIds: readonly string[]; readonly unreadCount?: number }) {
  const [expanded, setExpanded] = useState(true); const closeTimer = useRef<number | undefined>(undefined)
  const keepOpen = () => { if (closeTimer.current !== undefined) window.clearTimeout(closeTimer.current); setExpanded(true) }; const scheduleClose = () => undefined
  useEffect(() => () => { if (closeTimer.current !== undefined) window.clearTimeout(closeTimer.current) }, [])
  const pinned = DESKTOP_APPS.filter((app) => app.defaultPinned && app.id !== 'bdm'); const apps = [...pinned, ...openAppIds.map(getDesktopApp).filter((app): app is DesktopAppDefinition => app !== undefined && app.id !== 'bdm' && !pinned.some((pinnedApp) => pinnedApp.id === app.id))]
  return <nav aria-label="BDM taskbar" className={'desktop-dock desktop-taskbar' + (expanded || launcherOpen ? ' is-expanded' : ' is-collapsed')} data-testid="desktop-dock" onFocus={keepOpen} onMouseEnter={keepOpen} onMouseLeave={scheduleClose}><div className="desktop-taskbar__apps"><DockItem active={false} app={DESKTOP_APPS[0]!} central launcherOpen={launcherOpen} notificationCount={unreadCount} open={false} onClick={onLauncherToggle} />{apps.map((app) => <DockItem active={app.id === activeAppId} app={app} key={app.id} open={openAppIds.includes(app.id)} onClick={() => onAppOpen(app.id)} />)}</div></nav>
}

function DockItem({ active, app, central = false, launcherOpen = false, notificationCount = 0, onClick, open }: { readonly active: boolean; readonly app: DesktopAppDefinition; readonly central?: boolean; readonly launcherOpen?: boolean; readonly notificationCount?: number; readonly onClick: () => void; readonly open: boolean }) { const label = central ? 'BDM' : app.label; return <Tooltip content={label}><button aria-current={active ? 'page' : undefined} aria-expanded={central ? launcherOpen : undefined} aria-label={central ? 'Toggle BDM launcher' : app.label} className={'desktop-dock__item' + (central ? ' desktop-dock__item--system' : '') + (active ? ' is-active' : '') + (open ? ' is-open' : '')} onClick={onClick} title={label} type="button"><DesktopIcon icon={app.icon} /><span className="desktop-dock__label">{label}</span>{notificationCount > 0 && <Badge className="desktop-dock__badge" tone="danger">{notificationCount}</Badge>}</button></Tooltip> }

export function DesktopLauncher({ activeAppId = null, capabilities = {}, isOpen, launcherOrder = [], onAppOpen, onClose, onReorder, onAdvanceDay, onSave, onLoad, onCustomizeDesktop = () => undefined, canAdvanceDay, canLoad, query, onQueryChange, recentAppIds }: { readonly activeAppId?: string | null; readonly capabilities?: Partial<GameCapabilities>; readonly isOpen: boolean; readonly launcherOrder?: readonly string[]; readonly onAppOpen: (appId: string) => void; readonly onClose: () => void; readonly onReorder?: (movedId: string, targetId: string) => void; readonly onAdvanceDay: () => void; readonly onSave: () => void; readonly onLoad: () => void; readonly onCustomizeDesktop?: () => void; readonly canAdvanceDay: boolean; readonly canLoad: boolean; readonly query: string; readonly onQueryChange: (query: string) => void; readonly recentAppIds: readonly string[] }) {
  const [draggedId, setDraggedId] = useState<string | null>(null)
  const [allApps, setAllApps] = useState(false)
  useEffect(() => { if (!isOpen) return; const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown) }, [isOpen, onClose])
  if (!isOpen) return null
  const apps = getLauncherApps(query, capabilities, launcherOrder); const pinned = apps.filter((app) => app.defaultPinned); const visible = allApps ? apps : pinned; const primaryApps = visible.filter((app) => app.launcherGroup === undefined); const collegeApps = visible.filter((app) => app.launcherGroup === 'College Performance Center'); const recent = recentAppIds.map(getDesktopApp).filter((app): app is DesktopAppDefinition => app !== undefined).slice(0, 6)
  const appClassName = 'desktop-launcher__apps' + (allApps ? ' desktop-launcher__apps--list' : '')
  const renderApp = (app: DesktopAppDefinition) => <button aria-current={activeAppId === app.id ? 'page' : undefined} className={'desktop-launcher__app' + (draggedId === app.id ? ' is-dragging' : '')} draggable={!allApps && onReorder !== undefined} key={app.id} onClick={() => { onAppOpen(app.id); onClose() }} onDragEnd={() => setDraggedId(null)} onDragOver={(event) => { if (onReorder !== undefined) event.preventDefault() }} onDragStart={() => setDraggedId(app.id)} onDrop={() => { if (draggedId !== null) onReorder?.(draggedId, app.id); setDraggedId(null) }} type="button"><DesktopIcon icon={app.icon} /><span>{app.label}</span></button>
  return <div className="desktop-launcher-backdrop" onPointerDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section aria-label="BDM Start Menu" className="desktop-launcher" data-testid="desktop-launcher"><label className="desktop-launcher__search">Search<input aria-label="Search BDM" onChange={(event) => onQueryChange(event.target.value)} placeholder="Search apps" type="search" value={query} /></label><div className="desktop-launcher__section"><div className="desktop-launcher__section-heading"><p>{allApps ? 'ALL APPS' : 'PINNED'}</p><button onClick={() => setAllApps((current) => !current)} type="button">{allApps ? '‹ Back' : 'All apps ›'}</button></div><div className={appClassName}>{primaryApps.map(renderApp)}</div>{collegeApps.length > 0 && <section className="desktop-launcher__group"><p>College Performance Center</p><div className={appClassName}>{collegeApps.map(renderApp)}</div></section>}</div>{!allApps && recent.length > 0 && <div className="desktop-launcher__section desktop-launcher__recent"><p>RECENT</p>{recent.map((app) => <button key={app.id} onClick={() => { onAppOpen(app.id); onClose() }} type="button"><DesktopIcon icon={app.icon} />{app.label}</button>)}</div>}<div className="desktop-launcher__section desktop-launcher__actions"><button disabled={!canAdvanceDay} onClick={onAdvanceDay} type="button">Advance day</button><button onClick={onSave} type="button">Save game</button><button disabled={!canLoad} onClick={onLoad} type="button">Load game</button><button onClick={() => { onCustomizeDesktop(); onClose() }} type="button">Customize desktop</button></div></section></div>
}

export function StatusCluster({ date, saveMessage }: { readonly date?: string; readonly saveMessage: string | null }) { return date === undefined && saveMessage === null ? null : <div aria-label="Game status" className="status-cluster">{date !== undefined && <time>{date}</time>}{saveMessage !== null && <span>{saveMessage}</span>}</div> }

export function DesktopIcon({ icon }: { readonly icon: DesktopIcon }) { return <img alt="" className="desktop-icon desktop-icon--illustrated" draggable={false} src={DOCK_APP_ICON_REGISTRY[icon]} /> }
