import { useEffect, useMemo, useRef, useState } from 'react'
import { getCurrentSeason } from '@/app/game'
import { getTeamRoster } from '@/domain/world'
import { getUserTeam } from '@/engine/calendar'
import { DESKTOP_APPS } from './DesktopAppRegistry'

export type SearchType = 'APP' | 'ACTION' | 'PLAYER' | 'TEAM' | 'FIXTURE'
export interface GlobalSearchResult { readonly id: string; readonly type: SearchType; readonly title: string; readonly subtitle?: string; readonly keywords: readonly string[]; readonly execute: () => void }
export function normalizeSearchQuery(value: string) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase().trim().replace(/\s+/g, ' ') }
export function scoreSearch(result: Omit<GlobalSearchResult, 'execute'>, query: string) { const needle = normalizeSearchQuery(query); if (needle === '') return 1; const title = normalizeSearchQuery(result.title); const words = title.split(' '); if (title === needle) return 1000; if (title.startsWith(needle)) return 800; if (words.some((word) => word.startsWith(needle))) return 650; if (title.includes(needle)) return 500; if (result.keywords.some((item) => normalizeSearchQuery(item).includes(needle))) return 350; if (normalizeSearchQuery(result.subtitle ?? '').includes(needle)) return 250; return 0 }

export function GlobalSearchOverlay({ world, isOpen, onClose, onOpenApp, onCustomize, onSave, onLoad, onAdvanceDay, canAdvanceDay, canLoad }: { readonly world: Parameters<typeof getUserTeam>[0]; readonly isOpen: boolean; readonly onClose: () => void; readonly onOpenApp: (id: string) => void; readonly onCustomize: () => void; readonly onSave: () => void; readonly onLoad: () => void; readonly onAdvanceDay: () => void; readonly canAdvanceDay: boolean; readonly canLoad: boolean }) {
  const input = useRef<HTMLInputElement>(null); const [query, setQuery] = useState(''); const [selected, setSelected] = useState(0); const [recents, setRecents] = useState<string[]>([])
  const results = useMemo(() => buildResults(world, { onOpenApp, onCustomize, onSave, onLoad, onAdvanceDay, canAdvanceDay, canLoad }), [world, onOpenApp, onCustomize, onSave, onLoad, onAdvanceDay, canAdvanceDay, canLoad])
  const ranked = useMemo(() => (query === '' ? [...results.filter((item) => recents.includes(item.id)).sort((a, b) => recents.indexOf(a.id) - recents.indexOf(b.id)), ...results.filter((item) => item.type === 'ACTION' || item.type === 'APP')].slice(0, 12) : results.map((item) => ({ item, score: scoreSearch(item, query) })).filter((item) => item.score > 0).sort((a, b) => b.score - a.score || typePriority(a.item.type) - typePriority(b.item.type) || a.item.title.localeCompare(b.item.title)).slice(0, 12).map((item) => item.item)), [query, recents, results])
  useEffect(() => { if (!isOpen) return; setQuery(''); setSelected(0); queueMicrotask(() => input.current?.focus()) }, [isOpen]); useEffect(() => setSelected((value) => Math.min(value, Math.max(0, ranked.length - 1))), [ranked.length])
  if (!isOpen) return null
  const execute = (result: GlobalSearchResult) => { setRecents((items) => [result.id, ...items.filter((id) => id !== result.id)].slice(0, 8)); result.execute(); onClose() }
  return <div className="global-search-backdrop" onPointerDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section aria-label="Búsqueda global" className="global-search"><input aria-label="Buscar en BDM" onChange={(event) => { setQuery(event.target.value); setSelected(0) }} onKeyDown={(event) => { if (event.key === 'Escape') onClose(); if (event.key === 'ArrowDown') { event.preventDefault(); setSelected((value) => Math.min(value + 1, ranked.length - 1)) }; if (event.key === 'ArrowUp') { event.preventDefault(); setSelected((value) => Math.max(0, value - 1)) }; if (event.key === 'Enter' && ranked[selected] !== undefined) execute(ranked[selected]!) }} placeholder="Buscar en BDM..." ref={input} value={query} /><p className="global-search__hint">↑↓ navegar · Enter ejecutar · Esc cerrar</p><div>{ranked.length === 0 ? <p className="global-search__empty">Sin resultados para “{query}”</p> : ranked.map((result, index) => <button className={'global-search__result' + (index === selected ? ' is-selected' : '')} key={result.id} onClick={() => execute(result)} onMouseEnter={() => setSelected(index)} type="button"><span>{result.type}</span><strong>{result.title}</strong>{result.subtitle !== undefined && <small>{result.subtitle}</small>}</button>)}</div></section></div>
}
function typePriority(type: SearchType) { return type === 'APP' ? 0 : type === 'ACTION' ? 1 : 2 }
function buildResults(world: Parameters<typeof getUserTeam>[0], actions: { onOpenApp: (id: string) => void; onCustomize: () => void; onSave: () => void; onLoad: () => void; onAdvanceDay: () => void; canAdvanceDay: boolean; canLoad: boolean }) {
  const results: GlobalSearchResult[] = DESKTOP_APPS.filter((app) => app.availability === 'available' && app.id !== 'bdm').map((app) => ({ id: 'app:' + app.id, type: 'APP', title: app.label, keywords: [app.id, app.label === 'Plantilla' ? 'roster jugadores' : '', app.id === 'training' ? 'training entrenamiento' : '', app.id === 'match' ? 'partido match próximo partido' : ''], execute: () => actions.onOpenApp(app.id) }))
  results.push({ id: 'action:customize', type: 'ACTION', title: 'Personalizar escritorio', keywords: ['editar desktop widgets'], execute: actions.onCustomize }, { id: 'action:save', type: 'ACTION', title: 'Guardar partida', keywords: ['guardar save'], execute: actions.onSave })
  if (actions.canLoad) results.push({ id: 'action:load', type: 'ACTION', title: 'Cargar partida', keywords: ['cargar load'], execute: actions.onLoad }); if (actions.canAdvanceDay) results.push({ id: 'action:advance', type: 'ACTION', title: 'Avanzar día', keywords: ['calendario'], execute: actions.onAdvanceDay })
  const team = getUserTeam(world); const season = getCurrentSeason(world); for (const item of Object.values(world.teams)) results.push({ id: 'team:' + item.id, type: 'TEAM', title: item.name, subtitle: 'Equipo · Liga actual', keywords: [item.name], execute: () => actions.onOpenApp('standings') }); if (team !== undefined) for (const player of getTeamRoster(world, team.id)) results.push({ id: 'player:' + player.id, type: 'PLAYER', title: player.firstName + ' ' + player.lastName, subtitle: player.basketball.primaryPosition + ' · ' + team.name, keywords: [player.firstName, player.lastName, player.basketball.primaryPosition, team.name], execute: () => actions.onOpenApp('squad') }); for (const game of Object.values(world.games).filter((game) => game.seasonId === season.id)) { const title = world.teams[game.homeTeamId]!.name + ' vs ' + world.teams[game.awayTeamId]!.name; results.push({ id: 'fixture:' + game.id, type: 'FIXTURE', title, subtitle: game.date + ' · ' + (game.status === 'scheduled' ? 'Programado' : 'Final'), keywords: [title, game.date, 'próximo partido'], execute: () => actions.onOpenApp(game.date === world.currentDate && (game.homeTeamId === team?.id || game.awayTeamId === team?.id) ? 'match' : 'schedule') }) }
  return results
}
