import type { CSSProperties } from 'react'

type IconProps = { readonly size?: number; readonly color?: string; readonly style?: CSSProperties }
const icon = (symbol: string) => ({ size = 16, color = 'currentColor', style }: IconProps) => <span aria-hidden="true" style={{ alignItems: 'center', color, display: 'inline-flex', fontSize: size, height: size, justifyContent: 'center', lineHeight: 1, width: size, ...style }}>{symbol}</span>

export const MousePointer2 = icon('⌖')
export const Circle = icon('○')
export const ArrowRight = icon('→')
export const Type = icon('T')
export const RotateCcw = icon('↶')
export const Eraser = icon('⌫')
export const Save = icon('▣')
export const Move = icon('↔')
export const X = icon('×')
export const Plus = icon('+')
export const Trash2 = icon('⌫')
export const Play = icon('▶')
export const Pause = icon('Ⅱ')
export const SkipBack = icon('◀')
export const ListChecks = icon('☷')
export const AlertTriangle = icon('⚠')
export const FolderOpen = icon('▱')
export const Book = icon('▤')
export const BookOpen = icon('▥')
export const PlusSquare = icon('⊞')
export const Settings = icon('⚙')
export const Database = icon('◫')
export const CheckCircle = icon('✓')
export const User = icon('●')
export const GripVertical = icon('⠿')
export const Target = icon('◎')
export const Lock = icon('▣')
export const LayoutGrid = icon('▦')
export const Repeat = icon('↻')
export const Zap = icon('ϟ')
export const Crosshair = icon('⌖')
export const Anchor = icon('⚓')
export const Shield = icon('⬟')
export const ArrowLeftRight = icon('↔')
export const Scale = icon('⚖')
export const ShieldAlert = icon('⚠')
export const Flame = icon('♨')
export const ArrowUpCircle = icon('↑')
export const Check = icon('✓')
export const ShieldCheck = icon('✓')
