import { describe, expect, it } from 'vitest'
import { createGameDate } from '@/domain/date'
import { DEFAULT_FIBA_LIKE_ECOSYSTEM_ID } from '@/domain/ecosystem'
import { teamIdFromString } from '@/domain/ids'
import { defaultRecruitingRules } from '@/domain/recruiting'
import { createGameWorld, updateGameWorld } from '@/domain/world'
import { createValidGameWorldInput } from '@/domain/world/testFixtures'
import { deserializeGameWorldV1, serializeGameWorldV1 } from '@/save/GameWorldSaveV1'
import { addRecruitingBoardEntry, arriveSignedRecruits, generateRecruitingPool, getRecruitingClass, makeRecruitingOffer, performRecruitingAction, removeRecruitingBoardEntry, resolveRecruitingCommitments, signCommittedRecruit } from './RecruitingEngine'

const program = teamIdFromString('team-home')
function base(status: 'open'|'signing' = 'open') {
  return generateRecruitingPool(updateGameWorld(createGameWorld(createValidGameWorldInput()), { recruitingCycles: [{ id: 'cycle', ecosystemId: DEFAULT_FIBA_LIKE_ECOSYSTEM_ID, sourceSeasonId: 'season-a' as never, targetSeasonId: 'season-a' as never, opensOn: createGameDate(2032, 10, 1), signingOn: createGameDate(2032, 10, 2), closesOn: createGameDate(2032, 10, 4), status, rules: { ...defaultRecruitingRules, poolSize: 5, maxOffers: 2, maxSignings: 1, periodCapacity: 6, commitmentThreshold: 1 } }] }), 'cycle')
}
function committed() { const world = base(); const recruit = Object.values(world.recruitProfilesById)[0]!; const contacted = performRecruitingAction(world, 'cycle', recruit.id, program, 'contact'); if (!contacted.ok) throw new Error('contact'); const offered = makeRecruitingOffer(contacted.value, 'cycle', recruit.id, program); if (!offered.ok) throw new Error('offer'); return resolveRecruitingCommitments(offered.value, 'cycle') }

describe('Recruiting lifecycle contracts', () => {
  it('keeps boards unique and supports priority replacement/removal', () => { const world = base(); const recruit = Object.values(world.recruitProfilesById)[0]!; const high = addRecruitingBoardEntry(world, { programTeamId: program, recruitId: recruit.id, priority: 'high' }); const low = addRecruitingBoardEntry(high, { programTeamId: program, recruitId: recruit.id, priority: 'low' }); expect(low.recruitingBoards).toEqual([{ programTeamId: program, recruitId: recruit.id, priority: 'low' }]); expect(removeRecruitingBoardEntry(low, program, recruit.id).recruitingBoards).toEqual([]) })
  it('consumes action capacity and rejects without mutation when exhausted', () => { const world = base(); const recruit = Object.values(world.recruitProfilesById)[0]!; const contact = performRecruitingAction(world, 'cycle', recruit.id, program, 'contact'); expect(contact.ok).toBe(true); if (!contact.ok) return; expect(contact.value.recruitingCapacityByProgramId[program]).toBe(5); const visit = performRecruitingAction(contact.value, 'cycle', recruit.id, program, 'visit'); expect(visit.ok).toBe(true); if (!visit.ok) return; expect(Object.values(visit.value.recruitingVisitsById)).toHaveLength(1); const exhausted = updateGameWorld(visit.value, { recruitingCapacityByProgramId: { [program]: 0 } }); const rejected = performRecruitingAction(exhausted, 'cycle', recruit.id, program, 'pitch'); expect(rejected).toMatchObject({ ok: false, reason: 'INSUFFICIENT_RECRUITING_CAPACITY' }); expect(Object.values(exhausted.recruitingActionHistoryById)).toHaveLength(2) })
  it('allows competing offers but creates one commitment and no automatic signing', () => { const world = base(); const recruit = Object.values(world.recruitProfilesById)[0]!; const contacted = performRecruitingAction(world, 'cycle', recruit.id, program, 'contact'); if (!contacted.ok) throw new Error('contact'); const first = makeRecruitingOffer(contacted.value, 'cycle', recruit.id, program); if (!first.ok) throw new Error('offer'); const second = makeRecruitingOffer(first.value, 'cycle', recruit.id, teamIdFromString('team-away')); if (!second.ok) throw new Error('offer'); const resolved = resolveRecruitingCommitments(second.value, 'cycle'); expect(Object.values(resolved.recruitingOffersById)).toHaveLength(2); expect(Object.values(resolved.recruitingCommitmentsById)).toHaveLength(1); expect(Object.values(resolved.recruitSigningsById)).toHaveLength(0); expect(resolved.teams[program]!.rosterPlayerIds).not.toContain(recruit.playerId) })
  it('enforces signing window and keeps canonical player unrostered until idempotent arrival', () => { const world = committed(); const recruitId = Object.values(world.recruitingCommitmentsById)[0]!.recruitId; const recruit = world.recruitProfilesById[recruitId]!; expect(signCommittedRecruit(world, 'cycle', recruit.id)).toMatchObject({ ok: false }); const signingWorld = updateGameWorld(world, { recruitingCycles: Object.values(world.recruitingCyclesById).map((cycle) => ({ ...cycle, status: 'signing' })) }); const signed = signCommittedRecruit(signingWorld, 'cycle', recruit.id); expect(signed.ok).toBe(true); if (!signed.ok) return; const player = signed.value.players[recruit.playerId]!; expect(signed.value.teams[program]!.rosterPlayerIds).not.toContain(recruit.playerId); const arrived = arriveSignedRecruits(signed.value); expect(arrived.teams[program]!.rosterPlayerIds.filter((id) => id === recruit.playerId)).toHaveLength(1); expect(arrived.players[recruit.playerId]).toEqual(player); expect(arriveSignedRecruits(arrived).teams[program]!.rosterPlayerIds.filter((id) => id === recruit.playerId)).toHaveLength(1) })
  it('round-trips a committed and signed incoming class without regeneration', () => { const world = committed(); const recruit = world.recruitProfilesById[Object.values(world.recruitingCommitmentsById)[0]!.recruitId]!; const signingWorld = updateGameWorld(world, { recruitingCycles: Object.values(world.recruitingCyclesById).map((cycle) => ({ ...cycle, status: 'signing' })) }); const signed = signCommittedRecruit(signingWorld, 'cycle', recruit.id); if (!signed.ok) throw new Error('sign'); const loaded = deserializeGameWorldV1(serializeGameWorldV1(signed.value, '2032-10-02T00:00:00.000Z')); expect(loaded.recruitProfilesById).toEqual(signed.value.recruitProfilesById); expect(loaded.recruitSigningsById).toEqual(signed.value.recruitSigningsById); expect(loaded.teams[program]!.rosterPlayerIds).not.toContain(recruit.playerId); expect(getRecruitingClass(loaded, 'cycle', program).incoming).toHaveLength(1) })
})
