import { useState } from 'react'
import CompetitionPage from './CompetitionSectionPage'
import './CompetitionPcbPage.css'

const names = ['Real Madrid','Barca','Valencia Basket','Baskonia','Unicaja Malaga','Dreamland Gran Canaria','La Laguna Tenerife','Joventut Badalona','UCAM Murcia','Casademont Zaragoza','BAXI Manresa','Surne Bilbao Basket','MoraBanc Andorra','Recoletas Salud San Pablo Burgos','Hiopos Lleida','Basquet Girona','Rio Breogan','Coviran Granada']
const teams = names.map((name, index) => ({ id: `team-${index}`, name, data: { league_id: 'ACB', recent_results: [{ result: 'W' }, { result: index % 2 ? 'L' : 'W' }, { result: 'W' }], stats: { ppg: 87 - index, papg: 78 + index / 2, rpg: 35, apg: 19, fg_pct: 47, three_pct: 36 } } }))
const players = names.slice(0, 12).map((name, index) => ({ id: `player-${index}`, name: ['Sergio Llull','Kevin Punter','Jean Montero','Markus Howard','Kendrick Perry','Nico Brussino','Marcelinho Huertas','Ante Tomic','Dylan Ennis','Trae Bell-Haynes','Dani Perez','Melwin Pantzar'][index], data: { team_id: `team-${index}`, position: ['PG','SG','SF','PF','C'][index % 5], stats: { ppg: 21 - index / 2, apg: 7 - index / 5, rpg: 8 - index / 4, games_played: 18 } } }))
const fixtures = names.slice(0, 14).map((_, index) => ({ id: `acb-${index}`, date: '2025-10-04', homeId: `team-${index}`, awayId: `team-${(index + 15) % names.length}`, competition: 'liga' }))
const CALENDAR_MONTHS = ['Septiembre de 2025', 'Octubre de 2025', 'Noviembre de 2025']
const JORNADAS = [1, 2, 3].map((jornada) => ({ jornada, fixtures: fixtures.map((fixture, index) => ({ ...fixture, id: `${fixture.id}-j${jornada}`, homeId: `team-${(index + jornada - 1) % names.length}`, awayId: `team-${(index + jornada + 14) % names.length}` })) }))
const Calendar = () => { const [monthIndex, setMonthIndex] = useState(0); return <section className="bento competition-page"><div className="card competition-calendar"><div className="calendar-header"><div><div className="eyebrow">Liga Endesa</div><h2>Calendario</h2></div><div className="calendar-nav"><button className="subnav-item" disabled={monthIndex === 0} onClick={() => setMonthIndex((value) => Math.max(0, value - 1))} type="button">Anterior</button><div className="calendar-month">{CALENDAR_MONTHS[monthIndex]}</div><button className="subnav-item" disabled={monthIndex === CALENDAR_MONTHS.length - 1} onClick={() => setMonthIndex((value) => Math.min(CALENDAR_MONTHS.length - 1, value + 1))} type="button">Siguiente</button></div></div><div className="calendar-grid">{['Lun','Mar','Mie','Jue','Vie','Sab','Dom'].map((day) => <div className="calendar-weekday" key={day}>{day}</div>)}{Array.from({ length: 42 }, (_, index) => <div className="calendar-day" key={index}><div className="calendar-day-number">{index + 1}</div>{index === 32 && fixtures.slice(0, 3).map((fixture) => <div className="calendar-event simple" key={fixture.id}>{teams.find((team) => team.id === fixture.homeId)?.name} — {teams.find((team) => team.id === fixture.awayId)?.name}</div>)}</div>)}</div></div></section> }
const Results = () => { const [jornadaIndex, setJornadaIndex] = useState(0); const current = JORNADAS[jornadaIndex]!; return <section className="bento competition-page"><div className="card competition-jornadas"><div className="calendar-header"><div><div className="eyebrow">Liga Endesa</div><h2>Jornada {current.jornada}</h2></div></div><div className="jornada-controls"><button className="subnav-item" disabled={jornadaIndex === 0} onClick={() => setJornadaIndex((value) => Math.max(0, value - 1))} type="button">Jornada anterior</button><select onChange={(event) => setJornadaIndex(Number(event.target.value))} value={jornadaIndex}>{JORNADAS.map((item, index) => <option key={item.jornada} value={index}>Jornada {item.jornada}</option>)}</select><button className="subnav-item" disabled={jornadaIndex === JORNADAS.length - 1} onClick={() => setJornadaIndex((value) => Math.min(JORNADAS.length - 1, value + 1))} type="button">Jornada siguiente</button></div><div className="jornada-list">{current.fixtures.map((fixture) => <div className="jornada-item" key={fixture.id}><div className="jornada-date">{fixture.date}</div><div className="jornada-teams">{teams.find((team) => team.id === fixture.homeId)?.name}<span className="jornada-score">Pendiente</span>{teams.find((team) => team.id === fixture.awayId)?.name}</div></div>)}</div></div></section> }
const Standings = () => <section className="bento competition-page"><div className="card competition-standings"><div className="card-header"><h2>Clasificación ACB</h2><span className="tag muted">Liga Regular</span></div><div className="table standings-table"><div className="row head standings"><div>#</div><div>Equipo</div><div>W</div><div>L</div><div>PF</div><div>PA</div><div>Diff</div><div>Pct</div></div>{teams.map((team, index) => <div className="row standings" key={team.id}><div>{index + 1}</div><div>{team.name}</div><div>{14 - index * 2}</div><div>{4 + index * 2}</div><div>1498</div><div>1420</div><div>+78</div><div>.778</div></div>)}</div></div></section>

export function CompetitionPcbPage() {
  const [competitionView, setCompetitionView] = useState('calendar')
  const [selectedTeamId, setSelectedTeamId] = useState<string | null>(null)
  const [selectedPlayerId, setSelectedPlayerId] = useState<string | null>(null)
  const [simulatedResults, setSimulatedResults] = useState<Record<string, string>>({})
  const cupBrackets = { copa: { current_round: 'Cuartos', matches: fixtures.slice(0, 4).map((fixture) => ({ id: fixture.id, round: 'Cuartos', date: '2026-02-19', home: fixture.homeId, away: fixture.awayId, played: false })) }, supercopa: { current_round: 'Semifinales', matches: [] }, playoff: { current_round: 'Cuartos', matches: [] } }
  const selectedTeam = teams.find((team) => team.id === selectedTeamId)
  const selectedPlayer = players.find((player) => player.id === selectedPlayerId)
  const onSimulateMatch = (fixtureId: string) => { const fixture = fixtures.find((item) => item.id === fixtureId); if (fixture === undefined) return; const homeScore = 70 + (fixture.homeId.length % 20); const awayScore = 65 + (fixture.awayId.length % 20); setSimulatedResults((value) => ({ ...value, [fixtureId]: `${homeScore}-${awayScore}` })) }
  return <><CompetitionPage competitionView={competitionView} setCompetitionView={setCompetitionView} renderCalendar={() => <Calendar />} renderJornadas={() => <Results />} renderStandings={() => <Standings />} upcomingFixtures={fixtures} myTeamId="team-9" allTeams={teams} allPlayers={players} cupBrackets={cupBrackets} leagueId="ACB" onTeamClick={setSelectedTeamId} onPlayerClick={setSelectedPlayerId} onSimulateMatch={onSimulateMatch} />
    {selectedTeam && <aside className="pcb-competition__detail" aria-label="Detalle de equipo"><header><h3>{selectedTeam.name}</h3><button onClick={() => setSelectedTeamId(null)} type="button">Cerrar</button></header><dl><div><dt>PPG</dt><dd>{selectedTeam.data.stats.ppg}</dd></div><div><dt>PAPG</dt><dd>{selectedTeam.data.stats.papg}</dd></div><div><dt>REB</dt><dd>{selectedTeam.data.stats.rpg}</dd></div><div><dt>AST</dt><dd>{selectedTeam.data.stats.apg}</dd></div></dl></aside>}
    {selectedPlayer && <aside className="pcb-competition__detail" aria-label="Detalle de jugador"><header><h3>{selectedPlayer.name}</h3><button onClick={() => setSelectedPlayerId(null)} type="button">Cerrar</button></header><dl><div><dt>Posición</dt><dd>{selectedPlayer.data.position}</dd></div><div><dt>PPG</dt><dd>{selectedPlayer.data.stats.ppg}</dd></div><div><dt>APG</dt><dd>{selectedPlayer.data.stats.apg}</dd></div><div><dt>RPG</dt><dd>{selectedPlayer.data.stats.rpg}</dd></div></dl></aside>}
    {Object.keys(simulatedResults).length > 0 && <aside className="pcb-competition__detail" aria-label="Resultados simulados"><h3>Resultados simulados</h3><ul>{Object.entries(simulatedResults).map(([fixtureId, score]) => <li key={fixtureId}>{fixtureId}: {score}</li>)}</ul></aside>}
  </>
}
