import { createMemory, type MemoryRecord } from '@/domain/memory'
import { addMemoriesToGameWorld, applyRelationshipEventsToWorld, type GameWorld } from '@/domain/world'
import type { DirectedRelationshipEvent } from '@/domain/world/RelationshipEvents'
import type { StaffPoliticalAction } from '@/domain/staffPolitics'

const effects = { ENDORSE: { delta: 3, dimensions: { perceivedSupport: 6, trust: 3, professionalRespect: 2 }, memory: ['support', 'notable', 45, 45, 5, ['staff-politics', 'endorse', 'support']] }, SUPPORT_LOBBY: { delta: 5, dimensions: { perceivedSupport: 9, trust: 4, professionalRespect: 3, professionalAlignment: 2 }, memory: ['support', 'important', 65, 65, 4, ['staff-politics', 'lobby', 'support']] }, OPPOSE_LOBBY: { delta: -5, dimensions: { perceivedSupport: -9, trust: -5, professionalRespect: -2, professionalAlignment: -3 }, memory: ['trust', 'important', -60, 60, 4, ['staff-politics', 'lobby', 'oppose']] }, MEDIATE: { delta: 3, dimensions: { professionalRespect: 4, communicationQuality: 5, trust: 2 }, memory: ['trust', 'notable', 35, 40, 5, ['staff-politics', 'mediate']] }, COORDINATE: { delta: 2, dimensions: { collaboration: 3, professionalAlignment: 2, trust: 1 } } } as const
export function applyStaffPoliticalActionConsequences(world: GameWorld, actions: readonly StaffPoliticalAction[]): GameWorld {
  const events: DirectedRelationshipEvent[] = []; const memories: MemoryRecord[] = []; const pendingMemoryIds = new Set<string>()
  for (const action of actions) { const politicalCase = world.staffPoliticalCasesById[action.caseId]; if (politicalCase === undefined) continue; const subjectId = politicalCase.subjectStaffId
    if (action.kind === 'COORDINATE') { for (let i = 0; i < action.actorIds.length; i += 1) for (let j = i + 1; j < action.actorIds.length; j += 1) for (const [sourceId, targetId] of [[action.actorIds[i]!, action.actorIds[j]!], [action.actorIds[j]!, action.actorIds[i]!]] as const) events.push(event(action, sourceId, targetId, effects.COORDINATE)); continue }
    if (subjectId === undefined) continue; const actorId = action.actorIds[0]!; const effect = action.kind === 'ENDORSE' ? effects.ENDORSE : action.kind === 'MEDIATE' ? effects.MEDIATE : action.stance === 'SUPPORT' ? effects.SUPPORT_LOBBY : effects.OPPOSE_LOBBY; events.push(event(action, subjectId, actorId, effect)); const [type, importance, valence, intensity, decayPerMonth, tags] = effect.memory; const id = `memory:staff-politics:${action.id}:${subjectId}:${actorId}`; if (world.memoriesById[id] === undefined && !pendingMemoryIds.has(id)) { pendingMemoryIds.add(id); memories.push(createMemory({ id, owner: { kind: 'staff', id: subjectId }, type, occurredOn: action.performedOn, entityRefs: [{ kind: 'staff', id: actorId }, { kind: 'team', id: action.teamId }], sourceId: action.id, semanticKey: `staff-politics:${action.id}:${subjectId}:${actorId}`, importance, valence, intensity, decayPerMonth, permanent: false, tags, context: { politicalActionId: action.id, politicalCaseId: action.caseId, teamId: action.teamId, kind: action.kind, stance: action.stance } })) }
  }
  const related = applyRelationshipEventsToWorld(world, events); return memories.length === 0 ? related : addMemoriesToGameWorld(related, memories)
}
function event(action: StaffPoliticalAction, sourceId: string, targetId: string, effect: { readonly delta: number; readonly dimensions: object }) { return { sourceId, targetId, event: { id: `staff-politics:${action.id}:relationship:${sourceId}->${targetId}`, gameDate: action.performedOn, source: 'professionalInteraction' as const, delta: effect.delta, dimensionDeltas: effect.dimensions, context: { politicalActionId: action.id } } } }
