import { describe, expect, it } from 'vitest'
import { createNewGame } from '@/app/game/createNewGame'
import { getUserTeam } from '@/engine/calendar'
import { updateGameWorld } from '@/domain/world'
import { applyStaffConflictTrigger, progressStaffConflicts } from './StaffConflictEngine'

function fixture() { const world = createNewGame(); const team = getUserTeam(world)!; const staff = Object.values(world.teamStaffAssignmentsById).filter((item) => item.teamId === team.id).slice(0, 2).map((item) => item.staffPersonId); return { world, team, first: staff[0]!, second: staff[1]! } }
function trigger(world: ReturnType<typeof fixture>, pressure = 80) { return { id: 'trigger:conflict:one', occurredOn: world.world.currentDate, scopeKey: world.team.id as string, teamId: world.team.id as string, subjectActorId: world.first as string, counterpartActorId: world.second as string, type: 'PROFESSIONAL_METHOD' as const, cause: 'recommendationRejected' as const, basePressure: pressure, sourceKind: 'test' } }
describe('StaffConflictEngine', () => {
  it('does not create a conflict from a low trigger in a healthy relationship', () => { const value = fixture(); expect(Object.keys(applyStaffConflictTrigger(value.world, trigger(value, 30)).staffConflictsById)).toHaveLength(0) })
  it('gives the same important trigger different outcomes in unhealthy and genuinely healthy contexts', () => { const value = fixture(); const dimensions = (signal: number) => ({ trust: signal, professionalRespect: signal, communicationQuality: signal, collaboration: signal, personalCloseness: 0, perceivedSupport: signal, reliability: signal, professionalAlignment: signal }); const unhealthy = updateGameWorld(value.world, { relationshipsByKey: { [`${value.first}->${value.second}`]: { sourceId: value.first, targetId: value.second, value: -80, dimensions: dimensions(-80), events: [] }, [`${value.second}->${value.first}`]: { sourceId: value.second, targetId: value.first, value: -80, dimensions: dimensions(-80), events: [] } } }); const healthy = updateGameWorld(value.world, { relationshipsByKey: { [`${value.first}->${value.second}`]: { sourceId: value.first, targetId: value.second, value: 80, dimensions: dimensions(80), events: [] }, [`${value.second}->${value.first}`]: { sourceId: value.second, targetId: value.first, value: 80, dimensions: dimensions(80), events: [] } } }); expect(Object.keys(applyStaffConflictTrigger(unhealthy, trigger(value, 76)).staffConflictsById)).toHaveLength(1); expect(Object.keys(applyStaffConflictTrigger(healthy, trigger(value, 76)).staffConflictsById)).toHaveLength(0) })
  it('creates one sparse episode, groups related triggers, and is idempotent', () => { const value = fixture(); const first = applyStaffConflictTrigger(value.world, trigger(value)); const grouped = applyStaffConflictTrigger(first, { ...trigger(value), id: 'trigger:conflict:two', cause: 'methodDisagreement' }); const replay = applyStaffConflictTrigger(grouped, { ...trigger(value), id: 'trigger:conflict:two', cause: 'methodDisagreement' }); expect(Object.keys(grouped.staffConflictsById)).toHaveLength(1); expect(replay).toBe(grouped) })
  it('only changes professional relationship facets and never personalCloseness', () => { const value = fixture(); const next = applyStaffConflictTrigger(value.world, trigger(value)); expect(next.relationshipsByKey[`${value.first}->${value.second}`]!.dimensions!.personalCloseness).toBe(0) })
  it('does not progress resolved episodes', () => { const value = fixture(); const created = applyStaffConflictTrigger(value.world, trigger(value)); const conflict = Object.values(created.staffConflictsById)[0]!; const resolved = updateGameWorld(created, { staffConflicts: [{ ...conflict, status: 'RESOLVED', stage: 'RESOLVED', resolvedOn: created.currentDate, resolution: { type: 'FADED', resolvedOn: created.currentDate } }] }); expect(progressStaffConflicts(resolved).staffConflictsById[conflict.id]).toEqual(resolved.staffConflictsById[conflict.id]) })
  it('suppresses an ordinary same-pair episode during resolved cooldown without mutating the old one', () => { const value = fixture(); const created = applyStaffConflictTrigger(value.world, trigger(value)); const conflict = Object.values(created.staffConflictsById)[0]!; const resolved = updateGameWorld(created, { staffConflicts: [{ ...conflict, status: 'RESOLVED', stage: 'RESOLVED', resolvedOn: created.currentDate, resolution: { type: 'FADED', resolvedOn: created.currentDate } }] }); const next = applyStaffConflictTrigger(resolved, { ...trigger(value, 80), id: 'trigger:cooldown', occurredOn: addDays(resolved.currentDate, 10) as never }); expect(next).toBe(resolved); expect(next.staffConflictsById[conflict.id]).toEqual(resolved.staffConflictsById[conflict.id]) })
  it('allows a severe new episode after cooldown or through the explicit bypass', () => { const value = fixture(); const created = applyStaffConflictTrigger(value.world, trigger(value)); const conflict = Object.values(created.staffConflictsById)[0]!; const resolved = updateGameWorld(created, { staffConflicts: [{ ...conflict, status: 'RESOLVED', stage: 'RESOLVED', resolvedOn: created.currentDate, resolution: { type: 'FADED', resolvedOn: created.currentDate } }] }); const bypass = applyStaffConflictTrigger(resolved, { ...trigger(value, 100), id: 'trigger:bypass', occurredOn: addDays(resolved.currentDate, 10) as never }); expect(Object.keys(bypass.staffConflictsById)).toHaveLength(2); expect(Object.keys(bypass.staffConflictsById).find((id) => id !== conflict.id)).toBeDefined(); const later = applyStaffConflictTrigger(resolved, { ...trigger(value, 80), id: 'trigger:later', occurredOn: addDays(resolved.currentDate, 31) as never }); expect(Object.keys(later.staffConflictsById)).toHaveLength(2) })
  it('only records escalation when lifecycle actually transitions to ESCALATING', () => { const value = fixture(); const first = applyStaffConflictTrigger(value.world, trigger(value, 68)); const moderate = applyStaffConflictTrigger(first, { ...trigger(value, 68), id: 'trigger:moderate' }); expect(Object.values(moderate.memoriesById).some((memory) => memory.semanticKey.includes(':escalated'))).toBe(false); const severe = applyStaffConflictTrigger(moderate, { ...trigger(value, 100), id: 'trigger:severe' }); const escalated = Object.values(severe.memoriesById).filter((memory) => memory.semanticKey.includes(':escalated')); expect(escalated).toHaveLength(2); const later = applyStaffConflictTrigger(severe, { ...trigger(value, 100), id: 'trigger:later-severe' }); expect(Object.values(later.memoriesById).filter((memory) => memory.semanticKey.includes(':escalated'))).toHaveLength(2) })
})
function addDays(date: string, days: number): string { const value = new Date(`${date}T00:00:00Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0, 10) }
