import { createBoardState, getJobSecurity, type BoardObjective, type BoardOutcome, type BoardProfile, type BoardState } from '@/domain/board'
import type { TeamId } from '@/domain/ids'
import { updateGameWorld, type GameWorld } from '@/domain/world'
import { calculateStandings } from '@/engine/competition/standings'
import { recordMemory } from '@/engine/memory'

export type BoardRecommendation = 'renew' | 'wait' | 'doNotRenew'
export const BOARD_CONFIG={initialConfidence:60,maxReasons:12,impacts:{exceptional:14,exceeded:8,met:3,nearMiss:-3,failed:-9,severelyFailed:-16}} as const
export function deriveBoardProfile(world:GameWorld,teamId:TeamId):BoardProfile{const team=world.teams[teamId]!;const historical=Object.values(world.seasonHistoryBySeasonId).filter((item)=>item.championTeamId===teamId).length;const seed=[...team.id].reduce((a,c)=>a+c.charCodeAt(0),0);return{ambition:Math.min(95,45+historical*12+seed%20),patience:35+seed%51,stability:40+seed%41,resultsFocus:55+seed%36,developmentFocus:30+seed%46,prestigeFocus:35+historical*15+seed%26}}
export function calculateExpectationBaseline(world:GameWorld,teamId:TeamId,seasonId:string):number{const season=world.seasons[seasonId as keyof typeof world.seasons]!;const teams=world.competitions[season.competitionId]!.participantTeamIds;const prior=Object.values(world.seasonHistoryBySeasonId).filter((item)=>world.seasons[item.seasonId]?.competitionId===season.competitionId).sort((a,b)=>b.completedOn.localeCompare(a.completedOn))[0];const previous=prior?.finalStandings.find((line)=>line.teamId===teamId)?.position;return previous??Math.ceil(teams.length/2)}
export function initializeBoardState(world:GameWorld,teamId:TeamId):GameWorld{const team=world.teams[teamId];if(team?.coachId===undefined||world.boardStatesByTeamId[teamId]!==undefined)return world;const season=Object.values(world.seasons).find((item)=>world.competitions[item.competitionId]?.participantTeamIds.includes(teamId));if(!season)return world;const baseline=calculateExpectationBaseline(world,teamId,season.id);const profile=deriveBoardProfile(world,teamId);const objective=generateObjective(teamId,season.id,baseline,world.competitions[season.competitionId]!.participantTeamIds.length);const state=createBoardState({teamId,coachId:team.coachId,startedOn:world.currentDate,profile,expectation:{summary:objective.label,baselinePosition:baseline,seasonId:season.id},objectives:[objective],confidence:BOARD_CONFIG.initialConfidence,reasons:[],processedEventKeys:[]});return updateGameWorld(world,{boardStatesByTeamId:{...world.boardStatesByTeamId,[teamId]:state}})}
export function generateObjective(teamId:TeamId,seasonId:any,baseline:number,size:number):BoardObjective{if(baseline>=size-1)return{id:`board:${teamId}:${seasonId}:survival`,kind:'avoidRelegation',label:'Avoid relegation',priority:'critical',horizon:'season',seasonId,targetPosition:size-2,outcome:'inProgress'};if(baseline<=2)return{id:`board:${teamId}:${seasonId}:title`,kind:'winChampionship',label:'Win the championship',priority:'critical',horizon:'season',seasonId,outcome:'inProgress'};return{id:`board:${teamId}:${seasonId}:placement`,kind:'reachTopPosition',label:`Finish in the top ${baseline}`,priority:'high',horizon:'season',seasonId,targetPosition:baseline,outcome:'inProgress'}}
export function evaluateObjective(objective:BoardObjective,position:number,size:number):BoardOutcome{if(objective.kind==='winChampionship')return position===1?'met':position===2?'nearMiss':position<=Math.ceil(size/2)?'failed':'severelyFailed';const target=objective.targetPosition??size-2;if(position<=target-3)return'exceptional';if(position<target)return'exceeded';if(position===target)return'met';if(position===target+1)return'nearMiss';return position<=target+3?'failed':'severelyFailed'}
export function evaluateBoardSeason(world:GameWorld,teamId:TeamId,seasonId:string):GameWorld{const state=world.boardStatesByTeamId[teamId],season=world.seasons[seasonId as keyof typeof world.seasons];if(!state||!season)return world;const key=`board:season:${teamId}:${seasonId}`;if(state.processedEventKeys.includes(key))return world;const standings=calculateStandings(world,season.id);const position=standings.find((line)=>line.teamId===teamId)?.position;if(!position)return world;const objectives=state.objectives.map((item)=>item.seasonId===season.id?{...item,outcome:evaluateObjective(item,position,standings.length)}:item);const outcomes=objectives.filter((item)=>item.seasonId===season.id);const raw=outcomes.reduce((sum,item)=>sum+(item.outcome==='inProgress'?0:BOARD_CONFIG.impacts[item.outcome]),0);const patience=Math.round((state.profile.patience-50)/10);const delta=raw<0?raw+patience:raw;const next=createBoardState({...state,objectives,confidence:Math.max(0,Math.min(100,state.confidence+delta)),reasons:[...state.reasons,{id:key,date:world.currentDate,delta,code:'seasonEvaluation',detail:outcomes.map((item)=>`${item.id}:${item.outcome}`).join(',')}].slice(-BOARD_CONFIG.maxReasons),processedEventKeys:[...state.processedEventKeys,key]});const updated=updateGameWorld(world,{boardStatesByTeamId:{...world.boardStatesByTeamId,[teamId]:next}});const extreme=outcomes.find((item)=>item.outcome==='exceptional'||item.priority==='critical'&&item.outcome==='severelyFailed');return extreme===undefined?updated:recordMemory(updated,{id:`memory:${key}:${extreme.id}`,owner:{kind:'team',id:teamId},type:extreme.outcome==='exceptional'?'historicSeason':'majorDefeat',occurredOn:updated.currentDate,entityRefs:[{kind:'coach',id:state.coachId}],semanticKey:`${key}:${extreme.id}`,importance:'major',valence:extreme.outcome==='exceptional'?80:-80,intensity:80,decayPerMonth:1,permanent:false,tags:['board','objective'],context:{seasonId,objectiveId:extreme.id,outcome:extreme.outcome}})}
export function rolloverBoardState(world:GameWorld,teamId:TeamId,nextSeasonId:string):GameWorld{const state=world.boardStatesByTeamId[teamId],season=world.seasons[nextSeasonId as keyof typeof world.seasons];if(!state||!season)return world;const key=`board:rollover:${teamId}:${nextSeasonId}`;if(state.processedEventKeys.includes(key))return world;const size=world.competitions[season.competitionId]!.participantTeamIds.length;const promoted=Object.values(world.promotionRelegationResolutionsById).some((item)=>item.promotedTeamIds.includes(teamId));const baseline=promoted?Math.max(2,size-1):calculateExpectationBaseline(world,teamId,season.id);const objective=generateObjective(teamId,season.id,baseline,size);const next=createBoardState({...state,expectation:{summary:objective.label,baselinePosition:baseline,seasonId:season.id},objectives:[...state.objectives,objective],reasons:[...state.reasons,{id:key,date:world.currentDate,delta:0,code:promoted?'newlyPromoted':'seasonRollover',detail:objective.label}].slice(-BOARD_CONFIG.maxReasons),processedEventKeys:[...state.processedEventKeys,key]});return updateGameWorld(world,{boardStatesByTeamId:{...world.boardStatesByTeamId,[teamId]:next}})}
export function applyBoardTierMovement(world:GameWorld,teamId:TeamId):GameWorld{const state=world.boardStatesByTeamId[teamId];if(!state)return world;const resolution=Object.values(world.promotionRelegationResolutionsById).find((item)=>item.promotedTeamIds.includes(teamId)||item.relegatedTeamIds.includes(teamId));if(!resolution)return world;const promoted=resolution.promotedTeamIds.includes(teamId);const key=`board:tier:${resolution.id}:${teamId}`;if(state.processedEventKeys.includes(key))return world;const unexpected=promoted&&state.expectation.baselinePosition>2;const delta=promoted?(unexpected?16:10):-(state.expectation.baselinePosition>=6?8:18)+Math.round((state.profile.patience-50)/10);const outcome:BoardOutcome=promoted?(unexpected?'exceptional':'met'):(state.expectation.baselinePosition>=6?'failed':'severelyFailed');const objectives=state.objectives.map((item)=>item.outcome==='inProgress'&&((promoted&&item.kind==='earnPromotion')||(!promoted&&item.kind==='avoidRelegation'))?{...item,outcome}:item);const next=createBoardState({...state,objectives,confidence:Math.max(0,Math.min(100,state.confidence+delta)),reasons:[...state.reasons,{id:key,date:resolution.resolvedDate,delta,code:promoted?'promotion':'relegation',detail:outcome}].slice(-BOARD_CONFIG.maxReasons),processedEventKeys:[...state.processedEventKeys,key]});return updateGameWorld(world,{boardStatesByTeamId:{...world.boardStatesByTeamId,[teamId]:next}})}
export function evaluateFiringRisk(state:BoardState):boolean{return getJobSecurity(state)==='critical'&&state.objectives.some((item)=>item.priority==='critical'&&item.outcome==='severelyFailed')}
export function evaluateRenewalRecommendation(state:BoardState):BoardRecommendation{return state.confidence>=75&&state.objectives.some((item)=>['met','exceeded','exceptional'].includes(item.outcome))?'renew':getJobSecurity(state)==='critical'?'doNotRenew':'wait'}
export function getBoardSummary(world:GameWorld,teamId:TeamId){const state=world.boardStatesByTeamId[teamId];return state===undefined?undefined:{state,jobSecurity:getJobSecurity(state)}}
