import { describe, expect, it } from 'vitest'
import { createNewGame } from '@/app/game'
import { updateGameWorld } from '@/domain/world'
import { acceptNilOpportunity, createNilOpportunity, ensureNcaaNil, marketabilityForPlayer, nilRecruitingAppeal } from './NilEngine'

describe('NIL and collectives', () => {
  it('initializes deterministic NCAA-only profiles and collectives', () => { const world = createNewGame(), again = ensureNcaaNil(world); expect(again).toBe(world); expect(Object.values(world.nilProfilesById).every((p) => world.ecosystems[p.ecosystemId]!.kind === 'ncaaLike')).toBe(true); expect(Object.values(world.collectivesById)).not.toHaveLength(0); const profile = Object.values(world.nilProfilesById)[0]!; expect(marketabilityForPlayer(world, profile.playerId)).toBe(profile.marketability) })
  it('creates, accepts and closes NIL deals without salary contracts or payroll state', () => { const world = createNewGame(), profile = Object.values(world.nilProfilesById)[0]!, beforeContracts = Object.keys(world.contractsById); const created = createNilOpportunity(world, profile.playerId); expect(created.ok).toBe(true); if (!created.ok) return; const accepted = acceptNilOpportunity(created.value, Object.keys(created.value.nilOpportunitiesById)[0]!); expect(accepted.ok).toBe(true); if (!accepted.ok) return; expect(Object.values(accepted.value.nilDealsById)).toHaveLength(1); expect(Object.keys(accepted.value.contractsById)).toEqual(beforeContracts) })
  it('consumes collective resources and respects recruiting appeal configuration', () => { const world = createNewGame(), profile = Object.values(world.nilProfilesById)[0]!, collective = Object.values(world.collectivesById).find((c) => c.programTeamId === profile.programTeamId)!; const created = createNilOpportunity(world, profile.playerId, 'collectiveBacked', collective.id); expect(created.ok).toBe(true); if (!created.ok) return; const accepted = acceptNilOpportunity(created.value, Object.keys(created.value.nilOpportunitiesById)[0]!); expect(accepted.ok).toBe(true); if (!accepted.ok) return; expect(accepted.value.collectivesById[collective.id]!.resourcesRemaining).toBeLessThan(collective.resourcesRemaining); const configured = updateGameWorld(accepted.value, { nilRulesByEcosystemId: { ...accepted.value.nilRulesByEcosystemId, [profile.ecosystemId]: { ...accepted.value.nilRulesByEcosystemId[profile.ecosystemId]!, recruitingAppealFactor: 10 } } }); expect(nilRecruitingAppeal(configured, profile.programTeamId, profile.ecosystemId)).toBeGreaterThan(0) })
})
