import { addDays, compareGameDates } from '@/domain/date'
import type { EcosystemId, PlayerId, TeamId } from '@/domain/ids'
import { defaultNilRules, type NilOpportunityType, type NilRules } from '@/domain/nil'
import { updateGameWorld, type GameWorld } from '@/domain/world'
import { isNilRestricted } from '@/engine/enforcement'

const hash = (value: string) => [...value].reduce((n, c) => ((n * 31) + c.charCodeAt(0)) >>> 0, 17)
const profileId = (ecosystemId: EcosystemId, teamId: TeamId, playerId: PlayerId) => `nil-profile:${ecosystemId}:${teamId}:${playerId}`
const collectiveId = (ecosystemId: EcosystemId, teamId: TeamId) => `collective:${ecosystemId}:${teamId}`
export function marketabilityForPlayer(world: GameWorld, playerId: PlayerId): number { const player = world.players[playerId]; if (!player) return 0; const ratings = Object.values(player.basketball.ratings); return Math.max(20, Math.min(95, Math.round(ratings.reduce((sum, value) => sum + value, 0) / ratings.length * .7 + hash(`${player.id}:${player.firstName}:${player.lastName}`) % 31))) }
export function ensureNcaaNil(world: GameWorld): GameWorld { const profiles = Object.values(world.nilProfilesById), collectives = Object.values(world.collectivesById), rules = { ...world.nilRulesByEcosystemId }, addProfiles: any[] = [], addCollectives: any[] = []; for (const competition of Object.values(world.competitions)) { const ecosystem = world.ecosystems[competition.ecosystemId]; if (ecosystem?.kind !== 'ncaaLike') continue; rules[ecosystem.id] ??= defaultNilRules(ecosystem.id); for (const teamId of competition.participantTeamIds) { const team = world.teams[teamId]!, cid = collectiveId(ecosystem.id, teamId); if (!collectives.some((item) => item.id === cid)) addCollectives.push({ id: cid, ecosystemId: ecosystem.id, programTeamId: teamId, name: `${team.name} Collective`, resourceCapacity: 100, resourcesRemaining: 100 }); for (const playerId of team.rosterPlayerIds) if (!profiles.some((item) => item.id === profileId(ecosystem.id, teamId, playerId))) addProfiles.push({ id: profileId(ecosystem.id, teamId, playerId), playerId, ecosystemId: ecosystem.id, programTeamId: teamId, marketability: marketabilityForPlayer(world, playerId) }) } }; return addProfiles.length || addCollectives.length || Object.keys(rules).length !== Object.keys(world.nilRulesByEcosystemId).length ? updateGameWorld(world, { nilRulesByEcosystemId: rules, nilProfiles: [...profiles, ...addProfiles], collectives: [...collectives, ...addCollectives] }) : world }
export function initializeNilProfile(world: GameWorld, playerId: PlayerId, teamId: TeamId, ecosystemId: EcosystemId): GameWorld { if (world.ecosystems[ecosystemId]?.kind !== 'ncaaLike') return world; const id = profileId(ecosystemId, teamId, playerId); if (world.nilProfilesById[id]) return world; return ensureNcaaNil(updateGameWorld(world, { nilRulesByEcosystemId: { ...world.nilRulesByEcosystemId, [ecosystemId]: world.nilRulesByEcosystemId[ecosystemId] ?? defaultNilRules(ecosystemId) }, nilProfiles: [...Object.values(world.nilProfilesById), { id, playerId, ecosystemId, programTeamId: teamId, marketability: marketabilityForPlayer(world, playerId) }] })) }
export function createNilOpportunity(world: GameWorld, playerId: PlayerId, type: NilOpportunityType = 'localEndorsement', collectiveIdValue?: string) { const profile = Object.values(world.nilProfilesById).find((item) => item.playerId === playerId); if (!profile) return { ok: false as const, reason: 'NIL_PROFILE_UNAVAILABLE' }; const rules = world.nilRulesByEcosystemId[profile.ecosystemId] ?? defaultNilRules(profile.ecosystemId); if (!rules.enabled || isNilRestricted(world, profile.programTeamId)) return { ok: false as const, reason: 'NIL_DISABLED' }; const collective = collectiveIdValue === undefined ? undefined : world.collectivesById[collectiveIdValue]; if (type === 'collectiveBacked' && (!rules.collectiveParticipation || !collective || collective.programTeamId !== profile.programTeamId)) return { ok: false as const, reason: 'COLLECTIVE_UNAVAILABLE' }; const id = `nil-opportunity:${world.currentDate}:${playerId}:${type}:${Object.keys(world.nilOpportunitiesById).length + 1}`, resourceCost = type === 'collectiveBacked' ? Math.max(5, Math.round(profile.marketability / 4)) : undefined; return { ok: true as const, value: updateGameWorld(world, { nilOpportunities: [...Object.values(world.nilOpportunitiesById), { id, playerId, type, estimatedValue: Math.max(100, profile.marketability * (type === 'collectiveBacked' ? 20 : 12)), durationDays: rules.dealDurationDays, status: 'available', createdAt: world.currentDate, expiresAt: addDays(world.currentDate, 7), ...(collective ? { collectiveId: collective.id, resourceCost } : {}) }] }) } }
export function acceptNilOpportunity(world: GameWorld, opportunityId: string) { const opportunity = world.nilOpportunitiesById[opportunityId]; if (!opportunity || opportunity.status !== 'available') return { ok: false as const, reason: 'NIL_OPPORTUNITY_UNAVAILABLE' }; if (compareGameDates(world.currentDate, opportunity.expiresAt) > 0) return { ok: false as const, reason: 'NIL_OPPORTUNITY_EXPIRED' }; const profile = Object.values(world.nilProfilesById).find((item) => item.playerId === opportunity.playerId); if (!profile) return { ok: false as const, reason: 'NIL_PROFILE_UNAVAILABLE' }; const rules = world.nilRulesByEcosystemId[profile.ecosystemId] ?? defaultNilRules(profile.ecosystemId); if (Object.values(world.nilDealsById).filter((deal) => deal.playerId === opportunity.playerId && deal.status === 'active').length >= rules.maxActiveDeals) return { ok: false as const, reason: 'NIL_ACTIVE_DEAL_LIMIT' }; let collectives = Object.values(world.collectivesById); if (opportunity.collectiveId) { const collective = world.collectivesById[opportunity.collectiveId], cost = opportunity.resourceCost ?? 0; if (!collective || collective.resourcesRemaining < cost) return { ok: false as const, reason: 'COLLECTIVE_RESOURCES_EXHAUSTED' }; collectives = collectives.map((item) => item.id === collective.id ? { ...item, resourcesRemaining: item.resourcesRemaining - cost } : item) }; const deal = { id: `nil-deal:${opportunity.id}`, playerId: opportunity.playerId, opportunityId: opportunity.id, type: opportunity.type, value: opportunity.estimatedValue, startsAt: world.currentDate, endsAt: addDays(world.currentDate, opportunity.durationDays), status: 'active' as const }; return { ok: true as const, value: updateGameWorld(world, { collectives, nilOpportunities: Object.values(world.nilOpportunitiesById).map((item) => item.id === opportunity.id ? { ...item, status: 'accepted' as const } : item), nilDeals: [...Object.values(world.nilDealsById), deal] }) } }
export function progressNilLifecycle(world: GameWorld): GameWorld { const oldOpportunities = Object.values(world.nilOpportunitiesById), oldDeals = Object.values(world.nilDealsById), opportunities = oldOpportunities.map((item) => item.status === 'available' && compareGameDates(world.currentDate, item.expiresAt) > 0 ? { ...item, status: 'expired' as const } : item), deals = oldDeals.map((item) => item.status === 'active' && compareGameDates(world.currentDate, item.endsAt) > 0 ? { ...item, status: 'completed' as const } : item); return opportunities.some((item, index) => item !== oldOpportunities[index]) || deals.some((item, index) => item !== oldDeals[index]) ? updateGameWorld(world, { nilOpportunities: opportunities, nilDeals: deals }) : world }
export function progressAiNil(world: GameWorld): GameWorld { let next = world; const userTeam = Object.values(world.teams).find((team) => team.coachId === world.userCoachId)?.id; for (const profile of Object.values(next.nilProfilesById).filter((item) => item.programTeamId !== userTeam).sort((a, b) => b.marketability - a.marketability || a.playerId.localeCompare(b.playerId))) { const collective = Object.values(next.collectivesById).find((item) => item.programTeamId === profile.programTeamId), created = createNilOpportunity(next, profile.playerId, collective ? 'collectiveBacked' : 'localEndorsement', collective?.id); if (created.ok) { const id = Object.values(created.value.nilOpportunitiesById).at(-1)!.id, accepted = acceptNilOpportunity(created.value, id); next = accepted.ok ? accepted.value : created.value } }; return next }
export function nilRecruitingAppeal(world: GameWorld, teamId: TeamId, ecosystemId: EcosystemId): number { const rules: NilRules = world.nilRulesByEcosystemId[ecosystemId] ?? defaultNilRules(ecosystemId); if (!rules.enabled || rules.recruitingAppealFactor === 0) return 0; const collective = Object.values(world.collectivesById).find((item) => item.ecosystemId === ecosystemId && item.programTeamId === teamId); return collective ? Math.round(collective.resourcesRemaining / collective.resourceCapacity * rules.recruitingAppealFactor) : 0 }
