import { COACH_REPUTATION_DIMENSIONS, getCoachReputationBand, getRecentCoachReputationEvents } from '@/domain/coachReputation'
import type { CoachPerkId, CoachSkillId } from '@/domain/ids'
import type { GameWorld } from '@/domain/world'
import { COACH_PERK_CATALOG, COACH_SKILL_CATALOG } from '@/engine/coach'
import { coachReputationBandLabel, coachReputationEventLabel, coachReputationSourceLabel, formatCoachReputationDelta } from '@/ui/coachReputationPresentation'
import { formatPrototypeDate } from '@/ui/formatters'
import { STAFF_PROFESSIONAL_ATTRIBUTE_LABELS } from '@/ui/staffPresentation'
import { getRelationshipBandForPeople, getRelationshipsForPerson } from '@/domain/world'
import { getMoraleBand } from '@/domain/morale'
import { evaluateCoachJobEligibility } from '@/domain/coachCareer'

const REPUTATION_DIMENSION_LABELS = { competitive: 'Competitive', development: 'Development', professional: 'Professional', publicStanding: 'Public Standing' } as const

export function CoachScreen({ world, onSkill, onPerk, onApply = () => undefined, onAcceptOffer = () => undefined, onDeclineOffer = () => undefined }: { readonly world: GameWorld; readonly onSkill: (id: CoachSkillId) => void; readonly onPerk: (id: CoachPerkId) => void; readonly onApply?: (id: string) => void; readonly onAcceptOffer?: (id: string) => void; readonly onDeclineOffer?: (id: string) => void }) {
  const coach=world.coaches[world.userCoachId], professional=world.coachProfessionalProfilesByCoachId[world.userCoachId], rpg=world.coachRpgProfilesByCoachId[world.userCoachId], reputation=world.coachReputationProfilesByCoachId[world.userCoachId]
  if (!coach || !professional || !rpg || !reputation) return <section className="screen"><p className="content-panel">COACH PROFILE UNAVAILABLE</p></section>
  const focus=COACH_PERK_CATALOG.filter(x=>x.type==='careerFocus'&&rpg.perks[x.id]).length
  const recentEvents=getRecentCoachReputationEvents(reputation,5)
  const employment=world.coachEmploymentByCoachId[world.userCoachId], history=world.coachCareerHistoryByCoachId[world.userCoachId]??[], offers=Object.values(world.coachJobOffersById).filter(offer=>offer.coachId===world.userCoachId), candidacies=Object.values(world.coachJobCandidaciesById).filter(candidacy=>candidacy.coachId===world.userCoachId&&['identified','interviewing','offered'].includes(candidacy.status))
  const relationships=getRelationshipsForPerson(world,world.userCoachId)
  const morale=world.moraleByPersonId[world.userCoachId], personality=world.personalitiesByPersonId[world.userCoachId]
  const personName=(id:string)=>{const player=world.players[id as keyof typeof world.players];if(player)return `${player.firstName} ${player.lastName}`;const staff=world.staffPeopleById[id as keyof typeof world.staffPeopleById];if(staff)return `${staff.identity.firstName} ${staff.identity.lastName}`;const otherCoach=world.coaches[id as keyof typeof world.coaches];return otherCoach?`${otherCoach.firstName} ${otherCoach.lastName}`:id}
  const personType=(id:string)=>world.players[id as keyof typeof world.players]?'Player':world.staffPeopleById[id as keyof typeof world.staffPeopleById]?'Staff':'Coach'
  const opportunityContext=(teamId:string)=>{const competition=Object.values(world.competitions).find((item)=>item.participantTeamIds.includes(teamId as never));const ecosystem=competition===undefined?undefined:world.ecosystems[competition.ecosystemId];return `${ecosystem?.name ?? 'Unknown ecosystem'} · ${world.teams[teamId as keyof typeof world.teams]?.name ?? teamId}`}
  return <section className="screen"><div className="page-heading"><div><p className="eyebrow">COACH</p><h1>{coach.firstName} {coach.lastName}</h1></div><span>{rpg.development.developmentPoints} DEVELOPMENT POINTS</span></div>
    <section className="content-panel"><p>GLOBAL PROGRESS {rpg.development.globalProgress} / 100 · CAREER FOCUS {focus} / 2</p><h2>PROFESSIONAL ATTRIBUTES</h2><dl className="staff-attributes">{Object.entries(professional.attributes).map(([key,value])=><div key={key}><dt>{STAFF_PROFESSIONAL_ATTRIBUTE_LABELS[key as keyof typeof STAFF_PROFESSIONAL_ATTRIBUTE_LABELS]}</dt><dd>{value}</dd></div>)}</dl></section>
    <section className="content-panel"><h2>MORALE</h2><p>{morale?.value} / 100 · {morale&&getMoraleBand(morale.value)}</p><h3>PERSONALITY</h3><p>{personality&&Object.entries(personality.values).map(([key,value])=>`${key} ${value}`).join(' · ')}</p></section>
    <section className="content-panel"><h2>REPUTATION</h2><div className="reputation-dimensions">{COACH_REPUTATION_DIMENSIONS.map((dimension)=>{const value=reputation.values[dimension],band=getCoachReputationBand(value);return <article className="reputation-dimension" key={dimension}><div><strong>{REPUTATION_DIMENSION_LABELS[dimension]}</strong><span>{coachReputationBandLabel(band)}</span></div><progress value={value} max={1000} aria-label={`${REPUTATION_DIMENSION_LABELS[dimension]} reputation: ${value} of 1000, ${coachReputationBandLabel(band)}`} /><p>{value} / 1000</p></article>})}</div></section>
    <section className="content-panel"><h2>CAREER</h2><h3>Current Employment</h3><p>{employment?.status==='employed'?<>Employed by {world.teams[employment.teamId!]!.name} since {formatPrototypeDate(employment.startedOn!)}</>:'Unemployed'}</p><h3>Career History</h3>{history.length===0?<p>No prior career history.</p>:<ul>{history.map((entry,index)=><li key={`${entry.date}:${index}`}>{formatPrototypeDate(entry.date)} · {world.teams[entry.teamId]!.name} · {entry.reason==='initialAppointment'?'Initial Appointment':entry.reason==='acceptedOtherJob'?'Left for Another Job':entry.reason==='hired'?'Hired':'Fired'}</li>)}</ul>}<h3>Pending Offers</h3>{offers.length===0?<p>No pending offers.</p>:offers.map(offer=><p key={offer.id}>{world.teams[offer.teamId]!.name} · {offer.status} · {formatPrototypeDate(offer.createdOn)} {offer.status==='pending'&&<><button type="button" onClick={()=>onAcceptOffer(offer.id)}>Accept</button><button type="button" onClick={()=>onDeclineOffer(offer.id)}>Decline</button></>}</p>)}<h3>Active Career Processes</h3>{candidacies.length===0?<p>No active career processes.</p>:<ul>{candidacies.map(candidacy=><li key={candidacy.id}>{world.teams[world.coachJobOpeningsById[candidacy.jobOpeningId]!.teamId]!.name} · {candidacy.status}{world.coachInterviewsByCandidacyId[candidacy.id]&&` · Interview ${world.coachInterviewsByCandidacyId[candidacy.id]!.status}`}</li>)}</ul>}</section>
    <section className="content-panel"><h2>GLOBAL OPPORTUNITIES</h2>{Object.values(world.coachJobOpeningsById).filter((opening)=>opening.status==='open').length===0?<p>No global opportunities.</p>:<ul>{Object.values(world.coachJobOpeningsById).filter((opening)=>opening.status==='open').map((opening)=>{const applied=candidacies.some((item)=>item.jobOpeningId===opening.id), ecosystem=opening.ecosystemId===undefined?undefined:world.ecosystems[opening.ecosystemId], eligibility=evaluateCoachJobEligibility(world.coachEmploymentByCoachId[world.userCoachId]!,reputation,opening); return <li key={opening.id}>{world.teams[opening.teamId]!.name} · {ecosystem?.kind ?? 'Unknown'} · {opening.sportsCategory ?? 'Unknown'} · {opening.role ?? 'headCoach'} · {applied?'Applied':<button type="button" disabled={!eligibility.eligible} title={eligibility.eligible?'Eligible':eligibility.reasons.map((reason)=>reason.reason).join(', ')} onClick={()=>onApply(opening.id)}>Apply</button>}</li>})}</ul>}</section>
    <section className="content-panel"><h2>RECENT REPUTATION CHANGES</h2>{recentEvents.length===0?<p>No reputation changes yet.</p>:<div className="reputation-events">{recentEvents.map(event=><article key={event.id} className="reputation-event"><time>{formatPrototypeDate(event.gameDate as import('@/domain/date').GameDate)}</time><div><strong>{coachReputationEventLabel(world,event)}</strong><span>{coachReputationSourceLabel(event.source)}</span></div><p>{Object.entries(event.deltas).map(([dimension,delta])=><span className={delta!>0?'reputation-positive':delta!<0?'reputation-negative':''} key={dimension}>{REPUTATION_DIMENSION_LABELS[dimension as keyof typeof REPUTATION_DIMENSION_LABELS]} {formatCoachReputationDelta(delta!)}</span>)}</p></article>)}</div>}</section>
    <section className="content-panel"><h2>RELATIONSHIPS</h2>{relationships.length===0?<p>No materialized relationships.</p>:<ul>{relationships.map(profile=>{const otherId=profile.sourceId===world.userCoachId?profile.targetId:profile.sourceId;return <li key={`${profile.sourceId}->${profile.targetId}`}>{personName(otherId)} · {personType(otherId)} · {profile.value} · {getRelationshipBandForPeople(world,profile.sourceId,profile.targetId)}</li>})}</ul>}</section>
    <section className="content-panel"><h2>SKILLS</h2>{COACH_SKILL_CATALOG.map(s=>{const rank=rpg.skills[s.id]?.rank??0;return <p key={s.id}>{s.id} · Rank {rank} · {s.primaryAttribute} <button type="button" disabled={rank===3} onClick={()=>onSkill(s.id)}>DEVELOP</button></p>})}</section>
    <section className="content-panel"><h2>PROFESSIONAL TRAITS</h2><p>{rpg.professionalTraits.length?rpg.professionalTraits.join(', '):'No traits acquired'}</p></section>
    <section className="content-panel"><h2>PERKS</h2>{COACH_PERK_CATALOG.map(p=><p key={p.id}>{p.id} · {p.type} · {p.cost} DP {rpg.perks[p.id]?'OWNED':<button type="button" onClick={()=>onPerk(p.id)}>PURCHASE</button>}</p>)}</section>
  </section>
}
