import { useState } from 'react'
import { COACH_REPUTATION_DIMENSIONS, getCoachReputationBand, getRecentCoachReputationEvents } from '@/domain/coachReputation'
import type { CoachPerkId, CoachSkillId } from '@/domain/ids'
import { getRelationshipBandForPeople, getRelationshipsForPerson, type GameWorld } from '@/domain/world'
import { COACH_PERK_CATALOG, COACH_SKILL_CATALOG } from '@/engine/coach'
import { evaluateCoachJobEligibility } from '@/domain/coachCareer'
import { formatPrototypeDate } from '@/ui/formatters'
import { coachReputationEventLabel, coachReputationSourceLabel, formatCoachReputationDelta } from '@/ui/coachReputationPresentation'
import { AppFrame, AppHeader, DataTable, DetailGroup, SplitWorkspace, type DataColumn } from '@/ui/desktop/AppFramework'
import { BdmButton, Badge, Tabs } from '@/ui/components/designSystem'
import { LegacyScreen } from './LegacyScreen'

type CoachTab = 'overview' | 'opportunities' | 'career' | 'reputation' | 'relationships' | 'development' | 'legacy'
type Employment = GameWorld['coachEmploymentByCoachId'][keyof GameWorld['coachEmploymentByCoachId']]
type Opening = GameWorld['coachJobOpeningsById'][keyof GameWorld['coachJobOpeningsById']]
type Offer = GameWorld['coachJobOffersById'][keyof GameWorld['coachJobOffersById']]
type Professional = GameWorld['coachProfessionalProfilesByCoachId'][keyof GameWorld['coachProfessionalProfilesByCoachId']]
type Reputation = GameWorld['coachReputationProfilesByCoachId'][keyof GameWorld['coachReputationProfilesByCoachId']]
type Rpg = GameWorld['coachRpgProfilesByCoachId'][keyof GameWorld['coachRpgProfilesByCoachId']]
const label = { competitive: 'Competitive', development: 'Development', professional: 'Professional', publicStanding: 'Public Standing' } as const

export function CoachScreen({ world, onSkill, onPerk, onApply = () => undefined, onAcceptOffer = () => undefined, onDeclineOffer = () => undefined }: { readonly world: GameWorld; readonly onSkill: (id: CoachSkillId) => void; readonly onPerk: (id: CoachPerkId) => void; readonly onApply?: (id: string) => void; readonly onAcceptOffer?: (id: string) => void; readonly onDeclineOffer?: (id: string) => void }) {
  const [tab, setTab] = useState<CoachTab>('overview'); const coach = world.coaches[world.userCoachId]; const reputation = world.coachReputationProfilesByCoachId[world.userCoachId]; const rpg = world.coachRpgProfilesByCoachId[world.userCoachId]; const professional = world.coachProfessionalProfilesByCoachId[world.userCoachId]
  if (!coach || !reputation || !rpg || !professional) return <section className="screen"><p className="content-panel">Coach profile unavailable.</p></section>
  const employment = world.coachEmploymentByCoachId[world.userCoachId]; const history = world.coachCareerHistoryByCoachId[world.userCoachId] ?? []; const offers = Object.values(world.coachJobOffersById).filter((offer) => offer.coachId === coach.id); const openings = Object.values(world.coachJobOpeningsById).filter((opening) => opening.status === 'open'); const relationships = getRelationshipsForPerson(world, coach.id)
  const title = employment?.status === 'employed' && employment.teamId ? world.teams[employment.teamId]?.name ?? 'Employed' : 'Unemployed'
  const tabs: readonly { id: CoachTab; label: string }[] = [{ id: 'overview', label: 'Overview' }, { id: 'opportunities', label: 'Opportunities' }, { id: 'career', label: 'Career' }, { id: 'reputation', label: 'Reputation' }, { id: 'relationships', label: 'Relationships' }, { id: 'development', label: 'Development' }, { id: 'legacy', label: 'Legacy' }]
  return <AppFrame header={<AppHeader eyebrow="COACH CAREER" meta={title} title={<><span aria-label="Coach portrait unavailable" className="entity-profile__portrait">{coach.firstName[0]}{coach.lastName[0]}</span>{coach.firstName} {coach.lastName}</>} />} navigation={<Tabs onChange={(next) => setTab(next as CoachTab)} tabs={tabs} value={tab} />}><CoachWorkspace employment={employment} history={history} onAcceptOffer={onAcceptOffer} onApply={onApply} onDeclineOffer={onDeclineOffer} onPerk={onPerk} onSkill={onSkill} openings={openings} offers={offers} professional={professional} reputation={reputation} relationships={relationships} rpg={rpg} tab={tab} world={world} /></AppFrame>
}

function CoachWorkspace({ employment, history, onAcceptOffer, onApply, onDeclineOffer, onPerk, onSkill, openings, offers, professional, reputation, relationships, rpg, tab, world }: { readonly employment: Employment | undefined; readonly history: readonly { readonly teamId: string; readonly date: string; readonly reason: string }[]; readonly onAcceptOffer: (id: string) => void; readonly onApply: (id: string) => void; readonly onDeclineOffer: (id: string) => void; readonly onPerk: (id: CoachPerkId) => void; readonly onSkill: (id: CoachSkillId) => void; readonly openings: readonly Opening[]; readonly offers: readonly Offer[]; readonly professional: Professional; readonly reputation: Reputation; readonly relationships: ReturnType<typeof getRelationshipsForPerson>; readonly rpg: Rpg; readonly tab: CoachTab; readonly world: GameWorld }) {
  if (tab === 'overview') { const recent = getRecentCoachReputationEvents(reputation, 5); const personName = (id: string) => { const player = world.players[id as keyof typeof world.players]; if (player) return `${player.firstName} ${player.lastName} · Player`; const otherCoach = world.coaches[id as keyof typeof world.coaches]; return otherCoach ? `${otherCoach.firstName} ${otherCoach.lastName} · Coach` : id }; return <SplitWorkspace inspector={<aside className="coach-inspector"><DetailGroup title="Employment"><p>{employment?.status === 'employed' && employment.teamId ? `${world.teams[employment.teamId]?.name ?? employment.teamId} since ${employment.startedOn === undefined ? 'unknown' : formatPrototypeDate(employment.startedOn)}` : 'Unemployed'}</p></DetailGroup><DetailGroup title="Development"><p>{rpg.development.developmentPoints} development points</p><p>{rpg.development.globalProgress} / 100 global progress</p></DetailGroup></aside>}><section className="coach-overview"><DetailGroup title="Professional attributes"><dl>{Object.entries(professional.attributes).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl></DetailGroup><DetailGroup title="REPUTATION"><dl>{COACH_REPUTATION_DIMENSIONS.map((dimension) => { const value = reputation.values[dimension]; const band = getCoachReputationBand(value); return <div key={dimension}><dt>{label[dimension]}</dt><dd><Badge tone="info">{value} / 1000</Badge> {band[0]?.toUpperCase()}{band.slice(1)}</dd></div> })}</dl></DetailGroup><DetailGroup title="RECENT REPUTATION CHANGES">{recent.length === 0 ? <p>No reputation changes yet.</p> : recent.map((event) => <p key={event.id}>{coachReputationEventLabel(world, event)} · {coachReputationSourceLabel(event.source)} · {Object.values(event.deltas).map((delta) => formatCoachReputationDelta(delta ?? 0)).join(' ')}</p>)}</DetailGroup><DetailGroup title="RELATIONSHIPS">{relationships.length === 0 ? <p>No materialized relationships.</p> : relationships.map((item) => { const otherId = item.sourceId === world.userCoachId ? item.targetId : item.sourceId; return <p key={`${item.sourceId}-${item.targetId}`}>{personName(otherId)} · {item.value} · {getRelationshipBandForPeople(world, item.sourceId, item.targetId)}</p> })}</DetailGroup></section></SplitWorkspace> }
  if (tab === 'opportunities') return <OpportunityTable employment={employment} onAcceptOffer={onAcceptOffer} onApply={onApply} onDeclineOffer={onDeclineOffer} openings={openings} offers={offers} reputation={reputation} world={world} />
  if (tab === 'career') return <section className="coach-overview"><DetailGroup title="Career history">{history.length === 0 ? <p>No prior career history.</p> : <DataTable columns={[{ id: 'date', label: 'DATE', render: (item: typeof history[number]) => formatPrototypeDate(item.date as never) }, { id: 'team', label: 'TEAM', render: (item) => world.teams[item.teamId as keyof typeof world.teams]?.name ?? item.teamId }, { id: 'reason', label: 'EVENT', render: (item) => item.reason }]} rows={history.map((item, index) => ({ ...item, id: `${item.date}-${index}` }))} />}</DetailGroup></section>
  if (tab === 'reputation') return <section className="coach-overview"><DetailGroup title="Reputation"><dl>{COACH_REPUTATION_DIMENSIONS.map((dimension) => <div key={dimension}><dt>{label[dimension]}</dt><dd>{reputation.values[dimension]} · {getCoachReputationBand(reputation.values[dimension])}</dd></div>)}</dl></DetailGroup></section>
  if (tab === 'relationships') return <section className="coach-overview"><DetailGroup title="Relationships">{relationships.length === 0 ? <p>No materialized relationships.</p> : <DataTable columns={[{ id: 'person', label: 'PERSON', render: (item: typeof relationships[number]) => item.sourceId === world.userCoachId ? item.targetId : item.sourceId }, { id: 'value', label: 'VALUE', numeric: true, render: (item) => item.value }, { id: 'band', label: 'BAND', render: (item) => getRelationshipBandForPeople(world, item.sourceId, item.targetId) }]} rows={relationships.map((item, index) => ({ ...item, id: `${item.sourceId}-${item.targetId}-${index}` }))} />}</DetailGroup></section>
  if (tab === 'legacy') return <LegacyScreen world={world} />
  return <section className="coach-overview"><DetailGroup title="Skills">{COACH_SKILL_CATALOG.map((skill) => { const rank = rpg.skills[skill.id]?.rank ?? 0; return <p key={skill.id}>{skill.id} · rank {rank} <BdmButton disabled={rank === 3} onClick={() => onSkill(skill.id)} size="compact" variant="ghost">Develop</BdmButton></p> })}</DetailGroup><DetailGroup title="Perks">{COACH_PERK_CATALOG.map((perk) => <p key={perk.id}>{perk.id} · {rpg.perks[perk.id] ? 'owned' : <BdmButton onClick={() => onPerk(perk.id)} size="compact" variant="ghost">Purchase</BdmButton>}</p>)}</DetailGroup></section>
}

function OpportunityTable({ employment, onAcceptOffer, onApply, onDeclineOffer, openings, offers, reputation, world }: { readonly employment: Employment | undefined; readonly onAcceptOffer: (id: string) => void; readonly onApply: (id: string) => void; readonly onDeclineOffer: (id: string) => void; readonly openings: readonly Opening[]; readonly offers: readonly Offer[]; readonly reputation: Reputation; readonly world: GameWorld }) {
  const rows = [...offers.map((offer) => ({ id: `offer-${offer.id}`, kind: 'Offer', teamId: offer.teamId, date: offer.createdOn, status: offer.status, source: offer })), ...openings.map((opening) => ({ id: `opening-${opening.id}`, kind: 'Opening', teamId: opening.teamId, date: opening.createdOn, status: opening.status, source: opening }))]
  const columns: readonly DataColumn<(typeof rows)[number]>[] = [{ id: 'kind', label: 'TYPE', render: (row) => row.kind }, { id: 'team', label: 'TEAM', render: (row) => world.teams[row.teamId]?.name ?? row.teamId }, { id: 'date', label: 'DATE', render: (row) => formatPrototypeDate(row.date as never) }, { id: 'status', label: 'STATUS', render: (row) => row.status }, { id: 'action', label: 'ACTION', render: (row) => { if (row.kind === 'Offer' && row.source.status === 'pending') return <><BdmButton onClick={() => onAcceptOffer(row.source.id)} size="compact">Accept</BdmButton><BdmButton onClick={() => onDeclineOffer(row.source.id)} size="compact" variant="ghost">Decline</BdmButton></>; const opening = row.source as Opening; const eligibility = employment === undefined ? { eligible: false, reasons: [] } : evaluateCoachJobEligibility(employment, reputation, opening); return <BdmButton disabled={!eligibility.eligible} onClick={() => onApply(opening.id)} size="compact" title={eligibility.reasons.map((reason) => reason.reason).join(', ')} variant="ghost">Apply</BdmButton> } }]
  return <SplitWorkspace inspector={<aside className="coach-inspector"><DetailGroup title="Opportunity context"><p>Offers and openings are canonical career records. Actions are enabled only through the current career eligibility API.</p></DetailGroup></aside>}><DataTable columns={columns} emptyTitle="No active career opportunities" rows={rows} /></SplitWorkspace>
}
