import { useState } from 'react'
import type { GameWorld } from '@/domain/world'
import { getUserTeam } from '@/engine/calendar'
import type { Priority } from '@/domain/recruiting'

const reasonText: Readonly<Record<string, string>> = { RECRUITING_NOT_OPEN: 'La ventana de recruiting no está abierta.', INVALID_RECRUIT: 'Este recruit no pertenece al ciclo activo.', INSUFFICIENT_RECRUITING_CAPACITY: 'No queda capacidad de recruiting.', DUPLICATE_OFFER: 'Ya existe una oferta activa.', OFFER_LIMIT_REACHED: 'Se alcanzó el límite de ofertas o firmas.', RECRUIT_ALREADY_COMMITTED: 'El recruit ya no está disponible.', NO_CONTROLLED_PROGRAM: 'No controlas un programa NCAA.' }

export function RecruitingScreen({ world, onAddTarget, onRemoveTarget, onAction, onOffer }: { readonly world: GameWorld; readonly onAddTarget: (cycleId: string, recruitId: string, priority: Priority) => void; readonly onRemoveTarget: (recruitId: string) => void; readonly onAction: (cycleId: string, recruitId: string, kind: 'contact'|'pitch'|'visit') => string | null; readonly onOffer: (cycleId: string, recruitId: string) => string | null }) {
  const team = getUserTeam(world); const [feedback, setFeedback] = useState<string | null>(null)
  const controlled = team !== undefined && Object.values(world.competitions).some((competition) => competition.participantTeamIds.includes(team.id) && world.ecosystems[competition.ecosystemId]?.kind === 'ncaaLike')
  const profiles = Object.values(world.recruitProfilesById).sort((a, b) => a.publicRank - b.publicRank)
  const cycle = Object.values(world.recruitingCyclesById).find((item) => item.status === 'open' || item.status === 'signing')
  const run = (callback: () => string | null) => { const reason = callback(); setFeedback(reason === null ? 'Acción completada.' : (reasonText[reason] ?? reason)) }
  return <section className="screen"><div className="page-heading"><div><p className="eyebrow">RECRUITING</p><h1>RECRUITING CENTER</h1></div></div><div className="content-panel"><p>{controlled ? `Capacidad restante: ${world.recruitingCapacityByProgramId[team!.id] ?? cycle?.rules.periodCapacity ?? 0}` : 'Modo consulta: no controlas un programa NCAA.'}</p><p>Clase firmada: {Object.values(world.recruitSigningsById).filter((signing) => signing.programTeamId === team?.id).length} · Compromisos: {Object.values(world.recruitingCommitmentsById).filter((commitment) => commitment.programTeamId === team?.id).length}</p>{feedback !== null && <p role="status">{feedback}</p>}</div><div className="content-panel table-wrap"><table><thead><tr><th>RANK</th><th>PLAYER</th><th>POS</th><th>PUBLIC TALENT</th><th>ORIGIN</th><th>INTEREST</th><th>OFFER</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{profiles.map((profile) => { const player = world.players[profile.playerId]!; const board = team !== undefined && world.recruitingBoards.find((entry) => entry.recruitId === profile.id && entry.programTeamId === team.id); const interest = team === undefined ? undefined : world.recruitingInterests.find((item) => item.recruitId === profile.id && item.programTeamId === team.id)?.value; const offer = team === undefined ? undefined : Object.values(world.recruitingOffersById).find((item) => item.recruitId === profile.id && item.programTeamId === team.id && item.status === 'active'); return <tr key={profile.id}><td>{profile.publicRank}</td><td>{player.firstName} {player.lastName}</td><td>{profile.position}</td><td>{profile.tier.toUpperCase()}</td><td>{profile.origin}</td><td>{interest === undefined ? 'COLD' : interest >= 75 ? 'LEADER' : interest >= 55 ? 'STRONG' : interest >= 30 ? 'WARM' : 'INTERESTED'}</td><td>{offer === undefined ? '—' : 'OFFERED'}</td><td>{profile.status.toUpperCase()}</td><td>{controlled && cycle !== undefined && <div className="game-actions">{board === undefined ? <button type="button" onClick={() => onAddTarget(cycle.id, profile.id, 'normal')}>TARGET</button> : <button type="button" onClick={() => onRemoveTarget(profile.id)}>REMOVE</button>}<button type="button" onClick={() => run(() => onAction(cycle.id, profile.id, 'contact'))}>CONTACT ({cycle.rules.costs.contact})</button><button type="button" onClick={() => run(() => onAction(cycle.id, profile.id, 'pitch'))}>PITCH ({cycle.rules.costs.pitch})</button><button type="button" onClick={() => run(() => onAction(cycle.id, profile.id, 'visit'))}>VISIT ({cycle.rules.costs.visit})</button><button type="button" onClick={() => run(() => onOffer(cycle.id, profile.id))}>OFFER</button></div>}</td></tr> })}</tbody></table></div></section>
}
