import type { Player } from '@/domain/player'
import type { MatchTacticalPlan, TacticalLevel } from '@/engine/match'
import { BdmButton, Select, Surface } from '@/ui/components/designSystem'

const levels: readonly TacticalLevel[] = [-2, -1, 0, 1, 2]
const levelOptions = levels.map((level) => ({ value: String(level), label: level > 0 ? `+${level}` : String(level) }))
export function TacticsScreen({ players, plan, onChange, onReset }: { readonly players: readonly Player[]; readonly plan: MatchTacticalPlan; readonly onChange: (plan: MatchTacticalPlan) => void; readonly onReset: () => void }) {
  const select = (label: string, value: TacticalLevel, onSelect: (level: TacticalLevel) => void) => <Select ariaLabel={label} label={label} onChange={(next) => onSelect(Number(next) as TacticalLevel)} options={levelOptions} value={String(value)} />
  return <section className="screen tactics-app"><header className="page-heading"><div><p className="eyebrow">PRE-MATCH</p><h1>TACTICS</h1><p>Adjust the existing match plan.</p></div><BdmButton onClick={onReset} variant="secondary">Reset to balanced</BdmButton></header><Surface className="tactics-app__controls" elevated>{select('Pace', plan.pace, (pace) => onChange({ ...plan, pace }))}{select('Rim', plan.shotProfile.rim, (rim) => onChange({ ...plan, shotProfile: { ...plan.shotProfile, rim } }))}{select('Mid range', plan.shotProfile.midRange, (midRange) => onChange({ ...plan, shotProfile: { ...plan.shotProfile, midRange } }))}{select('Three point', plan.shotProfile.threePoint, (threePoint) => onChange({ ...plan, shotProfile: { ...plan.shotProfile, threePoint } }))}<Select ariaLabel="Defense" label="Defense" onChange={(value) => { const [interior, perimeter] = value.split('/').map(Number) as [TacticalLevel, TacticalLevel]; onChange({ ...plan, defense: { interior, perimeter } }) }} options={[{ value: '0/0', label: 'Balanced' }, { value: '2/-1', label: 'Protect paint' }, { value: '-1/2', label: 'Pressure perimeter' }]} value={`${plan.defense.interior}/${plan.defense.perimeter}`} /><Select ariaLabel="Featured player" label="Featured player" onChange={(value) => onChange({ ...plan, ...(value === '' ? { featuredPlayerId: undefined } : { featuredPlayerId: value as Player['id'] }) })} options={[{ value: '', label: 'None' }, ...players.map((player) => ({ value: player.id, label: `${player.firstName} ${player.lastName} · ${player.basketball.primaryPosition}` }))]} value={plan.featuredPlayerId ?? ''} /></Surface></section>
}
