import { useState } from 'react'
import type { GameWorld } from '@/domain/world'
import type { TeamId } from '@/domain/ids'
import { executeTrade, validateTrade } from '@/engine/trade'

export function TradeCenterScreen({ world, onExecute }: { readonly world: GameWorld; readonly onExecute: (proposal: Parameters<typeof executeTrade>[1]) => void }) {
  const seasonId = Object.keys(world.tradeRulesBySeasonId)[0] as keyof GameWorld['seasons'] | undefined
  const rules = seasonId === undefined ? undefined : world.tradeRulesBySeasonId[seasonId]
  const teams = rules === undefined ? [] : Object.values(world.teams).filter((team) => Object.values(world.competitions).some((competition) => competition.ecosystemId === rules.ecosystemId && competition.participantTeamIds.includes(team.id)))
  const [participants, setParticipants] = useState<readonly TeamId[]>(() => teams.slice(0, 2).map((team) => team.id))
  const [moves, setMoves] = useState<readonly { readonly playerId: string; readonly from: TeamId; readonly to: TeamId }[]>([])
  if (rules === undefined || teams.length < 2) return <section className="screen"><div className="page-heading"><div><p className="eyebrow">TRADES</p><h1>Trade Center</h1></div></div><p className="content-panel">No hay reglas de trade para un ciclo NBA-like activo.</p></section>
  const proposal = { id: `user-trade:${world.currentDate}:${moves.map((move) => move.playerId).join(':')}`, ecosystemId: rules.ecosystemId, seasonId: rules.seasonId, participantTeamIds: participants, movements: moves.map((move) => ({ asset: { kind: 'player' as const, playerId: move.playerId as never }, fromTeamId: move.from, toTeamId: move.to })) }
  const validation = validateTrade(world, proposal)
  const addTeam = () => { const next = teams.find((team) => !participants.includes(team.id)); if (next !== undefined && participants.length < rules.maxTeamsPerTrade) setParticipants([...participants, next.id]) }
  return <section className="screen"><div className="page-heading"><div><p className="eyebrow">TRADES</p><h1>Trade Center</h1></div><button disabled={participants.length >= rules.maxTeamsPerTrade} onClick={addTeam} type="button">+ Add team</button></div><div className="content-panel"><p>{participants.length} participants · maximum {rules.maxTeamsPerTrade}</p><label>Add player movement <select onChange={(event) => { const [from, playerId] = event.target.value.split('|'); const to = participants.find((id) => id !== from); if (to !== undefined && playerId !== undefined) setMoves([...moves, { playerId, from: from as TeamId, to }]) }} value=""><option value="">Select player</option>{participants.flatMap((teamId) => world.teams[teamId]!.rosterPlayerIds.map((playerId) => <option key={playerId} value={`${teamId}|${playerId}`}>{world.players[playerId]!.firstName} {world.players[playerId]!.lastName} from {world.teams[teamId]!.name}</option>))}</select></label></div>{participants.map((teamId) => { const result = validation.teamResults.find((item) => item.teamId === teamId); return <article className="content-panel" key={teamId}><h2>{world.teams[teamId]!.name}</h2><p>Outgoing {result?.outgoingSalary ?? 0} · Incoming {result?.incomingSalary ?? 0} · Limit {result?.incomingSalaryLimit ?? '—'} · Projected payroll {result?.projectedPayroll ?? '—'}</p><p>{result?.reasons.length === 0 ? 'Valid' : result?.reasons.join(', ')}</p></article> })}<div className="content-panel"><h2>History</h2>{Object.values(world.tradeHistoryById).map((trade) => <p key={trade.id}>{trade.executedAt} · {trade.participantTeamIds.map((id) => world.teams[id]!.name).join(' / ')} · {trade.movements.length} assets</p>)}</div><button disabled={!validation.allowed} onClick={() => onExecute(proposal)} type="button">Execute trade</button></section>
}
