import type { GameWorld } from '@/domain/world'
import { getDevelopmentStimulusForPlayer, getTeamRoster } from '@/domain/world'
import { getUserTeam } from '@/engine/calendar'
import type { TrainingFocus, TrainingIntensity } from '@/domain/training'
import { selectLatestUserTrainingSession, selectUserTeamCareerFatigueSummary, selectUserTrainingPlan } from '@/stores/gameStore'

const labels: Record<TrainingFocus, string> = { balanced: 'Balanced', finishing: 'Finishing', shooting: 'Shooting', playmaking: 'Playmaking', perimeterDefense: 'Perimeter Defense', interiorDefense: 'Interior Defense', rebounding: 'Rebounding', athleticism: 'Athleticism' }
export function TrainingScreen({ world, onIntensity, onFocus }: { readonly world: GameWorld; readonly onIntensity: (value: TrainingIntensity) => void; readonly onFocus: (value: TrainingFocus) => void }) {
  const team = getUserTeam(world); if (team === undefined) return null
  const plan = selectUserTrainingPlan(world)!; const latest = selectLatestUserTrainingSession(world); const fatigue = selectUserTeamCareerFatigueSummary(world)
  return <section className="screen"><div className="page-heading"><div><p className="eyebrow">TRAINING</p><h1>{team.name}</h1></div></div><section className="content-panel"><p className="eyebrow">CURRENT TRAINING PLAN</p><label>INTENSITY <select value={plan.intensity} onChange={(event) => onIntensity(event.target.value as TrainingIntensity)}>{(['light', 'normal', 'high'] as const).map((value) => <option key={value} value={value}>{value[0].toUpperCase() + value.slice(1)}</option>)}</select></label><label>FOCUS <select value={plan.focus} onChange={(event) => onFocus(event.target.value as TrainingFocus)}>{(Object.keys(labels) as TrainingFocus[]).map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select></label></section><section className="content-panel"><p className="eyebrow">LATEST TRAINING SESSION</p>{latest === undefined ? <p>No training sessions yet.</p> : <p>{latest.gameDate} · {latest.intensity.toUpperCase()} · {labels[latest.focus]}</p>}<p>CAREER FATIGUE / CONDITION: {fatigue.toFixed(1)} average fatigue</p></section><section className="content-panel table-wrap"><p className="eyebrow">DEVELOPMENT STIMULUS / TRAINING PROGRESS</p><table><thead><tr><th>PLAYER</th><th>FOCUS PROGRESS</th></tr></thead><tbody>{getTeamRoster(world, team.id).map((player) => { const stimulus = getDevelopmentStimulusForPlayer(world, player.id); const value = plan.focus === 'balanced' ? Object.values(stimulus.byRating).reduce((sum, item) => sum + item, 0) : stimulus.byRating[plan.focus]; return <tr key={player.id}><td>{player.firstName} {player.lastName}</td><td>{labels[plan.focus]} training stimulus: {value.toFixed(1)}</td></tr> })}</tbody></table></section></section>
}
