import { useState } from 'react'

import { BASKETBALL_RATING_KEYS, type BasketballRatingKey } from '@/domain/player'
import type { TeamId } from '@/domain/ids'
import { getCareerFatigueForPlayer, getDevelopmentStimulusForPlayer, getTeamRoster } from '@/domain/world'
import { getGamesToday, getUserTeam } from '@/engine/calendar'
import type { GameWorld } from '@/domain/world'
import type { TrainingFocus, TrainingIntensity } from '@/domain/training'
import { Progress } from '@/ui/components/primitives'
import { Select, Tooltip } from '@/ui/components/designSystem'
import { ATTRIBUTE_LABELS } from '@/ui/attributeLabels'
import { selectLatestUserTrainingSession, selectUserTrainingPlan } from '@/stores/gameStore'

const labels: Record<TrainingFocus, string> = { balanced: 'Equilibrado', finishing: 'Finalización', shooting: 'Tiro', playmaking: 'Creación', perimeterDefense: 'Defensa exterior', interiorDefense: 'Defensa interior', rebounding: 'Rebote', athleticism: 'Atletismo' }
type SortKey = 'name' | 'fatigue' | 'total' | BasketballRatingKey
export function getTrainingImpact(world: GameWorld, teamId: TeamId) { const players = getTeamRoster(world, teamId); const totals = Object.fromEntries(BASKETBALL_RATING_KEYS.map((key) => [key, players.reduce((sum, player) => sum + (getDevelopmentStimulusForPlayer(world, player.id)?.byRating[key] ?? 0), 0)])) as Record<BasketballRatingKey, number>; const fatigue = players.map((player) => getCareerFatigueForPlayer(world, player.id)); return { players, totals, averageFatigue: fatigue.length === 0 ? 0 : fatigue.reduce((sum, value) => sum + value, 0) / fatigue.length } }
export function TrainingScreen({ world, onIntensity, onFocus }: { readonly world: GameWorld; readonly onIntensity: (value: TrainingIntensity) => void; readonly onFocus: (value: TrainingFocus) => void }) {
  const team = getUserTeam(world); const [sortKey, setSortKey] = useState<SortKey>('fatigue'); const [descending, setDescending] = useState(true)
  if (team === undefined) return <section className="training-app">El entrenador de usuario no tiene equipo asignado.</section>
  const plan = selectUserTrainingPlan(world)!; const latest = selectLatestUserTrainingSession(world); const matchDay = getGamesToday(world).some((game) => game.homeTeamId === team.id || game.awayTeamId === team.id); const trainedToday = latest?.gameDate === world.currentDate; const impact = getTrainingImpact(world, team.id); const rows = impact.players.slice().sort((a, b) => compareTraining(world, a, b, sortKey, descending)); const sort = (key: SortKey) => { if (key === sortKey) setDescending((value) => !value); else { setSortKey(key); setDescending(true) } }
  const status = matchDay ? 'Entrenamiento no disponible: día de partido.' : trainedToday ? 'La sesión ya se ejecutó hoy.' : 'Entrenamiento disponible al avanzar el calendario.'
  return <section className="training-app"><header><p className="eyebrow">TRAINING</p><h1>{team.name}</h1><p>{world.currentDate} · {status}</p></header><div className="training-app__plan"><section><h2>Active plan</h2><Select ariaLabel="Training intensity" label="Intensity" onChange={(value) => onIntensity(value as TrainingIntensity)} options={(['light', 'normal', 'high'] as const).map((value) => ({ value, label: value }))} value={plan.intensity} /><Tooltip content="The attribute focus applied by the existing training system."><span>Focus</span></Tooltip><Select ariaLabel="Training focus" onChange={(value) => onFocus(value as TrainingFocus)} options={(Object.keys(labels) as TrainingFocus[]).map((value) => ({ value, label: labels[value] }))} value={plan.focus} /></section><section><h2>Latest session</h2>{latest === undefined ? <p>No training sessions yet.</p> : <p>{latest.gameDate} · {latest.intensity} · {labels[latest.focus]}</p>}<p>Plan settings apply when the calendar runs an eligible training day.</p></section></div><div className="training-app__impact"><section><h2>Career Fatigue</h2><strong>{impact.averageFatigue.toFixed(1)} team average</strong><Progress label="Average Career Fatigue" value={impact.averageFatigue} /><p>Persistent training load on the domain’s 0–100 scale.</p></section><section><h2>Development Stimulus accumulated</h2><p>Stimulus is consumed by PlayerDevelopment; it is not a rating.</p><dl>{BASKETBALL_RATING_KEYS.map((key) => <div key={key}><dt>{key}</dt><dd>{impact.totals[key].toFixed(1)}</dd></div>)}</dl></section></div><div className="training-app__table-wrap"><table><thead><tr><Head active={sortKey === 'name'} label="PLAYER" onClick={() => sort('name')} /><th>POS</th><Head active={sortKey === 'fatigue'} label="FATIGUE" onClick={() => sort('fatigue')} />{BASKETBALL_RATING_KEYS.map((key) => <Head active={sortKey === key} key={key} label={key} onClick={() => sort(key)} />)}<Head active={sortKey === 'total'} label="TOTAL" onClick={() => sort('total')} /></tr></thead><tbody>{rows.map((player) => { const stimulus = getDevelopmentStimulusForPlayer(world, player.id); const total = BASKETBALL_RATING_KEYS.reduce((sum, key) => sum + (stimulus?.byRating[key] ?? 0), 0); return <tr key={player.id}><td>{player.firstName} {player.lastName}</td><td>{player.basketball.primaryPosition}</td><td>{getCareerFatigueForPlayer(world, player.id)}</td>{BASKETBALL_RATING_KEYS.map((key) => <td key={key}>{(stimulus?.byRating[key] ?? 0).toFixed(1)}</td>)}<td>{total.toFixed(1)}</td></tr>})}</tbody></table></div></section>
}
function Head({ active, label, onClick }: { readonly active: boolean; readonly label: string; readonly onClick: () => void }) { return <th aria-sort={active ? 'descending' : 'none'}><button onClick={onClick} type="button">{label}</button></th> }
function compareTraining(world: GameWorld, a: import('@/domain/player').Player, b: import('@/domain/player').Player, key: SortKey, descending: boolean) { if (key === 'name') return a.lastName.localeCompare(b.lastName) * (descending ? -1 : 1); const value = (player: import('@/domain/player').Player) => { const stimulus = getDevelopmentStimulusForPlayer(world, player.id); if (key === 'fatigue') return getCareerFatigueForPlayer(world, player.id); if (key === 'total') return BASKETBALL_RATING_KEYS.reduce((sum, rating) => sum + (stimulus?.byRating[rating] ?? 0), 0); return stimulus?.byRating[key] ?? 0 }; return (value(a) - value(b)) * (descending ? -1 : 1) || a.lastName.localeCompare(b.lastName) }
