import { describe, expect, it } from 'vitest'
import { createNewGame } from '@/app/game'
import { addDays, addYears } from '@/domain/date'
import { createPlayerContract, getPlayerContractStatus } from '@/domain/contract'
import { contractIdFromString } from '@/domain/ids'
import { assignLineupSlot, createDefaultTeamLineup, getLineupAssignments } from '@/domain/tactics'
import { updateGameWorld } from '@/domain/world'
import { getFreeAgents, getPlayerRosterTeamId, getPlayerTransactions } from '@/domain/world'
import { reconcileExpiredPlayerContracts } from './ContractLifecycle'
describe('ContractLifecycle',()=>{
it('removes an expired contracted player once and makes them a free agent',()=>{const world=createNewGame();const contract=Object.values(world.contractsById)[0]!;const date=addYears(contract.term.expiresOn,1);const next=reconcileExpiredPlayerContracts(world,date);expect(getPlayerRosterTeamId(next,contract.playerId)).toBeUndefined();expect(getFreeAgents(next,date).some(p=>p.id===contract.playerId)).toBe(true);expect(getPlayerTransactions(next,contract.playerId)).toHaveLength(1);expect(reconcileExpiredPlayerContracts(next,date)).toEqual(next)})
it('clears an expired player from the saved lineup while preserving other assignments',()=>{const base=createNewGame();const contracts=Object.values(base.contractsById).sort((a,b)=>a.term.expiresOn.localeCompare(b.term.expiresOn));const contract=contracts.find((item)=>contracts.some((other)=>other.teamId===item.teamId&&other.playerId!==item.playerId&&other.term.expiresOn>item.term.expiresOn))!;const team=base.teams[contract.teamId]!;const remainingContract=contracts.find((item)=>item.teamId===team.id&&item.term.expiresOn>contract.term.expiresOn)!;const remaining=remainingContract.playerId;let lineup=createDefaultTeamLineup(team.id);lineup=assignLineupSlot(lineup,'PG',contract.playerId);lineup=assignLineupSlot(lineup,'SG',remaining);const world=updateGameWorld(base,{lineupsByTeamId:{...base.lineupsByTeamId,[team.id]:lineup}});const next=reconcileExpiredPlayerContracts(world,addDays(contract.term.expiresOn,1));const assignments=getLineupAssignments(next.lineupsByTeamId[team.id]!);expect(assignments.some((item)=>item.playerId===contract.playerId)).toBe(false);expect(assignments).toContainEqual({slot:'SG',playerId:remaining})})
it('keeps a no-successor player rostered the day before expiry and releases them on expiry without a gap',()=>{const world=createNewGame();const contract=Object.values(world.contractsById)[0]!;const team=world.teams[contract.teamId]!;const before=reconcileExpiredPlayerContracts(world,addDays(contract.term.expiresOn,-1));expect(before.teams[team.id]!.rosterPlayerIds).toContain(contract.playerId);const expiry=reconcileExpiredPlayerContracts(before,contract.term.expiresOn);expect(expiry.teams[team.id]!.rosterPlayerIds).not.toContain(contract.playerId);expect(getFreeAgents(expiry,contract.term.expiresOn).some((player)=>player.id===contract.playerId)).toBe(true);const after=reconcileExpiredPlayerContracts(expiry,addDays(contract.term.expiresOn,1));expect(after).toEqual(expiry)})
it('keeps a scheduled-successor player rostered before, on, and after the activation boundary',()=>{const base=createNewGame();const predecessor=Object.values(base.contractsById)[0]!;const team=base.teams[predecessor.teamId]!;const successor=createPlayerContract({id:contractIdFromString(`lifecycle-successor:${predecessor.id}`),playerId:predecessor.playerId,teamId:team.id,kind:'standard',predecessorContractId:predecessor.id,term:{startsOn:predecessor.term.expiresOn,expiresOn:addYears(predecessor.term.expiresOn,1)},compensation:{annualSalary:predecessor.compensation.annualSalary}});const world=updateGameWorld(base,{contracts:[...Object.values(base.contractsById),successor]});const before=reconcileExpiredPlayerContracts(world,addDays(successor.term.startsOn,-1));expect(before.teams[team.id]!.rosterPlayerIds).toContain(predecessor.playerId);const expiry=reconcileExpiredPlayerContracts(before,successor.term.startsOn);expect(getPlayerContractStatus(successor,successor.term.startsOn)).toBe('active');expect(expiry.teams[team.id]!.rosterPlayerIds).toContain(predecessor.playerId);const after=reconcileExpiredPlayerContracts(expiry,addDays(successor.term.startsOn,1));expect(after.teams[team.id]!.rosterPlayerIds).toContain(predecessor.playerId);expect(Object.values(after.playerTransactionsById).some((item)=>item.kind==='contractExpired'&&item.playerId===predecessor.playerId)).toBe(false)})
})
