import { consolidateMarketSignal, type ContractNegotiation, type MarketSignal } from '@/domain/market'
import { agencyIdFromString, agentIdFromString, organizationIdForTeam, type OrganizationId, type PlayerId } from '@/domain/ids'
import { updateGameWorld, type GameWorld } from '@/domain/world'

/** Deterministic Wave 4 bootstrap: a portfolio model, not one agent per player. */
export function initializeMarketAgents(world:GameWorld):GameWorld{if(Object.keys(world.agentsById).length>0)return world;const agencies=Array.from({length:4},(_,index)=>({id:agencyIdFromString(`agency:market:${index+1}`),name:['Northline','Vertex','Pioneer','Crown'][index]+' Sports',reputation:45+index*12}));const agents=Array.from({length:8},(_,index)=>{const agencyId=agencies[index%agencies.length]!.id;return{id:agentIdFromString(`agent:market:${index+1}`),name:`Agent ${index+1}`,agencyId,reputation:40+(index*7)%50,abilities:{negotiation:45+(index*11)%45,marketKnowledge:40+(index*13)%50,network:42+(index*17)%45,clientManagement:44+(index*19)%43,mediaInfluence:35+(index*23)%48},personality:{aggressiveness:35+(index*7)%55,loyalty:35+(index*9)%55,opportunism:35+(index*11)%55,patience:35+(index*13)%55,discretion:35+(index*17)%55}}});const players=Object.values(world.players).sort((a,b)=>a.id.localeCompare(b.id));return updateGameWorld(world,{agencies,agents,playerRepresentations:players.map((player,index)=>({playerId:player.id,agentId:agents[index%agents.length]!.id,trust:55+(index%30),startedOn:world.currentDate})),marketReality:players.map((player,index)=>({playerId:player.id,availability:index%7===0?'OPEN':index%3===0?'LISTENING':'NOT_FOR_SALE',expectedSalary:300_000+(index%12)*75_000,expectedYears:1+index%4,playerWillingness:35+(index*7)%55,sellerWillingness:25+(index*11)%65,competition:index%6}))})}

/** Signals are the only route through which an organization gains market perception. */
export function receiveMarketSignal(world:GameWorld,signal:MarketSignal):GameWorld{return updateGameWorld(world,{marketSignals:[...Object.values(world.marketSignalsById),signal],marketKnowledge:consolidateMarketSignal(world.marketKnowledge,signal)})}
export function openNegotiation(world:GameWorld,input:Omit<ContractNegotiation,'id'|'status'|'round'>):GameWorld{const id=`negotiation:${input.organizationId}:${input.playerId}:${world.currentDate}`;return updateGameWorld(world,{negotiations:[...Object.values(world.negotiationsById),{...input,id,status:'OPEN',round:0}]})}
export function agentForPlayer(world:GameWorld,playerId:PlayerId){const representation=world.playerRepresentations.find(item=>item.playerId===playerId);return representation===undefined?undefined:world.agentsById[representation.agentId]}
export function organizationMarketContact(world:GameWorld,teamId:import('@/domain/ids').TeamId,playerId:PlayerId):OrganizationId{return organizationIdForTeam(teamId)}
