import { createInjury, injuryReturnDate, recoveryDaysForSeverity, type InjuryKind, type InjuryRecord, type InjurySeverity } from '@/domain/injury'
import { injuryIdFromString, type GameId } from '@/domain/ids'
import { createGameWorld, getActiveInjuryForPlayer, isPlayerAvailable, type GameWorld } from '@/domain/world'
import { hashStringToSeed, SeededRandomSource } from '@/engine/random'

const KINDS:readonly InjuryKind[]=['ankleSprain','hamstringStrain','kneeSprain','backStrain','handInjury','shoulderStrain']
export function injuryProbability(secondsPlayed:number):number{return secondsPlayed<=0?0:0.005+0.015*Math.max(0,Math.min(1,secondsPlayed/(40*60)))}
export function generatePostMatchInjuries(world:GameWorld,gameId:GameId):readonly InjuryRecord[]{const game=world.games[gameId];const log=world.matchStatLogsByGameId[gameId];if(!game||!log)throw new Error('Completed Game and MatchStatLog are required');return log.playerLines.filter(l=>l.stats.secondsPlayed>0&&!getActiveInjuryForPlayer(world,l.playerId,game.date)).flatMap(line=>{const playerId=line.playerId;const occurrence=new SeededRandomSource(hashStringToSeed(`player-injury-occurrence-v1:${gameId}:${playerId}`));if(occurrence.nextFloat(0,1)>=injuryProbability(line.stats.secondsPlayed))return[];const kind=KINDS[new SeededRandomSource(hashStringToSeed(`player-injury-kind-v1:${gameId}:${playerId}`)).nextInt(0,KINDS.length-1)]!;const roll=new SeededRandomSource(hashStringToSeed(`player-injury-severity-v1:${gameId}:${playerId}`)).nextFloat(0,1);const severity:InjurySeverity=roll<.7?'minor':roll<.95?'moderate':'serious';const [min,max]=recoveryDaysForSeverity(severity);const days=new SeededRandomSource(hashStringToSeed(`player-injury-duration-v1:${gameId}:${playerId}`)).nextInt(min,max);return [createInjury({id:injuryIdFromString(`injury:${gameId}:${playerId}`),playerId,kind,severity,injuredOn:game.date,expectedReturnDate:injuryReturnDate(game.date,days),sourceGameId:gameId})]})}
export function applyPostMatchInjuries(world:GameWorld,gameId:GameId):GameWorld{const candidates=generatePostMatchInjuries(world,gameId);const game=world.games[gameId]!;const available=new Map([game.homeTeamId,game.awayTeamId].map(id=>[id,Object.values(world.teams[id]!.rosterPlayerIds).filter(playerId=>isPlayerAvailable(world,playerId,game.date)).length]));const applied=[...candidates].sort((a,b)=>a.playerId.localeCompare(b.playerId)).filter(injury=>{const teamId=world.teams[game.homeTeamId]!.rosterPlayerIds.includes(injury.playerId)?game.homeTeamId:game.awayTeamId;const count=available.get(teamId)!;if(count<=5)return false;available.set(teamId,count-1);return true});if(!applied.length)return world;return createGameWorld({currentDate:world.currentDate,currentSeasonId:world.currentSeasonId,userCoachId:world.userCoachId,countries:Object.values(world.countries),coaches:Object.values(world.coaches),players:Object.values(world.players),teams:Object.values(world.teams),competitions:Object.values(world.competitions),seasons:Object.values(world.seasons),games:Object.values(world.games),matchStatLogs:Object.values(world.matchStatLogsByGameId),seasonHistory:Object.values(world.seasonHistoryBySeasonId),injuries:[...Object.values(world.injuriesById),...applied],contracts:Object.values(world.contractsById),teamFinances:Object.values(world.teamFinancesByTeamId),playerTransactions:Object.values(world.playerTransactionsById),playerKnowledge:Object.values(world.playerKnowledgeById),staffPeople:Object.values(world.staffPeopleById),teamStaffAssignments:Object.values(world.teamStaffAssignmentsById),coachProfessionalProfilesByCoachId:world.coachProfessionalProfilesByCoachId,coachRpgProfilesByCoachId: world.coachRpgProfilesByCoachId, coachReputationProfilesByCoachId: world.coachReputationProfilesByCoachId, coachEmploymentByCoachId: world.coachEmploymentByCoachId, coachCareerHistoryByCoachId: world.coachCareerHistoryByCoachId, coachJobOpeningsById: world.coachJobOpeningsById, coachJobCandidaciesById: world.coachJobCandidaciesById, coachInterviewsByCandidacyId: world.coachInterviewsByCandidacyId, coachJobOffersById: world.coachJobOffersById})}
