import type { PlayerGameStatsSnapshot } from '@/domain/stats/MatchStatLog'
import type { PlayerId, SeasonId } from '@/domain/ids'
import type { GameWorld } from '@/domain/world'

export interface PlayerAggregateStats extends Omit<PlayerGameStatsSnapshot, 'playerId'> { readonly gamesPlayed: number; readonly gamesStarted: number }
export interface PlayerSeasonStats extends PlayerAggregateStats { readonly playerId: PlayerId; readonly seasonId: SeasonId }
export interface PlayerCareerStats extends PlayerAggregateStats { readonly playerId: PlayerId }
export interface PlayerStatAverages { readonly mpg: number; readonly ppg: number; readonly rpg: number; readonly apg: number; readonly spg: number; readonly bpg: number; readonly turnoversPerGame: number; readonly foulsPerGame: number; readonly plusMinusPerGame: number; readonly fieldGoalPercentage: number; readonly twoPointPercentage: number; readonly threePointPercentage: number; readonly freeThrowPercentage: number }
type GameLine = ReturnType<typeof getPlayerGameLogs>[number]

export function getPlayerGameLogs(world: GameWorld, playerId: PlayerId) { return Object.values(world.matchStatLogsByGameId).flatMap((log) => log.playerLines.filter((line) => line.playerId === playerId).map((line) => ({ ...line, gameId: log.gameId, gameDate: log.gameDate, competitionId: log.competitionId, seasonId: log.seasonId, finalScore: log.finalScore }))).sort((a, b) => b.gameDate.localeCompare(a.gameDate) || b.gameId.localeCompare(a.gameId)) }
export function getPlayerSeasonStats(world: GameWorld, playerId: PlayerId, seasonId: SeasonId): PlayerSeasonStats { return { ...aggregate(playerId, getPlayerGameLogs(world, playerId).filter((line) => line.seasonId === seasonId)), seasonId } }
export function getPlayerCareerStats(world: GameWorld, playerId: PlayerId): PlayerCareerStats { return aggregate(playerId, getPlayerGameLogs(world, playerId)) }
export function getPlayerSeasonStatLines(world: GameWorld, playerId: PlayerId): readonly PlayerSeasonStats[] { return [...new Set(getPlayerGameLogs(world, playerId).map((line) => line.seasonId))].sort((a, b) => b.localeCompare(a)).map((seasonId) => getPlayerSeasonStats(world, playerId, seasonId)) }
export function calculatePlayerStatAverages(stats: PlayerAggregateStats): PlayerStatAverages { const perGame = (value: number) => stats.gamesPlayed === 0 ? 0 : value / stats.gamesPlayed; const percentage = (made: number, attempted: number) => attempted === 0 ? 0 : made / attempted * 100; return { mpg: perGame(stats.secondsPlayed) / 60, ppg: perGame(stats.points), rpg: perGame(stats.rebounds), apg: perGame(stats.assists), spg: perGame(stats.steals), bpg: perGame(stats.blocks), turnoversPerGame: perGame(stats.turnovers), foulsPerGame: perGame(stats.foulsCommitted), plusMinusPerGame: perGame(stats.plusMinus), fieldGoalPercentage: percentage(stats.fieldGoalsMade, stats.fieldGoalsAttempted), twoPointPercentage: percentage(stats.twoPointMade, stats.twoPointAttempted), threePointPercentage: percentage(stats.threePointMade, stats.threePointAttempted), freeThrowPercentage: percentage(stats.freeThrowsMade, stats.freeThrowsAttempted) } }
function aggregate(playerId: PlayerId, lines: readonly GameLine[]): PlayerCareerStats { const total: { -readonly [Key in keyof PlayerCareerStats]: PlayerCareerStats[Key] } = { playerId, secondsPlayed: 0, points: 0, fieldGoalsMade: 0, fieldGoalsAttempted: 0, twoPointMade: 0, twoPointAttempted: 0, threePointMade: 0, threePointAttempted: 0, freeThrowsMade: 0, freeThrowsAttempted: 0, offensiveRebounds: 0, defensiveRebounds: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0, foulsCommitted: 0, plusMinus: 0, gamesPlayed: 0, gamesStarted: 0 }; for (const line of lines) { const stats = line.stats; total.gamesPlayed += stats.secondsPlayed > 0 ? 1 : 0; total.gamesStarted += line.started ? 1 : 0; total.secondsPlayed += stats.secondsPlayed; total.points += stats.points; total.fieldGoalsMade += stats.fieldGoalsMade; total.fieldGoalsAttempted += stats.fieldGoalsAttempted; total.twoPointMade += stats.twoPointMade; total.twoPointAttempted += stats.twoPointAttempted; total.threePointMade += stats.threePointMade; total.threePointAttempted += stats.threePointAttempted; total.freeThrowsMade += stats.freeThrowsMade; total.freeThrowsAttempted += stats.freeThrowsAttempted; total.offensiveRebounds += stats.offensiveRebounds; total.defensiveRebounds += stats.defensiveRebounds; total.rebounds += stats.rebounds; total.assists += stats.assists; total.steals += stats.steals; total.blocks += stats.blocks; total.turnovers += stats.turnovers; total.foulsCommitted += stats.foulsCommitted; total.plusMinus += stats.plusMinus } return total }
