import { compareGameDates, type GameDate } from '@/domain/date'
import type { ContractId, PlayerId, TeamId } from '@/domain/ids'
export type PlayerContractKind='standard'
export type ContractTerminationReason='released'
export interface ContractYearCompensation { readonly cashSalary: number; readonly capHit: number; readonly guaranteedAmount: number }
export interface PlayerContract { readonly id:ContractId;readonly playerId:PlayerId;readonly teamId:TeamId;readonly kind:PlayerContractKind;readonly term:{readonly startsOn:GameDate;readonly expiresOn:GameDate};readonly compensation:{readonly annualSalary:number;readonly years?:readonly ContractYearCompensation[]};readonly termination?:{readonly terminatedOn:GameDate;readonly reason:ContractTerminationReason} }
export type PlayerContractStatus='scheduled'|'active'|'expired'|'terminated'
export function createPlayerContract(input:PlayerContract):PlayerContract{if(input.kind!=='standard')throw new TypeError('Contract kind is invalid');if(compareGameDates(input.term.expiresOn,input.term.startsOn)<=0)throw new RangeError('Contract expiry must be after start');if(input.termination&&(input.termination.reason!=='released'||compareGameDates(input.termination.terminatedOn,input.term.startsOn)<0||compareGameDates(input.termination.terminatedOn,input.term.expiresOn)>=0))throw new RangeError('Contract termination is invalid');if(!Number.isInteger(input.compensation.annualSalary)||input.compensation.annualSalary<1||input.compensation.annualSalary>100_000_000)throw new RangeError('Contract annual salary must be an integer from 1 to 100000000');const years=input.compensation.years; if(years!==undefined&&(years.length===0||years.some(year=>!validMoney(year.cashSalary)||!validMoney(year.capHit)||!validMoney(year.guaranteedAmount)||year.guaranteedAmount>year.cashSalary)))throw new RangeError('Contract year compensation is invalid');return{...input,term:{...input.term},compensation:{...input.compensation,...(years===undefined?{}:{years:Object.freeze(years.map(year=>Object.freeze({...year})))})},...(input.termination?{termination:{...input.termination}}:{})}}
export function getPlayerContractStatus(contract:PlayerContract,onDate:GameDate):PlayerContractStatus{if(contract.termination&&compareGameDates(onDate,contract.termination.terminatedOn)>=0)return'terminated';return compareGameDates(onDate,contract.term.startsOn)<0?'scheduled':compareGameDates(onDate,contract.term.expiresOn)<0?'active':'expired'}
export function getContractYearCompensation(contract: PlayerContract, onDate: GameDate): ContractYearCompensation { const index = Math.max(0, Number(onDate.slice(0, 4)) - Number(contract.term.startsOn.slice(0, 4))); return contract.compensation.years?.[Math.min(index, contract.compensation.years.length - 1)] ?? { cashSalary: contract.compensation.annualSalary, capHit: contract.compensation.annualSalary, guaranteedAmount: contract.compensation.annualSalary } }
function validMoney(value:number):boolean{return Number.isInteger(value)&&value>=0&&value<=100_000_000}
