import { describe, expect, it } from 'vitest'
import { createNewGame } from '@/app/game'
import { getCurrentlyRelevantMemoriesForEntity, getMemoriesBetweenEntities, getMemoryReinforcementForEntities, getRecentMemoriesForEntity } from '@/domain/world'
import { deserializeGameWorldV1, serializeGameWorldV1 } from '@/save/GameWorldSaveV1'
import { decayMemoriesForMonth, recordMemory } from './MemoryEngine'

describe('Memory system', () => {
  const baseMemory = (world: ReturnType<typeof createNewGame>, id: string, valence: number, permanent = false) => ({ id, owner: { kind: 'coach' as const, id: world.userCoachId }, type: 'opportunity' as const, occurredOn: world.currentDate, entityRefs: [{ kind: 'team' as const, id: Object.values(world.teams)[0]!.id }], semanticKey: 'first-opportunity', importance: permanent ? 'historic' as const : 'important' as const, valence, intensity: 80, decayPerMonth: 5, permanent, tags: ['career'], context: {} })
  it('keeps distinct perspectives while deduplicating one observer semantic event', () => { const world = createNewGame(); const playerId = Object.values(world.players)[0]!.id; const coach = recordMemory(world, baseMemory(world, 'memory:coach', 70)); const player = recordMemory(coach, { ...baseMemory(world, 'memory:player', -70), owner: { kind: 'player', id: playerId } }); const duplicate = recordMemory(player, baseMemory(world, 'memory:duplicate', 70)); expect(Object.keys(player.memoriesById)).toHaveLength(2); expect(duplicate).toEqual(player); expect([...Object.values(player.memoriesById).map((item) => item.valence)].sort()).toEqual([-70, 70]) })
  it('decays ordinary memories once per month but preserves permanent history', () => { const world = createNewGame(); const remembered = recordMemory(recordMemory(world, baseMemory(world, 'memory:ordinary', -20)), { ...baseMemory(world, 'memory:historic', 100, true), semanticKey: 'championship' }); const decayed = decayMemoriesForMonth(remembered); expect(decayed.memoriesById['memory:ordinary']!.intensity).toBe(75); expect(decayed.memoriesById['memory:historic']!.intensity).toBe(80); expect(decayMemoriesForMonth(decayed)).toEqual(decayed) })
  it('round-trips memory history and supplies empty defaults to legacy saves', () => { const world = recordMemory(createNewGame(), baseMemory(createNewGame(), 'memory:round-trip', 30)); const saved = serializeGameWorldV1(world, '2032-10-01T00:00:00.000Z'); expect(deserializeGameWorldV1(saved).memoriesById).toEqual(world.memoriesById); const legacy = { ...saved, payload: { ...saved.payload } }; delete (legacy.payload as { memories?: unknown }).memories; expect(deserializeGameWorldV1(legacy).memoriesById).toEqual({}) })
  it('queries shared history through the world query API', () => { const world = createNewGame(); const teamId = Object.values(world.teams)[0]!.id; const remembered = recordMemory(world, baseMemory(world, 'memory:shared', 40)); expect(getMemoriesBetweenEntities(remembered, remembered.userCoachId, teamId)).toHaveLength(1) })
  it('keeps contradictory memories and exposes recency, relevance and reinforcement', () => { const world = createNewGame(); const teamId = Object.values(world.teams)[0]!.id; const positive = recordMemory(world, { ...baseMemory(world, 'memory:positive', 70), semanticKey: 'opportunity:one', occurredOn: '2032-10-01' as never }); const contradictory = recordMemory(positive, { ...baseMemory(world, 'memory:negative', -80), type: 'conflict', semanticKey: 'conflict:two', occurredOn: '2033-10-01' as never, intensity: 90 }); expect(getMemoriesBetweenEntities(contradictory, world.userCoachId, teamId).map((memory) => memory.valence).sort()).toEqual([-80, 70]); expect(getRecentMemoriesForEntity(contradictory, world.userCoachId)[0]!.id).toBe('memory:negative'); expect(getCurrentlyRelevantMemoriesForEntity(contradictory, world.userCoachId)[0]!.memory.id).toBe('memory:negative'); expect(Object.values(getMemoryReinforcementForEntities(contradictory, world.userCoachId, teamId)).flat()).toHaveLength(2) })
  it('handles several decades of structured memory without duplicate results', () => { const world = createNewGame(); const teamId = Object.values(world.teams)[0]!.id; let accumulated = world; for (let index = 0; index < 600; index += 1) accumulated = recordMemory(accumulated, { ...baseMemory(world, `memory:volume:${index}`, index % 2 === 0 ? 30 : -30), semanticKey: `volume:${index}`, intensity: 1 + index % 100, occurredOn: `${2032 + Math.floor(index / 12)}-${String(index % 12 + 1).padStart(2, '0')}-01` as never }); expect(Object.keys(accumulated.memoriesById)).toHaveLength(600); expect(getRecentMemoriesForEntity(accumulated, world.userCoachId, 25)).toHaveLength(25); expect(getCurrentlyRelevantMemoriesForEntity(accumulated, world.userCoachId, 25)).toHaveLength(25); expect(getMemoriesBetweenEntities(accumulated, world.userCoachId, teamId)).toHaveLength(600) })
})
