import { parseGameDate, type GameDate } from '@/domain/date'
import type { StaffPersonId, TeamId, TeamStaffAssignmentId } from '@/domain/ids'
import { requireNonEmptyString } from '@/domain/validation'
import { ASSIGNABLE_STAFF_ROLE_IDS, type StaffRoleId } from './StaffRoleId'

export const STAFF_PROFESSIONAL_ATTRIBUTE_KEYS = ['coaching','tacticalKnowledge','playerDevelopment','talentEvaluation','potentialEvaluation','medicalKnowledge','rehabilitation','analysis','leadership','communication','motivation','discipline','adaptability'] as const
export type StaffProfessionalAttributeKey = typeof STAFF_PROFESSIONAL_ATTRIBUTE_KEYS[number]
/** @deprecated Legacy closed 3-role union, kept only for `STAFF_ROLE_ATTRIBUTE_WEIGHTS`/`calculateStaffRoleProficiency` backward-compat call sites and legacy save values. `TeamStaffAssignment.role` uses the canonical, extensible `StaffRoleId` (see `StaffRoleRegistry.ts`) — never this union. */
export const STAFF_ROLES = ['assistantCoach','scout','medical'] as const
export type StaffRole = typeof STAFF_ROLES[number]
// dateOfBirth/nationality mirror the Player.bio.dateOfBirth pattern: age is always a derived projection, never stored.
export interface StaffIdentity { readonly firstName:string; readonly lastName:string; readonly dateOfBirth?:GameDate; readonly nationality?:string }
export interface StaffProfessionalProfile { readonly attributes: Readonly<Record<StaffProfessionalAttributeKey,number>> }
/** Primary market speciality. Optional for legacy staff; it does not restrict a later assignment. */
export interface StaffPerson { readonly id:StaffPersonId; readonly identity:StaffIdentity; readonly professional:StaffProfessionalProfile; readonly marketRole?:StaffRoleId }
/** `role` is the canonical `StaffRoleId` (see `StaffRoleRegistry.ts`) — the real, sole assignment authority. Never `headCoach`. */
export interface TeamStaffAssignment { readonly id:TeamStaffAssignmentId; readonly staffPersonId:StaffPersonId; readonly teamId:TeamId; readonly role:StaffRoleId; readonly assignedOn:GameDate }
export const STAFF_ROLE_ATTRIBUTE_WEIGHTS: Readonly<Record<StaffRole,Readonly<Partial<Record<StaffProfessionalAttributeKey,number>>>>> = { assistantCoach:{coaching:.2,tacticalKnowledge:.18,playerDevelopment:.14,leadership:.1,communication:.1,motivation:.1,analysis:.07,discipline:.06,adaptability:.05}, scout:{talentEvaluation:.25,potentialEvaluation:.25,analysis:.15,adaptability:.1,communication:.1,tacticalKnowledge:.05,playerDevelopment:.05,leadership:.05}, medical:{medicalKnowledge:.35,rehabilitation:.3,analysis:.1,communication:.1,discipline:.05,adaptability:.05,leadership:.05} }
export function createStaffProfessionalProfile(input:StaffProfessionalProfile):StaffProfessionalProfile { const attributes=input.attributes as Record<string,number>; if(Object.keys(attributes).length!==STAFF_PROFESSIONAL_ATTRIBUTE_KEYS.length||STAFF_PROFESSIONAL_ATTRIBUTE_KEYS.some(key=>!Object.hasOwn(attributes,key)))throw new RangeError('Staff professional attributes must contain exactly every bootstrap key'); for(const key of STAFF_PROFESSIONAL_ATTRIBUTE_KEYS){const value=attributes[key];if(!Number.isInteger(value)||value<0||value>100)throw new RangeError(`Staff ${key} must be an integer from 0 to 100`)} return {attributes:input.attributes} }
export function createStaffPerson(input:StaffPerson):StaffPerson { const professional=createStaffProfessionalProfile(input.professional); if(input.marketRole!==undefined&&!(ASSIGNABLE_STAFF_ROLE_IDS as readonly string[]).includes(input.marketRole))throw new RangeError('Invalid Staff market role'); return {id:requireNonEmptyString(input.id,'Staff person id') as StaffPersonId,identity:{firstName:requireNonEmptyString(input.identity.firstName,'Staff first name'),lastName:requireNonEmptyString(input.identity.lastName,'Staff last name'),...(input.identity.dateOfBirth===undefined?{}:{dateOfBirth:parseGameDate(input.identity.dateOfBirth)}),...(input.identity.nationality===undefined?{}:{nationality:requireNonEmptyString(input.identity.nationality,'Staff nationality')})},professional,...(input.marketRole===undefined?{}:{marketRole:input.marketRole})} }
export function createTeamStaffAssignment(input:TeamStaffAssignment):TeamStaffAssignment { if(!(ASSIGNABLE_STAFF_ROLE_IDS as readonly string[]).includes(input.role))throw new RangeError('Invalid Staff role');return{id:requireNonEmptyString(input.id,'Staff assignment id') as TeamStaffAssignmentId,staffPersonId:requireNonEmptyString(input.staffPersonId,'Staff assignment person') as StaffPersonId,teamId:requireNonEmptyString(input.teamId,'Staff assignment team') as TeamId,role:input.role,assignedOn:parseGameDate(input.assignedOn)} }
export function calculateStaffRoleProficiency(person:StaffPerson,role:StaffRole):number { return Math.round(Object.entries(STAFF_ROLE_ATTRIBUTE_WEIGHTS[role]).reduce((sum,[key,weight])=>sum+person.professional.attributes[key as StaffProfessionalAttributeKey]*weight!,0)) }
